### ISSUE TITLE
@ in SQL users password

### ISSUE THREAD

**Issue by GnaXi** [GriefPrevention/GriefPrevention#100]
Getting the following error, when starting a server:
[Server thread/ERROR]: Cannot load plugins/mcMMO/config.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'string', line 138, column 24:
            User_Password: <password with an @ in it>

Shouldn't we be able to have @ in our passwords? :P

**Comment by GnaXi** [comment]
I found a workaround.
Using <"password"> instead of <'password'> seems to understand that the @ is part of the password :)

**Comment by Jikoo** [comment]
Just popping through old tickets - why is this open? It's an issue with the YAML implementation Bukkit uses, not the plugin in question, which is mcMMO, not GP.

**Comment by RoboMWM** [comment]
Lol, thanks for pointing that out.
