### ISSUE TITLE
Using TrustChangedEvent

### ISSUE THREAD

**Issue by ThaCrash** [GriefPrevention/GriefPrevention#1002]
### What happened:
When trying to listen to the TrustChangedEvent, it throws 
"Unable to find handlerlist for event me.ryanhamshire.GriefPrevent.events.TrustChangedEvent. Static getHandlerList method required.
Assume it just needs the same structure as fx. ClaimModifiedEvent by adding the :
    public static HandlerList getHandlerList()
    {
        return handlers;
    }
like ClaimModifiedEvent has.

### What was expected:
That it would be possible to listen to. Fx. ClaimModifiedEvent works fine when listening to it.

### Steps to reproduce:
Run a program that tries to listen to the event. Code used atm is simply:
 in onEnable:
        try {
            getServer().getPluginManager().registerEvents(new ClaimModified(), this);
            getServer().getPluginManager().registerEvents(new TrustChanged(), this);
        } catch (Exception e) {
            initErrors.add(e.getMessage());
        }

What is being called:
    public class TrustChanged implements Listener {
        @EventHandler
        public void blah(TrustChangedEvent event) {

            Player player = (Player) event.getChanger();

            player.sendMessage(ChatColor.GREEN+"Trust changed event with claim id:"+ChatColor.YELLOW+event.getClaims().get(0).getID());

        }
    }

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Paper 1.16.2-R0.1-SNAPSHOT
Paste of `/version GriefPrevention`: 
GriefPrevention version 16.14.0
(Also what is used for the API)

**Comment by RoboMWM** [comment]
Ya, prolly whoever PR'd it didn't test it, which doesn't surprise me with some of these PRs sometimes.

**Comment by RoboMWM** [comment]
guessing he never did implement what he planned to implement. https://github.com/TechFortress/GriefPrevention/pull/623
