### ISSUE TITLE
ProtectItemsDroppedOnDeath arguement for PvPWorlds and NonPvPWorlds does not work as intended

### ISSUE THREAD

**Issue by Kairosen** [GriefPrevention/GriefPrevention#1007]
**Question/Issue with ProtectItemsDroppedOnDeath:**

I have a non-pvp based survival server I am setting up, and I want to keep ProtectItemsDroppedOnDeath enabled for most of the server except for a PVP arena I have created on a separate world via Multiverse Core.

I have PVP enabled in server.properties, because as far as I know, it needs to be in order for players to hurt each other in the PVP arena world.
I then disable PVP via WorldGuard (Globally), and Multiverse Core in all worlds except the PVP arena world, so that the PVP arena would technically be the only world you can actually hurt other players in.

But, the following config does not seem to work for me, even though it should be the solution to my problem:

  _ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true_

Yet, with this following config, no items are protected what so ever, even on the worlds with pvp disabled via plugins (WorldGuard and Multiverse).

The configs "PvPWorlds:" and "NonPvPWorlds:" seem to only define themselves as whether or not PVP is enabled on the server as a whole in server.properties, which just doesn't make any sense as to why the word "world" would even be mentioned in the config argument. 

You would think it's supposed to protect items dropped on all worlds, except the only one with pvp enabled, right? But it doesn't. 

Whether PvP is enabled or disabled in server.properties, it seems to be that no matter what I do to the configs listed above, item drops are either protected in all worlds, or none of them. 
It seems to be an all or nothing scenario, which just doesn't make sense as to why these config arguments exist in the first place...
**Does anyone know if I can do anything to fix this?**

I hope I am doing something wrong and there is an actual solution to this.
And I know I can disable Grief-Prevention features on specific worlds, but I don't want to disable Grief-Prevention on the entire PVP arena world, because I still wan't to use it's PVP related features to punish combat loggers.

**Comment by RoboMWM** [comment]
Use the bug report template, and try on a fresh server.

**Comment by Jikoo** [comment]
Closing due to lack of response. Please open a new issue using the bug report template and fill out the requested information.
