### ISSUE TITLE
Add ClaimCreatedEvent

### ISSUE THREAD

**Issue by MrPowerGamerBR** [GriefPrevention/GriefPrevention#101]
I asked BigScary to add this a long time ago, but he didn't want to add (to not feature creep his plugin... for some reason)

There is event for when a claim is deleted, so why not add one for when a claim is created?

**Comment by RoboMWM** [comment]
#63

**Comment by MrPowerGamerBR** [comment]
@RoboMWM oh okay, I remember viewing that issue before but I couldn't find it again (that's why I created this issue)
