### ISSUE TITLE
Size color

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#1019]
Is the color from the size message (82x106=8692) changeable

**Comment by Jikoo** [comment]
Not at this time, no. I would have sworn that this was a duplicate (the guy who opened the previous ticket about it was exceptionally nasty about the lack of urgency) but I can't seem to find the old ticket.

**Comment by ghost** [comment]
Can I request this?

**Comment by RoboMWM** [comment]
search for the duplicate issue.

**Comment by Jikoo** [comment]
I searched through open issues and was unable to find a duplicate. I actually found the old issue in my email after searches didn't work, and it looks like GH actually deleted it and the guy's account after I reported his last message to me. It was previously #722

**Comment by RoboMWM** [comment]
Hmm, that sort of behavior further pushes me to self-host this thing... fortunately I also setup GitHub emails so I guess I at least have that.

I would've just locked the issue instead of reporting, I rather have people's bad behavior be on display for a good example of what not to do.

**Comment by Jikoo** [comment]
Fair enough, I suppose I could always email you directly if I need a lock - I don't have any IM support presence any more, I find it really only enables entitled user behavior. The comments themselves were honestly hilarious - did the guy actually think that anyone was going to hop up and address it after that? I was going to tackle it until the attacks on you started, changed my mind real quick, and then they just kept digging the hole deeper.

If you or @DasPotata would change the title to something a little more descriptive like "Allow customizing color of claims in /claimslist" we can just make this the issue for it.
