### ISSUE TITLE
Not an issue, just a question.

### ISSUE THREAD

**Issue by ResqDiver1317** [GriefPrevention/GriefPrevention#102]
We are using V9.1 on a 1.7.10 server that we are running Project Ozone 2 on. I noticed that the creeper explosions will damage the ground around the claim, but not in it. Part of PO2 is the challenge/risks of the mobs. I looked at the config to see if there was a way to allow mobs to damage in claims but didn't see it. Is this something that is possible to allow? I have it set to allow the explosion on the surface already, but that is not allowing them to damage in the claim like we want.

Thanks

**Comment by RoboMWM** [comment]
Yea, not possible at the moment. Big_Scary's design, unless you make players do /claimexplosions or similar. May be possible in an addon though.

**Comment by MrPowerGamerBR** [comment]
Also, the latest GriefPrevention version doesn't work in 1.7.10, so, unless @RoboMWM changes how GriefPrevention is incompatible between versions, you wouldn't benefit from such a change in newer GP versions.

**Comment by RoboMWM** [comment]
I'm likely going to delegate the concept of "flags" to another plugin. (i.e., I probably wouldn't change this behavior anyways, at least not in the core plugin).

**Comment by ResqDiver1317** [comment]
Yea, that's what I was afraid of. I may have to look at some alternatives to GP so we can get the function we want, but man I hate to do that. GP serves us so well on our other servers, I hate to move away from it just for this and have to learn a new one just for 1 server :(

Thank you for the info though :)

**Comment by RoboMWM** [comment]
@ResqDiver1317 what you're asking for is easily doable in an addon.

**Comment by ResqDiver1317** [comment]
Is there any chance you would know what add-on can do this?

**Comment by RoboMWM** [comment]
No, but I could write a quick plugin that allows explosions to occur regardless of which plugin that blocks it if that would work for you.

**Comment by ResqDiver1317** [comment]
That would be amazing! I really prefer to keep GriefPrevention as we have it on all our other servers so our players are used to it.

**Comment by RoboMWM** [comment]
@ResqDiver1317 https://github.com/RoboMWM/AlwaysExplode/releases/tag/1.0
