### ISSUE TITLE
More Custome Events for Vault specific things.

### ISSUE THREAD

**Issue by Avankziar** [GriefPrevention/GriefPrevention#1025]
Hello, 
as written in the title, I would be happy to have more custom events available.
For example..: An event for buying etc.

I would like to use this as interface for my Economy Plugin. Thanks in advance^^.

Avan

**Comment by Jikoo** [comment]
I don't understand. Could you explain in more detail what you're looking for and what your use case is?

Price per block is already configurable by server admins. If you're trying to change how `/buyclaimblocks` and `/sellclaimblocks` work wholesale you should just implement your own commands and override GP's, you'd have to depend on it either way. If you're trying to use claim blocks as balance or something you could just write an Economy layer for that without any additional events.

**Comment by Avankziar** [comment]
In your folder https://github.com/TechFortress/GriefPrevention/tree/master/src/main/java/me/ryanhamshire/GriefPrevention/events are Custom events. Extern Plugin can access these. 

What I would like you to do is call a new custom event when money specific things are happen in your plugin. E.g. when something is bought or sold (possibly marked with enum what is being done), with the amount and the player that calls the buy/sell here.

If this is the case, I want to access these events as external events to save the purchase in a money log, so that I can show the player the buy/sell in their history.

I hope it is now better understandable^^

Here is a Image, from what I suppose to do with the Info in the end^^
https://www.spigotmc.org/attachments/economy-mony-log-jpg.522203/

Avan

**Comment by Jikoo** [comment]
I understood what you meant by custom events, just not why you would want them when the Economy already knows it's being accessed when balance is changed.

I think you might be better off supporting generic command usage, i.e.
1) Listen to PlayerCommandPreprocessEvent
2) Store used command and time
3) If economy is accessed and balance is changed within a reasonable amount of time (50-150ms in case of async queries?) log command as cause

You're very unlikely to hit false positives as players are unlikely to be capable of performing actions in the same tick that they run a command, and you'll support any economy-supporting commands from any plugin without additional dependencies.

**Comment by RoboMWM** [comment]
Yea, I think checking balance for changes is inexpensive too, I have a "notifications" scoreboard that will monitor for any economy transactions.

**Comment by Avankziar** [comment]
It may be unlikely, but according to your suggestion you would have to disassemble commands to get info for a log, which would then always have to be done on transactions. I honestly think this is inefficient and theoretically simpler if your plugin simply calls a specific event.

But if I unfortunately can't convince you, then I wish you a nice day^^

**Comment by Jikoo** [comment]
Why disassemble the commands at all? You could just include "-10 from command" and a tooltip of the full command.

It's more that what you're asking is essentially duplicating the vault requests with more information. If you're going to be asking every vault-supporting plugin to support your plugin, maybe you should instead be discussing this with Vault.

**Comment by RoboMWM** [comment]
@Avankziar disassemble the command? No I don't do that at all! https://github.com/MLG-Fortress/MountainDewritoes/blob/cc0eafcc2f8e832c20109b334dd85b397e683a7d/src/main/java/me/robomwm/MountainDewritoes/Events/ReverseOsmosis.java#L112-L128
 which I use in a couple places, e.g. https://github.com/MLG-Fortress/MountainDewritoes/blob/master/src/main/java/me/robomwm/MountainDewritoes/notifications/TransactionNotification.java

**Comment by Avankziar** [comment]
> 
> 
> Why disassemble the commands at all? You could just include "-10 from command" and a tooltip of the full command.
> 
> It's more that what you're asking is essentially duplicating the vault requests with more information. If you're going to be asking every vault-supporting plugin to support your plugin, maybe you should instead be discussing this with Vault.

If I had all the commands that are theoretically triggered for money specific things, then first of all I would have to know them all and sort them according to them, right?

You are right if I only search GriefPrevention for commands, but that is not the final goal.

I see it a bit different with vault. Vault is for me a communication possibility to tell the money plugin which player gets how much money withdrawn or deposited.
So if I need a specific information about what has been done with the money, for example in the ChestShop plugin, then the per event is given in detail. Aka Who is selling/buying from whom, which item and how much. https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Events/TransactionEvent.java 

And all this specific data I can then convert into a log entry. I have done the same with JobsReborn and Headdatabase.



> 
> 
> @Avankziar disassemble the command? No I don't do that at all! https://github.com/MLG-Fortress/MountainDewritoes/blob/cc0eafcc2f8e832c20109b334dd85b397e683a7d/src/main/java/me/robomwm/MountainDewritoes/Events/ReverseOsmosis.java#L112-L128
> which I use in a couple places, e.g. https://github.com/MLG-Fortress/MountainDewritoes/blob/master/src/main/java/me/robomwm/MountainDewritoes/notifications/TransactionNotification.java

Yeah, but it told me not for what it was used. Or?

**Comment by RoboMWM** [comment]
Sounds like you should PR an API capability to Vault for a "reason" field or similar then. I don't know of any plugins that fire an event for vault operations, since vault itself is an API. ChestShop appears to be an exception to this, which makes sense given that it is a shop/economy plugin. (My PrettySimpleShop plugin fires events for sales too iirc, which makes sense since the plugin itself listens to such events and makes it easier to perform other interactions such as updating the displayed shop information on top of the shop block, etc.)
