### ISSUE TITLE
GP issue with geyser (crossplay) - PlayerItemHeldEvent firing erroneously

### ISSUE THREAD

**Issue by RaspberryTech01** [GriefPrevention/GriefPrevention#1030]
Hi! I am having issues with griefprevention and geyser. When trying to create a claim on bedrock edition, it takes multiple tries whilst resizing is fine. It spams the users client with how many blocks remaining multiple times.

Steps to reproduce: GP, Geyser, Floodgate plugins.

Expected: Easily create claims, no chat spam from server to user.

**Comment by RoboMWM** [comment]
Sounds like event firing isn't working too well.

**Comment by RoboMWM** [comment]
Since geyser's a protocol plugin it's gonna be on you to gather up what's going on. Using EventDebug is a good start.

**Comment by RaspberryTech01** [comment]
> Since geyser's a protocol plugin it's gonna be on you to gather up what's going on. Using EventDebug is a good start.

https://www.spigotmc.org/resources/eventdebug.5940/

Do you mean this plugin?

**Comment by RoboMWM** [comment]
Yup, that's the one.

**Comment by RaspberryTech01** [comment]
[debuglogMC.txt](https://github.com/TechFortress/GriefPrevention/files/5299305/debuglogMC.txt)
Here is the debug log

**Comment by RoboMWM** [comment]
You can paste logs in paste services such as https://gist.github.com

**Comment by RaspberryTech01** [comment]
https://gist.github.com/RaspberryTech01/78c637220c21fd9c78c2822c08bb2745

**Comment by Camotoy** [comment]
This was linked in our Discord - thanks for the link! This is definitely a Geyser issue explicitly (unless GriefPrevention doesn't handle special characters in usernames well). @RaspberryTech01 - are you on the latest Geyser? We patched an interacting spam fix recently. RoboMWM - anything interesting in those debug logs?

**Comment by RoboMWM** [comment]
Yup, Geyser or the client is doing something weird, for some reason is firing PlayerItemHeldEvent multiple times for no reason. https://gist.github.com/RaspberryTech01/78c637220c21fd9c78c2822c08bb2745#file-mclog-txt-L15-L17

**Comment by RaspberryTech01** [comment]
> This was linked in our Discord - thanks for the link! This is definitely a Geyser issue explicitly (unless GriefPrevention doesn't handle special characters in usernames well). @RaspberryTech01 - are you on the latest Geyser? We patched an interacting spam fix recently. RoboMWM - anything interesting in those debug logs?

I had downloaded the geyser plugin on the 27th (2 days ago). I can get the latest version if that is needed

**Comment by Camotoy** [comment]
Please do.

**Comment by RaspberryTech01** [comment]
Updated to latest version of geyser, still multiple events being fired https://gist.github.com/RaspberryTech01/78c637220c21fd9c78c2822c08bb2745

**Comment by Camotoy** [comment]
It's been a long time since I've used GriefPrevention - how can I replicate this myself?

**Comment by RaspberryTech01** [comment]
> It's been a long time since I've used GriefPrevention - how can I replicate this myself?

@DoctorMacc So it would just be GriefPrevention, floodgate and Geyser. 
These are my plugins:
![image](https://user-images.githubusercontent.com/31044433/94602112-5b937700-028c-11eb-8dcb-4e0120971ed2.png)

I am going to test out something, I found that McMMO shows "Shovel have been raised" when the GP shovel is used on the ground. I am going to remove the plugin temporarily and try.

**Comment by RaspberryTech01** [comment]
Alright, so if I remove the McMMO plugin it seems that the failure rate of the claim not working has decreased but still triggers the events multiple times occasionally.

**Comment by Camotoy** [comment]
Well, more specifically - what do I have to do in GP? Just use the golden shovel and right-click something?

**Comment by RoboMWM** [comment]
@DoctorMacc the PlayerItemHeldEvent should not be firing when the player's slot isn't changing.

**Comment by RoboMWM** [comment]
In the most recent log at this post, https://gist.github.com/RaspberryTech01/78c637220c21fd9c78c2822c08bb2745/c035e166ae3d609b28082cd289da04b9d051f014#file-mclog-txt-L569-L573

(The entry below that is a valid firing of the event, where the slot changes from 4 to 2).

**Comment by Camotoy** [comment]
https://github.com/GeyserMC/Geyser/pull/1353 this PR should fix the issue. @RaspberryTech01 if you would like to test it, feel free to hop on our Discord for assistance with download a PR.

**Comment by RaspberryTech01** [comment]
Right, that fixed it, thank you everyone for your help.

**Comment by Camotoy** [comment]
RoboMWM, thanks for the pointer on where to look! This will be merged into Geyser's main branch soon.

**Comment by RoboMWM** [comment]
No problem! It (fortunately) just happened to be what I guessed it would be.
