### ISSUE TITLE
I added GriefPrevention to my mc server and for some reason it prevents mobs from dealing damage to players. How would I change it so mobs can damage players?

### ISSUE THREAD

**Issue by jedimasternate** [GriefPrevention/GriefPrevention#1032]
The answer to your question may exist in the wiki, go check that out first! 

Wiki: https://github.com/TechFortress/GriefPrevention/wiki

Otherwise, if you have a spigot account, you may have better luck posting in the discussion thread so people who follow the thread may see your question. https://www.spigotmc.org/threads/griefprevention.35615/page-311

Still no luck? Really? Then go ahead and ask here.

Please remember to provide as much detail as you can - smart questions are
much more likely to be answered.  See "Asking questions the smart way":
http://www.catb.org/~esr/faqs/smart-questions.html

As an open-source project, we're all volunteers with limited time to spend,
so providing enough info (including any error messages etc) up-front makes
it more likely we can provide you an answer with limited time.

**Comment by RoboMWM** [comment]
GP doesn't stop mobs from damaging players. You've got another plugin doing this.
