### ISSUE TITLE
/adminclaims issue with geyser (crossplay)

### ISSUE THREAD

**Issue by fabiomarchesi77** [GriefPrevention/GriefPrevention#1033]
Hi! I am having issues with griefprevention and geyser. When trying to create an admin claim on bedrock edition, I click on the firs corner shovel returned to basic claim mode.

[I attach a video](https://drive.google.com/file/d/1bqxR0hUB591gl-QltlNryLTnCBBIpAEt/view?usp=sharing).

Steps to reproduce: GP, Geyser, Floodgate plugins.

**Comment by RoboMWM** [comment]
Duplicate of #1030

**Comment by RoboMWM** [comment]
Are you the same guy since the phrasing and lack of using the proper template seem to be common in both reports?

**Comment by fabiomarchesi77** [comment]
I'm not the same guy and that Is not the same issue. Why have you closed?

Il mar 29 set 2020, 00:25 RoboMWM <notifications@github.com> ha scritto:

**Comment by RoboMWM** [comment]
I closed because it is the same issue (Geyser is not firing Bukkit events properly), and just like he is, you will be responsible for debugging since Geyser is a protocol plugin. Please post future info over there to consolidate this information.
