### ISSUE TITLE
how to allow pistons to move blocks

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#1034]
How do I allow pistons to move blocks inside of claimed land?

I'm getting an error saying pistons wont move blocks outside of land claims

**Comment by RoboMWM** [comment]
Check config. Documentation talks about it too.

**Comment by JaredTurck** [comment]
very unhelpful, can you not provide a link?

**Comment by RoboMWM** [comment]
it was in the template you deleted. Also in the readme, and on the plugin overview pages.
