### ISSUE TITLE
how to allow pistons to move blocks

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#1035]
How do I allow pistons to move blocks inside of claimed land?

I'm getting an error saying pistons wont move blocks outside of land claims

(opening a new question since the other one was closed without any answer)

**Comment by Santhosh8465e** [comment]
why are they not responding this plugin is too overrated cant even fix a piston

**Comment by bigpresh** [comment]
> why are they not responding this plugin is too overrated cant even fix a piston

Eh?  The ticket was closed by the person who raised it shortly after opening.  It's rare that you will find people responding to closed tickets - why would anyone?  Typically that would signify they no longer have a problem.

If you have a problem of your own, please [raise a ticket](https://github.com/TechFortress/GriefPrevention/issues/new/choose) providing all the details requested.

**Comment by RoboMWM** [comment]
The original author deleted his original question, probably to avoid responses like this resurrecting an already-resolved issue. I've since restored it, and am now locking.
