### ISSUE TITLE
/AbandonAllClaims not working properly

### ISSUE THREAD

**Issue by MarkosGiakoumis** [GriefPrevention/GriefPrevention#1048]
So basically /abandonclaim works perfectly fine but when I am trying to /abandonallclaims it doesn't send me a confirmation message. It just sends another message of the command back
![image](https://user-images.githubusercontent.com/65721589/95212912-e1687280-07f6-11eb-8ea6-70ff229a62e1.png)

**Comment by MarkosGiakoumis** [comment]
And yes I tried typing /AbandonAllClaims instead of /abandonallclaims

**Comment by bigpresh** [comment]
Hmm, that shouldn't happen.  Can you provide the information in the template you deleted please (server version, GriefPrevention version, any other plugins etc) to help us figure out what's going on there?

**Comment by Jikoo** [comment]
Duplicate of #1008

**Comment by Jikoo** [comment]
Also what BigPresh said, if you include the information requested by the bug report template it's a lot easier to track down your issue.

**Comment by gkNcy** [comment]
the guy at the other thread was getting confirmation messages

**Comment by gkNcy** [comment]
also the version that i am using is 16.15.0-39f385e
other plugins
![image](https://user-images.githubusercontent.com/65721589/95216042-4ffaff80-07fa-11eb-8975-b62694cdf6ee.png)
