### ISSUE TITLE
Armed armor stands problem

### ISSUE THREAD

**Issue by Danrique** [GriefPrevention/GriefPrevention#1051]
### What happened:

I use this plugin: https://www.spigotmc.org/resources/armedarmorstands-automatically-add-arms-on-armor-stands.7098/
it adds arms to armors stands. I upgraded from 1.16.2 to 1.16.3 and now anyone can place armor stands in any plot. the permissions for the land dont count to this armors stands. I made some tests, without the plugin and with vanila armor stands it work fine.

Its really not a big deal and in the tests and in the oficial server I use paper, latest version from your plugin and the one of the armor stands, I upgraded everything yesterday.

I deleted the rest of the requested information because its irrelevant for this problem... but if you need ask away!

Thanks!

**Comment by Jikoo** [comment]
Get the author to add `ignoreCancelled = true` to their EventHandler annotation.
