### ISSUE TITLE
Chest sometimes won't auto protect or lock

### ISSUE THREAD

**Issue by eliyash31** [GriefPrevention/GriefPrevention#1059]
plugin version 16.15.0
paper version 1.16.3

Sometimes chest that are placed by players won't auto claim or is not protected. They already have the permission .claims

**Comment by bigpreshkt** [comment]
Only the first chest a player places should get the automatic claim around it; after that, if they place additional chests elsewhere, those will not be protected unless they place a claim around them (but they should get a message warning them that it's outside a claim and thus unprotected).  Is that what you mean?

Or are you saying that brand new players aren't getting the automatic claim around their first chest placed?  If so, please share your config, particularly check the `Claims.AutomaticNewPlayerClaimsRadius` setting.

**Comment by bigpresh** [comment]
Only the first chest a player places should get the automatic claim around it; after that, if they place additional chests elsewhere, those will not be protected unless they place a claim around them (but they should get a message warning them that it's outside a claim and thus unprotected). Is that what you mean?

Or are you saying that brand new players aren't getting the automatic claim around their first chest placed? If so, please share your config, particularly check the `Claims.AutomaticNewPlayerClaimsRadius` setting.

**Comment by eliyash31** [comment]
Oh okay I understand thank you for the response :) player does protect their claims with the first chest that they place :) thank you I didn't know that it works like this

**Comment by lucasantoniooficial** [comment]
@bigpresh  even with the configuration in the game, I have an UnprotectedChestWarning message, how to enable the Chest to have protection when I put it, I already configured everything.

Or as an administrator he has no protection?

**Comment by RoboMWM** [comment]
@lucasantoniooficial Only applies if player has no claim beforehand. If the player already has a claim, then subsequent chest placements will not generate a claim. If you have further questions, please use discussions.
