### ISSUE TITLE
Include claim size in message when right-clicking with a stick

### ISSUE THREAD

**Issue by bigpresh** [GriefPrevention/GriefPrevention#106]
Feature request from one of my staff - raising here as I don't have time to look at implementing it right now, but will try to have a look as soon as time permits.

When right-clicking with a stick (investigation tool) and a claim is found, it would be nice if the mesage which appears to show whose claim it is also included the claim size (width and height) for easy reference.

**Comment by RoboMWM** [comment]
It does, for staff (i.e. permission required, not sure which one but it's there.)

**Comment by bigpresh** [comment]
Hmm, does it?  I know it does if you have permission to edit the claim... the code in question appears to be: https://github.com/TechFortress/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java#L1894-L1898

Is there any reason that that if() block shouldn't have an alternate condition for some new permission to see other player's claim sizes?  Or, in fact, to just show it for everyone, as it's hardly private information - the claim boundaries are displayed anyway, so you could just walk from one corner to the other and count the blocks / compare the coords?

I don't want staff to have to be able to use ignoreclaims just to conveniently see the size of a claim.

**Comment by RoboMWM** [comment]
Well the point of ignoreclaims is that it's a toggle. (No, you don't have to enable it to see the dimensions).

**Comment by bigpresh** [comment]
Looking at `Claim.allowEdit()`, having the permission `griefprevention.deleteclaims` will pass the "can edit others claims" check, which means you'd get the size displayed.  It doesn't look like ignoreclaims actually comes in to it at all.

I still think showing the size for staff who don't need the permission to edit claims (or, in fact, just for everyone - as said, it's not exactly secret information) would be useful.  What do you think?

**Comment by bigpresh** [comment]
If you decide that showing the claim size to everyone is reasonable, then I've opened PR #107 for it for convenience.  If you don't agree, fair enough :)
