### ISSUE TITLE
/ignore command

### ISSUE THREAD

**Issue by elaineandsparky** [GriefPrevention/GriefPrevention#1076]
Bare with me, this is a really hard one to explain and not sure i fully understand it.

I use esentialsx along with grief prevention and i THINK the /ignore and /irgnoreplayer or /unignore and /unignoreplayer commands are conflicting with eachother. 

Player A does /ignore B which results in neither player A or player B being able to see eachothers messages. So from what i unerstand the grief prevention command has over-ridden the essnetials command as with essentials if player A does /ignore B player B can still see player A's messages it's just player A that can't see B's messages.

when player A does /unignore B if player A talks first the command doesn't work and player A has to do the command /unignoreplayer B. (i think i've got that the right way round and not if player B talks first)
but either way, something isn't working properly when the command /unignore is used and not /unignoreplayer.

I would like to be able to turn off the grief prevention ignore command as i don't like the idea of the messages being blocked both ways and just use the essentials ignore but I can't see how to do this. When negating the griefprevention.ignore permission it also turns off the ability to use /ignore along with /ignoreplayer. 

so is there anyway to have it as a option to turn off in the configs?

**Comment by bigpresh** [comment]
You should be able to just alias `/ignore` to `essentials:ignore` in commands.yml to have it go to essentials?

Have a read of https://bukkit.gamepedia.com/Commands.yml

**Comment by Jikoo** [comment]
Essentials attempts to give precedence to other plugins' commands over its own. In addition to what Bigpresh suggested, you may need to add `ignore` to [overridden-commands](https://github.com/EssentialsX/Essentials/blob/295bc9f76d670b809e0090260d7cb3bc828e0206/Essentials/src/config.yml#L162) in your Essentials configuration.

**Comment by elaineandsparky** [comment]
changing the allias didn't work as doing so it said that we didn't have perms to use the ignore command.

However, adding ignore to the overridden commands DID work.

thank you for your replies and help.
