### ISSUE TITLE
Command to hand over ownership of a subdivided claim inside an admin claim for a price/no price.

### ISSUE THREAD

**Issue by leviandstuff** [GriefPrevention/GriefPrevention#1078]
As the owner of a survival server,
I want to be able to make subdivides in admin claims that players can input a command to purchase that claim (Ex. /buyclaim) 
Because I want to allow players to own a claim in a large town without having to login myself and transfer ownership to them. To determine whether or not a subdivide can be purchased by another player, perhaps a command like /setclaimbuyable (price) could set that to true or false. A configurable limit for how many subdivides a player can buy in one claim could also be nice so that one player can't purchase everything inside of a town. This request is very specific, but any way to be able to do a command to claim a subdivided claim would be very helpful to me.

Optional questions:

**Is your feature request related to a problem? Please describe.**
My problem is that I currently would have to login and transfer ownership of a claim to a player if they want to create a building in a starter town on our survival mode.

**Comment by Jikoo** [comment]
Sounds like you want [GPRealEstate](https://github.com/RoboMWM/GPRealEstate).
