### ISSUE TITLE
I'm having problems with pistons not being able to PUSH blocks, what can cause this?

### ISSUE THREAD

**Issue by DeaDCorEx** [GriefPrevention/GriefPrevention#1081]
So I'm setting up an event for Halloween and it needs some redstone. I had created a world and started building. I had discovered that:
1.Pistons and sticky pistons can not  push blocks
2.Sticky pistons can pull blocks no problem

So I think to myself, there's only 2 plugins I have on my server that can cause anything like this WorldGuard and GriefPrevention. To troubleshoot the problem, I start by removing WorldGuard and testing if I have the problem still. Removing WorldGuard did not fix the issue. Then I removed GriefPrevention, BINGO, everything was working normally (with respect to the redstone). My path of inquiry didn't end here though, because my server also has GriefPreventionFlags, so I needed to find out if this could possible be the issue. I conducted the same sort of test, and as far as I can determine, it is not. So in summary these are the steps I have taken:
1.Removed WorldGuard.... test fail
2.Installed WorldGuard Removed GriefPrevention.... test passed
3.Installed GriefPrevention removed GriefPreventionFlags.... test failed

here's more information about my server: 
version: paper(249) 1.16.3-r0.1-snapshot
 Plugins (36): AdvancedGift, ArtMap, BedWars, BottledExp, Brewery, ChestShop, ChestShopNotifier, CMI, CMIPaperLib, CoreProtect, CratesPlus, DiscordSRV, EnjinMinecraftPlugin, GriefPrevention, GriefPreventionFlags, HeadDatabase*, HolographicDisplays, KixsChatAnnouncer, LastLoginAPI, LibsDisguises, LuckPerms, LWC, MobArena, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, MurderMystery, ProtocolLib, Vault, Vehicles, Votifier, VotingPlugin, WorldEdit, WorldGuard, WorldGuardExtraFlags, xpBottler

World - not affected
world_nether - not affected
world_the_end - affected
resource_world- not affected
contest - not affected
staff - not affected
creative - not affected
Halloween - affected

from the reports i heard from my players the problems started happening with the last update of your plugin. The strange thing is I'm not noticing any errors in console. any help you guys can provide would be much appreciated.

**Comment by Jikoo** [comment]
Could you please post an image of a failing piston setup (ideally with claim boundaries rendered) and your config's piston mode?

**Comment by DeaDCorEx** [comment]
I am unsure of the part of the config you are referring to. am unable to find anything in the config that refers to "piston" (ctrl+f)
should I delete the config and have the plugin auto-generate a new one?

![2020-10-28_20 49 56](https://user-images.githubusercontent.com/73572639/97519998-e46f0280-195f-11eb-967d-32c749e12fad.png)

weird thing is, this only affect 2 of my worlds as mentioned and the claim did not exist before you had asked for the screenshot, as there were no claims in that world.

Here is a paste of my current config.yml

# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    contest: -1
    buildbattle: -1
    Start: -1
    Staff: -1
    creative: -1
    res_nether: -1
    gold_world: -1
    world_resource: -1
    Halloween: -1
  Claims:
    Mode:
      Staff: Survival
      contest: Survival
      creative: Disabled
      Start: Survival
      gold_world: Survival
      world: Survival
      res_nether: Disabled
      world_resource: Survival
      world_the_end: Survival
      Halloween: Survival
      buildbattle: Survival
      world_nether: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 1000
    Claim Blocks Accrued Per Hour:
      Default: 0
    Max Accrued Claim Blocks:
      Default: -1
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: -1
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 25
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 0
      UnusedClaimDays: 0
      AllClaims:
        DaysInactive: -1
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
      contest: false
      buildbattle: false
      Start: true
      Staff: true
      creative: true
      res_nether: true
      gold_world: true
      world_resource: false
      Halloween: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.5
    ClaimBlocksSellValue: 0.5
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: false
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE_SIMPLE
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: false
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 600
    OfflinePlayer_cache_days: 900
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

**Comment by Jikoo** [comment]
Awesome, thanks. Please try changing piston mode from `EVERYWHERE_SIMPLE` to `EVERYWHERE` to see if that'll fix it, haven't seen reproducible cases to debug before.

If you do have any other issues aside from directly up, could you post those with F3 up too please?

**Comment by DeaDCorEx** [comment]
Ok that fixed it, thankyou!
