### ISSUE TITLE
Unable to figure out reason lucky blocks cant be placed

### ISSUE THREAD

**Issue by Kirb3h** [GriefPrevention/GriefPrevention#1084]
I have been having issues with my members and non op users unable to place lucky blocks. they just dissapear upon placement in the non claimed areas of the world. it give the message "other players can build here too" ive tweaked and turned on and off alot of features trying to figure it out, i have traced it to grief prevention. so im not sure what im missing to allow the placement of them. if any help can be given i would greatly appreciate that. right now if you place the lucky block on the side of a block instead of the top of the block it will work, so for now ive let my members know that its currently the only know work around to use them.
im running the most recent 1.16.3 spigot server.

**Comment by Jikoo** [comment]
With that little information I doubt we can help. Consider closing this and [filling out a bug report](https://github.com/TechFortress/GriefPrevention/issues/new?assignees=&labels=Unverified+Bug&template=bug-report.md&title=).

Points for a more useful bug report:
* What is a "lucky block" and what plugin (provide a link please, preferably to its source!) is adding it?
* "Most recent" is never a valid version. Use /version to obtain an actual version including commit hashes or build number.

**Comment by Jikoo** [comment]
Closing due to lack of response. Please fill out a bug report including plugin list if you do continue to have issues.
