### ISSUE TITLE
Unknown command for the lates version

### ISSUE THREAD

**Issue by SnowyB1** [GriefPrevention/GriefPrevention#1089]
Hello, i currently running a pixelmon server bur wit hthis plugin i install it but when i try to use a command it says Unknown command, why does this happend

**Comment by bigpresh** [comment]
There's absolutely no way we can help you with this little detail.

Please raise another, filling out the details requested in the issue template.

In the meantime, look at your server log for any errors when the plugin loads (and to check that it did load!), see if it appears in `/plugins`, etc.

**Comment by Jikoo** [comment]
Pixelmon indicates a Cauldron/Thermos server which usually indicates 1.7.10 as far as I'm aware.

If OP does check back in (which they might not, new accounts seem to forget about issues a lot) try looking through the [files on DevBukkit](https://dev.bukkit.org/projects/grief-prevention/files) to find your server version - it's a lot easer to see what versions are supported there.
