### ISSUE TITLE
Can't see private messages from random players

### ISSUE THREAD

**Issue by felixqnd** [GriefPrevention/GriefPrevention#1093]
### What happened:
I can see players conversing using private messages, but for certain players, it's only one side of the conversation (people speaking to them I can't see them responding), and I know they are not using another means of communication (like vc). 

### What was expected:
Would expect to see both sides of the conversation. 

### Steps to reproduce:
No idea how to reproduce, as it's only a handful of random players whom I can't figure out the relation between-- except that I think they were all banned and unbanned at some point in time. 

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: This server is running Yatopia version git-Yatopia-"eb35761" (MC: 1.167.3) (Implementing API Version 1.16.3-R0.1-SNAPSHOT) Previous version: git-Paper-193 (MC: 1.16.3)
You are 23 version(s) behind
Paste of `/version GriefPrevention`: GriefPrevention version 16.14.0

Please note that I am NOT the server Admin, I'm a mod.. though I think I may have /OP. Not totally sure.

**Comment by RoboMWM** [comment]
Yup, more info needed, sorry. Very likely others are /ignoring or the like, but without evidence of configuration or logs there's no way to tell.
