### ISSUE TITLE
Automatically restore unclaimed area every week

### ISSUE THREAD

**Issue by gg4goat** [GriefPrevention/GriefPrevention#1096]
As a server admin, I'd like my world to be restored periodically so that new player can access ressources around spawn.

It would be nice to have an option to restore the entire world (including Nether an End). 

Claimed area would remain intact of course.

**Comment by Jikoo** [comment]
Both [Regenerator](https://github.com/StargateMC/Regenerator) and my own [Regionerator](https://github.com/Jikoo/Regionerator) support GP. You probably want Regenerator - it uses WE to regenerate area where Regionerator deletes it and lets the generator take over. Regionerator doesn't do well around areas that are too active even if it's configured to delete active area.

**Comment by gg4goat** [comment]
Thank you for the links. 

I ended up using Regionerator since Regenerator doesn't seems to be active.

I've set the ignore flag to 1 day and flag radius to 1 chunk.
