### ISSUE TITLE
/deleteclaim should restorenature in survival worlds too (when AutomaticNatureRestoration.Survival is enabled)

### ISSUE THREAD

**Issue by RoboMWM** [GriefPrevention/GriefPrevention#11]
From @bigpresh 

One feature I'd really like would be the ability to remove a claim and restore nature on it at the same time.  I know that creative-rules worlds can have claims that are deleted get automatically "reset" to nature, so the support is already there - so what I'd really like is for an admin to be able to use a new command, e.g. /deleteclaimandrestorenature or similar (or maybe it be a parameter passed to /deleteclaim?) to remove a specific claim and undo all player changes within the claim too.

This would be really helpful for cases where someone is banned for x-raying, duping or whatever, and you want their build gone so that nobody profits from their ill-gotten gains - another player finding their build and getting loads of illegitimately-obtained diamonds from it could unbalance the economy.

Of course an admin could already delete the claim then click around with the shovel in restorenature mode to do this, but it would be nicer if there was an option to automate it.
Thoughts on this feature?  If it's agreed it would be good, I may be able to find time to have a go at implementing it, but I'd rather know if it would be welcomed first :)

**Comment by RoboMWM** [comment]
You can try using /deleteclaim, though I'm not sure if this causes the claim to be restored in survival worlds for whatever reason (I know Big_Scary commented on that in the spigot thread). I'll look into it, since I don't see why not - and admins can just use /abandonclaim if they don't want the claim to be restored.

**Comment by bigpresh** [comment]
> You can try using /deleteclaim, though I'm not sure if this causes the claim to be restored in survival worlds

It doesn't - I use it relatively often to remove old claims.  That's why I'd like a command (or argument to /deleteclaim, whichever) which causes an automatic restorenature within the boundaries of that claim - I'd find it useful for sure.

**Comment by RoboMWM** [comment]
/deleteclaim automatically triggers the restorenature feature in creative worlds, but doesn't do so in survival worlds. I'm busy right now but should be something relatively easy to PR. I'll see if I can find Big_Scary's post.

**Comment by RoboMWM** [comment]
https://www.spigotmc.org/threads/griefprevention.35615/page-77#post-1173596

Don't see what his reasoning is when one can simply use `/abandonclaim`. Not sure if `/deleteclaim` offers any other behavior other than instantly restoring creative claims? (Need to investigate).

If not, otherwise okay to PR altering `/deleteclaim`, provided that the config option RestoreSurvivalWorlds (iirc) is set to true

**Comment by RoboMWM** [comment]
Actually, now I know why he said that - if survival worlds have that enabled by default, there might be some sort of build worth keeping but not having a claim around. Using `/deleteclaim` would be your only recourse to preserve such a structure while also removing the claim.

Regardless, I still don't see why such things would not want to be claimed though. So I'll keep the change as-is, until somebody complains to have it back the old way...
