### ISSUE TITLE
Shulker Boxes are unprotected on claimed blocks

### ISSUE THREAD

**Issue by MithrandirCraft** [GriefPrevention/GriefPrevention#110]
Anyone can open and retrieve stuff from non owned shulker boxes inside an other player's claimed terrain.

Grief Prevention v16.5.1

I think this is more than enough info. It's obvious that this new container type was left out from GP's protected containers list with the latest 1.11.2 update of Minecraft.

**Comment by RoboMWM** [comment]
Uh, no, they definitely are protected. Please test with just GP installed.

> GP's protected containers list with the latest 1.11.2 update of Minecraft.

I doubt there is such a list. Pretty sure it just protects any block-based inventory.

**Comment by plasticblues** [comment]
They are completely protected on my server via GP, somethings conflicting.

**Comment by RoboMWM** [comment]
I had players (as well as myself) test for specifically this when 1.11 came out, so I'm positive GP is doing its job here. So yea, if you can isolate to just GP, a plugin is definitely ignoring/overriding GP's cancelation.

**Comment by MithrandirCraft** [comment]
Feel free to close the ticket, I'm not even certain this is true. I'll re-open if I'm 100% certain.
One of my staff reported this very convincedly, I can't remember how it ended.
