### ISSUE TITLE
Piston Movement

### ISSUE THREAD

**Issue by Leo2391** [GriefPrevention/GriefPrevention#1100]
The answer to your question may exist in the wiki, go check that out first! 

Wiki: https://github.com/TechFortress/GriefPrevention/wiki

Otherwise, if you have a spigot account, you may have better luck posting in the discussion thread so people who follow the thread may see your question. https://www.spigotmc.org/threads/griefprevention.35615/page-311

Still no luck? Really? Then go ahead and ask here.

Please remember to provide as much detail as you can - smart questions are
much more likely to be answered.  See "Asking questions the smart way":
http://www.catb.org/~esr/faqs/smart-questions.html

As an open-source project, we're all volunteers with limited time to spend,
so providing enough info (including any error messages etc) up-front makes
it more likely we can provide you an answer with limited time.

I was having a bit of troubles finding a way to make pistons work everywhere. I saw the “PistonMovement: CLAIMS_ONLY” part and I would like to know how to set it to everywhere.

**Comment by RoboMWM** [comment]
Read the documentation as linked.
