### ISSUE TITLE
The Plugin keeps getting breaking and fixing randomly and i have no clue why.

### ISSUE THREAD

**Issue by EternalWolff** [GriefPrevention/GriefPrevention#1101]
### What happened:
_a couple times now i have reset my server and its just stopped working with the same error message and then randomly in a couple days/weeks works and players are getting super angry and i cant seem to figure it out, not sure if  plugin is messing with it or  something else._

### What was expected:
_it used to run fine, but starting 2 months ago this started happening and i just want it to work. i have tried everything to fix this issue even removing most of my plugins and redoing the files_

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1.
2. Step 2.
3. ???
4. Profit!

### Server and GriefPrevention version:
___The server version is Craft Bukkit Spigot 1.16.1 and the Plugin version is 16.16.0.

### Stack trace/error or server log

`
![error](https://user-images.githubusercontent.com/74511339/99196828-aa3a9900-2786-11eb-9e70-65aa81c572e5.png)
``
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

`

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.
`

`



### Plugin list (if applicable):
![Plugins](https://user-images.githubusercontent.com/74511339/99196753-4d3ee300-2786-11eb-9d48-29e67e86070b.png)





### Debugging steps attempted
<!--These will be checkboxes you can click after creating the issue)-->
- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by Jikoo** [comment]
The plugin DeathChestPro has mistakenly included files from GP in their plugin. Contact them and get them to fix their build.
