### ISSUE TITLE
Projectiles fired by dispensers in claimed areas do not break armor stands/item frames.

### ISSUE THREAD

**Issue by BubbaAl** [GriefPrevention/GriefPrevention#1103]
https://github.com/TechFortress/GriefPrevention/blob/8c7abf9fd56f7dfdf496cb038221f405d0b29bd2/src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java#L963

**Comment by RoboMWM** [comment]
What, did this work before? Why did you not choose a template?

Idk if @Jikoo has any context.

**Comment by Jikoo** [comment]
My best guess is that OP wants projectile dispensers to break objects in the same claim as them, similar to the fireball changes I submitted a while ago.

I think we may want to revisit other entity "ownership" handling (projectiles, vehicles, etc.) entirely. I  do have a couple ideas for it but have yet to flesh out the finer details. Maybe we should close this and have a discussion on that at some point.

**Comment by BubbaAl** [comment]
Yes, this works on Vanilla. Eg. Breaking a item inside an item frame using
a snowball fored by a dispenser.

**Comment by RoboMWM** [comment]
closing in favor of #2278 Seems this one may have gotten lost in notifications.
