### ISSUE TITLE
[issue] can't change GOLD_SPADE to WOODEN_SHOVEL

### ISSUE THREAD

**Issue by ShaneBeee** [GriefPrevention/GriefPrevention#111]
### What behaviour is observed:
In the config file, when I change GOLD_SPADE to WOODEN_SHOVEL, and save it. when i start the server, it goes right back to gold_spade
### Steps/models to reproduce:
stop server, open config.yml ... change GOLD_SPADE to WOODEN_SHOVEL, start server, look back at config and it has changed

### Spigot/Craftbukkit/Paper and GriefPrevention version:
git-Spigot-625bc00-d09304e (MC: 1.11.2)
GriefPrevention version 16.6

### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```

**Comment by ShaneBeee** [comment]
OH WAIT... ok so now I see this in the server load...
INFO]: [GriefPrevention] ERROR: Material WOODEN_SHOVEL not found.  Defaulting to the golden shovel.  Please update your config.yml.

**Comment by ShaneBeee** [comment]
okay, I tried many things and fixed it, FINALLY tried WOOD_SPADE and it worked... don't know why, but it did

**Comment by Jikoo** [comment]
For future reference for anyone else, GP accepts only Bukkit's [Material](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html) names.

**Comment by ShaneBeee** [comment]
Duly noted thank you
