### ISSUE TITLE
Flint and Steel works inside claims

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#1113]
### What happened:
I have turned off PvP in my world and enabled protection from Flint and Steel but it continues work and players are not safe inside claim.

### What was expected:
Flint and Steel aren't avaible near (also) players.
### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Turn of PvP in world in config GP
2. Get inside claim
3. Use Flint and Steel near player.
4. He got be damaged, profit!

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 1.16.4 Spigot
Paste of `/version GriefPrevention`: 16.16.0

### Plugin list (if applicable):
Tested without any extra plugins.

**Comment by bigpresh** [comment]
I haven't had a chance to attempt to reproduce this yet.

We prevent using a flint & steel on blocks within a claim you don't have permission to build in: https://github.com/TechFortress/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java#L1844-L1863

Are you finding that that check isn't working, or that you can use it directly upon a player (i.e. interacting with the player, not with a block near them)?

**Comment by ghost** [comment]
Them both. It just doesn't prevent player from using it on or near a player.

**Comment by ghost** [comment]
If I'm trusted by some player then he can use flint and steel on me? It's stupid, because player can specially add me to his claim and kill by that.

**Comment by bigpresh** [comment]
If it's a claim you're trusted in, then yes, it's working as designed, currently.

He could also e.g. place an anvil which would fall on you, or place sand/gravel to fall onto you and suffocate you, or break a block you're standing on letting you fall into a drop trap, or place lava that would flow on to you...

That said - we *do* prevent lava placements too close to another player if PvP is off: https://github.com/TechFortress/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java#L1495-L1512

... it may be possible for that to be refactored to also prevent usage of flint & steel too close to another player.

**Comment by ghost** [comment]
PvP is turned off, but flint and steel works near any players on any claims, I didn't changed anything in config.

**Comment by RoboMWM** [comment]
So a missing step in the "reproduction steps" section is that the player needs to be trusted in the claim, is that correct?

**Comment by Jikoo** [comment]
Given we're missing config and OP has deleted their GH account, going to close this. I was not able to reproduce this with GP's anti-fire settings enabled. With them disabled, setting fires near players works as expected in and out of claims because GP is configured not to do anything.
