### ISSUE TITLE
Mushrooms, Sapplings, and other plants that grow horizontally can break chests.

### ISSUE THREAD

**Issue by Evidentsinger14** [GriefPrevention/GriefPrevention#1116]
Grief Prevention has a bug where chests on the edge of a claim. (around 5 blocks in) can be destroyed with items like a sappling, or a mushroom when they are grown on the edge of a claim. https://youtu.be/Qm4RbfeC02w here is a video of it happening.

**Comment by RoboMWM** [comment]
Having chests on the edges of claims is never a good idea, but I'll see what can be done, as I know BigScary removed this check (presumably due to performance reasons - as each block needs to be checked for a claim on every grow action).

**Comment by RoboMWM** [comment]
Long-term goal: segregate "edge" checks to addons, and maybe implement warning for chests placed on edges? Hmm.

**Comment by Jikoo** [comment]
Could extract the bounding box logic I did for claims intersecting piston zone for a faster check - could make a #getBoundingBox(Collection\<Block\>) and #getClaimsIntersecting(AxisAlignedBB). Would also allow for related unit tests more easily. Viable to do much more efficiently than BigScary used to, but a chore.

**Comment by RoboMWM** [comment]
Eh, I guess if it can be done efficiently then it could be re-added. Just kinda wondering if that really should be part of core design or not though, ehh...

**Comment by Jikoo** [comment]
Please enable the config option `GriefPrevention.LimitTreeGrowth`. If the issue persists, please fill out the info in the template. Looks like the option was never removed, just disabled by default.
