### ISSUE TITLE
How to get admin on my own server? 

### ISSUE THREAD

**Issue by AidanF9** [GriefPrevention/GriefPrevention#1121]
I have been trying to get admin but to no luck any help?

**Comment by Jikoo** [comment]
By "admin" do you mean you are trying to use GriefPrevention's admin permissions or you are trying to op yourself on your server?

If you're trying to op yourself, run `op YourMinecraftName` in your server console.

If you're trying to use GP's admin permissions, you need to use a permissions plugin to add the relevant GP [permission nodes](https://github.com/TechFortress/GriefPrevention/wiki/Permissions) to yourself or a group you are in. I recommend [LuckPerms](https://github.com/lucko/LuckPerms).
