### ISSUE TITLE
Players can breake blocks inside of other players claims without trust

### ISSUE THREAD

**Issue by slt3123** [GriefPrevention/GriefPrevention#1123]
So on my minecraft server I use the GriefPrevention and on 29.11.2020 me and my friends can build and mine blocks on the claims without truse bur we cant open doors and use chests, but when we build blcoks it comes up in chat that we dont have perm but we can still place blocks. PLS help.

**Comment by bigpresh** [comment]
Please fill out the issue template under bug report, which asks for various information which could help us to help you - including exact Minecraft server version and type, Grief Prevention version, and any other plugins you have installed.  In particular, try without other plugins, as it's very likely some other plugin you have installed is inadvertently uncancelling the events which GP cancels, thus overriding GP.

**Comment by Jikoo** [comment]
Definitely need the info from a bug report to help with this. Be sure to include your plugin list.
