### ISSUE TITLE
[suggestion] siege hang-out time

### ISSUE THREAD

**Issue by ShaneBeee** [GriefPrevention/GriefPrevention#113]
I noticed in the video and the written workings for siege, that when a player wins, your doors unlock and they can enter your house. After a short time they will be kicked out.
I had a player siege me, and it told him he had 5 minutes in my claim.
Is it possible to add to the config file, an option to change the time?
I feel 5 minutes is too long! I escaped, and the came back, so he had 5 minutes to keep roaming around my house and claiming blocks. I didn't die so he really didn't get anything.
I would just like the option to change the time he can "hang out" in my claim after the siege has ended :)

**Comment by TomLewis** [comment]
Ive asked for this multiple times, I have no idea why the siege times are not customisable.

**Comment by ShaneBeee** [comment]
I hope it'll be added in.   It's annoying that after I escaped I come back to someone hanging out in my house for 5 minutes.  I never died.  Therefor never dropped anything.   So all he can do is spend 5 minutes destroying my soft blocks.  I also think once he's won and the door is unlocked... soft.l blocks should no longer be breakable.

**Comment by ShaneBeee** [comment]
I just wanted to bump this. 
I was wondering if anything is in the works for adding a configurable amount of time a player can stay in your claim after the siege is over.

Another thing I would suggest, once the siege ends, maybe stop the player from breaking soft blocks. I mean the doors open, why does the player need to still be able to break my soft blocks?

**Comment by RoboMWM** [comment]
Just commenting here in case you might think I'm ignoring this; I'm not. However, I don't use the siege feature myself, and I don't like how it's kinda hacked into the plugin (making it difficult to debug). While I will accept PRs for improvements of this feature in 16.x, it will (and should've been) be an addon for GP v20; then such requests and bugs can be implemented and fixed much faster and easier.

**Comment by TomLewis** [comment]
@RoboMWM Thats actually brilliant to have it separate, as I have a developer working on a plugin to completely replace siege as its always been awful implementation and we've used it for 4 years and know how it should work. Any ETA?

**Comment by ShaneBeee** [comment]
Hey @RoboMWM  I know we've already talked about this, but Now I'm curious about changing something!
I want to compile the plugin myself to change a setting in the end of a siege. When a siege is over the winner has 5 minutes to hang out in the claim and keep destroying blocks, as well as accessing containers (on my server container access is on) which is fine, but I want to change the 5 minutes to something less, like maybe 1 minute?
Where in the code would I find it? The 5 minute part?
I have searched in both the siege areas and I'm lost, I can not find where it permits the winner 5 minutes to hang out in the claim!

**Comment by RoboMWM** [comment]
@ShaneBolenback probably best to ask this question in either a new issue, or better yet, a spigot post (since it's a "personal" question rather than an issue or suggestion). It's probably a scheduled task somewhere - try using the github search function (you might have to search big_scary's repo, since this repo doesn't have over 46 stars yet.)

@FrozenBeard Not sure, there's quite a bit of work to do. Can discuss more on this in IRC, everything else though is in #63

**Comment by TomLewis** [comment]
@ShaneBolenback can you add that as a config option and push to the main git as I would be interested in that too.

**Comment by ShaneBeee** [comment]
Hey @frozenbeard
Due to the pvp issues with siege I have decided to turn siege mode off on my server.   Therefor I will not be editing code to change the 5 minute thing. 
I have found it in the code, but unfortunately I’m not skilled enough to set it as a configurable item.  All i’d know to do is change the actually time.   
Maybe someone else can help here?

**Comment by bigpresh** [comment]
@FrozenBeard https://github.com/TechFortress/GriefPrevention/pull/203 should do the trick for you, but I haven't had time to test it on my test server yet.
