### ISSUE TITLE
Discussions Beta

### ISSUE THREAD

**Issue by Jikoo** [GriefPrevention/GriefPrevention#1131]
I know you touched on Discussions a while ago - looks like you can opt in by expressing interest [here](https://github.community/t/can-one-apply-for-github-discussions-beta/121120), specifying repo and primary feedback contact user. Repo must have 3 contributors per an early comment.

**Comment by RoboMWM** [comment]
I saw it, but eh, idk if I wanna deal with a beta feature where stuff may accidentally get deleted n' stuff. idk. Guess I'll go request it when I get around to it.

on another related note I've recently decided to refocus on setting up a forum (for my server). Saw that a few days after. Also been looking at ways to just back things up from github in general.

**Comment by Jikoo** [comment]
> I saw it, but eh, idk if I wanna deal with a beta feature where stuff may accidentally get deleted n' stuff. idk. Guess I'll go request it when I get around to it.

I imagine if they had problems with that people would be pissed - a lot of communities and mailing lists have already migrated.  For example, [ImageMagick](https://imagemagick.org/) has been in the program since nearly the beginning I believe, and they've actually gone so far as to archive their forum and redirect their entire community to discussions.

> on another related note I've recently decided to refocus on setting up a forum (for my server). Saw that a few days after. Also been looking at ways to just back things up from github in general.

Depending on what kind of solution you're after, there's GitHub's recommendation [BackHub](https://github.com/marketplace/backhub), a number of scripts, or setting up a webhook to mirror new data to your own server (though you'd then have to interpret the content, which is work).

**Comment by RoboMWM** [comment]
Yea I don't need to interpret data, just more of a just-in-case scenario so having the raw json is good enough. BackHub only seems to have a 14 day free trial no matter if public or private repos.

Mk, I'll go ahead and get this in.

**Comment by Jikoo** [comment]
Apparently Discussions are now in open beta as of today. They can be enabled in the options, last in the list of features.

**Comment by RoboMWM** [comment]
Yea, and they emailed me yesterday about putting me in the beta.

Wonderful.

**Comment by RoboMWM** [comment]
Interesting, title changes aren't logged. Oh well. A small price to pay.
