### ISSUE TITLE
No message for PVP timeout

### ISSUE THREAD

**Issue by FuchiK0ma** [GriefPrevention/GriefPrevention#1132]
Have been poking through messages as well as exploring other plugins, but then came to the conclusion that GP might be the best place to resolve this.

Essentially we want players to be notified when they are in PVP eg

"You have entered combat!  --[Timeout = 15 seconds]--"

"You will exit combat soon! --[Timeout = 3 seconds]--"

"Combat is over. >>slow clap<<"

or.. ya know something like that.

Suggestions?

**Comment by RoboMWM** [comment]
think this is a duplicate

**Comment by FuchiK0ma** [comment]
> think this is a duplicate

You are correct! And I did run a search before posting this, but they used different terminology:

https://github.com/TechFortress/GriefPrevention/issues/569

I concur(ish) with their suggestions, but think mine is a bit more encompassing of the use-case scenario.

**Comment by RoboMWM** [comment]
You can add yours there, going to be moving some "advanced" PvP stuff out anyways(?) But ya want to consolidate similar issues.
