### ISSUE TITLE
items wont drop and no creepers

### ISSUE THREAD

**Issue by rebeccastanke** [GriefPrevention/GriefPrevention#1135]
### What happened:
_What you saw_
the q key does not drop items and there are no creepers in the world
### What was expected:
_What you expected to see_
I should be able to drop items and creepers should spawn
### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1.click on q
2. Step 2.item does not drop and there are no errors
3. ???
4. Profit!
[latest (1).log](https://github.com/TechFortress/GriefPrevention/files/5659203/latest.1.log)
[config.yml.log](https://github.com/TechFortress/GriefPrevention/files/5659212/config.yml.log)

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Paste of `/version GriefPrevention`: [Server thread/INFO]: GriefPrevention version 16.16.0
[08.12 05:08:26] [Server] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-a19903d-5b74714 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
[08.12 05:08:26] [Server] [Server thread/INFO]: Checking version, please wait...
[08.12 05:08:26] [Server] [Thread-29/INFO]: You are running the latest version
### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Debugging steps attempted

- [x] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by rebeccastanke** [comment]
I removed griefprotection plugin and I was able to drop items, not sure yet if creepers are spawning without plugin

**Comment by Jikoo** [comment]
You're using the creative ruleset. As part of the creative ruleset, GP prevents item dropping and mob spawning. You must use either Survival or SurvivalRequiringClaims if you want those to occur.

**Comment by rebeccastanke** [comment]
I installed this version and now it works
https://www.spigotmc.org/resources/griefprevention.1884/

Status
Installed (Version: 16.13.0 - Feb 04, 2020)

**Comment by Jikoo** [comment]
I am assuming it now works because you reset your config and it defaulted to survival. I strongly recommend reinstalling 16.16 over 16.13, you're missing out on a lot of fixes.
