### ISSUE TITLE
Remove WorldGuard dependency

### ISSUE THREAD

**Issue by RoboMWM** [GriefPrevention/GriefPrevention#1140]
As a developer
So that I don't have to deal with the cost of WorldGuard questions and issues, and supporting their changing API
I want to remove WorldGuard integration from GP

**Comment by eusgoogle** [comment]
IF ERRORLEVEL TO 20.0R EXIT BYE WIN ERRORLEVEL BYE TO PLANET NINE EXIT TO BYE IF ERRORLEVEL TO C 04 TO BYE 20.0R TO BYE BB.120/4.0.0200.72SBR BYE/BYE BAAL NABU 8070/2031/98/1386/98 BYE OK 750 TO 1 ENTER
