### ISSUE TITLE
Remove Siege

### ISSUE THREAD

**Issue by RoboMWM** [GriefPrevention/GriefPrevention#1143]
Siege is mostly unused ([currently at 0.6% of users](https://bstats.org/plugin/bukkit/GriefPrevention-legacy/3295#uses_siege)) and is embedded into a lot of the very messy pvp codebase. Removing siege would help make the process of refactoring the pvp code to a distinct "module" a lot less costly.

**Comment by Sogekeeper** [comment]
Hi there!
Was Siege already removed? I was very interested in using something like it but I can't find where I can enable the mode.
I like it better than other pvp modes for open world survival servers.

**Comment by Jikoo** [comment]
> Was Siege already removed? I was very interested in using something like it but I can't find where I can enable the mode.

No, siege is available in the `GriefPrevention.Siege` section of the configuration.

**Comment by RoboMWM** [comment]
ok I don't recall setting up automation so now I have to figure out why this is happening.
