### ISSUE TITLE
Fence bug

### ISSUE THREAD

**Issue by RafalKedziora** [GriefPrevention/GriefPrevention#1154]
### What happened:
It's possible to pour out the water in the fence

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. pour out the water in the fence
2. the water is flowing
3. No profit

### Server and GriefPrevention version:
The newest version of GriefPrevention 16.16.0

### Stack trace/error or server log
No console error
```


### GriefPrevention config.yml
config.yml not affected


### Plugin list (if applicable):
without affecting the bug

**Comment by RoboMWM** [comment]
what.

**Comment by RoboMWM** [comment]
1. I have no idea what you mean by "pour out the water in the fence"
2. please fill out the template.
