### ISSUE TITLE
adjustclaimbloc based on permissions

### ISSUE THREAD

**Issue by NoWing31** [GriefPrevention/GriefPrevention#116]
### What behaviour is expected:
Claim limit adjusted for a group having the corresponding permission 
(using /acb [permission] [qty])

### What behaviour is observed:
error message saying 'No player by that name has logged in recently"

### Steps/models to reproduce:
use the /acb command with a permission name

### Spigot/Craftbukkit/Paper and GriefPrevention version:
GP 16.6
Spigot 1.11.2

### Plugin list (if applicable):
PermissionsEx
Vault
ProtocolLib
Coreprotec
WorldEdit
Worldguard
Shopkeeper
Deathmessages
Chairs
PorteCoulissante
Bungeeportals
Mutlichatbridge
Essentials
EssentialsChat
EssentiialsSpawn
EssentialsAntibuild
Scoreboardstat
JsonAPI
Autorank

**Comment by Jikoo** [comment]
~~That's not how that command works. If you want to change accrual, you'll need an add-on.~~ Unfortunately, it seems GPAccruals is no longer available on Spigot, so I'm not sure where to direct you. Paging @BillyGalbreath, is it still available, assuming it even supports separate caps per node?

**Comment by RoboMWM** [comment]
@NoWing31 You need to include the brackets when inputting the permission.

@Jikoo It is possible to distribute bonus blocks based on permissions. However, I strongly discourage its use as it may be the cause of erroneously giving players additional blocks.

**Comment by Jikoo** [comment]
Ah, thanks, wasn't aware, wasn't in the old documentation that I could see. However, isn't /acb for adjusting claim blocks, not the max value?

**Comment by RoboMWM** [comment]
that's correct, it's for adjusting bonus blocks only. Not sure if that's what he's trying to do or not ¯\_(ツ)_/¯

**Comment by NoWing31** [comment]
@RoboMWM Thanks ! It's work fine. To change the 
Max Accrued Claim Blocks regarding the rank of the player I tried to use the griefprevention.max-accrued-claim-blocks option in pex ... but evryone seems to be sticked at the value 'default' from config.yml ...
What did I do wrong .

**Comment by RoboMWM** [comment]
that's different. See https://github.com/TechFortress/GriefPrevention/issues/18#issuecomment-261895573

**Comment by NoWing31** [comment]
@RoboMWM GPAccruals seems to solve my pb but the link 
found in the issue#18 comment ( https://www.spigotmc.org/resources/gpaccruals.32122/) isn't working and I did'nt found this plugin on bukkit or spigot .... Is GPAccruals still maintained ?

**Comment by RoboMWM** [comment]
Ah, yea it is. He deleted all his resources but he has that one still hosted somewhere, I'll put a link in the wiki.

**Comment by Jikoo** [comment]
His CI seems to have moved, old link just redirects to his server's forum. Source is [still on his Bitbucket](https://bitbucket.org/BillyGalbreath/gpaccruals), but that's all I could find.

**Comment by NoWing31** [comment]
Other solution than compiling it ?

**Comment by RoboMWM** [comment]
Not sure, his jenkins does seem to be down/moved. Should be easy to compile though since it's mavenized.

**Comment by BillyGalbreath** [comment]
Sorry about that, guys. I'll put up a new project page on spigot here shortly. My Jenkins was taken down because it somehow got compromised and someone spammed jobs until my HDD filled up. I didn't even notice it until my mc server crashed :S

**Comment by NoWing31** [comment]
@BillyGalbreath You think it will be available again when ?

**Comment by BillyGalbreath** [comment]
Sorry for the delay. I've been extremely lazy here lately..

I went ahead and pushed up my [latest changes](https://bitbucket.org/BillyGalbreath/gpaccruals/commits/branch/master) to BitBucket, which includes the new accrued idle percents found in the [GP builds after Feb 18](https://github.com/TechFortress/GriefPrevention/pull/90). @RoboMWM this means a 16.7 is needed (your last release was Feb 4).

Here's a link to the GPAccruals jar for v1.1 (for 16.7+) and v1.0.1 (for 16.6) hosted on my DropBox. The config included should be self explanatory. I'll get around to making a new resource page on Spigot eventually (no ETA on that, though).

https://www.dropbox.com/s/5ilyqmkydbp0yhh/GPAccruals-1.1.jar?dl=0 (for GP 16.7+)

https://www.dropbox.com/s/nmntcr66gcm6ums/GPAccruals-1.0.1.jar?dl=0 (for GP 16.6)

**Comment by Crytikill** [comment]
For someone who is not that familiar with scripting and such, could you explain how I would go about setting the Accrued Claim Blocks Per Hour depending on each permission? I want permission "Default" to get 100/hr and permission "VIP" to get 225/hr. Could you please explain how? Thanks

**Comment by RoboMWM** [comment]
Afaik GPAccruals should generate a default config, and it should be easy to figure out from there. He did have a spigot page for his plugin, but he's since "left" spigot and took all his plugins from it.
