### ISSUE TITLE
Claim Blocks Accrued Per Hour based on permissions

### ISSUE THREAD

**Issue by witoszekdev** [GriefPrevention/GriefPrevention#117]
### What behaviour is expected:
Setting different accrued blocks per hour based on set permissions nodes or permission groups.

I recently stumbled upon this plugin's _ripoff_ made for Sponge (not that I like it or anything) which had some interesting feature: you could set this option (and others like claim expiration, abandon ratio - blocks given back when abandoning claim, etc.) based on players permission. It would be a great feature to implement for rewarding loyal players and VIP's.

Link to _mentioned inspiration_: [https://github.com/MinecraftPortCentral/GriefPrevention/wiki](https://github.com/MinecraftPortCentral/GriefPrevention/wiki)

Taking this opportunity I would like to thank you for maintaining this plugin. You guys are the best :)

**Comment by RoboMWM** [comment]
Already possible in an addon, see discussion in #18 

Specifically https://github.com/TechFortress/GriefPrevention/issues/18#issuecomment-261895573
