### ISSUE TITLE
/claim command doesn't work.1.7.10 Thermos server

### ISSUE THREAD

**Issue by ThatGuy1oo1** [GriefPrevention/GriefPrevention#118]
### What behaviour is expected: For an area to be claimed with a certain radius.
_What you expected to see_
### What behaviour is observed: An error spit out in chat.
_What you actually saw_
### Steps/models to reproduce: Run a Thermos server with the "Escape the Barren Fallout" pack on curse
_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_

### Spigot/Craftbukkit/Paper and GriefPrevention version: 16.5.1, Thermos version 1614
___This can be found by running `/version` and `/version GriefPrevention` on your server.___

### Stack trace/error (if applicable)
[12:51:57] [Server thread/INFO]: jello88 issued server command: /claim
[12:51:57] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'claim' in plugin GriefPrevention v16.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.58]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.NoSuchFieldError: BEETROOT_BLOCK
	at me.ryanhamshire.GriefPrevention.Claim.<init>(Claim.java:310) ~[?:?]
	at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:805) ~[?:?]
	at me.ryanhamshire.GriefPrevention.GriefPrevention.onCommand(GriefPrevention.java:1061) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.58]
	... 13 more
[12:52:04] [Server thread/INFO]: jello88 issued server command: /unclaim
```
Paste entire stack trace inside here
```?

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here
``# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    DIM-100: -1
    DIM-37: -1
    DIM-38: -1
    DIM-39: -1
    DIM-42: -1
    DIM-112: -1
    DIM-1: -1
    DIM1: -1
  Claims:
    Mode:
      DIM1: Disabled
      DIM-42: Disabled
      DIM-112: Disabled
      DIM-37: Disabled
      DIM-38: Disabled
      world: Survival
      DIM-1: Disabled
      DIM-100: Disabled
      DIM-39: Disabled
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 20000
    Accrued Idle Threshold: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      DIM-100: true
      DIM-37: true
      DIM-38: true
      DIM-39: true
      DIM-42: true
      DIM-112: true
      DIM-1: true
      DIM1: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
`

### Plugin list (if applicable):
AutoRestart-Reloaded
EasyHome
EasyWarp
GriefPrevention (Obviously...)
worldedit-bukkit-6.1.5

**Comment by bigpresh** [comment]
Your Minecraft version is too old to use GP 16.5.1.

For a 1.7.10 server, you need http://dev.bukkit.org/media/files/833/268/GriefPrevention.jar

**Comment by ThatGuy1oo1** [comment]
The link you provided doesn't work

**Comment by bigpresh** [comment]
> The link you provided doesn't work

Ah yes, sorry - I copied & pasted it from the other versions section on https://dev.bukkit.org/projects/grief-prevention without checking.  (@RoboMWM can we fix those links?)

However, looking at https://www.spigotmc.org/resources/griefprevention.1884/history it looks like you might have to go all the way back to 9.2.2: https://www.spigotmc.org/resources/griefprevention.1884/download?version=7307

Very old Minecraft versions aren't supported by recent GP builds, is the crux of the matter.

**Comment by RoboMWM** [comment]
I honestly would rather move all those relevant pages and info to the github wiki
