### ISSUE TITLE
Detecting whether MC version is supported by the GP version in use

### ISSUE THREAD

**Issue by bigpresh** [GriefPrevention/GriefPrevention#119]
I wonder if it would be possible for GP, early on in loading, to check the MC version being used, and loudly squawk an informative message that the GP version is too new for the MC version in use, and link to a page which explains it further and links to the older builds that are suitable for old MC versions? 

It'd help with e.g #118 and various other cases where people have too new a GP build to use with an old MC version (they've just grabbed the latest GP version without reading the "for older MC versions" section with links to older builds) and get uninformative explosions that look like bugs.

 @RoboMWM what do you think?

**Comment by Jikoo** [comment]
This is now handled by Bukkit's `api-version`, which spits out a pretty descriptive error.
