### ISSUE TITLE
Atomic claim data writes, particularly for _nextClaimID

### ISSUE THREAD

**Issue by bigpresh** [GriefPrevention/GriefPrevention#120]
A server I help admin ran out of disk space (through a lack of suitable monitoring - I've now added decent monitoring!) - because of this, the `_nextClaimID` file was truncated; when the next claim was added, it was claim ID 1, and clobbered that claim, and `nextClaimID` was set to 2, and from that point, each new claim overwrote an old one.

Now, yes, the fault lies with us for not having monitored well enough, and I restored the overwritten claims from a backup, but I still think it would be nicer if GP:

* wrote files atomically - i.e. write to a temporary file with a different extension, or whatever, then renamed it into place, to avoid data loss
* bailed if the claim ID it got from reading `_nextClaimID` already existed as a file, rather than just overwriting it

**Comment by RoboMWM** [comment]
Partially addressed in https://github.com/TechFortress/GriefPrevention/commit/e17403feb2e8bef41099421e46e00ee2acf9c04e which is implementation-agnostic.
