### ISSUE TITLE
Tree saplings not place able 

### ISSUE THREAD

**Issue by DarkChromaMC** [GriefPrevention/GriefPrevention#1202]
### What happened: Tree saplings can not be placed on grass blocks that are at y75 to y76
_What you saw_
Saplings just disappear when placed. This issue is definitely from GP because I tested without other plugins.
### What was expected:
_What you expected to see_
The sapling to be placed on grass block as normal.
### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1. Place grass blocks at y75 or y76
2. Step 2. Place saplings on grass blocks
3. 
### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Paste of `/version GriefPrevention`:  16.16.0

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.
I used a completely fresh config, no adjustments.
```

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by RoboMWM** [comment]
see documentation about sky trees.
