### ISSUE TITLE
AntiSpam unban

### ISSUE THREAD

**Issue by m-Phoenix852** [GriefPrevention/GriefPrevention#1207]
### What happened:
_Player banned for spamming, can't unban now_

### What was expected:
_The player was banned for spamming, I don't see any command to unban him. I tried unban, unban-ip, pardon, pardon-ip. None works. Please help._

**Comment by TDMidkwhatisxd** [comment]
delete banned file xd

**Comment by RoboMWM** [comment]
you're missing a ton of info that you deleted, but I guess your ban plugin is hijacking all of those commands. Try `/minecraft:pardon`.

**Comment by RoboMWM** [comment]
Also, this is a question not a bug report. Moving to discussions.
