### ISSUE TITLE
Unable to find Minecraft 1.7.10 version of GriefPrevention

### ISSUE THREAD

**Issue by ThatGuy1oo1** [GriefPrevention/GriefPrevention#121]
Link provided from staff and griefprevention post leading to 1.7.10 use do not work.

**Comment by bigpresh** [comment]
The post in question being the older versions links on https://dev.bukkit.org/projects/grief-prevention which I referred @ThatGuy1oo1 to in issue #118.

~~@RoboMWM can the links be updated there?  On the previous versions lists, there or here on GH, could each version be tagged/annotated with the MC version(s) it is known to work with?~~

EDIT: er, the game version is already shown there, I was just being blind.  Sorry about that!

**Comment by ThatGuy1oo1** [comment]
The link you gave me in my last post, when you closed it, leads to no where, as does the one you showed me, it leads to the links of the version list, this guy, http://dev.bukkit.org/media/files/833/268/GriefPrevention.jar
leads to nothing.

**Comment by bigpresh** [comment]
I just realised I was blind before.

Look at https://dev.bukkit.org/projects/grief-prevention/files - there's a "game version" column, telling you which version of the game it works with.

**Comment by ThatGuy1oo1** [comment]
Yes I realized this, however it stops showing which version the game is before 1.8, leaving me with no clues, I am using Thermos so I have no clue what bukkit version I have, or spigot.

**Comment by bigpresh** [comment]
I'm not at all familiar with Thermos, but in #118 your logs contained e.g. `[PluginCommand.class:1.7.10-1614.58]` which leads me to believe it's MC 1.7.10, so you need quite an old version of GP; 1.7.10 is ancient and not actively supported these days.

**Comment by ThatGuy1oo1** [comment]
Do you know which version of GP supports 1.7.10?

**Comment by ThatGuy1oo1** [comment]
I know I have 1.7.10, I'm still trying to figure out what bukkit version I actually have though, but if you could give me a compatible version of GP I might be able to figure it out.

**Comment by ThatGuy1oo1** [comment]
Any help?

**Comment by Jikoo** [comment]
The next button is your friend. 1.7 files start on Bukkit's page 5 currently.

**Comment by bestxp** [comment]
CB 1.7.9-R0.2	is not 1.7.10  о_О

**Comment by RoboMWM** [comment]
Iirc, 1.7.10 wasn't a major server change (something similar to 1.8.9 if I remember reading that correctly - I was on a hiatus from hosting back then). Either way it should be compatible.

**Comment by ThatGuy1oo1** [comment]
Alright well it worked, thanks guys!

**Comment by MadWolf94** [comment]
https://www.curseforge.com/minecraft/bukkit-plugins/grief-prevention/files/833268
