### ISSUE TITLE
Error with GP

### ISSUE THREAD

**Issue by PiroX4256** [GriefPrevention/GriefPrevention#122]
Hi, I have a problem, when I try to execute the command "/claim" I get this error:

-----------------------------------------------------------------------------------------------------------

27.04 10:15:30 [Server] INFO AleMasterJ_ issued server command: /claim 27.04 10:15:30 [Server] ERROR null 27.04 10:15:30 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'claim' in plugin GriefPrevention v16.6 27.04 10:15:30 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:30 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:30 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:31 [Multicraft] Skipped 42 lines due to rate limit (30/s) 27.04 10:15:31 [Server] INFO AleMasterJ_ issued server command: /claim 27.04 10:15:31 [Server] ERROR null 27.04 10:15:31 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'claim' in plugin GriefPrevention v16.6 27.04 10:15:31 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:31 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:31 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:31 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:31 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:31 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:31 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:31 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:31 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121] 27.04 10:15:31 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121] 27.04 10:15:31 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:31 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:31 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:31 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:31 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121] 27.04 10:15:31 [Server] INFO Caused by: java.lang.NoSuchFieldError: BEETROOT_BLOCK 27.04 10:15:31 [Server] INFO at me.ryanhamshire.GriefPrevention.Claim.<init>(Claim.java:310) ~[?:?] 27.04 10:15:31 [Server] INFO at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:805) ~[?:?] 27.04 10:15:31 [Server] INFO at me.ryanhamshire.GriefPrevention.GriefPrevention.onCommand(GriefPrevention.java:1061) ~[?:?] 27.04 10:15:31 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-550ebac-7019900] 27.04 10:15:31 [Server] INFO ... 14 more

-----------------------------------------------------------------------------------------------------------
### Spigot/Craftbukkit/Paper and GriefPrevention version:
I have minecraft server 1.8 and GriefPrevention 16.6

```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here
```

**Comment by Jikoo** [comment]
Update your server or downgrade GP, the current version is for 1.11. Older GP versions can be found [here](https://dev.bukkit.org/projects/grief-prevention/files).

Next time, please post the trace in the right area, a code box would have made that so much less of a pain to read. Also, when reporting errors, disable Multicraft's rate limiting, it cuts out bits that are generally pretty important.

**Comment by bigpresh** [comment]
What @Jikoo said :)
