### ISSUE TITLE
Way to restrict stone pressure plate use?

### ISSUE THREAD

**Issue by different-name** [GriefPrevention/GriefPrevention#1236]
I've been playing on a prison server, and a they are using GriefPrevention and cannot disable stone pressure plate use within private claims. This is a huge issue as the server forces redstone harvesting for crops and anyone can come to my claim, stand on my plates and take my crops when they please. Please respond with a method of resolving this issue.

**Comment by RoboMWM** [comment]
How did you manage to make an issue without using the template.

Doesn't belong here anyways (transferring to discussions), and please check the FAQ. https://docs.griefprevention.com/faq/
