### ISSUE TITLE
Mobs despawn inside claim areas even when named.

### ISSUE THREAD

**Issue by Blzd87** [GriefPrevention/GriefPrevention#1239]
### What happened:
when getting a zombie inside a claim area for ( iron golem farm ) then name them set them up to scare villagers.... 
come back later and zombie gone? just despawns... i even tried them holding item or named or even used command to spawn them in with persistent so the dont despawn yet the zombie still gone...

### What was expected:
zombie to just stay there like normal minecraft without plugins... named.. will never despawn.

### Steps to reproduce:
not sure... ive set flags so monsters dont spawn in claims.. but there isnt a setting to stop them from despawning once they are inside a claim.

### Server and GriefPrevention version:
16.16.0

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

https://pastebin.com/aKArsY6i

**Comment by RoboMWM** [comment]
Doesn't happen on my server. Please include plugin list and server version.

**Comment by RoboMWM** [comment]
> ive set flags so monsters dont spawn in claims.. but there isnt a setting to stop them from despawning once they are inside a claim.

Yea, take this up with the addon developer.
