### ISSUE TITLE
Claim blocks not being awarded for legitimate playtime

### ISSUE THREAD

**Issue by Ashodinn** [GriefPrevention/GriefPrevention#1240]
Having an issue with a new player who has yet to receive any playtime awarded claim blocks.  Bonus blocks are working fine, but it does not seem to be registering any of the playtime awarded.  Confirmed not AFKing, not swimming, just regular playing has played over 10 hours at this point not receiving any claim blocks.  Server version 1.16.4, don't seem to be having the issue with any other players.  Considering blowing out profile & having them rejoin the server.  Thoughts?

**Comment by Jikoo** [comment]
Going to need the details from the bug template you deleted to be able to help. Debug logs would also be of use.

**Comment by Jikoo** [comment]
Closing due to lack of response. If you can reliably replicate this please open a new issue and fill out the template in addition to including the debug logs.
