### ISSUE TITLE
Granedes from Thermal Series can grief

### ISSUE THREAD

**Issue by jusobreira** [GriefPrevention/GriefPrevention#1243]
### What happened:
A few items from mods can grief inside the claim.

Granades - thermal series
Tiny TnT - applied Energistics
Rod of Shifting crust - Botania

(I assume this is a bug since i tested Atomic Disassembler and Infinity drill and they can't grief)
### What was expected:

They don't grief

### Steps to reproduce:

Instal the mods and grief inside the claim

### Server and GriefPrevention version:

![image](https://user-images.githubusercontent.com/10175304/107107812-43bb9900-6812-11eb-95cc-609a7e16e788.png)

### Stack trace/error or server log

```
There's no error

### GriefPrevention config.yml

There was no change at config.yml. Its the same as it came from bukkit site

### Plugin list (if applicable):



### Debugging steps attempted
<!--These will be checkboxes you can click after creating the issue)-->
- [Y ] I attempted running only GriefPrevention on the server
  - [Y] Issue still occurs even if GriefPrevention is the only plugin running
- [Y] I attempted testing for the issue on a new server
  - [Y] Issue still occurs even after testing on a new server
- [N] I attempted testing for the issue with the vanilla client (no mods)
  - [N] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by Jikoo** [comment]
See https://github.com/TechFortress/GriefPrevention/discussions/1105#discussioncomment-180745

If the server mod doesn't fire events, there is nothing GP can do about it.
