### ISSUE TITLE
Claiming does not work

### ISSUE THREAD

**Issue by Mikgreg** [GriefPrevention/GriefPrevention#125]
### What behaviour is expected:
When right clicking with a shovel on two corners a claim should be created.
### What behaviour is observed:
When right clicking with a shovel on one corner, it will be selected, however when you right click again on another corner nothing happens.
### Steps/models to reproduce:
https://www.youtube.com/watch?v=RDDQPIg1Z7c&feature=youtu.be

### Spigot/Craftbukkit/Paper and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paper 1075
GriefPrevention 11.6

**Comment by bigpresh** [comment]
Anything helpful appear in the logs when you do it?

**Comment by Mikgreg** [comment]
Ahh found some errors. Here you go:
https://hastebin.com/jumarikupe.vbs

**Comment by RoboMWM** [comment]
That's an ancient version.

**Comment by Mikgreg** [comment]
@robomwm This issue still continues on a fully updated version.

**Comment by Jikoo** [comment]
Reinstall Java - there's no reasonable explanation for `java.awt.Rectangle` being missing.

Alternatively, a bad solution would be to not use WG and the WG integration in GP. You should probably update all your plugins anyway though, considering how outdated your GP version was.
