### ISSUE TITLE
Anticheat compatability

### ISSUE THREAD

**Issue by freppp** [GriefPrevention/GriefPrevention#1257]
I have an anti-cheat on spigot (https://www.spigotmc.org/resources/vulcan-advanced-cheat-detection-1-7-1-16-5.83626/) and I have a few customers who are having lots of issues with grief prevention.

When you guys create fake blocks as part of showing land/border claims, there is almost no way for the server to know that they exist as they only exist client-sided for that user. For example, if people walk on them, they get flagged for fly, etc (since from what we see (we check directly from the packets as well, no events)) they are in the 'air' since we can't see the blocks or know that they are there at all. Same for Jesus, if there is a land claim over water, and they walk on the edge, they will be spammed with Jesus flags, since, again, from our perspective and the server, they are actually walking on water.

I was wondering if there was anything you guys could do about this - such as adding an option to disable this, or perhaps use particles or something that doesn't interfere so much with other plugins.

Thanks,
frap

**Comment by steviebeenz** [comment]
Confirmed this causes bugs with basically every Anticheat just Vulcan is so fast it flags more earlier.

Maybe add an API for Anticheats to integrate?

**Comment by bigpresh** [comment]
I don't think changing from golden blocks etc to particles is particularly likely, as so many players are already used to the current way, and in particular used to clicking on the golden blocks to resize claims etc.

The "fake blocks" are set by calling:

```java
player.sendBlockChange(element.location, element.visualizedBlock);
```

I'm not sure if that results in an event which anti-cheat plugins could catch to know about the block.  If not, I suppose one option would be for GP to fire an event itself which could be listened for - anti-cheat plugins which want to know about the temporary blocks which GP tells the client about could then catch that event.

**Comment by freppp** [comment]
Per Spigot's JavaDocs, "Send a block change. This fakes a block change packet for a user at a certain location. This will not actually change the world in any way." We're using World#getBlockAt for our collisions/bounding boxes, so we have no way of knowing when it's actually there. We could perhaps listen to PacketPlayOutBlockChange since that is what that method is sending, but an API/event or even just a method to check if they are near/on a claim border would definitely be easier and more lightweight.

Thanks for the quick reply.

**Comment by Jikoo** [comment]
Sounds like you might be able to slap together a workaround using the [VisualizationEvent](https://github.com/TechFortress/GriefPrevention/blob/8956a37e9dbfe31c9e1306653898d46f68adec8c/src/main/java/me/ryanhamshire/GriefPrevention/events/VisualizationEvent.java) - the Visualization in it should provide the blocks that will be changed clientside.

There's been talk about improving the visualization system (#558, #823), but personally I'm much more focused on the event funnel section of the GP roadmap. Would definitely like to see a way for addons to provide full visualization replacement - hijacking CUI, structure blocks, glowing block(-like invisible entities), and particles have all been mentioned before.

**Comment by RoboMWM** [comment]
Yea, wish there was a way for bukkit to natively notify plugins about fake blocks sent to clients, because every anticheat plugin struggles with this sort of stuff.

**Comment by RoboMWM** [comment]
this is a duplicate of an issue tho I'm almost definitely sure and discussion should be consolidated to such.
