### ISSUE TITLE
Villagers Won't Breed Inside Claims

### ISSUE THREAD

**Issue by Blzd87** [GriefPrevention/GriefPrevention#1258]
### What happened:
built a villager breeder inside claim... they show hearts then broken hearts then nothing happened.

### What was expected:
they breed and make baby villagers.

### Steps to reproduce:
put two villagers inside claim 4 beds stack carrots... 

### Server and GriefPrevention version:
16.17-1

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by Blzd87** [comment]
testing breeding villagers outside a claim and works straight away

**Comment by Nomaxx-marco** [comment]
its still a issue, how to fix it ?

**Comment by Jikoo** [comment]
Presumably another plugin with a bad integration.

From a similar issue:
> GP does not touch mob spawning at all unless you have the creative ruleset enabled, which you do not. Another plugin is at fault here. You can try using [EventDebugger](https://www.spigotmc.org/resources/eventdebugger.82055/) to track it down.
> 
>https://github.com/TechFortress/GriefPrevention/blob/d75b3cdd8fd51c67478bbf01ecfa0b78b8cdb41f/src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java#L531

In addition to this, GP blocks all spawns outside of claims with the creative ruleset enabled, so you definitely are not running into anything with GP itself.

If you're still having issues with only GP installed, please create a new issue and fill out the entire template - this one is missing a bunch of information that would have been useful.
