### ISSUE TITLE
Suggestion: claim nicknames

### ISSUE THREAD

**Issue by zedwick** [GriefPrevention/GriefPrevention#126]
As it can be difficult to remember what all those claims in /claimslist are, it would be handy to allow players to name their claims. Then when using /claimslist it could return both the claim nickname alongside their coordinates.

**Comment by RoboMWM** [comment]
This was suggested before, big_scary eventually declined due to it requiring a db change. Doable in an addon though, since every claim is tied to an ID.

I may print a claim id.

**Comment by zedwick** [comment]
Yeah, I thought it may be something for an add-on. Would you add a way to modify the output of the /claimslist command, or expect an add-on to completely replace it?

**Comment by bigpresh** [comment]
Definitely a feature I'd like, too!

I sort of see the point of it being an add-on, but at the same time, it seems annoying for an add-on to have to override and duplicate the claim listing abilities.  A single extra column in the DB schema, and a single extra optional line at the end of the claim flatfiles wouldn't be a massive deal, would it?  I'd certainly see it as a useful core feature.

**Comment by RoboMWM** [comment]
FYI, I made claimlistclassifier, an addon that allows for claim naming and listing. Could maybe also add clickable teleportation to the printed list if requested. https://github.com/RoboMWM/claimlistclassifier
