### ISSUE TITLE
Maximum Number Of Claims Per Player not working

### ISSUE THREAD

**Issue by eliyash31** [GriefPrevention/GriefPrevention#1267]
Hello I set the config to 
MaximumNumberOfClaimsPerPlayer: 1
then I restarted the server and deop myself 
tried claiming some blocks, but it doesn't limit me or the player with only 1 claim. I can still claim up to unlimited claims.
Note that I have 30000 initial claimblocks but all I want was to only let players with only 1 claim so that they just need to expand their land or area and not create many small areas.

**Comment by bigpresh** [comment]
Can you show us your actual config file, please?

It could be something as a minor formatting error e.g. bad indentation.

**Comment by eliyash31** [comment]
sure here
https://pastebin.com/BKMQxGen

**Comment by bigpresh** [comment]
Thanks, that config looks right, and parses fine with a YAML parser.

```
[davidp@supernova:~/tmp/gp-gh1267]$ perl -MYAML -E 'say YAML::LoadFile("supplied.yaml")->{GriefPrevention}{Claims}{MaximumNumberOfClaimsPerPlayer}'
1
```

Just to check, you don't have the `griefprevention.overrideclaimcountlimit` permission (either set directly, or via having `griefprevention.*` or `*`?  That's the only way I can see, from a quick check of the code, of this not working.

GP version and server version as requested in the issue template would be handy, but I don't think the handling of this option has changed for some time...

**Comment by eliyash31** [comment]
Oh thank you so much! I just checked from my owner permissions and I did got the griefprevention.admin 
I tried removing it or changing to a lower rank and it did warn me or disabled me from claiming another area thank you for your time :)

**Comment by bigpresh** [comment]
You're very welcome, thanks for confirming it's sorted! :)
