### ISSUE TITLE
[bug] No way to turn off stopping people from being set on fire

### ISSUE THREAD

**Issue by TomLewis** [GriefPrevention/GriefPrevention#127]
There is no way to disable the block to setting people on fire, theres one for placing lava, I don't want this block on, and I cant disable it.
players should be allowed to set each other on fire.
Can we please have a config option.

**Comment by bigpresh** [comment]
Setting on fire how?  AFAIAA, that's only prevented if PvP prevention is in effect (e.g. in an admin claim) - it should work fine outside of one. If not - more details?

**Comment by TomLewis** [comment]
Triggers the message:
  PlayerTooCloseForFire2:
    Text: You can't start a fire this close to another player.

Anywhere on the world, Even with the PVP featured disabled for all worlds.

**Comment by bigpresh** [comment]
The code that checks for other players being too near first checks:

`if(block.getType() == Material.FIRE && (!GriefPrevention.instance.pvpRulesApply(block.getWorld()) || !GriefPrevention.instance.config_pvp_allowFireNearPlayers))`

So, it looks like it's already configurable, and won't apply if PVP isn't blocked at the location they're placing the fire anyway?

**Comment by TomLewis** [comment]
I added allowFireNearPlayers: true
Under AllowLavaDumpingNearOtherPlayers: true.
This did not work, but again: RulesEnabledInWorld is set to false for all my worlds.

**Comment by bigpresh** [comment]
Hmm.  Re-reading that code, it looks like a logic fail - surely that `||` wants to be an `&&`?  Otherwise, either having that config setting not enabled, or PvP rules disabled, will make it check for fire near players.  I imagine the intention was to never check if the world isn't subject to PvP rules; if it *is* subject to PvP rules, still don' t check if allowFireNearPlayers is set to override it.

I think that ought to be:

```
if(block.getType() == Material.FIRE && 
    (GriefPrevention.instance.pvpRulesApply(block.getWorld())
     && !GriefPrevention.instance.config_pvp_allowFireNearPlayers))
```

... but I'm a bit tired, so may well be misunderstanding :)

**Comment by bigpresh** [comment]
Oh...:

```
[davidp@supersonic:~/dev/GriefPrevention]$ ack AllowFlintAndSteelNearOtherPlayers
src/me/ryanhamshire/GriefPrevention/GriefPrevention.java
753:        this.config_pvp_allowFireNearPlayers = config.getBoolean("GriefPrevention.PvP.AllowFlintAndSteelNearOtherPlayers", true);
852:        outConfig.set("GriefPrevention.PvP.AllowFlintAndSteelNearOtherPlayers", this.config_pvp_allowFireNearPlayers);
```

... I think the setting name in the config file is `AllowFlintAndSteelNearOtherPlayers`, which is translated into `config_pvp_allowFireNearPlayers` in the plugin.  (That's... misleading.)

**Comment by RoboMWM** [comment]
> Even with the PVP featured disabled for all worlds.

Yea, Big_Scary treats this as applying the non-PvP rules (or so he said when explaining this to me when I wondered why it was telling me in a creative world.) One of many reasons why I'm decoupling bloat from this...

**Comment by TomLewis** [comment]
Alright! As long as its known! I can tell my players its being worked on then.

**Comment by RoboMWM** [comment]
https://github.com/TechFortress/GriefPrevention/pull/371 should have fixed this.
