### ISSUE TITLE
this data base is not connecting to the plugin 

### ISSUE THREAD

**Issue by shawn3308** [GriefPrevention/GriefPrevention#1275]
![image](https://user-images.githubusercontent.com/60691117/108734094-19c5de80-7555-11eb-91e0-6dce835a0ce1.png)

**Comment by Jikoo** [comment]
Please post the DB connection information from your config (excluding login info, of course).

Without that info I'd say it looks like you're missing the protocol, i.e. `mysql://` or `mariadb://` if you happen to have installed the MariaDB JDBC adapter.

**Comment by Jikoo** [comment]
Closing due to lack of response. Please see https://github.com/TechFortress/GriefPrevention/wiki/MySQL-Setup#configure-mysql for how to properly configure MySQL. Note that MySQL support is pretty poor right now and likely will not improve much until v19.
