### ISSUE TITLE
Players can use expand claim command to claim outside of the worldborder

### ISSUE THREAD

**Issue by destro174** [GriefPrevention/GriefPrevention#1276]
### What happened:
players can use expand claim command to claim beyond the world border.

### What was expected:
I'd expect claims to stop at the world border and not go beyond it.

### Steps to reproduce:
https://www.youtube.com/watch?v=M5hXMaaHDqw

**Comment by RoboMWM** [comment]
I don't get the issue here, aren't they just wasting their own blocks?
