### ISSUE TITLE
players die in dissconect in pvp mode

### ISSUE THREAD

**Issue by Skyfay** [GriefPrevention/GriefPrevention#1279]
If my players fight, and then it says that they cannot open boxes and disconect, they die after the disconect.
Is that normal so the player dont dissconect in a fight?

**Comment by bigpresh** [comment]
Yes, that's a feature, controlled by the `PvP.PunishLogout` setting.

It's designed to discourage people from logging out when they're about to lose a PvP fight, but you can disable it if you don't want it.

**Comment by bigpresh** [comment]
(The effect stops affter `PvP.CombatTimeoutSeconds` settings, default 15 seconds, after last PvP damage.)
