### ISSUE TITLE
Claimbook not being given to new players

### ISSUE THREAD

**Issue by EnderSurge** [GriefPrevention/GriefPrevention#128]
New players are not being given the claimbook

Plugins:
CoreProtect
WorldEdit
OpenInv
PermissionsEx
Plugman
Races
MCMMO
Vault
Commandspy
WorldGuard
ProtocolLib
Essentials
CompatNCP
HolographicDisplayes
SuperVanish
NCP
ProtectionLib
FurnitureLib
DiceFurniture
GriefPrevention

**Comment by bigpresh** [comment]
What GP version, and Bukkit/Spigot etc version?

Anything useful in your logs?

is the `DeliverManuals` setting set to true in your config?

**Comment by EnderSurge** [comment]
GP version 16.6
CraftBukkit version git-Spigot-7d78b81-70bc70b (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Nothing useful I can find in logs

DeliverManuals is set to true

**Comment by RoboMWM** [comment]
Manuals are not delivered if less than 10 claims in total exist on the server. I probably will adjust this, but my guess is to avoid delivering manuals for servers that don't use GP for claims.
