### ISSUE TITLE
Can't Build Enderman Melon Farms

### ISSUE THREAD

**Issue by Praseodymium59Pr** [GriefPrevention/GriefPrevention#1282]
Enderman can't pick up melon blocks in the end dimension, preventing the farm from operating. Cant find any settings or where in the files to change to allow it to work.

**Comment by RoboMWM** [comment]
it's in the config, enderman grief or pickup blocks or something.

It would be very helpful if you could fill out the template next time that includes the config... hmm, idk how people keep bypassing it.

**Comment by RoboMWM** [comment]
Please don't do this, why people do this is beyond me.
