### ISSUE TITLE
Lava and Water buckets can be placed on claims

### ISSUE THREAD

**Issue by jay457** [GriefPrevention/GriefPrevention#1292]
### What happened:
Water and Lava could be placed anywhere in anyone's claim by any player with buckets, regardless of permissions/admin status. Any water and lava placed with buckets will interact with the claim's blocks (flowing, destroying crops, lava and water can create cobblestone). Administration claims remain protected, only player made claims suffer from this issue.

### What was expected:
Players are entirely incapable of placing lava and water unless it is their own claim or public land.

### Steps to reproduce:

- https://youtu.be/6vi2fufHSl8

1. Go to claim that you do not own or do not have access to.
2. Place water or lava.
3. Realize the gravity of the situation and destroy all nether portals leading to your claim.

### Server and GriefPrevention version:

[15:41:46] [Server thread/INFO]: This server is running CraftBukkit version 3016-Spigot-73fb609-ea050e6 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[15:41:46] [Server thread/INFO]: You are running the latest version

[15:42:13] [Server thread/INFO]: GriefPrevention version 16.17.1-2b69191

### Stack trace/error or server log
N/A - no errors or content logged

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    astral_plane: -1
    lost_seas: -1
  Claims:
    Mode:
      astral_plane: Disabled
      world_the_end: Survival
      world_nether: Survival
      world: Survival
      lost_seas: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: false
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 10000
    Claim Blocks Accrued Per Hour:
      Default: 2500
    Max Accrued Claim Blocks:
      Default: 2000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 365
      UnusedClaimDays: 365
      AllClaims:
        DaysInactive: 365
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome; /tpaccept
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
      astral_plane: true
      lost_seas: true
    ProtectFreshSpawns: false
    PunishLogout: true
    CombatTimeoutSeconds: 120
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/warp;/tpa;/back;/tpaccept
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: true
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE_SIMPLE
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: false
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: true
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: true
      Debug: true
      Muted Chat Messages: false


```

### Plugin list (if applicable):
[15:45:39] [Server thread/INFO]: Plugins (28): ServerRestart, LuckPerms, SetHome, Harbor, Skript, TradeShop, GFly, PlaceholderAPI, NametagEdit, Multiverse-Core, ProtocolLib, DeathMessagesPrime, Citizens, tpa, Dimensions, ImageOnMap, NoteBlockAPI, SleepVote, skript-reflect, EasyWarp, PowerRanks, Multiverse-Portals, ServerRestorer, GriefPrevention, ID-Library, skript-yaml, Vixio, BeautyQuests

### Debugging steps attempted

- [x] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server
- [x] I attempted testing for the issue with the vanilla client (no mods)
  - [x] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by RoboMWM** [comment]
lemme know once you finish with the last set of debugging steps.

**Comment by jay457** [comment]
Tried it out. Must not be playing nice with something else, because it worked fine alone.

**Comment by RoboMWM** [comment]
Yea, some other plugin must be messing around with bucketemptyevent (iirc I believe that's the event name).

**Comment by jay457** [comment]
Yep, problem was Dimensions. Thanks for the help.

**Comment by RoboMWM** [comment]
Interesting, thanks. Keep us posted on the solution.

**Comment by rain-py** [comment]
Having the same issue but have not found the reason im not using Dimensions.

**Comment by rain-py** [comment]
Can the lava and water placing be set to a higher priority then worldguard cause its happening just like this aswell and I believe worldguard is at fault here

**Comment by sukinaame** [comment]
So im thinking it has to do with worldguard and their priority on events

**Comment by jay457** [comment]
Dimensions uses an event for custom portal lighting, so I assume the priority was just wack. It has been fixed in the latest update of Dimensions.

**Comment by RoboMWM** [comment]
priority shouldn't matter if the event is canceled, so I guess it may've been uncanceling the event or something. Weird. Thanks for the update.
