### ISSUE TITLE
Claims moving to surface even if placed at bedrock

### ISSUE THREAD

**Issue by telepresencebot2** [GriefPrevention/GriefPrevention#1293]
### What happened:
After a server restart today all of my claims moved from bedrock to the surface, breaking all of my farms. I noticed that my kelp and sugarcane farms were no longer breaking plants. I was unable to unclaim from the level my farms were and had to go to the surface to update them. I tried unclaiming and reclaiming back at bedrock, and the yellow claim markers appeared. However the claim instantly moved to the surface again and the farms remained broken.
Everything has worked fine for around a week now since the plugin was installed, but this issue started after the daily server restart a few hours ago.

### What was expected:
Claims made at bedrock should encase the entire y dimension and remain that way.

### Steps to reproduce:
1. place a claim at bedrock underground
2. switch off of shovel and tap the claim corner to reset the visual indicator
3. switch back to shovel and notice that the claim is not shown (it is at the surface)
4. test with a piston, it should be able to move blocks, but can't

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 1.16.5-R0.1-SNAPSHOT
Paste of `/version GriefPrevention`: 16.17.1-2b69191

### Stack trace/error or server log

I am not the server admin :/

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Plugin list (if applicable):
server is vanilla otherwise

### Debugging steps attempted

- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by RoboMWM** [comment]
Claims are 2D. They always go to upwards to infinity and beyond.

**Comment by RoboMWM** [comment]
3D subclaims are a potential thing that's a common request (see faq I think I linked them there? I'll have to check), but will be provided via addon since that's added complexity.
