### ISSUE TITLE
ProtectPetsOutsideLandClaims config setting ambiguity

### ISSUE THREAD

**Issue by FrankHeijden** [GriefPrevention/GriefPrevention#1295]
GriefPrevention has a setting **GriefPrevention.PvP.ProtectPetsOutsideLandClaims**, but the code that provides this does not just takes care of pets outside the claim, but also inside the claim. If this setting is toggled off, players with trust are allowed to kill other player's non-wolf pets (such as Parrots, Cats) inside other player's claims:

https://github.com/TechFortress/GriefPrevention/blob/b3774efad84f666d01c0b793fc1646c155d96c96/src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java#L1012

**Comment by Jikoo** [comment]
This was resolved by #2040 and subsequent tweaks. Did spot another bug after #2220 where environmental damage isn't cancelled on pets while double checking this, so I guess I have to get off my lazy butt and de-duplicate the code in there again.
