### ISSUE TITLE
Failures of portal trap rescue system wasting players' time

### ISSUE THREAD

**Issue by Jikoo** [GriefPrevention/GriefPrevention#13]
The portal trap feature, while very nice, is causing my players a bit of grief by considering them trapped and "rescuing" when they're attempting to enter a different portal.
Ex.: Player enters the nether from a portal at 100, 50, 100 and walks to a portal at 100, 50, -100. This takes a minute, so while they wait in the next portal to be teleported, they are rescued back to their original entry point.

At first, I was going to propose that you use a method to find the center of the portal from the block used to teleport. Then, simply compare the current portal's center to the original portal's center, rescuing if it matches. Unfortunately, it would not properly handle hallways built of portals - build 2 or more portals staggered or of different sizes next to each other, and the functionality potentially breaks down.

Instead, I propose that GP's portal trap rescue be converted to a 2-task system:
1. First task is started when a player passes through a portal.
2. Original task completes. If player is not in a portal, return.
3. Warn the player that they will be rescued if they are in a portal in 5 seconds.
4. Start a new timer to do the actual rescuing.

In addition, either task, if scheduled, should be cancelled if the player travels through a portal - I've been rescued back to the overworld in a different location when attempting to re-enter the nether.

I'm very hesitant to fiddle with GP as it's always been riddled with practice I dislike, but if I need to do it to make this happen I'd be willing to open a PR.

**Comment by Jikoo** [comment]
For reference for my original idea, here's a snippet from a TravelAgent of mine:

``` Java
    @Override
    public Location findPortal(Location location) {
        /*
         * searchRadius is world-dependent due to nether:overworld being 1:8
         * That's modified elsewhere, this being a TravelAgent implementation.
         */
        Block block = location.getBlock();
        for (int dX = -searchRadius; dX <= searchRadius; dX++) {
            // When travelling to the overworld, allow 2 blocks of y-forgiveness in case of rounding errors
            int searchY = location.getWorld().getEnvironment() == Environment.NORMAL ? 3 : 1;
            for (int dY = 0; dY < searchY; ++dY) {
                for (int dZ = -searchRadius; dZ <= searchRadius; dZ++) {
                    Block portal = block.getRelative(dX, dY, dZ);
                    if (portal.getType() == Material.PORTAL) {
                        Location center = findCenter(portal);
                        center.setYaw(location.getYaw());
                        center.setPitch(location.getPitch());
                        return center;
                    }
                }
            }
        }
        return null;
    }

    public Location findCenter(Block portal) {
        if (portal == null) {
            return null;
        }
        double minX = 0;
        while (portal.getRelative((int) minX - 1, 0, 0).getType() == Material.PORTAL) {
            minX -= 1;
        }
        double maxX = 0;
        while (portal.getRelative((int) maxX + 1, 0, 0).getType() == Material.PORTAL) {
            maxX += 1;
        }
        double minY = 0;
        while (portal.getRelative(0, (int) minY - 1, 0).getType() == Material.PORTAL) {
            minY -= 1;
        }
        double minZ = 0;
        while (portal.getRelative(0, 0, (int) minZ - 1).getType() == Material.PORTAL) {
            minZ -= 1;
        }
        double maxZ = 0;
        while (portal.getRelative(0, 0, (int) maxZ + 1).getType() == Material.PORTAL) {
            maxZ += 1;
        }
        double x = portal.getX() + (maxX + 1 + minX) / 2.0;
        double y = portal.getY() + minY + 0.1;
        double z = portal.getZ() + (maxZ + 1 + minZ) / 2.0;
        return new Location(portal.getWorld(), x, y, z);
    }
```

You can see where it'd fall short. Any collection of portals that isn't a cuboid would have several areas that would not count as the same portal even though the player would be incapable of leaving.

**Comment by RoboMWM** [comment]
> Warn the player that they will be rescued if they are in a portal in 5 seconds.

I'd like to avoid this if at all possible.

Since GP already stores the location of the original portal, I guess it doesn't hurt to store the destination. Then, if and only if considered to be trapped will the system then perform a distance check. Though I wonder then if it'd be faster to check distance first, or getting the player's location and checking what block they are in.

**Comment by Jikoo** [comment]
The problem is that it's hard to identify a single portal destination when multiple portals can form so many shapes. Storing the destination alone wouldn't prevent a determined person creating a portal trap.
If you're opposed to a warning, perhaps instead periodic checks (say, every 5 seconds?) which verify that the player is still considered inside a portal. Last I checked the default rescue timer is a minute, and my problem is that players quite often happen to be attempting a return exactly when it finishes. A periodic check would reveal that they're quite safe.

**Comment by RoboMWM** [comment]
> perhaps instead periodic checks

As far as I know (and what I've seen in timings) is that it does get quite expensive when it detects a person trapped in a portal.

The portal rescue task is 30 seconds, which I may adjust to 20 (since the initial 10 seconds caused issues for players with poor internet connection, often taking 10 seconds or so to load chunks after teleporting).

**Comment by RoboMWM** [comment]
> perhaps instead periodic checks

As far as I know (and what I've seen in timings) is that it does get quite expensive when it detects a person trapped in a portal.

As for location, yea, I see what you mean now.

The portal rescue task is 30 seconds, which I may adjust to 20 (since the initial 10 seconds caused issues for players with poor internet connection, often taking 10 seconds or so to load chunks after teleporting).

Alternatively, I can make the portal rescue task only execute on logout, since most players seem to attempt to do that when they're stuck. Or... I could cancel the previous rescue task when they teleport again (since I'm assuming most of the rescuing is happening after they reach their final destination? Since it takes a while for chunks to load on the client before they're registered as moving out of the portal, therefore they're more likely often to be rescued after, not before teleport.)

**Comment by Jikoo** [comment]
Fair enough, it does have to be efficient, GP serves a lot of large servers. I'll probably end up implementing my own solution and disabling GP's portal trap checks then, figured that based on the quantity of negative feedback I get from regulars it should be mentioned.

If the inefficiency issue is related to getting the material of the blocks the player occupies, it's "safe" to asynchronously read the state of the blocks so long as you're not loading chunks, though if you don't want to fiddle with the API asynchronously I completely understand.

Definitely worth cancelling the rescue if they teleport, at very least. That would fix the vast majority of my issues with it due to my setup (/spawn in my nether leads to a nether hub, not the main spawn, so a lot of people use it as a shortcut) though it wouldn't fix issues with players actually walking to another portal.

Executing on logout unfortunately seems to break every couple versions, the PlayerQuitEvent gets called after the player's data has been saved. I can't speak for its current state because I no longer depend on it, but for at least a month after 1.10's release, any modifications made - teleports, inventory editing, whatnot - wouldn't persist.

**Comment by RoboMWM** [comment]
> Executing on logout unfortunately seems to break every couple versions, the PlayerQuitEvent gets called after the player's data has been saved. I can't speak for its current state because I no longer depend on it, but for at least a month after 1.10's release, any modifications made - teleports, inventory editing, whatnot - wouldn't persist.

I'm assuming you are talking about CB/the vanilla server. However, how GP operates regarding the rescue task is that it determines if a player is in a portal on logout (provided the task has not elapsed, iirc), and if so, stores its rescue location in the player's data. The teleport method is invoked when they join.

That being said I'm eager to resolve "false positives," just trying to find a good way to go about this.

> though it wouldn't fix issues with players actually walking to another portal.

~~Doesn't it take only like a second or two for the player to teleport through? They'd have to have exceptionally unfortunate timing for this to be the case. (Whereas I mentioned before it can take a lot longer for a player to leave a portal.)~~ According to the wiki, it seems to take 4 seconds.

I could also try monitoring some sort of event (successful interactions or chat?) and cancel the task that way.

**Comment by RoboMWM** [comment]
I did a quick look around, and it seems some other plugins do things like removing the portal blocks themselves. Not sure how much I'd like to be iterating, setting, and storing blocks, especially with the varying patterns (and wouldn't really be all that different than your original suggestion of determining the nether portal's center).

I think I have a solution that might work though. How about when the player is rescued, a message is printed that they can run a command to revert back to their original spot, in the case they actually weren't trapped? (And if they do run the command, should we schedule the portal rescue task again, in case they actually were trapped but dumbly ran the command?)

**Comment by Jikoo** [comment]
Sounds good to me. Definitely will solve the problem, plus it adds transparency so users know what's going on.

**Comment by RoboMWM** [comment]
And thoughts on

> And if they do run the command, should we schedule the portal rescue task again, in case they actually were trapped but dumbly ran the command?

**Comment by Jikoo** [comment]
Probably a good idea, as much as I hate to admit it. Users tend to do silly things.

**Comment by RoboMWM** [comment]
Interestingly, if I run /undorescue and am teleported back to the portal in question, I end up going through the portal. It appears the server recognizes when the player has "left" a portal block, and this data is saved.

If there's a way to clear this value (hopefully I don't have to rely on NMS) then we can get rid of this portal trap issue once and for all without having to do manual teleports and such.

**Comment by RoboMWM** [comment]
ooooooh... entityportalexitevent. This is getting good.

**Comment by Jikoo** [comment]
I'm pretty sure the EntityPortalExitEvent is fired right after the teleport completes, but I'll do some reading to see if I can easily find where the value for being inside a portal is saved.

**Comment by RoboMWM** [comment]
Yea, did more testing, you're right about that

**Comment by Jikoo** [comment]
Looks like the portal cooldown is not exposed.

While inside a portal, `Entity#e(BlockPosition)` is called each tick, which sets `Entity#portalCooldown` to `Entity#aE()` (always returns 10 for players, overridden in `EntityHuman`). Each tick, `Entity#H()` (overridden in `EntityPlayer`) is called, which reduces the value by 1 if the player is not temporarily invincible due to a world change.

The portal mechanic itself is handled in `Entity#U()`. If `Entity#al` is true, teleporting has started. In `Entity#V()` ticks (tracked by `Entity#am`) the entity will be teleported.

**Comment by RoboMWM** [comment]
> Looks like the portal cooldown is not exposed

Meaning would have to do reflection/some sort to change this? Oh well, thanks for looking into it though.

> Each tick, Entity#H() (overridden in EntityPlayer) is called, which reduces the value by 1 if the player is not temporarily invincible due to a world change.

Is this related to the portal cooldown?

**Comment by Jikoo** [comment]
> Is this related to the portal cooldown?

Yeah, that's where the cooldown is reduced. `Entity#H()` is called in `Entity#U()`, which is the base tick method. The player needs to be out of a portal for 10 ticks (or, more accurately, any portal blocks they happen to be in need to not be ticked) for the cooldown to completely expire.

I've opened [SPIGOT-2705](https://hub.spigotmc.org/jira/browse/SPIGOT-2705) requesting the API addition (really should sign the CLA and get my own Stash account, ugh) in the meantime.

**Comment by RoboMWM** [comment]
> (really should sign the CLA and get my own Stash account, ugh) in the meantime.

Or PR to paper :)

**Comment by RoboMWM** [comment]
Anyways, the latest commit should have this all implemented. I did some preliminary tests, and other than that interesting quirk I've found (which in that case, I probably don't need to do a "portal trap check" after they run the command), would like some feedback on its functionality (as well as testing for any bugs).

**Comment by Jikoo** [comment]
I'll check it out tomorrow morning, only just got back and it's somewhat late for me now. Looks like my ticket was closed, the new methods were added in [ae93d4fb492](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/ae93d4fb492bc737466666087dcd49c9f775e40c).

**Comment by RoboMWM** [comment]
Oh, looks like it's been added already. Neat. Now just need to ping the Paper people to update upstream.

**Comment by RoboMWM** [comment]
~~Alright, whenever I get to play with this (i.e. when paper merges), I'm thinking of doing two things~~
~~\- player.setPortalCooldown(0) on player quit (or join, since it might not be saved as you stated).~~
~~\- schedule a task to set the player's portal cooldown to 0 some time after teleporting via a nether portal (20 seconds?)~~

~~This, coupled with any existing task being canceled on teleport should basically prevent any possibility of an "unnecessary rescue" since I assume the cooldown is only applied after teleporting, not before.~~

~~Therefore I will remove the just-added /undorescue command and corresponding message.~~

~~Did I miss anything?~~

Either maven repo hasn't updated, or that stuff is only for the CraftPlayer class, not the API...? (Would really like to avoid depending on CB jar.) It's not showing up in my IDE despite deleting my local maven repo.

**Comment by Jikoo** [comment]
It was added to Bukkit as well, [450225fe17a](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/450225fe17a930d7bb0de2d646c4a892d5bdcd7e). You're right though, I've just forced a snapshot update and it's not showing up in Maven. Recompiling Spigot results in version 570526c-c1b529e, 2 versions behind.

I definitely like your idea of implementation as soon as the API is actually available, sounds perfect. I'll check it out in its current state anyway just to see if I can break it, but otherwise I think we're set.

**Comment by Jikoo** [comment]
Managed to break the existing option with /undorescue pretty quickly. Entered the nether, built a trap, exited the nether while setting the trap, and then re-entered the nether. When I was rescued, I was rescued back inside of the trap I'd set in the nether while already inside of it.
Here's [a recording](https://www.youtube.com/watch?v=dy-KN1JFncw). Obviously stupid, but it does break the intended behavior - I was rescued after the second portal trip to the first trip's original portal position.
I'd swear that the PlayerPortalEvent counts as a teleport and also fires the PlayerTeleportEvent, shouldn't the original trap rescue from the nether be cancelled, or is that feature not already included?

**Comment by RoboMWM** [comment]
Hmm, should be canceled here: https://github.com/TechFortress/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/GriefPrevention.java#L3674

Otherwise wouldn't it be trying to rescue you twice? I also wonder if it has anything to do with you being in creative... I only tested in survival gamemode.

Unless the hashmap `put` method doesn't override an existing entry (I'm under the assumption it does)...

**Comment by RoboMWM** [comment]
Alright, just added it. Go ahead and let me know how that works.

**Comment by RoboMWM** [comment]
Oh, and also make sure that both worlds have a claim mode - this is probably why you weren't rescued from the nether, since the nether is likely set to disabled claims, while the overworld isn't.

I may remove this check...

**Comment by RoboMWM** [comment]
Details as to why this check was in place (my guess): https://github.com/TechFortress/GriefPrevention/commit/b7162823e8a10d76b113a0d8642e2f864bc8aa1e

Otherwise, I think it should be working now. Let me know otherwise.

**Comment by Jikoo** [comment]
Sorry I've been quiet on this, yesterday was quite busy.

> Oh, and also make sure that both worlds have a claim mode - this is probably why you weren't rescued from the nether, since the nether is likely set to disabled claims, while the overworld isn't.

Yep, I was using the default config, claims in the nether were not enabled.

I'll get to testing, looks good though.
Edit: Works perfectly, thanks!
