### ISSUE TITLE
Fireballs break blocks inside claims, there not blocked. 

### ISSUE THREAD

**Issue by TomLewis** [GriefPrevention/GriefPrevention#130]
Bit of a big one here, Fireballs can be used to Grief Claims, Might need a hotfix for this.

Fireballs can be used outside of claims to fire into claims and burn/break blocks, no matter if explosions are turned on or off. No siege needed, just straight up breaks blocks, both nether and overworld.

Config: https://pastebin.com/yRB5gz0e

Heres a video recorded by a member of staff on my server who discovered and reported it.

https://www.youtube.com/watch?v=xcXMhWiHsN4&feature=youtu.be

**Comment by bigpresh** [comment]
Can you confirm that, by "fireballs" you mean the vanilla fire charge item, not something from some other plugin?

I've never seen fire charges cause damage in claims, but I'll try to reproduce it.

**Comment by TomLewis** [comment]
@bigpresh Yes fireballs, No no "OtherExplosion" type deal, Normal fireballs are breaking claimed land, this is why I posted the issue.
Nether have I, I assume its been broken from an update at some point, you can see it working in the video I linked:
https://youtu.be/xcXMhWiHsN4?t=184

**Comment by RoboMWM** [comment]
I'm on 1.11.2, Paper build 1100, GP 16.7.1, cannot reproduce. Wood logs don't disappear. http://i.imgur.com/zhEHbPd.png

**Comment by Jikoo** [comment]
Fireballs do not instantly break flammable blocks in that manner, they set fires. You have another plugin modifying fireball or fire behavior.
