### ISSUE TITLE
Create mod deployer FakePlayer can't be trusted. Only with /trust public

### ISSUE THREAD

**Issue by muriplz** [GriefPrevention/GriefPrevention#1302]
### What happened:

Deployers from Create mod can't place saplings inside claims. (when they are inside of course).
I tried /trust public, and is the only thing that works, i cant /trust the deployer's fake player with UUID 9e2faded-cafe-4ec2-c314-dad129ae971d.
### What was expected:
I expect the deployer to be able to place saplings, if not a main feature of the mod can be exposed.

### Steps to reproduce:
1. Install the Create mod 0.3 and grief prevention.
2. Make a claimed area.
3. Try to make a deployer place saplings inside it. (Easiest way: with Hand Crank)

### Server and GriefPrevention version:

Paste of `/version`: This server is running Mohist version 1.16.5-384 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.0.46)
Paste of `/version GriefPrevention`:  GriefPrevention v16.17.1-2b69191

### Stack trace/error or server log

There is no logs, it just won't place it.

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by RoboMWM** [comment]
Mod configuration was dropped with the MC 1.13 material flattening. You'll need an addon to deal with these.
