### ISSUE TITLE
Players can claim in Worldguard regions

### ISSUE THREAD

**Issue by DoodieDev** [GriefPrevention/GriefPrevention#1308]
Regular players can create a claim in a worldguard region.

I have this set in the config `CreationRequiresWorldGuardBuildPermission: true`
The `build` flag is also set to deny in the region.

**Versions:**
PaperSpigot: git-Paper-530 (MC: 1.16.5)
GriefPrevention: 16.17.1-2b69191
WorldGuard: 7.0.4+f7ff984

**Comment by RoboMWM** [comment]
believe it should be passthrough flag.

**Comment by DoodieDev** [comment]
> believe it should be passthrough flag.

I just tried setting the `passthrough` flag to deny & allow in my region, neither changes anything. They can still create claims.

**Comment by RoboMWM** [comment]
hmm, well for now you can use an admin claim to stop that stuff.

**Comment by DoodieDev** [comment]
> hmm, well for now you can use an admin claim to stop that stuff.

That is true, but the thing is, I have a marketplace in my spawn, which consists of 9 regions that players can rent & create a shop.
Claiming the entire spawn using an admin claim will do so they cannot build in their market plots.

**Comment by Jikoo** [comment]
>That is true, but the thing is, I have a marketplace in my spawn, which consists of 9 regions that players can rent & create a shop.
Claiming the entire spawn using an admin claim will do so they cannot build in their market plots.

Trust public in the admin region. GP won't un-cancel events WG cancels, so as long as WG is preventing un-authorized actions there the GP claim will solely prevent creation of GP claims.

**Comment by DoodieDev** [comment]
> > That is true, but the thing is, I have a marketplace in my spawn, which consists of 9 regions that players can rent & create a shop.
> > Claiming the entire spawn using an admin claim will do so they cannot build in their market plots.
> 
> Trust public in the admin region. GP won't un-cancel events WG cancels, so as long as WG is preventing un-authorized actions there the GP claim will solely prevent creation of GP claims.

Thank you so much, that worked.
Have a nice day!

**Comment by RoboMWM** [comment]
yea, the other solution is to get a region protection-compatible shop plugin like PrettySimpleShop which was designed for cases like these.
