### ISSUE TITLE
TnT can be lighted with fire bow on claimed land when they aren't trusted

### ISSUE THREAD

**Issue by Fonzee9** [GriefPrevention/GriefPrevention#131]
### What behaviour is expected:
It stops the arrow and says you don't have permission
### What behaviour is observed:
The fire bow lighted the tnt

Version:
Spigot 1.12 pre 2 also happened on Spigot 1.11.2

**Comment by bigpresh** [comment]
Please supply the versions you're using, and any other plugins in use, etc. (The info requested in the new issue template, which is there for a reason.)

**Comment by RoboMWM** [comment]
@Fonzee9 As per template, `/version GriefPrevention` and other plugins in use.

Otherwise I'm guessing you're using an older version.

**Comment by Fonzee9** [comment]
I am using the latest version of GriefPrevention and the problem happens the only plugin installed is GriefPrevention i tested this on my test server.

**Comment by RoboMWM** [comment]
I need numbers, not "latest" as per template.

**Comment by Fonzee9** [comment]
I am using 16.7.1

**Comment by RoboMWM** [comment]
To anyone concerned about this - remember that claims are protected from explosions by default - and this is no exception to that rule (nothing gets blown up inside the claim).

**Comment by Fonzee9** [comment]
True the bug only works when claimexplosions is on in the players land. Then shoot a tnt beside it and boom goes the claim.

**Comment by RoboMWM** [comment]
Hmm, will need to see if it's possible to determine who ignited TNT if the source is an arrow. IIRC there is no "ignite" event that fires on ignition (there is something that fires just before explosion, but it's way too late at this time).

**Comment by RoboMWM** [comment]
So, it seems doable(?), but a bit of work to test and debug. A variety of events are fired, and not sure whether canceling these would be sufficient to stop the TNT from being ignited (along with only some having a source entity). 

```
[16:45:00] [Server thread/INFO]: [EventDebug] Event fired: EntityCombustEvent
getDuration: 100
isCancelled: false
getEntity: CraftArrow
getEntityType: ARROW
[16:45:00] [Server thread/INFO]: [EventDebug] Event fired: EntityCombustEvent
getDuration: 100
isCancelled: false
getEntity: CraftArrow
getEntityType: ARROW
[16:45:00] [Server thread/INFO]: [EventDebug] Event fired: EntityCombustEvent
getDuration: 100
isCancelled: false
getEntity: CraftArrow
getEntityType: ARROW
[16:45:00] [Server thread/INFO]: [EventDebug] Event fired: EntityShootBowEvent
getForce: 1.0
getBow: LEGACY_BOW(0) x1
getArrowItem: LEGACY_ARROW(0) x1
isCancelled: false
getEntity: RoboMWM
getEntity: RoboMWM
getProjectile: CraftArrow
getConsumeArrow: true
getEntityType: PLAYER
[16:45:00] [Server thread/INFO]: [EventDebug] Event fired: ProjectileLaunchEvent
isCancelled: false
getEntity: CraftArrow
getEntity: CraftArrow
getEntityType: ARROW
[16:45:00] [Server thread/INFO]: [EventDebug] Event fired: ProjectileHitEvent
getHitBlock: TNT at Location{world=CraftWorld{name=cyberworld},x=577.0,y=30.0,z=470.0,pitch=0.0,yaw=0.0}
getHitBlockFace: UP
getEntity: CraftArrow
getEntity: CraftArrow
getEntityType: ARROW
[16:45:00] [Server thread/INFO]: [EventDebug] Event fired: EntityChangeBlockEvent
isCancelled: false
getBlock: TNT at Location{world=CraftWorld{name=cyberworld},x=577.0,y=30.0,z=470.0,pitch=0.0,yaw=0.0}
getBlockData: CraftBlockData{minecraft:air}
getTo: AIR
getEntity: CraftArrow
getEntityType: ARROW
[16:45:00] [Server thread/INFO]: [EventDebug] Event fired: EntityChangeBlockEvent
isCancelled: false
getBlock: TNT at Location{world=CraftWorld{name=cyberworld},x=577.0,y=30.0,z=470.0,pitch=0.0,yaw=0.0}
getBlockData: CraftBlockData{minecraft:air}
getTo: AIR
getEntity: CraftArrow
getEntityType: ARROW
[16:45:01] [Server thread/INFO]: [EventDebug] Event fired: ProjectileHitEvent
getHitBlock: STONE at Location{world=CraftWorld{name=cyberworld},x=577.0,y=29.0,z=470.0,pitch=0.0,yaw=0.0}
getHitBlockFace: UP
getEntity: CraftArrow
getEntity: CraftArrow
getEntityType: ARROW
```

**Comment by bigpresh** [comment]
I would *guess* that the `EntityChangeBlockEvent` event is the one which turns the TNT into a "lit TNT" block, and `getEntity()` on it will give you the `CraftArrow` from which you can get the shooter with `getShooter()`.

I'll try to verify that if I get a chance soon, but that's my gut feeling, from having played around a little with finding the shooter of arrows to implement temporary PvP protection measures in a custom plugin we run.

**Comment by RoboMWM** [comment]
No, that just states that the TNT block has been changed (removed) via an entity (the arrow). Don't think canceling that will prevent the PrimedTNT from spawning.

**Comment by Jikoo** [comment]
Closing in favor of #1401
