### ISSUE TITLE
I disabled pvp in claims but it still works 

### ISSUE THREAD

**Issue by chariciliy** [GriefPrevention/GriefPrevention#1315]
PvP:
    RulesEnabledInWorld:
      Wandering Isles: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: false 
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
What have i done wrong

**Comment by RoboMWM** [comment]
```
PvP:
RulesEnabledInWorld:
Wandering Isles: false
```

set that to true.

and next time use/don't delete the template so the formatting doesn't get screwed up.
