### ISSUE TITLE
Deleting claims ends up deleteing builds

### ISSUE THREAD

**Issue by ALufkin24** [GriefPrevention/GriefPrevention#132]
### What behaviour is expected: Delete claims command.
_What you expected to see_
### What behaviour is observed: When I did /deleteclaim, it delete the build that I didn't want to do.
_What you actually saw_
### Steps/models to reproduce: I was standing inside claim and did the command /deleteclaim. It deleted the building with it. I was wanting to delete the claim not the build. :(
_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_

### Spigot/Craftbukkit/Paper and GriefPrevention version: Version: 16.4
___This can be found by running `/version` and `/version GriefPrevention` on your server.___

### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here
```

**Comment by RoboMWM** [comment]
Use `/abandonclaim`

`/deleteclaim` is an administrative command, and will cleanup claims.

**Comment by ALufkin24** [comment]
Thank you!

**Comment by nachos992** [comment]
Is there a way to get the build back?

**Comment by bigpresh** [comment]
> Is there a way to get the build back?

I believe restoring the data files for that chunk from your backups would be the only way.  Not for the faint-hearted, and would also restore anything else that happened within that same chunk in the meantime, so be careful if two players have built close together and overlap on a chunk :)
