### ISSUE TITLE
transferclaim bug

### ISSUE THREAD

**Issue by MightyEclipseAWE** [GriefPrevention/GriefPrevention#1320]
### What happened:
/transferclaim without a name transfers the claim to nothing. 

### What was expected:
An Errormessage warning to type a name after transferclaim
### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Claim some blocks
2. type /transferclaim
3. done. Claim is owned by nothing

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: This server is running Paper version git-Paper-"d4532f7e7" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

You are running the latest version

Previous version: git-Paper-"ff9c82444" (MC: 1.16.5) 

Paste of `/version GriefPrevention`:  GriefPrevention version 16.17.1-2b69191 

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by RoboMWM** [comment]
intended feature. Without a parameter, it's converted into an admin claim.

**Comment by MightyEclipseAWE** [comment]
is there a way i can deactivate this feature? because it can cause problems if a player just trys the command

**Comment by Jikoo** [comment]
`/transferclaim` is an admin command, it's not designed for regular player usage. See the writeup of the suggestion in #1052 for problems with giving it to regular players.

**Comment by MightyEclipseAWE** [comment]
Ah okay thx.

Adam ***@***.***> schrieb am Do., 18. März 2021, 00:31:
