### ISSUE TITLE
claim dose not work under ground 

### ISSUE THREAD

**Issue by CoolBoyRule** [GriefPrevention/GriefPrevention#1322]
above ground is works as intended but under is it is like there is no claim

**Comment by bigpresh** [comment]
Covered in the FAQ at https://github.com/TechFortress/GriefPrevention/discussions/752 under "The ground underneath my player's claims isn't being protected!" - Read the documentation for `ExtendIntoGroundDistance`: https://github.com/TechFortress/GriefPrevention/wiki/Setup-and-Configuration#claim-limits for details.
