### ISSUE TITLE
Player Build/Break

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#1323]
HEY THERE,
This plugin is GR8 but i got a question that how do i let players build on land without claiming it
when players try to break or place blocks it says u must claim land to break/place block here.... smthin
how do i fix it
if i have to fix it using cmnd thn can u plz reply with the command or if i have to config it from config.yml thn plz reply with the line number in config.yml or if any other... plz help me :)

The plugin version is the latest version and game version is 1.16.5

**Comment by bigpresh** [comment]
You'll want to use `Survival` rather than `Creative` or `SurvivalRequiringClaims` under claims.mode in your config.yml - full details at https://github.com/TechFortress/GriefPrevention/wiki/Setup-and-Configuration#limiting-which-worlds-griefprevention-runs-on

**Comment by ghost** [comment]
So does it mean if I change the mode to Survival for the world Survival rhn ppl can build/break blocks without claiming the land @bigpresh

**Comment by RoboMWM** [comment]
yes.
