### ISSUE TITLE
Right clicking in admin claim causes spam

### ISSUE THREAD

**Issue by JadeiteWren** [GriefPrevention/GriefPrevention#133]
fml-server-latest.log file
https://gist.github.com/anonymous/63734fe16ba367417f5bbbb9c0681e6a

current flags in the admin claim
http://imgur.com/a/AERHR

Verbose Tracker on player when they right click
https://git.io/v9hgU

So I have an adminclaim with no one currently added to the trust but I'm allowing them to access things through interact-block/entity-primary/secondary. 

However, if they right click any item that isn't added to their interact list, they get spammed with 'You don't have an administrator's permission' twice in a row.

---------------------------

Jaedeite - Today at 4:56 AM
https://git.io/v9hgU

I have no one trusted to my admin claim. All containers/tables/pixelmon items are set to true for accessing via 'interact-block-secondary.

However, whenever someone left or right clicks anything else in spawn, they get spammed with 'do not have admin perms' to do this in spawn.
Gist
LuckPerms Verbose Checking Output
LuckPerms Verbose Checking Output

DeathVirus - Today at 7:24 AM
Screenshot of flags? And are you on the latest everything?

Jaedeite - Today at 11:52 AM
DeathVirus - Today at 7:24 AM
Screenshot of flags? And are you on the latest everything?

Give me a moment to screenshot the flags. And yes we are. We just updated all the major plugins we have to the latest versions.(edited)
http://imgur.com/a/AERHR
Are the current flags.

bloodshot - Today at 11:59 AM
@Jaedeite you need to post your fml-server-latest.log as stated in #rules

Jaedeite - Today at 11:59 AM
Ah sorry, give me a minute, I'll do that too.

Jaedeite - Today at 12:16 PM
https://gist.github.com/anonymous/63734fe16ba367417f5bbbb9c0681e6a
Gist
Hey it's a file.
Hey it's a file.
Sorry for the wait and not posting it originally
Pretty much when anyone who isn't op right clicks anything that isn't on the list for interact-block-secondary, they get the message 'You don't have an admin's perms to use this' twice in a row.(edited)

bloodshot - Today at 1:01 PM
thats because you can interact with main or offhand
just file a bug on tracker

**Comment by RoboMWM** [comment]
Need all the other info you deleted from the issue template.

**Comment by RoboMWM** [comment]
Wait a minute... spongepowered... Yea this the (original) bukkit plugin, not the sponge plugin.

(Hmm, it seems that forked version of GriefPrevention isn't as simple as the original is.)
