### ISSUE TITLE
Claims underground config doesnt work...

### ISSUE THREAD

**Issue by itskiiv** [GriefPrevention/GriefPrevention#1330]
Claims that go all the way to bedrock and no way to change that in the config. There is one option to set a the underground lvl but it doesnt work in game. It is default 5 but goes all the way down to bedrock in game. I tried changing it to multiple lvls does nothing.

**Comment by RoboMWM** [comment]
Invalid ticket format (lacks necessary information to determine problem). Please fill out the template you deleted.
