### ISSUE TITLE
Wrong display of accesstrustlist for claims

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#1334]
Even tho i gave BUILD / CONTAINER / ACCESS trust permissions for the adminclaim for two players it doesnt show all of it. We can build and access the claim also containers but it only shows Container permissions in list. With the command /trustlist it only shows them for container in green but they should be displayed next to access and build in yellow in blue too. Thats missing and misleading permission info. Thanks for the quick fix.

https://imgur.com/a/qCxy9q3

Thanks for the quick fix.

**Comment by RoboMWM** [comment]
I'm assuming you closed because you discovered that trust is inherited instead of being discrete?
