### ISSUE TITLE
administrator unable to place command block in administrative claim

### ISSUE THREAD

**Issue by zagarjr** [GriefPrevention/GriefPrevention#1349]
### What happened:
Unable to place command_block within an administrative claim despite being Level1 OP and in creative mode

### What was expected:
umm, placing a command block

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Log in as owner/operator
2. give @s command_block
3. create administrative claim
4. attempt to place command block in claim area

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 1.16.5
Paste of `/version GriefPrevention`: 16.17.1

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```
All default values used, no customization
```

### Debugging steps attempted

- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server
- [x] I attempted testing for the issue with the vanilla client (no mods)
  - [x] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by bigpresh** [comment]
You haven't provided any details on the actual output you get, but I don't think this is GP preventing this - most likely you need to actually enable command blocks in your server's config.

Look for `enable-command-block=false` in your server's config file `server.properties` and change it to true.

**Comment by zagarjr** [comment]
I was already testing command_blocks in a new minecraft server when I installed GriefPrevention as the first plugin, so I was surprised to find that I could not place new command_blocks

**Comment by Jikoo** [comment]
I note you specifically mention being OP level 1. On Java edition, using command blocks requires OP level 2. See https://minecraft.fandom.com/wiki/Command_Block#Modification
