### ISSUE TITLE
Overall GP isn't working

### ISSUE THREAD

**Issue by Ink-X** [GriefPrevention/GriefPrevention#1355]
I'm an admin on a server that needs a land claims, and this plugin has worked **wonders** in the past, but was deleted unintentionally. I then reinstated the GP plugin, but now the commands are completely unrecognized. In config files all the GP files are there, but when using /plugins it doesnt show up, and none of the commands or functions seem to be working. Its as if the plugin is recognized in the config files only

currently running a 1.16.4 Spigot server using 16.17.1 GP

### GriefPrevention config.yml
https://gist.github.com/Ink-X/29f3f88320241bc04d180ce17eb3f0a4

### server log
https://paste.shockbyte.com/ikohofozahunabuqanop

### Plugin list (if applicable):
-ImageOnMap 4.1.2
-Simple Tpa 5.3
-GriefPrevention 16.17.1
-GeyserLink v1.0.5
-[LAFURE] Inventory View 0.10.0-alpha
-Farm Protection for MC 1.16 1.0.0
-Armored Elytra 2.4.14
-Broadcast 1.0

### Debugging steps attempted

- [ ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [x] I attempted testing for the issue with the vanilla client (no mods)
  - [x] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by bigpresh** [comment]
Check your server logs for anything emitted during load which might explain why it's not loading GP.

Check the .jar file in your plugins dir has appropriate permissions etc; maybe re-download it in case you got a corrupted download or something?

Also, please confirm what GP version you're actually trying to use?

**Comment by RoboMWM** [comment]
need at least your server.log at the bare minimum if u just gonna delete all of the template questions like that.

**Comment by Ink-X** [comment]
I'm sorry for removing the template questions, i've never used this website and was very confused.
i've tried updating the post with the server log as well as the config.yml

thank you both for replying, I really appreciate putting up with my negligence.

**Comment by Jikoo** [comment]
Are you sure you installed the plugin correctly? If the file was even present you'd see warnings. There's absolutely nothing in your logs indicating that you have any GP jar file in your plugins folder at all, let alone a load failure.

**Comment by Ink-X** [comment]
im not too sure, GP .yml and .txt files appear in config, but is completely unrecognized by the actual server. im using shockbyte, so I simply pushed install and hoped for the best.

i know like nothing when it comes to this stuff, sorry.

**Comment by Jikoo** [comment]
You need to have a GriefPrevention jar file in your server's plugins folder, not just configuration files. I don't know what Shockbyte does, but I did notice that in your logs something reinstalls every plugin using Spigot plugin IDs every restart and GP isn't in there. If I were you I'd attempt to reinstall the plugin again using your host's recommended procedures.

**Comment by Ink-X** [comment]
It's Working! Thank you all so much!
