### ISSUE TITLE
[Suggestion]: Llamas are horses too

### ISSUE THREAD

**Issue by P0Pss** [GriefPrevention/GriefPrevention#136]
Great plugin, one issue I have with it is that when all the pet and creature protection is off llamas are still protected with /givepet and cant be leaded or ridden if you don't own the pet but they can still be damaged. Well, a fix to this would to treat llamas the same way you would horses, another would be to have to option of disabling /givepet entirely. You also can't allow horse sharing without disabling both creature and pet protection.
Thanks.

**Comment by RoboMWM** [comment]
Um, whether they can be damaged is linked with the pvp rules. The same applies to wolves and horses.

**Comment by P0Pss** [comment]
The problem isn't the damage, the problem is that only one person can ride a llama without having to /givepet inbetween, only the owner can access their chest and use a lead on them.

**Comment by RoboMWM** [comment]
Um, I'm confused, what's the issue? Iirc, anyone can ride llamas as there is no "owner" iirc (they're already tamed, yes?)

**Comment by P0Pss** [comment]
The problem is that as soon as someone tames the llama they become the owner, how do you let multiple people have access to riding that llama? When I try to ride a llama which someone else has tamed it says "That belongs to {name} until it's given to you with /GivePet." if the llama is "given" to me then the previous owner cant ride it.

**Comment by RoboMWM** [comment]
Is PvP enabled in that world, and what are the PvP rules set for it?

**Comment by P0Pss** [comment]
Disabled for all worlds, but there is a plugin called PvPManager so you can toggle pvp

**Comment by RoboMWM** [comment]
So, PvP is disabled - ok, so it must be using the PvE rules, which would make sense as to why it's restricting who can ride the llama.

**Comment by P0Pss** [comment]
The link to the config is https://hastebin.com/udumuqifeq.php could you have a look and tell me what should be changed?

**Comment by P0Pss** [comment]
@RoboMWM Have you managed to look at the config?

**Comment by RoboMWM** [comment]
You disabled PvP rules in all your worlds, and iirc, GP handles this by applying PvE rules. I think I already mentioned this in another ticket - if not, then definitely in the spigot discussion thread. As for why - well, ask Big_Scary - that's what he told me.

See refactoring discussion ticket for changes.

**Comment by P0Pss** [comment]
This doesn't make sense, the problem has nothing to with pvp/pve or any damage at all. I'm gonna rephrase it.

My friend can't ride my Llama.

**Comment by RoboMWM** [comment]
> GP handles this by applying PvE rules. 

But he can ride horses?

Hmm..

**Comment by P0Pss** [comment]
Yes, horses is not a problem, just the Llamas, and recently found out donkeys have the same problem

**Comment by RoboMWM** [comment]
Just noticed you're missing GP and server /version which you deleted from the issue template.

**Comment by P0Pss** [comment]
Paper Build 1103 (1.11.2)
GriefPrevention 16.6

**Comment by RoboMWM** [comment]
Try 16.7.1. Think there was a change regarding horses in that.

**Comment by RoboMWM** [comment]
Potentially a duplicate of #93

**Comment by RoboMWM** [comment]
Any update on this?

**Comment by P0Pss** [comment]
Oh yes sorry, I completely forgot about this thread, turns out the server owner didnt update the plugin cause he didnt think there were any major changes :/
Thanks for the help!

**Comment by RoboMWM** [comment]
Ok, assuming fixed then.
