### ISSUE TITLE
/givepet reveals staff in Vanish

### ISSUE THREAD

**Issue by crypticfel** [GriefPrevention/GriefPrevention#1369]
### What happened:
If a player wants to see if a staff member is in Vanish (we use PremiumVanish), they use /givepet.  The pet will teleport to the staff member and give them away.

### What was expected:
The /givepet command checked to see if the player was in vanish and did not reveal their presence.

### Steps to reproduce:
Player goes into Vanish.  Another player tames a pet and uses /givepet.  If pet teleports, the vanished staff member is online.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: git.tuinity.9bdc9b mc1.16.5

Paste of `/version GriefPrevention`: 16.17.1 2b69191

### Stack trace/error or server log
none
```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Plugin list (if applicable):
PremiumVanish

### Debugging steps attempted

- [ ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by RoboMWM** [comment]
Interesting. I do wonder if there's a good way to check if target is hidden from said player - guess an "API" method to return a player is probably the best course of action. Makes me wonder why Bukkit/Spigot hasn't added such API though.

**Comment by Jikoo** [comment]
Looked into this - problem is that GP also allows /givepet to work for offline players... which is convenient, except it means that if we block it for players they can't see, they'll still know something is up. To preserve this, we would need to either force a given pet to sit so it cannot teleport (which can still be bypassed by forcing it to swim) or flag given pets to prevent teleports to the user if they cannot be seen by the giver. We should probably just eliminate allowing offline targeting (or drop givepet entirely, why is that a feature of an anti-grief plugin?)

**Comment by RoboMWM** [comment]
I'm fine with dropping it. I do think it's useful, but I'm ok with dropping it from core plugin.

**Comment by Jikoo** [comment]
Oh yeah, players loved it back when I was running a server. Just one of those things where looking at it, it's the classic BigScary wanting something and just popping it into GP. Would definitely make a basic addon/standalone plugin for it if we drop it, but also am okay with keeping it around and just removing offline/vanished support.

**Comment by Jikoo** [comment]
Targeting this and #1392 with the [GivePet](https://github.com/GPAddons/GivePet) addon. When I find time to test that I'll PR the removal of /givepet here.
