### ISSUE TITLE
    ExtendIntoGroundDistance: not working?

### ISSUE THREAD

**Issue by smoke-kush** [GriefPrevention/GriefPrevention#1397]
ExtendIntoGroundDistance: 5
    
    but yet player claims go to bedrock claiming valuable resources?
    
    any fix? 
    
    Very confuse.

**Comment by RoboMWM** [comment]
Invalid ticket format (lacks necessary information to determine problem). Please fill out the template you deleted.

**Comment by smoke-kush** [comment]
Or just fix your shit. ez

**Comment by smoke-kush** [comment]
this has been a known issue in the latest version for a while now.

**Comment by RoboMWM** [comment]
> this has been a known issue in the latest version for a while now.

proof?

**Comment by RoboMWM** [comment]
So this is a duplicate. But unlike you, this person mentioned what is and isn't working. Please refer to the duplicate issue as an example of how you can help get things fixed. https://github.com/TechFortress/GriefPrevention/issues/1373

May also be a duplicate of https://github.com/TechFortress/GriefPrevention/issues/1259
