### ISSUE TITLE
claims became transferred to "someone"(UUID#)

### ISSUE THREAD

**Issue by GalacticArcanum** [GriefPrevention/GriefPrevention#14]
all claims in one world randomly (no updates were made) were transferred to a "someone"(45e20622-100f-3a02-9835-ebcc22e1c530)

Occurred on previous version. Tried updating to new version (even tho none of my other servers on the network were affected and running the same version) and this did not fix the problem.

Please assist so I don't have to transfer 500+ ppls claims back to them as they login (also how do i know if that claim belonged to them in the first place!?)

**Comment by RoboMWM** [comment]
And that is the UUID of the "someone" that went inactive (and apparently sometimes transferring claim data does it too for whatever reason, maybe a usercache.json thing). It will update back to their cached name when they log back in.

**Comment by GalacticArcanum** [comment]
its not one uuid EVERY SINGLE CLAIM has this EXACT uuid. All of them. And it doesnt seem to fix when they login or else I would have not posted anything. Also it happened to players who play daily.

**Comment by GalacticArcanum** [comment]
![2016-10-02_08 17 02](https://cloud.githubusercontent.com/assets/13890259/19020507/b2639dae-8878-11e6-8c2a-995cb68d67ce.png)
![2016-10-02_08 16 11](https://cloud.githubusercontent.com/assets/13890259/19020508/b52aae74-8878-11e6-98f3-5001b044957f.png)
![2016-10-02_08 15 59](https://cloud.githubusercontent.com/assets/13890259/19020510/b7727d60-8878-11e6-82c5-1bbfed6e10c0.png)

**Comment by GalacticArcanum** [comment]
well it does seem that occasionally its a different UUID but overall it only seems to be 2. and admin claims were not affected.

**Comment by GalacticArcanum** [comment]
i'll let you know what happens i guess over time. but how come only on one server of the bungee cord network? Not all of them? or all worlds even? just one world. Ive been using this plugin for 5 years it seems and never seen this once.

**Comment by GalacticArcanum** [comment]
MY players are logging in, "I dont have any claims on /claimlist" "so and so's house is unclaimed" "actually half of the claims around here are unclaimed now"

**Comment by RoboMWM** [comment]
Need `/version` `/version GriefPrevention`, and ~~whether you're using offline mode, and bungee.~~ Ok so you are using bungee. Please paste your spigot.yml for this particular server, and is your bungee in offline mode?

**Comment by GalacticArcanum** [comment]
bungee is online mode. http://one.denizenscript.com/paste/36578

and i was using the previous version of griefprevention when it occurred. updated to current version and it did not change the situation.

**Comment by RoboMWM** [comment]
Oh, also forgot to ask - do you use SQL storage or flatfile?

Only other thing I could think of is that you're regularly clearing usercache.json, or simply the offline-mode is tripping up the UUIDs at times. I'm assuming other tasks also happen when you update GP - GP itself doesn't change any database stuff when it gets an update. (And, if the only time you restart is to update... then there's even more possibilities to consider.)

**Comment by RoboMWM** [comment]
> but how come only on one server of the bungee cord network? Not all of them? or all worlds even? just one world.

Probably (and likely) an issue with your setup. I'm suspecting that you're probably loading this world in dynamically?

**Comment by GalacticArcanum** [comment]
no this is a solid server. we are talking 3 months no problems. created when 1.10 released. I do use SQL storage. I have a 40GB dedicated server that runs at the most 60% ram usage at any time. There was no update when I restarted. I restarted to update another part of my server which required shutting down bungee. 

This world isn't loaded dynamically, its the base overworld (however i do use multiverse and those worlds were NOT affected.)

Also no worlds on 3 other servers were affected, 2 of them are identical setups but for large biomes and amplified. The other is a creative server. All use multiverse.

**Comment by RoboMWM** [comment]
I'm not talking about the hardware nor performance. I'm talking specifically about your setup - your software/plugins setup. Can you share a claim entry from this server (and from the affected world)? Is the world dynamically loaded in (e.g. a script or /mv load)? I'm sure that if GP were the only plugin running

**Comment by GalacticArcanum** [comment]
read above i edited.

**Comment by RoboMWM** [comment]
And the claim mode for this world? Also would like to see a claim file.

> There was no update when I restarted. I restarted to update another part of my server which required shutting down bungee. 

And no issues? Or were there issues after restarting without updating?

**Comment by RoboMWM** [comment]
By the way, you can also join IRC if it'd be easier to chat about this. http://irc.spi.gt/iris/?nick=&channels=GriefPrevention

**Comment by RoboMWM** [comment]
[11:31:49] ~RoboMWM: Please check your logs for "UUID conversion process started.  Please be patient - this may take a while."

**Comment by RoboMWM** [comment]
Do you have those logs from when you restarted the server @CorporalBruno ? If not then I'm going to close the issue as this missing information is required to proceed from here.

**Comment by RoboMWM** [comment]
So, let me know when you have logs...
