### ISSUE TITLE
Portal Access

### ISSUE THREAD

**Issue by KadeWolfe** [GriefPrevention/GriefPrevention#1414]
Hello!

I have an issue where players are entering the nether through a portal in their base, but can't return through the portal because the destination is within someone else's claim. Presumably, the two players have portals close enough to each other that they path to the same portal. Is there any way to fix this? (aside from saying "more your portal far enough"). Thanks!

**Comment by bigpresh** [comment]
No, the portal "linking" is not controlled by GP at all.

They'd need to build their nether portal and overworld portal at the "matching" coordinates or as close as they can (you probably know, but divide the overworld x & z coordinates by 8 to get the "matching" coords in the nether).  As long as they do that, then they should always arrive at their portal on the other side, and not another near-enough portal (if there's an existing portal within a certain radius of the correct "matching" coordinates then Minecraft will just use it, but if they make theirs closer it'll use theirs instead).

Other than that (or the other player being kind and giving them permissions within their claim to get out from their portal), there's no other option - sorry!

**Comment by Jikoo** [comment]
This may be related to a vanilla issue. When creating a portal from the overworld, vanilla looks in a certain radius to find a pre-existing portal or a "good" spot to place a new one. However, on returning from the nether, it uses the same search radius, not 8x the search radius. That means that unlucky players' portals will not link back up, resulting in a new portal attempting to create on return.

You should still follow bigpresh's advice, but I think you'd find that they'd be unhappy with the result of returning even if GP wasn't blocking it.

**Comment by RoboMWM** [comment]
Thought that was an old paper issue that used the same default configuration radius. They implemented a fix for that but I can't recall exactly what it was.

**Comment by KadeWolfe** [comment]
Oh thanks! If you can recall, please let me know! I was surprised there
wasn't an option in the configs to just disable portal protection as a
whole.

**Comment by RoboMWM** [comment]
> I was surprised there wasn't an option in the configs to just disable portal protection as a whole.

Not sure what you mean, GP doesn't prevent any portal teleportations anymore because the TravelAgent has been removed from spigot a few versions ago.

**Comment by KadeWolfe** [comment]
Oh okay. I meant that griefprevention is preventing players from returning
through a portal in the nether since the destination is in a claim. Thought
maybe I could disable that 😅

**Comment by RoboMWM** [comment]
GP doesn't do anything with portals.

**Comment by KadeWolfe** [comment]
Is it a teleportation issue then? It's because of griefprevention claims
people can't return through portals. Multiple players built theirs too
closely is my guess and so they link to each other. But since these players
also built their portals in a claim, they can't return.

**Comment by RoboMWM** [comment]
GP doesn't do anything with portals.

You must be using some old version of GP if that's the case, and that option is disabled by default.

**Comment by RoboMWM** [comment]
This is why the template is useful, please use the template next time. Not sure how you got around it since you aren't a new github user... unless you intentionally did so.

**Comment by KadeWolfe** [comment]
I am running GP version 16.17.1 on Spigot 1.16.5.

**Comment by KadeWolfe** [comment]
I didn't see it when I went to post my support request. Also, it's been a
bit since I've had to request support 😂

**Comment by RoboMWM** [comment]
Yea that GP doesn't stop any portal teleportations. You'll probably have to better describe exactly what you mean by 

> but can't return through the portal because the destination is within someone else's claim.

**Comment by KadeWolfe** [comment]
Hmm okay. Let's see if I can describe it better xD So, when a player enters
through their portal in the overworld, when they try to return to the
overworld from the nether through their portal, it denies access because
the destination portal is in a claim. Basically, I have a problem where a
few players have bases too close to each other, those portals are all
linked to each other, and the players aren't able to return to the
overworld via portal since it says the destination is in a claim.

Let's see if I can explain it a little clearer with a model situation:

Player A builds a portal (1) in their claim.
Player B also builds portal (2) in their claim.
Player A and B have claims close to each other (100 or so blocks).

Player A travels to the nether from (1) which creates a portal in the
nether (n). Player B also travels from (2) to the nether and arrives at
(n). Now, Player A has no issue as (n) first pathed to (1), but when Player
B tries to leave the nether from (n) GP prevents them as the destination is
in a claim, because it's trying to send them to (1) which is in Player A's
claim.

So, that model, but add Player C, D, etc as multiple players have portals
near each other.

**Comment by RoboMWM** [comment]
>  but when Player B tries to leave the nether from (n) GP prevents them as the destination is in a claim, because it's trying to send them to (1) which is in Player A's claim.

Does an error message appear when this occurs?

**Comment by KadeWolfe** [comment]
No, it doesn't.

**Comment by RoboMWM** [comment]
Ok so GP isn't blocking the teleport then.

**Comment by KadeWolfe** [comment]
Well, the teleport is being blocked because the destination is in a claim.
I'm assuming that's the message what the players got when they tried. I
will see if I can get them to send a screenshot (I'm out of town and away
from my computer).
