### ISSUE TITLE
Crash with EcoEnchants enchantment

### ISSUE THREAD

**Issue by Petteu** [GriefPrevention/GriefPrevention#1415]
### What happened:
The claim check function is in conflict with an custom enchantment named Magma Walker.
I reported the error to the ecoenchant community, but the developer explained that it was the problem on the GriefPrevention.
![image](https://user-images.githubusercontent.com/71914240/122522032-77c08980-d050-11eb-88da-e21a082b219b.png)
https://spark.lucko.me/dNp6hPwRvv
the enchantment 'magma walker' have the ability to transform magma into an obsidian.
this ability appears to be in conflict with the function to check private property in GriefPrevention.

### Server and GriefPrevention version:
![image](https://user-images.githubusercontent.com/71914240/122523024-8bb8bb00-d051-11eb-80d6-f95643f2812c.png)
![image](https://user-images.githubusercontent.com/71914240/122523082-9c693100-d051-11eb-8165-94ee6f54c8a0.png)

### GriefPrevention config.yml

```
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    pvp: -1
    dungeon: -1
    '1': -1
    lobby: -1
    bed_wars: -1
    farming: -1
    parkour: -1
  Claims:
    Mode:
      world_nether: Disabled
      world_the_end: Disabled
      farming: Disabled
      lobby: Disabled
      world: Survival
      pvp: Disabled
      '1': Survival
      dungeon: Disabled
      bed_wars: Disabled
      parkour: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 2400
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: -1
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 25
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: BLAZE_ROD
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 250000
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
      pvp: true
      dungeon: true
      '1': true
      lobby: true
      bed_wars: false
      farming: true
      parkour: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 20.0
    ClaimBlocksSellValue: 10.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: CLAIMS_ONLY
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - GRASS_BLOCK
    - DIRT
    - COBBLESTONE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - SAND
    - GRAVEL
    - GLASS
    - GRASS
    - FERN
    - DEAD_BUSH
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    - GLASS_PANE
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false


```

### Plugin list (if applicable):
- griefprevention
- ecoenchant

**Comment by Jikoo** [comment]
Re: 4 offline player lookups per block - that would actually be 2 maximum dependent on the block type for block breaks. Not sure where they're seeing the other 2.

I'll amend my PR to rework this area to include a swap to a Supplier<String> for the returned message so it's not calculated unnecessarily like it is here.

A cache would also be simple to implement, but as I personally don't have the free time to do a lot of work on GP right (lot of other projects to update, MC 1.17 wasn't huge but it does take time) I am unlikely to get to that soon. If anyone else wants to have a stab at it (it's easy, it'd make a good first issue!) it's [this line](https://github.com/TechFortress/GriefPrevention/blob/f4680c40516eb6de398e20142b0ade600e951fa9/src/main/java/me/ryanhamshire/GriefPrevention/GriefPrevention.java#L3176).

**Comment by RoboMWM** [comment]
Hmm, GP used to cache offline lookups, was that removed? Or was it never used here?

**Comment by Jikoo** [comment]
> Hmm, GP used to cache offline lookups, was that removed? Or was it never used here?

I think at one point GP used its own name<->UUID cache, but I believe that got removed after the server's usercache became less garbage and/or more reliable due to reloading names occasionally. I would have sworn that the server's usercache was used for offline names at one point, but it looks like now they're always loaded from Bukkit's last name NBT tag in player data.

This addon can now rework its build permission check to use `Claim#checkPermission(player, ClaimPermission.Build, event)` - since the denial message is provided by a nullable `Supplier`, it's only calculated on demand, which removes the offline player lookup from this use case. The change also addressed the double player name fetch for non-farming blocks. Previously container access was always checked in addition to build access even if the material being built with was not a farming material. That means that even without updating the hook you should see a roughly 50% performance increase.

Pinging @Auxilor so they're aware that this method will be available in next GP release.

I'm leaving this issue open because GP could still benefit from caching offline players for a period on fetch (or ideally the server's usercache is exposed somehow and we can piggyback it directly), but the main performance issue for addons trying to check a boolean protection value should be resolved.

**Comment by RoboMWM** [comment]
Well there is a config option to determine the max inactive days a player has been offline that gets kept in GP's in-memory hashmap. If it isn't used here, then I'm not sure where it is used...

**Comment by Jikoo** [comment]
Closing in favor of #2212, which is a little more general.
