### ISSUE TITLE
permission to allow players to see claim size

### ISSUE THREAD

**Issue by Sidious82** [GriefPrevention/GriefPrevention#142]
### What behaviour is expected:
use a stick and see who has claimed the area, how large it is, and how long they have been inactive.
would like a simple griefprevention.seeclaimsize permission

### What behaviour is observed:
use a stick and see who has claimed the area + added perms to see how long they have been inactive  (no claim size)

### Steps/models to reproduce:
deop  yourself, use a stick to see the claim info you are standing on (yours or anyone elses)

### Spigot/Craftbukkit/Paper and GriefPrevention version:
craftbukkit git-Spigot-3fb9445-6e3cec8 (MC 1.11.2) ; griefprevention v16.7.1

### Stack trace/error (if applicable)
n/a

Paste entire stack trace inside here
n/a

### GriefPrevention config.yml (if applicable)
https://pastebin.com/J7d0LSCZ

### Plugin list (if applicable):
https://pastebin.com/tHJ1mVj4

**Comment by RoboMWM** [comment]
Already added............... #107 #106
