### ISSUE TITLE
[Request] Option to change more message.

### ISSUE THREAD

**Issue by Remski01** [GriefPrevention/GriefPrevention#143]
This is a great plugin. Simple to use. And not hard to understand. But there is a lack of Editable message what is a huge disappointment. So can you please add much more to the message.yml?

**Comment by RoboMWM** [comment]
What things in the messages.yml would you like to see that aren't already there?

**Comment by RoboMWM** [comment]
Closed in favor of duplicate but more specific request #191

**Comment by RoboMWM** [comment]
Duplicate of #191
