### ISSUE TITLE
Glowing item frames not protected

### ISSUE THREAD

**Issue by kena73** [GriefPrevention/GriefPrevention#1435]
### What happened:
Players were able to knock out items out of glowing item frames but not normal item frames.

### What was expected:
Players should not have been able to do so as normal item frames are protected.

### Steps to reproduce:
1. Claim area and place down a glowing item frame with a item inside of it.
2. Any person who is not the claim owner is now able to left click the item and it will pop out, this does not happen with normal item frames.

### Server and GriefPrevention version:
Spigot version 1.17
GriefPrevention version 16.17.1

**Comment by nouish** [comment]
A PR (#1413) for this has already been merged: https://github.com/TechFortress/GriefPrevention/commit/fbf4c7c45b4de3aa18fb6a455385d803bdb2cf9c

While a version that includes this change has not yet been released, you may download the latest development build from CI here: https://ci.appveyor.com/project/RoboMWM39862/griefprevention/builds/39732068/artifacts

Edit: newer build with more 1.17 support: https://ci.appveyor.com/project/RoboMWM39862/griefprevention/builds/39942636/artifacts

**Comment by Jikoo** [comment]
As Nouish said, this has already been resolved in development versions. Please use a build off the CI if you need the fix before a release is drafted.
