### ISSUE TITLE
GriefPrevention API NPE

### ISSUE THREAD

**Issue by Spazzinq** [GriefPrevention/GriefPrevention#1438]
I am the plugin developer for FlightControl, and one of my players reported a NullPointerException which seems to be GriefPrevention's fault.

### What happened:
Function checkPermission returned null from allowAccess and caused NPE because code cannot invoke java.util.function.Supplier.get()

### What was expected:
No error

### Steps to reproduce:
Not sure, not plugin owner

### Server and GriefPrevention version:
v50a65e8 (from server log)

### Stack trace/error or server log
https://gist.github.com/Spazzinq/5ff1efc8654e226ddb83267bb6098011

**Comment by Jikoo** [comment]
The supplier is nullable. The reason it's a supplier at all is that most addons don't actually care about the returned message, only its nullity. I was tempted to use an Optional but ended up deciding it was more consistent with GP's existing design not to. I did want to use nullity annotations, but GP does not currently contain a dependency for that, and adding them was outside of the scope of the PR.

**Comment by Spazzinq** [comment]
> The supplier is nullable. The reason it's a supplier at all is that most addons don't actually care about the returned message, only its nullity. I was tempted to use an Optional but ended up deciding it was more consistent with GP's existing design not to. I did want to use nullity annotations, but GP does not currently contain a dependency for that, and adding them was outside of the scope of the PR.

How would you suggest I fix this issue considering that I called a separate method that caused the NPE in another method? Try-catch is hardly an elegant solution.

**Comment by Spazzinq** [comment]
@Jikoo

**Comment by Jikoo** [comment]
Oh I see, I missed a case when converting it to suppliers. My bad, you're right

**Comment by Jikoo** [comment]
@Spazzinq I should note that you probably want to convert to the new API ASAP - most addons only care about a true/false condition, and updating to not actually consume the supplier should yield huge performance increases. In the case of [this spark](https://spark.lucko.me/dNp6hPwRvv) it's a 6450% performance increase (plus another load for other reasons) for the GP hook in question.

Something like this should work for backwards compatibility:
```java
public class GriefPreventionHook extends ProtectionHook {

  private final boolean useCheckPermission;

  public GriefPreventionHook() {
    boolean checkPermission;
    try {
      Claim.class.getDeclaredMethod("checkPermission");
      checkPermission = true;
    } catch (ReflectiveOperationException e) {
      checkPermission = false;
    }
    useCheckPermission = checkPermission;
  }

  @Override
  public boolean canBuild(Player player, Location location, Event event) {
    Claim claim =  GriefPrevention.instance.datastore.getClaimAt(location);

    if (claim == null) {
      return true;
    }

    if (useCheckPermission) {
      return claim.checkPermission(player, ClaimPermission.Build, event) == null;
    }

    return claim.allowBreak(player, Material.DIAMOND_BLOCK) == null;
  }
}
```
Note that I did hand write it, so the reflection bit is probably a tad wonky.

**Comment by Spazzinq** [comment]
Thank you so much, will do!
