### ISSUE TITLE
1.17 Height Claiming

### ISSUE THREAD

**Issue by Frcsty** [GriefPrevention/GriefPrevention#1442]
### What happened:
Claims do not properly register under y 0, thus anything bellow it will not be claimed - using 1.17's experimental world height feature.

### What was expected:
Mad stonks

**Comment by Tizooo** [comment]
on the spigot page it says griefprevention is for 1.16 and not for 1.17 yet

**Comment by krusic22** [comment]
> on the spigot page it says griefprevention is for 1.16 and not for 1.17 yet

Good argument. But then why does extended height work? Magic I say.

**Comment by Jikoo** [comment]
> on the spigot page it says griefprevention is for 1.16 and not for 1.17 yet

That doesn't mean it won't update to 1.17. Issues like this will need to be addressed for a release.

**Comment by RoboMWM** [comment]
Likely a duplicate.

**Comment by RoboMWM** [comment]
Duplicate of #1431
