### ISSUE TITLE
I can't trust bedrock players, my server accepts bedrock and java and I can't ban the bedrock from Claim

### ISSUE THREAD

**Issue by thiagogebrimm** [GriefPrevention/GriefPrevention#1443]
When trying to give trust to bedrock players it appears that it works, but the following appears in the trustlist:
![image](https://user-images.githubusercontent.com/75040244/124311954-ec152580-db44-11eb-9789-e75e697b0674.png)

Maybe it's the "." of the prefix, but a friend of mine said it's probably a UUID error

**Comment by Jikoo** [comment]
See #1360 - GriefPrevention interprets strings containing periods as permissions.
