### ISSUE TITLE
Taking an axolotl from a claim (while untrusted) removes it (1.17)

### ISSUE THREAD

**Issue by TheMysterys** [GriefPrevention/GriefPrevention#1446]
### What happened:
Have a water bucket and right click on an axolotl inside a claim that you don't have trust too

### What was expected:
axolotl reappears where you took it from

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Have a water bucket
2. right click axolotl that is inside a claim

### Server and GriefPrevention version:
Will update if received this information from server owner

### GriefPrevention config.yml
Can't fetch due to not owning server

### Debugging steps attempted

- [ ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by Jikoo** [comment]
If you can't replicate this on fish entities it's an inconsistency in Spigot's logic and you should open a ticket there instead.

**Comment by TheMysterys** [comment]
Hey did more testing. Turns out this is a client side issue (other people can still see the axolotl) 

Also no mods installed on client

**Comment by Jikoo** [comment]
Ok, in that case it is a Spigot bug - they need to re-send the spawn packet for the axolotl when the bucket fill event is cancelled.
