### ISSUE TITLE
mobs with nametag are losing their name

### ISSUE THREAD

**Issue by thiagogebrimm** [GriefPrevention/GriefPrevention#1465]
### What happened:
When putting a nametag on a mob, the tag disappears after a while

### What was expected:
Don't disappear and keep the name

### Steps to reproduce:
1. Put the nametag on the mob and it doesn't have the name

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 1.17.1 purpur
Paste of `/version GriefPrevention`: Grief prevention dev build most release 

### Stack trace/error or server log
No have
```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Debugging steps attempted

- [x] (If applicable) I attempted running the server without GriefPrevention installed
  - [x] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by Jikoo** [comment]
GP does not set [custom names](https://github.com/TechFortress/GriefPrevention/search?q=setCustomName) nor [display names](https://github.com/TechFortress/GriefPrevention/search?q=setDisplayName). Please verify that you have actually completed the debugging steps you have checked.

**Comment by destro174** [comment]
We had the same issue, revering https://github.com/TechFortress/GriefPrevention/pull/1337 fixed it.

**Comment by thiagogebrimm** [comment]
The problem is that I also need the new versions because I use 1.17, will it ever fix again? @destro174

**Comment by Jikoo** [comment]
If that's the issue, it's likely an issue on Spigot's end where the client is not being informed that the nametag isn't being applied when a claim prevents them from renaming an entity. We might be able to work around that by "renaming" the entity to the same thing it already was named on a delay to force resending the data.

**Comment by thiagogebrimm** [comment]
That's exactly the problem

**Comment by Jikoo** [comment]
Unable to reproduce. Tested using a sheep, and it retains name over time, across server restarts, etc. Names do not appear when GP prevents renaming due to a claim (though when using an unnamed tag there's a double message due to both hands interacting, probably need a cooldown on that). Please provide more detailed reproduction steps and verify that you are able to reproduce with only GP present.

![image](https://user-images.githubusercontent.com/1353270/142764016-6b826de5-eba4-4eeb-b376-11175e47833d.png)

**Comment by Jikoo** [comment]
Closing in favor of #1672 - based on the fact that OP has submitted an issue to the mcMMO tracker about this, I'm betting it's actually a duplicate, and the information provided there is more complete.
