### ISSUE TITLE
Items from glow frames can be taken out in claims without trust permissions, but not put back in

### ISSUE THREAD

**Issue by kixmc** [GriefPrevention/GriefPrevention#1472]
### What happened:
Players are able to take items out of glow frames in claims without permission on 1.17.1. They aren't able to put the items back in however

### What was expected:
Taking items out of glow frames to be blocked unless trusted on the claim

### Steps to reproduce:
1. Create a claim with a glow frame and item in it
2. On an untrusted account, try to take the item out of the glow frame

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: Purpur version git-Purpur-1267 (MC: 1.17.1)
Paste of `/version GriefPrevention`: 16.17.1-2b69191

### Stack trace/error or server log
na
```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml
na, happens on default config
```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Debugging steps attempted

- [ ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by akdukaan** [comment]
Duplicate of #1435 
This has already been fixed in the development builds at https://ci.appveyor.com/project/RoboMWM39862/griefprevention/history

**Comment by kixmc** [comment]
Thanks! Sorry for not looking more throughly if this had already been reported. Appreciate it
