### ISSUE TITLE
Mob spawning is strange in claims. does not work properly. only semi properly.

### ISSUE THREAD

**Issue by kalleswe** [GriefPrevention/GriefPrevention#1474]
latest dev version (a week ago).
does not allow mobspawners to work properly in a claim ( they work fine as they should outside claims).
you need to place about 6-8 spawners to get the spawn rate of 1-2 spawners in vanilla.
also mobs doesn't seem to spawn properly in claims either. it's much LESS than vanilla for some reason.
tested on plain spigot/paper latest version with only griefprevension plugin.
needs fixing, and no I can't code this shit so don't ask me code related questions. and such.
can't find anything about mobs in the config either. please fix.

**Comment by Jikoo** [comment]
Please fill out the template you deleted. Specifically, include your config (inside a code block please!) and in this case debug logs.

Also, "latest" is not a version - while the timeframe does help, it's way easier on us if you just include the output of `/version` that actually contains the commit hash.

**Comment by bigpresh** [comment]
Doesn't look like any more info is coming, and there's nothing we can do without it.

As far as I'm aware, GP doesn't even interfere with spawner spawns at all - for instance there's currently [5 results searching for 'spawn' across the repo](https://github.com/TechFortress/GriefPrevention/search?q=spawn) and none of them look like they'd have any impact on spawners, so I very much doubt GP was to blame here.
