### ISSUE TITLE
GriefPrevention set fly in random world

### ISSUE THREAD

**Issue by DarrienNN** [GriefPrevention/GriefPrevention#1485]
Im using 1.17.1 PaperMC lastest version

GriefPrevention + GriefPreventionFlags

Today my player's report to me that they suddenly can fly in overworld, and i also go tried and it really works for me. I already **Disabled** my fly and i go /spawn and go back again overworld and i can fly again, in console didnt write "fly {player}" in game chat too

After restart server the fly will works in /spawn world and overworld like normal. After remove _**GriefPrevention + GriefPreventionFlags**_ the fly not working anymore in overworld / spawn world and others world.

**Comment by DarrienNN** [comment]
![image](https://user-images.githubusercontent.com/58543201/126544267-4fb862d8-b9a1-4404-907b-60e59d12b6df.png)
![image](https://user-images.githubusercontent.com/58543201/126544307-602f5383-a209-48b0-97ca-a516b7745e6e.png)

[Thu, 22. Jul 2021 02:56:58 SGT INFO] Checking version, please wait...
[Thu, 22. Jul 2021 02:56:58 SGT INFO] This server is running Paper version git-Paper-120 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 2780e94)
You are 1 version(s) behind

**Comment by Jikoo** [comment]
Contact whoever is currently maintaining GPFlags - GP does not enable or manage flight under any circumstances.
