### ISSUE TITLE
Can't claim or expand claim in 1.12 with newest version (6/18/17)

### ISSUE THREAD

**Issue by LizC864** [GriefPrevention/GriefPrevention#149]
I just uploaded the newest version of Grief Prevention on my servers which have been updated to 1.12. I can click on the 1st corner with no problems, but when I try to click on the 2nd corner either to create a new claim or expand an existing one, nothing happens. Otherwise everything seems normal. Selecting the shovel tells me how many claim blocks I have available, etc.

**Comment by RoboMWM** [comment]
Can you please provide all the info in the issue template which you deleted?
