### ISSUE TITLE
SafariNet Plugin issue with griefprevention

### ISSUE THREAD

**Issue by TheLeby9** [GriefPrevention/GriefPrevention#1510]
### What happened:
I tried using griefprevention.jar build suggested to fix an issue with glow item frames. it does fix the issue indeed but i faced a problem with safarinet plugin wich stopped working and say it canno hook to griefprevention. i tried another build wich fixed the issue too but safarinet started bugging and spawning ghasts and duping catched mobs..

### What was expected:
normal safarinet plugin behavior

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`:  This server is running Purpur version git-Purpur-1262 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 162d05f on HEAD)
You are 52 version(s) behind
Previous version: git-Purpur-1199 (MC: 1.17)
Paste of `/version GriefPrevention`: 

### Debugging steps attempted

- [x] (If applicable) I attempted running the server with official GriefPrevention latest release installed
  - [x] (If applicable) The problem is resolved if running official GriefPrevention latest release from the server but glow frame not fixed.
- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server
- [ ] I attempted testing for the issue with the vanilla client (no mods)
  - [ ] Issue still occurs even after testing with the vanilla Minecraft client

**Comment by Jikoo** [comment]
You say you're using a dev build of GP, but you don't say which one. Without that information, I assume you downloaded a build including bbb1e5d58c1da68265e677d8385988ea96ca3c73 before 6727fa76e35e26e0db273879eef07a067f1324f9 and 7723d101961bdc98e1fe4afd98125cb4831299a1. If you are using the build for 7723d101961bdc98e1fe4afd98125cb4831299a1 or later and still seeing issues, you should probably contact the developer of the safari net plugin you're using.

Without basic information like GP version and logs of errors, we can't help you more.

**Comment by Jikoo** [comment]
Honestly you should probably contact the developer anyway and link them [this comment](https://github.com/TechFortress/GriefPrevention/issues/1438#issuecomment-872363793) - there is a significant performance increase available to plugins that only use a true/false condition from GP's protection state.

**Comment by TheLeby9** [comment]
The thing is its an unofficial build that is not released on spigot i found it in github someone posted it i will get u the commment/link

**Comment by TheLeby9** [comment]
https://github.com/TechFortress/GriefPrevention/issues/1435#issuecomment-871760920

This is where i got the jar file from this is supposed to be a fix for the glow item frames issue turns out it does fix it but it ruins safarinet plugin

**Comment by Jikoo** [comment]
You can find current dev builds [on the CI](https://ci.appveyor.com/project/RoboMWM39862/griefprevention/build/artifacts). Dev builds include the commit short hash in the version string, so if you were to do `/version GriefPrevention` you'd see something like `GriefPrevention v16.17.1-fbf4c7c`. It allows us to know exactly what you're running without this back and forth.

Any rate, please update GP to 219cf6edd18382b75b4d1f1a217d2ae2d59a6e0d and try again. If issues persist, either provide logs containing errors or get in touch with the safari net dev.

**Comment by TheLeby9** [comment]
wel i tried getting in touch with the safarinet devs and seems like they arent active on their hub. i will what u told me asap and will let u know.

**Comment by RoboMWM** [comment]
> normal safarinet plugin behavior

what is this.

**Comment by TheLeby9** [comment]
> You can find current dev builds [on the CI](https://ci.appveyor.com/project/RoboMWM39862/griefprevention/build/artifacts). Dev builds include the commit short hash in the version string, so if you were to do `/version GriefPrevention` you'd see something like `GriefPrevention v16.17.1-fbf4c7c`. It allows us to know exactly what you're running without this back and forth.
> 
> Any rate, please update GP to [219cf6e](https://github.com/TechFortress/GriefPrevention/commit/219cf6edd18382b75b4d1f1a217d2ae2d59a6e0d) and try again. If issues persist, either provide logs containing errors or get in touch with the safari net dev.



i tried this but still didnt work , however if i remove the griefprevention plugin from the server safarinet works fine.

**Comment by Jikoo** [comment]
> i tried this but still didnt work , however if i remove the griefprevention plugin from the server safarinet works fine.

> If issues persist, either provide logs containing errors or get in touch with the safari net dev.

Even knowing what expected behavior is and what the actual behavior is doesn't really help, because without errors we can't tell what's going wrong with someone else's code that we have no way to inspect.

Out of morbid curiosity I searched safari net plugins and found 3 that directly refer to their item as a safari net and another half dozen that didn't explicitly call it a safari net but had identical functionality. If it's a premium plugin (as 2/3 were) what would you even expect us to do with that? It's not like we can contact the dev and ask them for a copy/source, you already said they're unresponsive. Perhaps you should consider an alternative plugin if the one you're using is no longer maintained.
