### ISSUE TITLE
protect [ y negative ] with griefprevention on 1.18 maps.

### ISSUE THREAD

**Issue by comonier** [GriefPrevention/GriefPrevention#1553]
there is any way for solve the issue with [ y negative ] on multiplayer servers spigot/paper using new datapack 1.18 ?
in the true the server is 1.17.1 [but the map generator is using 1.18 datapack from mojang free gives.

**Comment by Jikoo** [comment]
Duplicate of #1431

**Comment by Jikoo** [comment]
If you think this is a different issue, please actually fill out the template you deleted.
