### ISSUE TITLE
Default blocks wont save

### ISSUE THREAD

**Issue by Jaydenisbae** [GriefPrevention/GriefPrevention#1558]
When i try to change the default ammount of blocks that you can claim it dosent save and just gives the person 0 insted

**Comment by bigpresh** [comment]
Please provide more info - how did you try to change it, what did your config file look like?  Are you updating the config with the server running then using `/gpreload`, or doing it with the server stopped?

The issue template also requests various info e.g. whate versions you're using, which may be needed.

**Comment by Jaydenisbae** [comment]
hi my set blocks are not saveing and i was doing it in the config with the server running and then restarting it says that it is saved in the config but it dose not apply in the game here is a paste bin for the config https://pastebin.pl/view/182e428f i am using version 4.30
