### ISSUE TITLE
Issue with flags not updating

### ISSUE THREAD

**Issue by joziahdd** [GriefPrevention/GriefPrevention#156]
### What behaviour is expected:
Quick and easy change of flag 'block-break' false, of that to true.
### What behaviour is observed:
/cf block-break any false override sets all blocks in claim to disallow breaking, but /cf block-break any true override does not, until the host restarts the server.
### Steps/models to reproduce:
make a claim, test if you can break blocks/set blocks.
type /cf block-break false any override you should NOW not be able to break anything, and you didn't have to even restart server. now type /cf block-break true any override and you now must restart server for changes to come into effect

### Spigot/Craftbukkit/Paper and GriefPrevention version:
Actually, I'm using sponge.
![46b723df0478852dc83290f0fb4816e7](https://user-images.githubusercontent.com/28240092/27428957-4056a9e4-5709-11e7-8439-8b87af59d091.gif)

### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here
```

**Comment by RoboMWM** [comment]
> Actually, I'm using sponge.
