### ISSUE TITLE
Plugin doesn't work with 1.12?

### ISSUE THREAD

**Issue by Chenchoon** [GriefPrevention/GriefPrevention#157]
### What behaviour is expected: 
It's supposed to let you claim land
### What behaviour is observed: 
It doesn't claim land at all no matter what you try, the first corner is fine but when you try the other it doesn't work.
### Steps/models to reproduce:
Get a gold shovel go right click the 2 opposite corners of a claim that's 10x10 or more.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
spigot 16.6

This plugin worked great until I updated to 1.12

**Comment by bigpresh** [comment]
What GriefPrevention version are you using (as requested in the issue template)?

Works fine for me, with 16.7.1 on 1.12.

**Comment by Chenchoon** [comment]
I'm using version  16.6

**Comment by bigpresh** [comment]
Try 16.7.1 and report back, please?

**Comment by RoboMWM** [comment]
Also make sure you update (or remove) worldguard, if you're using it.

**Comment by Chenchoon** [comment]
Ok it still wont work :(

**Comment by Chenchoon** [comment]
It works

**Comment by Chenchoon** [comment]
world guard was the problem

**Comment by RoboMWM** [comment]
Duplicate of #147

**Comment by bigpresh** [comment]
> world guard was the problem

Thanks for taking the time to respond to confirm you got to the bottom of it :)
