### ISSUE TITLE
claims of the players disappeared 

### ISSUE THREAD

**Issue by EiderFC** [GriefPrevention/GriefPrevention#1587]
suddenly all the claims of the players disappeared but in the files they appear

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
This server is running Purpur version git-Purpur-1377 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b6d1b6a on ver/1.17.1)

GriefPrevention version 16.17.1-2b69191

**Comment by bigpresh** [comment]
Anything appear in the server logs on startup when GriefPrevention loads?

Check the data files permissions are right?

Check your GriefPrevention config (as requested in the issue template) hasn't been messed up - e.g. by Claims.mode being set to disabled in the world you're seeing the problem in?

**Comment by EiderFC** [comment]
Everything looks good, it just happened in a world

**Comment by Jikoo** [comment]
Please include the information from the template that you deleted.

Just an FYI if you're using some form of dynamic world loading, worlds will need to be loaded on startup before GP loads or it won't load claim data for them.
