### ISSUE TITLE
Spelling mistake in wiki

### ISSUE THREAD

**Issue by Aytho** [GriefPrevention/GriefPrevention#1593]
### What happened:
It have a spelling mistake in wiki (Player commands part)
The alias of /IgnorePlayer command is /Ignore no /Ingore

Great Plugin
Have a good day.

**Comment by RoboMWM** [comment]
thanks lol

eventually docs will be migrated to https://docs.griefprevention.com where edits can be made with approval. Having the wiki open here unfortunately led to people vandalizing it.
