### ISSUE TITLE
[Error Hoglin]

### ISSUE THREAD

**Issue by Arthuuurr** [GriefPrevention/GriefPrevention#1610]
Hello, I have detected a GriefPrevention problem on my server, the fact is that when a "Hoglin" is within a claim, it cannot be killed being an aggressive creature. Is that a mistake or is it normal?

GriefPrevention version: GriefPrevention version ed57f0b

**Comment by Jikoo** [comment]
You should be able to kill hoglins if they are currently attempting to attack you. If they are passive (which can be permanently forced via the correct blocks nearby), the claim will protect them unless you have sufficient trust.

**Comment by Arthuuurr** [comment]
But it should be able to kill itself, it is a hostile creature, and if it is within a claim there is no way to hit it even if it attacks you.
I think it should be considered hostile even within the claim

**Comment by RoboMWM** [comment]
I think it's this way because hoglins are considered animals, if I recall correctly?

**Comment by Jikoo** [comment]
They're treated the same way as polar bears and aggressive pandas - if they're trying to attack you you're allowed to hurt them, but if they're minding their own business you can't. This does mean you can't shoot them from a distance before they see you in claims, which is mildly annoying, but given the number of requests for polar bears etc. over the years, it seemed like the lesser of two evils. Was added in #927

**Comment by RoboMWM** [comment]
Ah, I completely forgot about this. I still stand by the comments I made 3 years ago lol...

**Comment by Jikoo** [comment]
Frankly if you want to revert the neutral protection section it's not gonna hurt my feelings, I had split it up into 2 commits because I wasn't confident that it was a great fit. I believe at the time I was mostly tired of the requests for protecting named entities and this was the best way I could come up with supporting neutral mobs.
