### ISSUE TITLE
Faster and Fastest Accrual Config options gone

### ISSUE THREAD

**Issue by CeIebrimbor** [GriefPrevention/GriefPrevention#163]
### What behaviour is expected:
Config options for faster accrual and fastest accrual
### What behaviour is observed:
No config options

### Spigot/Craftbukkit/Paper and GriefPrevention version:
Latest PaperSpigot for 1.12 (1139) and GP 16.7.1 from [here](https://github.com/TechFortress/GriefPrevention/releases/tag/16.7.1)

### GriefPrevention config.yml (if applicable)
Fresh generated with a newly downloaded jar to be sure
https://hastebin.com/xedisanelo.php

**Comment by RoboMWM** [comment]
See #18 

And reading update notes helps too.

**Comment by CeIebrimbor** [comment]
@RoboMWM 
To get this straight, you removed a widely used function in GP and opened it up to people to provide Add-ons, yet none exist that replace said function?

Edit: Jikoo linked me to where I needed.

**Comment by CeIebrimbor** [comment]
Can I pay you $3 to make a micro-plugin so custom perms like "gpaddon.125" or "gpaddon.200" would hook and replace the default (in config) with the permission bonus?

**Comment by Jikoo** [comment]
@CeIebrimbor None exist? https://github.com/TechFortress/GriefPrevention/issues/116#issuecomment-301247818

Edit: GH editor appears to have gone wonky on my end, I only see my text once, but it's there twice when posted.

**Comment by CeIebrimbor** [comment]
I have trouble skimming gobs of random posts on a github looking for plugins. I didn't think to skim 50+ possible messages. Thank you for pointing it out @Jikoo, even if it was a bit sarcastic :p

**Comment by RoboMWM** [comment]
I added it to the wiki as well. I think the issue is also referenced in that original issue.
