### ISSUE TITLE
protection error

### ISSUE THREAD

**Issue by IvensDias** [GriefPrevention/GriefPrevention#1631]
hello, when I protect an area it is unprotected from layer 21 to 0, can you help me?

**Comment by bigpresh** [comment]
Correct default behaviour, the claim will auto-extend downwards if the player places blocks or mines below it... see the doco for the `Claims.ExtendIntoGroundDistance` config setting to control this: https://github.com/TechFortress/GriefPrevention/wiki/Setup-and-Configuration#claim-limits
