### ISSUE TITLE
Not hitting wolves

### ISSUE THREAD

**Issue by Reserpente** [GriefPrevention/GriefPrevention#1634]
Hi, wolves don't get shot as long as she/he owns it
Is there any way I can turn this setting off?
unfair fights take place, thank you.

**Comment by bigpresh** [comment]
You should find that other players can't harm a tamed wolf - *unless* they're being targeted by it, in which case it's fair game:

https://github.com/TechFortress/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java#L1134-L1151

In other words, if someone else's wolf is attacking you, you can attack (and kill) it, but you can't do so if it isn't targeting (trying to attack) you.

**Comment by Reserpente** [comment]
No, even if I attack the owner, it hits me, I can't hit it.

**Comment by Reserpente** [comment]
I have a video where can I reach you ?

**Comment by Reserpente** [comment]
?

**Comment by bigpresh** [comment]
You could post it to any public sharing site and put the URL here - or attach it, if it's not too big for GitHub to accept.

**Comment by bigpresh** [comment]
Also, please provide all the info in the bug report template - i.e. versions in use, other plugins etc.

**Comment by PrettyTroubles** [comment]
@Reserpente is there any way you can post the video here? Also, what build did this happen on?

**Comment by Jikoo** [comment]
Closing in favor of #1679
