### ISSUE TITLE
Candles

### ISSUE THREAD

**Issue by mjminer** [GriefPrevention/GriefPrevention#1637]
Untrusted players can put out candles in claimed lands by right clicking on it .

**Comment by Jikoo** [comment]
Please fill out the template you deleted. Without further information I assume you're running the latest release, which does not contain fixes for 1.17 issues. You can find dev builds that support 1.17 on the CI. The latest dev build can be found [here](https://ci.appveyor.com/project/RoboMWM39862/griefprevention/build/artifacts).
