### ISSUE TITLE
Name bug when adding bedrock player in trust

### ISSUE THREAD

**Issue by JonDeschenes** [GriefPrevention/GriefPrevention#1639]
### What happened:
[.nameofplayer]
### What was expected:
.nameofplayer

### Steps to reproduce:
1) Make sure you got MCGeyser for compatibility between a Java server and bedrocks players
2) Claim a land.
3) /trust the bedrock player (they have a . before their names)

The bug only happen when I use any Trust command. If the bedrock player claim a land his name will be correctly written.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
This server is running Paper version git-Paper-"f2cb9cb" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f2cb9cb)
16.17.1-2b69191

Here's an exemple of what it is written in a ClaimData :
Lesser Boundary Corner: world;75;25;-291
Greater Boundary Corner: world;125;58;-270
Owner: 342750d0-8fcc-430f-a948-ef75876b7e55
Builders:
- 1ee02bcd-ae34-423b-8bae-b81820840eb3
- 9b05267e-0654-4213-a895-a1c8e798c11c
- '[.comicsans490]'                                                             <--------------------- Problem Here
- da25b6e7-a100-43ca-9e74-7ffee68c9e73
Containers: []
Accessors: []
Managers:
- 9b05267e-0654-4213-a895-a1c8e798c11c
Parent Claim ID: -1
inheritNothing: false

Thank you for your time,
Jon

**Comment by HVSrekktt** [comment]
I got this problem too. I was searching for it. But could'nt find any solutions

**Comment by Jikoo** [comment]
Duplicate of #1360
