### ISSUE TITLE
Problems with modded mc

### ISSUE THREAD

**Issue by kill23445** [GriefPrevention/GriefPrevention#1642]
### Observed Behavior

Mc version 1.7.1 (still commonly used for modded mc) the gold outlines failed and destroyed some modded blocks. “Modpack: Gregtech new horizons”

### Expected Behavior

I guess…. Not to destroy things with the outline?

### Reproduction steps

Make a claim. Place a machine on the outline and make it appear. Machine is now dead.

### Server version

```shell
Mc vs 1.7.1
```

### GriefPrevention version

```shell
Latest build for mc vs 1.7.1
```

### Configuration

```yaml
Default
```

### Plugin list

```shell
Grief protection.
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by bigpresh** [comment]
I'll be honest, I think it's probably unlikely this will be fixed.  GP is designed mostly for typical survival servers - modpacks may be doing all manner of weird and wonderful things, and it's fairly unreasonable for GP to be tested against them all and make allowances for whatever they do.  Versions as old as whatever supported 1.7 are also so old that continuing updates and support for them are probably not realistic.

**Comment by Jikoo** [comment]
GP doesn't change the actual block - it sends fake blocks to the player. Odds are on that when the fake block is reverted, the server implementation does not resend all the block data it should be. Try reloading the chunk. I'm pretty sure clients that old don't have the debug option to reload chunks, so you may need to leave the area or log out and back in.

Echoing bigpresh, old versions aren't really supported here. If you're having a specific problem for a very outdated version, you'll probably need to find someone actually willing to program against a MC version that old to help you.

Going to close this, doubt anyone is willing to take it on. Even if they were you didn't fill out the template properly so we have no idea what server implementation you're running.
