### ISSUE TITLE
GriefPrevention mod 1.16.5

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#1648]
### Observed Behavior

The server is starting and then:

GriefPrevention.jar is missing mods.toml 

the server run but without GriefPrevention.

### Expected Behavior

The server starts with GriefPrevention normal

### Reproduction steps

1. download GriefPrevention from https://www.curseforge.com/minecraft/bukkit-plugins/grief-prevention
2. drop it in the mods folder
3. start server

### Stack trace or error log

```shell
[18:34:24] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file Mod File: /mnt/minecraftotherpacks/mods/GriefPrevention.jar is missing mods.toml file
[18:34:24] [main/WARN] [ne.mi.fm.lo.mo.ModDiscoverer/SCAN]: File /mnt/minecraftotherpacks/mods/GriefPrevention.jar has been ignored - it is invalid
```

### Server version

```shell
forge-Server-1.16.5 (i use Nitrado)
```

### GriefPrevention version

```shell
Dateiname;
GriefPrevention.jar

Hochgeladen von:
RoboMWM

Hochgeladen:
Jan 19, 2021

Spielversion:
1.16

Größe:
301,94 KB

MD5:
50655427835648d95cc79c5e7cc073e6

sorry if its not waht you like to see but i dont fine other options.
```

### Configuration

```yaml
First installation
```

### Plugin list

```shell
no
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
GriefPrevention is a Bukkit plugin, not a Forge mod. If you are using a server implementation that offers support for Bukkit plugins, you need to install it like a Bukkit plugin in the plugins directory.
