### ISSUE TITLE
claim.getGreaterBoundaryCorner() and claim.getLesserBoundaryCorner() returns the wrong Y

### ISSUE THREAD

**Issue by 7-75** [GriefPrevention/GriefPrevention#1654]
### Observed Behavior

I'm writing a plug-in that places a block in the middle of the claim.
I'm calling the methods in question to get the locations of the 2 corners of the claim and make a mathematical average rounded by defect to get the middle of the claim. But instead of that I'm getting random Y values from the methods.

### Expected Behavior

I'm expecting the methods in question to return the location of the corners where I right-clicked with the goldenshovel to create the claim.
Instead I'm getting a random Y location but the right  X and Z

### Reproduction steps

   public static Location addNexusToCenterOfClaim(Claim claim)
    {
        Location topLocation    = claim.getGreaterBoundaryCorner();
        Location bottomLocation = claim.getLesserBoundaryCorner();

        System.out.println(topLocation);
        System.out.println(bottomLocation);

        double x;
        double y;
        double z;

        x = Math.round((topLocation.getX()+bottomLocation.getX())/2);
        y = Math.round((topLocation.getY()+bottomLocation.getY())/2);
        z = Math.round((topLocation.getZ()+bottomLocation.getZ())/2);

        Location centerLocation = new Location(topLocation.getWorld(), x, y, z);

        centerLocation.getBlock().setType(Objects.requireNonNull(nexusMaterial));

        System.out.println(centerLocation);

        return centerLocation;
    }

### Server version

```shell
This server is running Purpur version git-Purpur-1423 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6cbba00 on ver/1.17.1)
```

### GriefPrevention version

```shell
GriefPrevention version 16.17.1-2b69191
```

### Configuration

```yaml
default configuration
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
Why would you expect the claim min and max to be anything other than min and max Y values encompassed? It being the actual clicked locations doesn't really make sense. The lowest clicked Y should affect the lowest corner, however, GP also subtracts the extend into ground distance from that number. The max Y should realistically be world max height, although sometimes that is not actually the case. GP always internally treats it that way though.

If you're looking for a nice Y level for display purposes you should probably determine it yourself based on the blocks on the axis.
