### ISSUE TITLE
1.7.9 Mods

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#166]
Hello there, I'm running a forge + bukkit/spigot server for 1.7.10
Whenever I clear the griefprevention config, it adds items from mods that I have removed ages ago, I even removed the world.
  Mods:
    BlockIdsRequiringAccessTrust:
    - 5432:*:Acacia Door
    BlockIdsRequiringContainerTrust:
    - 227:*:Battery Box
    - 130:*:Transmutation Tablet
    - 128:*:Alchemical Chest and Energy Condenser
    - 181:*:Various Chests
    - 178:*:Ender Chest
    - 150:*:Various BuildCraft Gadgets
    - 155:*:Filler
    - 157:*:Builder
    - 158:*:Template Drawing Table
    - 126:*:Various EE Gadgets
    - 138:*:Various RedPower Gadgets
    - 137:*:BuildCraft Project Table and Furnaces
    - 250:*:Various IC2 Machines
    - 161:*:BuildCraft Engines
    - 169:*:Automatic Crafting Table
    - 177:*:Wireless Components
    - 183:*:Solar Arrays
    - 187:*:Charging Benches
    - 188:*:More IC2 Machines
    - 190:*:Generators, Fabricators, Strainers
    - 194:*:More Gadgets
    - 207:*:Computer
    - 208:*:Computer Peripherals
    - 246:*:IC2 Generators
    - 24303:*:Teleport Pipe
    - 24304:*:Waterproof Teleport Pipe
    - 24305:*:Power Teleport Pipe
    - 4311:*:Diamond Sorting Pipe
    - 216:*:Turtle
    BlockIdsExplodable:
    - 161:*:BuildCraft Engines
    - 246:5:Nuclear Reactor
    PlayersIgnoringAllClaims: []

As you can see:
    - 130:*:Transmutation Tablet
I dont have ProjectE installed anymore, but it still adds it... and for the rest. the id's of the installed mod blocks are not even the correct ones.

**Comment by RoboMWM** [comment]
No idea - try editing the config while the server is stopped.

Only other guess is that something else (idk, maybe the mod or it's settings? Not sure if they can do that) is adding them.

That's about all I can say to help you out - this repo only supports craftbukkit (e.g. no "combo" type mods - although you can try to run it yourself) and derivatives I'm aware of like spigot and paper on the latest version.

**Comment by ghost** [comment]
would it be an solution if I remove the whole config?

**Comment by RoboMWM** [comment]
Whatever you do, try it when the server is stopped. That may help.

**Comment by ghost** [comment]
OK, seems like it might work. thanks <3
