### ISSUE TITLE
Could not pass event PlayerJoinEvent to GriefPrevention v16-RC1

### ISSUE THREAD

**Issue by franticTech** [GriefPrevention/GriefPrevention#169]
### What behaviour is expected:
No errors in console 
### What behaviour is observed:
Error in console when any player logs into the server
### Steps/models to reproduce:
Logging or relogging into the server

### Spigot/Craftbukkit/Paper and GriefPrevention version:
This server is running CraftBukkit version git-Spigot-7228328-6659ddf (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

GriefPrevention version 16-RC1

### Stack trace/error (if applicable)

15.07 00:46:26 [Server] ERROR Could not pass event PlayerJoinEvent to GriefPrevention v16-RC1
15.07 00:46:26 [Server] INFO org.bukkit.event.EventException: null
15.07 00:46:26 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:342) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:162) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
15.07 00:46:26 [Server] INFO Caused by: java.lang.UnsupportedOperationException: Not supported in this Minecraft version.
15.07 00:46:26 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.hasAchievement(CraftPlayer.java:573) ~[spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO at me.ryanhamshire.GriefPrevention.GriefPrevention.isNewToServer(GriefPrevention.java:3555) ~[?:?]
15.07 00:46:26 [Server] INFO at me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerJoin(PlayerEventHandler.java:635) ~[?:?]
15.07 00:46:26 [Server] INFO at sun.reflect.GeneratedMethodAccessor301.invoke(Unknown Source) ~[?:?]
15.07 00:46:26 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
15.07 00:46:26 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
15.07 00:46:26 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-7228328-6659ddf]
15.07 00:46:26 [Server] INFO ... 14 more
### GriefPrevention config.yml (if applicable)

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_nether: Survival
      world_the_end: Survival
      world: Survival
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: false
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 1316134912
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: -1
    ExtendIntoGroundDistance: 500
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 30
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: -1
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 5
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: false
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 1.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: true
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

### Plugin list (if applicable):
Plugins (36): CoreProtect, dynmap, WorldEdit, Orebfuscator4, Dragon, ChatControl, PlugMan, WorldBorder, Votifier, BetterPvP, WorldGuard, PhantomAdmin, VotingPlugin, Shopkeepers, PermissionsEx, PexGUI, TrophyHeads, Vault, GriefPrevention, boosCooldowns, AreaShop, Essentials, Announcer, PerWorldInventory, CommandSigns, TreasureChest, PermissionsExTabColors, ChestCommands, DiscordSRV, EssentialsGeoIP, EssentialsChat, Durexp, JDynmapGriefPrevention, PvPManager, EssentialsSpawn, EnjinMinecraftPlugin

**Comment by RoboMWM** [comment]
RC1, what version are you even using... one I uploaded for someone specific to use to troubleshoot? Please update.
