### ISSUE TITLE
1.18 claims don't work below y = 0

### ISSUE THREAD

**Issue by weihao** [GriefPrevention/GriefPrevention#1700]
### Observed Behavior

1.18 claims don't work below y = 0

### Expected Behavior

1.18 claims extends full height of the world

### Reproduction steps

in 1.18, ExtendIntoGroundDistance does not fully extend into y < 0

### Stack trace or error log

```shell
N/A
```

### Server version

```shell
This server is running Paper version git-Paper-55 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 0e25db2)
```

### GriefPrevention version

```shell
GriefPrevention version 16.17.1-39-ga7cb4a0
```

### Configuration

```yaml
N/A
```

### Running without GriefPrevention

- [x] I attempted running the server without GriefPrevention installed.
- [x] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [x] I attempted running only GriefPrevention on the server.
- [x] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [x] I attempted testing for the issue on a new server.
- [x] The issue still occurs on a new server.

### Using unmodified client

- [x] I attempted testing for the issue with the vanilla client.
- [x] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by weihao** [comment]
https://github.com/TechFortress/GriefPrevention/blob/a7cb4a0c788436f9808acbb831627a282fde4744/src/main/java/me/ryanhamshire/GriefPrevention/DataStore.java#L881-L883

found the problem, will submit a MR soon

**Comment by Jikoo** [comment]
Update the configuration you didn't bother to include to allow claims to extend below 0. The new default is the minimum possible value for an integer to support datapacks changing world depth.

**Comment by weihao** [comment]
Why not update the API to 1.18?

Although getMinHeight will return 0 or -64 depending on the runtime, we use should use the latest API.

**Comment by Jikoo** [comment]
Updating the API version to 1.18 will only serve to arbitrarily exclude 1.17 users because there are no changes that require it to be updated.

Min height is not guaranteed to be 0 or -64. It may be below -64 depending on datapack. Raising max depth from its current value of -2147483648 up to -64 is a useless support burden - if Mojang ever lowers the world height further, people will have the same problems. Feel free to check out how many people have already raised duplicate issues on this. Why would we knowingly make that a possibility when it's perfectly avoidable? My guess is that you forgot to update your config prior to testing and assumed that the current default value is a problem.

**Comment by weihao** [comment]
> 

yeah, you are right. my bad that I didn't update the config and it is now working after regeneration. 

thanks for the input on the issue and MR.

**Comment by celophys** [comment]
where can i download this new version?

**Comment by weihao** [comment]
> where can i download this new version?

you can build it or have ci have it.

**Comment by osfast** [comment]
my players have the same problem : no redstone below 0. 
i understand it should be something in the config file? but what thing should i set to what value?

**Comment by p4pper** [comment]
Change the MaximumDepth in config to -60
