### ISSUE TITLE
Disable all Messages for Players

### ISSUE THREAD

**Issue by MCTyler** [GriefPrevention/GriefPrevention#171]
I just use grief Prevention for Admin Claims. How can I disable all Messages being sent to Players?

**Comment by Jikoo** [comment]
Changing messages to blank in Messages.yml should do it, however, you should really configure the plugin and your permissions system so features you don't want players using are unavailable.

**Comment by MCTyler** [comment]
I have denied the permissions but it still Spams Website info and permission info. Not needed if they can't claim. Thanks! I'll try that! (Only problem is there is ALOT of messages to "blank out" and I was looking for a more efficient way).
http://imgur.com/a/5xUv0

**Comment by RoboMWM** [comment]
Version 20 should provide for better options, including being able to create and use admin claims in disabled worlds.

**Comment by MCTyler** [comment]
Here is a Empty Message file for the most part if anyone needs it!
https://pastebin.com/ZbE4eYjN

**Comment by MCTyler** [comment]
I will close this....
