### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by Remski01** [GriefPrevention/GriefPrevention#172]
### What behaviour is expected:
_What you expected to see_
### What behaviour is observed:
_What you actually saw_
### Steps/models to reproduce:
Just leave the server online and this error then show up in console.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
Server: Spigot 1.11.2
GriefPrev: v16.7.1

Note: Plugin will startup whitout any error.
### Stack trace/error (if applicable)
https://pastebin.com/N2vFzb7b

Paste entire stack trace inside here
https://pastebin.com/N2vFzb7b

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here
```

**Comment by RoboMWM** [comment]
It seems like playerdata file `1f78bf83-951e-425a-afd5-66955e5f5210` is corrupted. Please post the contents of this file here and delete/fix it, if possible.

**Comment by Remski01** [comment]
I checked the "PlayerData" and it was 0kb and empty. So i just deleted the file.

If the error is now gone i will close the topic. 

And i havea question. Can this caused our recent server closedups? The server sometimes close itzelf. (stopping the server) Or is this a issue regarding our host?

**Comment by RoboMWM** [comment]
> Can this caused our recent server closedups? The server sometimes close itzelf. (stopping the server) Or is this a issue regarding our host?

Possible it could be due to crashing. Another common problem is running out of space.
