### ISSUE TITLE
Toggle sign/whisper notifications

### ISSUE THREAD

**Issue by SiuanSong** [GriefPrevention/GriefPrevention#176]
Requesting some features.

- Command to toggle whisper notifications.
- Command to toggle sign notifications. 
- Permission to receive soft-mute messages.  Currently, only my OP's can see them so other staff members never know if someone is soft-muted without testing the command on them.

**Comment by RoboMWM** [comment]
> Permission to receive soft-mute messages.

Should be the griefprevention.spam perm node, iirc. Don't know if it also applies to signs.

**Comment by SiuanSong** [comment]
Nope, wasn't the griefprevention.spam perm D:

**Comment by RoboMWM** [comment]
My mistake, apparently it's `griefprevention.eavesdrop`

**Comment by RoboMWM** [comment]
Related to #38

**Comment by RoboMWM** [comment]
If you still want toggle commands, go ahead and make a new post in the discussions ideas category. Otherwise closing.
