### ISSUE TITLE
lastlogin was not updated

### ISSUE THREAD

**Issue by weihao** [GriefPrevention/GriefPrevention#1760]
### Observed Behavior

![lastlogin](https://user-images.githubusercontent.com/31719556/149613973-827ffa3e-9c2c-48f9-9179-f2d42cdd9acf.PNG)

### Expected Behavior

LastLogin should be updated

### Reproduction steps

N/A

### Stack trace or error log

```shell
N/A
```

### Server version

```shell
This server is running Paper version git-Paper-150 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0c64d40)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-142 (MC: 1.18.1)
```

### GriefPrevention version

```shell
GriefPrevention version 16.17.1-42-g3562a23
```

### Configuration

```yaml
N/A
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
`lastlogin` is a legacy field that only hasn't been removed because there hasn't been a db revision for it. GP relies on `OfflinePlayer#getLastPlayed` instead.
