### ISSUE TITLE
PlayerPickupItemEvent [WARN]

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#178]
### What behaviour is expected:
_What you expected to see_
### What behaviour is observed:
_What you actually saw_
### Steps/models to reproduce:
_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_

### Spigot/Craftbukkit/Paper and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___

### Stack trace/error (if applicable)
31.07 02:20:10 [Server] WARN [GriefPrevention] "GriefPrevention v16.7.1" has registered a listener for org.bukkit.event.player.PlayerPickupItemEvent on method "public void me.ryanhamshire.GriefPrevention.PlayerEventHandler.onPlayerPickupItem(org.bukkit.event.player.PlayerPickupItemEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [].

**Comment by Jikoo** [comment]
While GP probably should swap to the EntityPickupItemEvent, the [warning was removed](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/0ce77bc4b3825b1665b34f7dd6dc4b01a02e9443#src/main/java/org/bukkit/event/player/PlayerPickupItemEvent.java).

**Comment by RoboMWM** [comment]
See Jikoo's response.
