### ISSUE TITLE
Observer Block not working

### ISSUE THREAD

**Issue by FrostBlade5** [GriefPrevention/GriefPrevention#1801]
### Observed Behavior

**As i was told i changed the config,yml from claim only to everywhere to allow pistons globaly.
However now i was building an automatic sugar farm, the observer block will send a signal to the piston to break the sugar block.
But it does not work. Is griefprevention blocking observers aswell? Cant find a config option.

Screenshot:**
[https://i.postimg.cc/qqgsw-0qj/2022-02-12-22-31-15.png](url)
[https://i.postimg.cc/tCZdVXLg/2022-02-12-22-31-31.png](url)

### Expected Behavior

looking for help

### Reproduction steps

default settings

### Server version

```shell
1.18.1
```

### GriefPrevention version

```shell
latest
```

### Configuration

```yaml
default settings
```

### Plugin list

```shell
essentials
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
GP does not mess with observers. You say you have changed the config but did not paste it in its current state. Please actually fill out the template, it's there for a reason.

In addition, while it's unlikely to be relevant here, 1.18.1 is not a valid server implementation and build, nor is "latest" a valid GP version. Use the `/version` command and paste the output.

For my own convenience, embedding your images:
![img](https://i.postimg.cc/qqgsw-0qj/2022-02-12-22-31-15.png)
![img](https://i.postimg.cc/tCZdVXLg/2022-02-12-22-31-31.png)

**Comment by FrostBlade5** [comment]
Thanks for helping, it appears the bug fixed itself.
Cant say what happened exactly but everything works now, thanks for your support!

**Comment by Jikoo** [comment]
Glad to hear it's working 👍
