### ISSUE TITLE
Struck/Trapped keyword

### ISSUE THREAD

**Issue by mrcoffee1026** [GriefPrevention/GriefPrevention#182]
### What behaviour is expected:
Ability to DISABLE this keyword
### What behaviour is observed:
"stuck" still activates "trapped" message
### Steps/models to reproduce:
Default behavior: type "stuck" or "trapped" and GriefPrevention will alert of presence of /trapped command.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
CraftBukkit version git-Spigot-596221b-b1b9ab0 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
GriefPreveintion 16.7.1

### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)
Adjusted messages.yml as follows:
  TrappedChatKeyword:
    Text: _t_r_a_p_p_e_d_

Still fires on use of word "stuck" even though that's not an option.

```yml
Paste config inside here
```

**Comment by RoboMWM** [comment]
Adjust messages.yml value to an empty string (two single quotes).

```
Text: ''
```

**Comment by Jikoo** [comment]
Actually, [it's hardcoded as well](https://github.com/TechFortress/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java#L255).

**Comment by RoboMWM** [comment]
The keyword is, yes, but not the instructions. Was late at night so missed the exact thing he was referencing.

@mrcoffee1026 you'll want to set the instructions to an empty string, not the keyword.

**Comment by mrcoffee1026** [comment]
This did not work.  Still responds with the /trapped information anytime the word "stuck" is mentioned in chat.  Annoying as heck, especially to anyone who has been playing on a server that has had this plugin for longer than 2 minutes.

**Comment by mrcoffee1026** [comment]
Oh also, well done.  Changin it to '' causes every word i utter to be responded to with the /trapped statement, EVERY.  It fortunately doesn't spam EVERY player, just the "owner", but this is horrifying.  Also laggy as heck.  Not a solution, please revisit this issue.

**Comment by bigpresh** [comment]
At a quick glance, I think a sane course of action would be to:

* remove the hard-coded checks on trapped/stuck and check only for `Messages.TrappedChatKeyword` - and only if it's non-empty - and supporting multiple words separated by "|"
 * tweaking the default value for `Messages.TrappedChatKeyword` to `trapped|stuck`

**Comment by Jikoo** [comment]
>Oh also, well done. Changin it to '' causes every word i utter to be responded to with the /trapped statement, EVERY. It fortunately doesn't spam EVERY player, just the "owner", but this is horrifying. Also laggy as heck. Not a solution, please revisit this issue.

That's why you read what Robo says more carefully and adjust it in messages.yml, not the config :p

@bigpresh Personally I'd like to see a regex option instead, though that does mean more hassle with supporting users who aren't familiar with its syntax. Quite a bit more flexible, and allows for the old behavior of "trapped" but not "/trapped" triggering it.

**Comment by mrcoffee1026** [comment]
I DID read what Robo said carefully and that was the setting I put in messages.yml.  The result is every single thing I type gets responded to with the "/trapped" information.  I am reporting this bug since they've hardcoded the matches into their code and I can't take them out without altering source.  There should simply be an option to disable the feature.  Also config.yml has no information pertaining to this, whatsoever, so I don't know where you got the idea that this is where I was putting that setting.

**Comment by bigpresh** [comment]
Yeah, I'm working on it, give me a bit.

**Comment by bigpresh** [comment]
Robo's suggestion of setting the value of `TrappedInstructions` in messages.yml (*not* `TrappedChatKeyword`) does appear to do the job of stopping the messages appearing, so my PR isn't strictly necessary, but it does make it cleaner and easier, and allows still having the message while overriding the default words, so probably still has value.

I went with comma-separated words rather than a regex simply because I think it's easier for users to understand.

**Comment by Jikoo** [comment]
>Also config.yml has no information pertaining to this, whatsoever, so I don't know where you got the idea that this is where I was putting that setting.

Weird, that's pretty inconsistent. I was under the impression it was in the chat configuration section, shows how long it's been since I've left GP's chat listener enabled :V Either way, as bigpresh said, Robo was referring to the actual message sent to the players, not the word itself.

**Comment by mrcoffee1026** [comment]
Yeah, verified that works... if I just change the message instead of the keywords, it's fine... but this does seem highly inefficient since the code will keep (trying to) make matches against all text entered into chat, even though the result of the code is to "do nothing" at this point.  i do appreciate the help in this matter.

**Comment by bigpresh** [comment]
On Tue, 08 Aug 2017 23:38:42 +0000 (UTC)
mrcoffee1026 <notifications@github.com> wrote:

> Yeah, verified that works... if I just change the message instead of
> the keywords, it's fine... 

Good stuff, glad you got it sorted :)

> but this does seem highly inefficient since the code will keep
> (trying to) make matches against all text entered into chat, even
> though the result of the code is to "do nothing" at this point. 

I shouldn't think a couple of String.match() calls should be
particularly expensive, but fair point.

The stuff I did in my PR skips checking them if the trigger words was
empty, anyway.

**Comment by RoboMWM** [comment]
> Yeah, verified that works... if I just change the message instead of the keywords, it's fine... 

This is exactly what I said to do :P

Anyways, the regex is precompiled so unless you see otherwise in a profile (timings won't reveal as chat is an async operation), there's no performance impact.
