### ISSUE TITLE
[Suggestion] no commands

### ISSUE THREAD

**Issue by ShaneBeee** [GriefPrevention/GriefPrevention#184]
Would it be a possibility to add something so when players come in your claim you could turn off certain commands such as /Sethome?
I have a few players complaining that a player comes in their home and then setting a home, allowing them to enter anytime.

**Comment by Jikoo** [comment]
```yaml
GriefPrevention.Claims.CommandsRequiringAccessTrust: /sethome;/esethome
```

**Comment by RoboMWM** [comment]
See jikoo's response. It's in the config.

**Comment by ShaneBeee** [comment]
Ah. 
I didn’t see that in my config.  Thank you. 
If it’s not there do I just pop it in?

**Comment by ShaneBeee** [comment]
Okay, i found it. And it already has /sethome in the list, but for some reason a player was able to set a home in my claim.

**Comment by RoboMWM** [comment]
What plugin is responsible for sethome? Do they have /accesstrust?

**Comment by ShaneBeee** [comment]
I use essentials for set homes.  
They do not have access trust.  
I think it may be a problem on my end.  
I went on a players claim, typed set home and it wouldn’t let me. Yet one of my players has been able to do it.    Very confusing.

**Comment by Jikoo** [comment]
Essentials offers the alias `/esethome` and and alias can also be used via the plugin prefix, `/essentials:home` or `/essentials:esethome`
Add them all to your config and you should be good to go.

**Comment by ShaneBeee** [comment]
Perfect. Thank you guys. I’ll add those today and test them out
