### ISSUE TITLE
/ignoreclaims permission not working for non-OP

### ISSUE THREAD

**Issue by PathosMachine** [GriefPrevention/GriefPrevention#185]
I'm having issues with /ignoreclaims and /ic for Moderators (non-op) not working despite them having the permissions for the command. As someone with level 3 OP, I have access to the /ic command, but I need my mods to be able to do their full jobs and not have to come to me for things they should be able to do themselves. This randomly stopped working a few weeks ago (when I was still running 1.12). I didn't do any updates to any pluggins, it just...stopped. I tried changing how PEX perms were written, the order in which plugins loaded, and even removing GP and reinstalling it. 

Some users have also experienced being unable to subdivide claims, but I got that fixed, but now they can't /accesstrust despite being able to /containertrust.

**Version:** Craftbukkit, git-Spigot-edd0396-2a927e8 (MC: 1.12.1)

**GP Version:** 16.7.1

**GriefPrevention Config:** https://pastebin.com/Gnjd6PvY

**PEX Config Example:** https://pastebin.com/uu9Mnwrh

**Other Pluggins:** 

- PermissionsEx
- EssentialsX
- AFKTerminator
- Daily Rewards
- ClearLagg
- CoreProtect
- Autorank
- DisableCommandsPlus
- OpenInv
- NoCheatPlus
- WorldGuard
- WorldEdit
- Shopkeepers
- Votifier
- Statz
- ProtocolLib
- SuperbVote

**Comment by RoboMWM** [comment]
> This randomly stopped working a few weeks ago (when I was still running 1.12). I didn't do any updates to any pluggins, it just...stopped. 

So something changed. Try using older versions of GP (though I doubt we changed anything regarding that perm)?

> Some users have also experienced being unable to subdivide claims, but I got that fixed, but now they can't /accesstrust despite being able to /containertrust.

Don't recall perms existing for these but... idk, maybe disablecommandsplus interfering? What message do they receive when the command fails to work?

**Comment by PathosMachine** [comment]
I disabled DisabledCommandsPlus and that is what seemed to be interfering. It was weird though because not a single instance of _any_ GriefPrevention perm or command was listed within it. 

*sigh* Why does this stuff have to be so finicky? hahaha. 

Sorry for any trouble! Thanks for the help :)

**Comment by RoboMWM** [comment]
I betcha it's doing a very basic and amateur String#contains or startsWith check instead of an exact check. Also, you can use commands.yml to disable commands (assuming you already block /pluginname:command syntax)
