### ISSUE TITLE
Can't claim below 0 in Minecraft 1.18.2

### ISSUE THREAD

**Issue by RiDiCage** [GriefPrevention/GriefPrevention#1855]
### Observed Behavior

If I have a claim, it doesn't go lower then 0.

### Expected Behavior

The problem:
The claim area is visible with the wooden stick ( also below zero ), but if you want to demolish or place below zero, you can just do that. Even if it is not your own claim. The claim runs to level zero, so from -1 to -64 it is no longer protected.

### Reproduction steps

1. claim area
2. break or build blocks
3. go to level 0
4. break or build blocks
5. claim doesn't go below 0, although you can see the claim with the wooden stick.

### Stack trace or error log

```shell
There is no warning log.
```

### Server version

```shell
Server:
Spigot 1.18.2 R0.1 SNAPSHOT (27-03-2022)
```

### GriefPrevention version

```shell
Griefprevention version 16.18
```

### Configuration

```yaml
Not needed for this bug.
also it is just standard generated.
```

### Plugin list

```shell
Griefprevention works fine for what I use, ecxept the claim area.
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
Config is actually very important, because you likely have an old default config that does not have the value for `MaximumDepth` set to 1.17+ values.

**Comment by RiDiCage** [comment]
Aaah good to know, so if I delete the old config file and let the plugin create a new one, it could be fixed? I will try it later today!
If not I will react later again and will paste the config file over here as well.

**Comment by PirataGu** [comment]
Even modifiyng the MaximumDepth it does not work with negative y !!!

Just noticed that if I modify the claimdata to a negative Y coordinate IT WORKS but the plugin doesn't know how to put the - (minus) behind the number LOOOOL

**Comment by Jikoo** [comment]
Please stop spamming the tracker with the same message.

Judging by the fact that OP isn't back, it did in fact solve their problem.
