### ISSUE TITLE
Console color formatting broken on Paper

### ISSUE THREAD

**Issue by HexedHero** [GriefPrevention/GriefPrevention#1860]
### Observed Behavior

Console messages show the converted chat colors but due to a Paper change they are no longer parsed into actual visual colors, you now need to use the console command sender to support colors.

[GriefPrevention] §a§5§lClaims §7: Adjusted HexedHero's bonus claim blocks by 1000.  New total bonus blocks: 1000.

### Expected Behavior

Not have §5 etc in the message.

### Reproduction steps

Do any console related command that has a return message with color

### Server version

```shell
[04:37:11 INFO]: Checking version, please wait...
[04:37:11 INFO]: This server is running Paper version git-Paper-287 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: a9f252e)
```

### GriefPrevention version

```shell
GriefPrevention version 16.18
```

### Configuration

```yaml
N/A
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by RoboMWM** [comment]
epic
