### ISSUE TITLE
ProtectPetsOutsideLandClaims not working in MC1.12.1 + Some double messages

### ISSUE THREAD

**Issue by FrankHeijden** [GriefPrevention/GriefPrevention#187]
### What behaviour is expected:
 - pets which are protected outside land claims
 - one message and not double
 - no message when dog is outside claim?
### What behaviour is observed:
- players can hit pets belonging to others (when pet is in the claim, player has trust, or pet is outside)
- when you right click a pet in a claim of someone else, the message is doubled
- when you are outside a claim being attacked by someone elses dog, and you want to let the dog sit with right click, no message is displayed
### Steps/models to reproduce:
spigot server + GP

### Spigot/Craftbukkit/Paper and GriefPrevention version:
CraftBukkit version git-Spigot-5340a52-27b8bf9 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

GP 16.7.1

### Stack trace/error (if applicable)

```
no errors
```

### GriefPrevention config.yml (if applicable)

none

### Plugin list (if applicable):
GriefPrevention

**Comment by RoboMWM** [comment]
And what pets did you test with? Wolves are not protected in PVP worlds since they can attack (and cause a player unable to fight back).

**Comment by RoboMWM** [comment]
As for the double message, that's probably because an interactevent is being fired by each hand iirc.

**Comment by FrankHeijden** [comment]
Okay thanks, has been fixed. The PvP rules got somehow enabled again in the config, thats why.

Thanks!
