### ISSUE TITLE
You can break chorus flower in other claims

### ISSUE THREAD

**Issue by JHarris12345** [GriefPrevention/GriefPrevention#1882]
### Observed Behavior

You can shoot a chorus flower with a bow in someone elses claim and it will break. Gif below:

https://gyazo.com/2b401f79de362f6bc3cea626e16f882c

### Expected Behavior

It shouldnt break

### Reproduction steps

1. Claim land
2. Make a chrous flower
3. Shoot in

### Server version

```shell
This server is running Pufferfish version git-Pufferfish-22 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 42ef3dc on HEAD)
Received invalid status code (404) from server.
Previous version: git-Airplane-110 (MC: 1.17.1)
```

### GriefPrevention version

```shell
1.17.1
```

### Configuration

```yaml
https://pastebin.com/ExLqjVgx
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
This was fixed (indirectly) by #1424 - make sure your version of GP is up to date. 1.17.1 is not a valid GP version.
