### ISSUE TITLE
when i import the plugin server doesnt open

### ISSUE THREAD

**Issue by onurpince** [GriefPrevention/GriefPrevention#1883]
### Observed Behavior

i use advancedrealm plugin and i think they cant work with each other because there is commands in advanced plugin like claim and unclaim

### Expected Behavior

open the server :D

### Reproduction steps

no need i think

### Server version

```shell
1.18
```

### GriefPrevention version

```shell
last version
```

### Configuration

```yaml
defoult version
```

### Plugin list

```shell
advanced realm enough i think :D
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
What do you mean by "server doesn't open," the server doesn't start? If that's the case, we need startup logs.

1.18 is a Minecraft version. It is not a version of a server implementing the Bukkit API. Copy the output of `/version`.
"last version" is not a valid GP version.
