### ISSUE TITLE
error in the protect, no claim all layers 0 at 255

### ISSUE THREAD

**Issue by Pweg0** [GriefPrevention/GriefPrevention#192]
![screenshot_57](https://user-images.githubusercontent.com/28950032/29298990-07512c06-8142-11e7-8d98-c37de5910178.png)
### What behaviour is expected:
That he claimed from 0 to 255
### What behaviour is observed:
He claims up to a certain layer down, and the rest just up, see
in up
http://prntscr.com/g8k8al
in layer 56 have
http://prntscr.com/g8k8fy
but in layer 55
http://prntscr.com/g8k8qn
### Steps/models to reproduce:
_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_

### Spigot/Craftbukkit/Paper and GriefPrevention version:
 1.7.10

### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    DIM-100: -1
    DIM-37: -1
    DIM-38: -1
    DIM-39: -1
    DIM-42: -1
    DIM-19: -1
    DIM-112: -1
    DIM-1: -1
    DIM1: -1
  Claims:
    Mode:
      DIM-1: Disabled
      DIM-39: Disabled
      DIM-37: Disabled
      DIM-100: Disabled
      DIM-38: Disabled
      DIM-112: Disabled
      DIM1: Disabled
      DIM-19: Disabled
      world: Survival
      DIM-42: Disabled
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectFires: false
    ProtectHorses: true
    InitialBlocks: 500
    BlocksAccruedPerHour: 200
    MaxAccruedBlocks: 80000
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    CreationRequiresPermission: false
    MinimumSize: 10
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaimDays: 0
      AutomaticNatureRestoration:
        SurvivalWorlds: false
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    MonitorSlashCommands: /me;/tell;/global;/local;/w;/msg;/r;/t
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
  PvP:
    Worlds:
    - world
    - DIM-100
    - DIM-37
    - DIM-38
    - DIM-39
    - DIM-42
    - DIM-19
    - DIM-112
    - DIM-1
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  EavesdropEnabled: true
  WhisperCommands: /tell;/pm;/r;/w;/t;/msg
  SmartBan: true
  Siege:
    Worlds: []
    BreakableBlocks:
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  HardModeZombiesBreakDoors: false
  Database:
    URL: 'localhost'
    UserName: 'mc_8021'
    Password: 'ab85ac5'
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 227:*:Battery Box
    - 130:*:Transmutation Tablet
    - 128:*:Alchemical Chest and Energy Condenser
    - 181:*:Various Chests
    - 178:*:Ender Chest
    - 150:*:Various BuildCraft Gadgets
    - 155:*:Filler
    - 157:*:Builder
    - 158:*:Template Drawing Table
    - 126:*:Various EE Gadgets
    - 138:*:Various RedPower Gadgets
    - 137:*:BuildCraft Project Table and Furnaces
    - 250:*:Various IC2 Machines
    - 161:*:BuildCraft Engines
    - 169:*:Automatic Crafting Table
    - 177:*:Wireless Components
    - 183:*:Solar Arrays
    - 187:*:Charging Benches
    - 188:*:More IC2 Machines
    - 190:*:Generators, Fabricators, Strainers
    - 194:*:More Gadgets
    - 207:*:Computer
    - 208:*:Computer Peripherals
    - 246:*:IC2 Generators
    - 24303:*:Teleport Pipe
    - 24304:*:Waterproof Teleport Pipe
    - 24305:*:Power Teleport Pipe
    - 4311:*:Diamond Sorting Pipe
    - 216:*:Turtle
    BlockIdsExplodable:
    - 161:*:BuildCraft Engines
    - 246:5:Nuclear Reactor
    PlayersIgnoringAllClaims:
    -'[Mekanism]'

**Comment by RoboMWM** [comment]
> He claims up to a certain layer down, and the rest just up

That's how it works. As the player builds downwards in his claim, it will extend downwards.

You can of course configure this in the config if you so desire. `ExtendIntoGroundDistance`
