### ISSUE TITLE
Arrows activate buttons

### ISSUE THREAD

**Issue by ShaneBeee** [GriefPrevention/GriefPrevention#193]
### What behaviour is expected:
Buttons not be able to active on another players claim.
### What behaviour is observed:
When you shoot an arrow at a button on another persons claim, the button activates, in turn opening a door.
### Steps/models to reproduce:
Aim bow at a button on another person claim.
Shoot.
Arrow hits button.
Button activates
Door opens.
### Spigot/Craftbukkit/Paper and GriefPrevention version:
CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
GriefPrevention version 16.7.1

**Comment by RoboMWM** [comment]
Expected behavior. Players should use stone buttons, similar to using iron doors.

If you really want to protect wooden buttons, you could use an addon with whatever behavior you desire (checks shooter, cancels all arrows, deletes the arrow, has the arrow bounce off, etc.)

**Comment by ShaneBeee** [comment]
Ah.... didn't know the stone button offered different protection.
Ive changed the other players button, tested it, and it worked!

Thank you very much!
