### ISSUE TITLE
SlimeFun clash with GP

### ISSUE THREAD

**Issue by Ac3dUd3** [GriefPrevention/GriefPrevention#194]
### What behaviour is expected:
it not drop items
### What behaviour is observed:
it dropped items
### Steps/models to reproduce:
 if you hit a claimed animal with a one shot kill sword, then it doesnt die, but if you spam it, you will get the loot you get from the slimefun plugin
its normal, but becuase it doesnt die, you can do it for hours, and get a bunch of end game machines

### Spigot/Craftbukkit/Paper and GriefPrevention version:
This server is running CraftBukkit version git-Spigot-5340a52-27b8bf9 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
 GriefPrevention version 16.7.1

I know this is prob slimefun but i am posting it on both

**Comment by bigpresh** [comment]
Sounds like GP is doing the right thing, stopping the animal getting killed.  If SlimeFun is causing drops to appear anyway, that's solely a SF thing, not GP.

**Comment by RoboMWM** [comment]
Yea, no idea how slimefun is finding out if a mob dies, but it should be listening to entitydeathevent - which will never be fired if the animal never dies.
