### ISSUE TITLE
Disappeared 

### ISSUE THREAD

**Issue by DEEPSAH6105** [GriefPrevention/GriefPrevention#1945]
### Observed Behavior

Claimed land disappeared after some days of offline 

### Expected Behavior

It shouldn't be disappear and if then it should tell after how many days it is going to disappear.

### Reproduction steps

1. Step 1: Claim land (in any server)
2. Step 2: be offline for some days (around 30 days)
3. Step 3: see that the claimed went off

### Server version

```shell
1.19.2 java
```

### GriefPrevention version

```shell
Latest
```

### Configuration

```yaml
.
```

### Plugin list

```shell
7
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
As far as base GP is concerned, it's up to your server admin to distribute information about their activity requirements. If your server uses GPCE, there is a warning by default.
