### ISSUE TITLE
Claims not working

### ISSUE THREAD

**Issue by FatmanC** [GriefPrevention/GriefPrevention#196]
### What behaviour is expected:
_What you expected to see_ When creating a claim i expect to use a gold shovel to hit the first corner then the second corner to create the claim
### What behaviour is observed:
_What you actually saw_ Hitting the first corner works, but when you move diagonal to hit the second corner, you cannot create a claim. The shovel moves in an action movement, but does not create the second corner enabling the claim. doesnt matter where i move, it wont create a claim. BUT, then i rtp to  random spot, hit a block and then it decides to tell you you cant create a claim here as you do not have enough claim blocks. You need like 6 million claim blocks to make this claim. but even using /adminclaims doesnt work either. The same problem occurs. 
### Steps/models to reproduce:
_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_
Ive had other players try to claim small and large areas 
### Spigot/Craftbukkit/Paper and GriefPrevention version: 16.7.1
___This can be found by running `/version` and `/version GriefPrevention` on your server.___

### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here
```

**Comment by RoboMWM** [comment]
Yea, going to need more info here. Spigot version, plugins, if you're in gamemode 2, config, etc. I'm guessing this is a plugin conflict, provided that you are indeed successfully right clicking another block.

**Comment by FatmanC** [comment]
craftbukkit version-git-spigot-b78586d-03f1e37(mc1.12) (iimplementing API version 1.12-R0.1-SNAPSHOT)

plugins - essentialsX, coreprotect, epicworldgenerator, multiverse core, multiverse-portals, Guilds, vault
GroupManagerX, of course griefprevention, essentials chat, essentials spawn, essentials protect. tried using creative and survival modes to claim.

**Comment by RoboMWM** [comment]
Could I see an image or video of where exactly you click? Also try having just GP installed and see if it works then

**Comment by FatmanC** [comment]
i deleted it and reinstalled it. Fixed the issue
