### ISSUE TITLE
/accesstrust public not working in 1.12.1?

### ISSUE THREAD

**Issue by mnsnownutt** [GriefPrevention/GriefPrevention#202]
### What behaviour is expected:
Users able to open wooden doors in administrative claim that was created and then issued the command /accesstrust public.
### What behaviour is observed:
Users unable to open wooden doors.  Doors open for a tick and then immediately close.  Sometimes spaming on the door will cause it to open, but if player leaves they cannot reenter doorway even with the door open.  However, prior to loading GriefPrevention plugin, doors would open for the user (test user account I have created for this purpose).
### Steps/models to reproduce:
This is a brand new world.  Created a spawn building/area and then an admin claim around it to protect it.  Immediately after creating the claim, issued the /accesstrust public command and got the confirmation message.  However, when player without admin rights tries to open a door of the building in spawn, cannot do it.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
This server is running CraftBukkit version git-Spigot-65e8124-79e55b6 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
[GriefPrevention] Loading GriefPrevention v16.7.1

### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world_nether: Disabled
      world: Survival
      world_the_end: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: false
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 250
    Claim Blocks Accrued Per Hour:
      Default: 25
    Max Accrued Claim Blocks:
      Default: 2500
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 10
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: true
  SilverfishBreakBlocks: true
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

### Plugin list (if applicable):
ChopTree4, EssentialsX, EssentialsXChat, EssentialsXProtect, EssentialsXSpawn, GriefPrevention, OnePlayerSleep, PermissionsEx, ProtocolLib, RandomTP, Vault, mcMMO, WESV, WorldEdit

**Comment by mnsnownutt** [comment]
As additional information, logged back in as the admin and deleted the claim.  Run /adminclaimslist and it is now blank.  Log back in under user account and still cannot enter through doorway.  Spamming door will sometimes open a door and you can leave building, but cannot get back in.  Also, pressure plate on the inside of the door opens the door and allows player to leave, but they cannot get back in even if the door is open.

**Comment by RoboMWM** [comment]
Is this issue solved? You closed it...

Anyways, I highly suspect the issue is due to vanilla spawn protection, not GP, especially since you aren't getting a "no permission" message. Set spawnRadius in `server.properties` file to 0.

**Comment by mnsnownutt** [comment]
Sorry about that, did not realize I had closed it!

A little different syntax, but below was set to 16 in server.properties.  Changed it to 0 and all is good!  Guess I missed that.

spawn-protection=0

Thanks for the prompt response!!

**Comment by RoboMWM** [comment]
Ah yea, kinda guessed at what it would be named.
