### ISSUE TITLE
Won't enable plugin. "Empty path"

### ISSUE THREAD

**Issue by AnUglyWeirdo** [GriefPrevention/GriefPrevention#204]
### What behaviour is expected:
Expected the plugin to load onto the server and just work.
### What behaviour is observed:
An error saying "[Server] INFO java.lang.IllegalArgumentException: Cannot set to an empty path"
I've completely removed all GriefPrevention files and added a fresh .jar file and it still doesn't create a directory or anything like that.
### Spigot/Craftbukkit/Paper and GriefPrevention version:
Spigot 1.12 BuildTools: 60
Grief Prevention 16.7.1

### Stack trace/error:

https://pastebin.com/jRdtpRJX

**Comment by RoboMWM** [comment]
Weird. Maybe you somehow have a world with a blank name?

**Comment by RoboMWM** [comment]
Yea, seems to be caused by worlds with invalid names. https://www.spigotmc.org/threads/griefprevention.35615/page-219#post-2790680

(In case screenshot or thread link dies, author had the following folders in root directory of server):
```
_nether
_the_end
```
