### ISSUE TITLE
Issues with /containertrust

### ISSUE THREAD

**Issue by NiteCloak** [GriefPrevention/GriefPrevention#206]
### What behaviour is expected:

I used /adminclaims utilizing my golden shovel to create an admin claim around a new world spawn point. I want to be able to have a chest with a few basic goodies, freely available to new players as they spawn in at this location.

### What behaviour is observed:

After claiming as admin and depositing said goodies inside a basic chest,  I used '/containertrust all' (and later tried '/containertrust public' also) but no other player is able to open that chest in that admin claim unless I make them Op.

### Spigot/Craftbukkit/Paper and GriefPrevention version:

CraftBukkit version git-Spigot-edd0396-2a927e8 (MC: 1.12.1)
(Implementing API version 1.12.1-R0.1-SNAPSHOT)
GriefPrevention v16.7.1
DynMap GriefPrevention v0.8

### GriefPrevention config.yml (if applicable)

default config

### Plugin list (if applicable):

WorldEdit
GriefPrevention.jar
Vault.jar
dynmap-2.5.jar
worldedit-bukkit-6.1.7.3.jar
HolographicDisplays.jar
Essentials-2.x-SNAPSHOT.jar
EssentialsGroupManager.jar
EssentialsXChat-2.0.1.jar

**Comment by Jikoo** [comment]
Same as #202 probably, vanilla spawn protection.

**Comment by RoboMWM** [comment]
Please see my comments in #202
