### ISSUE TITLE
claim nextId reset to an earlier id, overwriting old claims

### ISSUE THREAD

**Issue by TomLewis** [GriefPrevention/GriefPrevention#207]
An admin claim of about 2-3 years, was deleted by itself for no reason at all, Nobody deleted it, GriefPrevention left no log of it being deleted, it just disappeared one day, and yesterday players noticed the claim was gone and raided it. This is a major issue, recently we have been seeing random long term claims removed without any reason or input from any user.

I did a grep on all my logs from 4 years to search to see if someone manually deleted this claim, nobody did. I searched for all admin claims being removed, it was not not in the list.

I scanned the logs created by GriefPrevention to see if the plugin had auto deleted it, it was not in these logs.

This is a major issue that admin claims can randomly just disappear for no reason, without a reason or log at all. How can I find out how this was removed?

it was not a user that did it.

**Comment by bigpresh** [comment]
Do you have a backup of your claim data to see what claim ID it had, and then check that claim data file to see (a) if it's corrupted somehow, (b) if it now contains details of a different claim?

The only time I've experienced any data loss with GP was when the server's disk temporarily filled up - it failed to write to the `_nextClaimID` file but didn't realise - so it then started again from ID 1, overwriting claims.  I raised issue #120 for that.

Either way, I think finding out what, if anything, is in the claim data file for that claim now would be useful.

**Comment by RoboMWM** [comment]
Yea, would check history/log of database since I know you use the MySQL option.

**Comment by TomLewis** [comment]
@bigpresh Yeah man, Daily MySQL backup since the dawn of time! And I run a test server with a duplicate of the main server, How do I find a claims ID in-game? Save a bit of time if I know what im looking for then!

Disk fill! Let me check:
```
tom@ns501023:~$ df -H
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        21G   12G  8.4G  57% /
devtmpfs        8.4G     0  8.4G   0% /dev
tmpfs           8.4G     0  8.4G   0% /dev/shm
tmpfs           8.4G  254M  8.2G   4% /run
tmpfs           5.3M     0  5.3M   0% /run/lock
tmpfs           8.4G     0  8.4G   0% /sys/fs/cgroup
/dev/sda3       2.0T  137G  1.8T   8% /home
```

dev/root is only 21G that's worrying, that's where the MySQL is saved haha Dammit I cant resize that without formatting. 57% shouldn't be that then.

Its still on my test server.

in the claim data file? I use MySQL for storage.

@RoboMWM Sorry to be such a noob how do I check the history/log of mysql? As in the raw log files? if so what would I be looking for? 

This claim is years old, it had a ton of sub-claims in it, i have always had issues of sub-claims getting randomly removed. Is there any way the plugin could have tried to remove a sub-claim and removed the actual main claim?

ive also had some other really random issues with normal claims getting auto removed too, I had one of my admins claims remove itself after being there for 4 years! Hes not even visited that island he claimed in about a year, he only noticed when he saw it on the live map it had been griefed and looted! (Good thing I keep backups!)

**Comment by Jikoo** [comment]
If your setup is anything like mine (an install using one of Kimsufi's presets), MySQL likely is configured to use `/home/mysql` for storage. Logs are in `/var/log/mysql`.

**Comment by bigpresh** [comment]
Ah, I didn't realise you were using the MySQL backend - in that case, mentions of the claim data files don't help you :)

The database backend stores the "next claim ID" in a table named `griefprevention_nextclaimid`.  I'm really not sure why it does that, rather than just making the claim ID column an auto-increment primary key and letting the database handle it, but, that's what it does.  So, check what the "next claim ID" is - e.g. `SELECT * FROM `griefprevention_nextclaimid` - and make sure it isn't unexpectedly low.

Also, look to see if there are any duplicated claim IDs - as the way the DB storage works, it shouldn't overwrite the claim data, but instead duplicate it, and which of the rows GP finds for that claim could be essentially random I think - so e.g. OTTOMH: `SELECT id, count(*) as records FROM griefprevention_claimdata GROUP BY id HAVING records > 1;`

Otherwise, to find out which claim ID it is, you could grab a list of your claims and compare their coords with a point that would have been within the claim, or go to the claim itself on your test server, give someone trust on it, then search the DB for claims that person has trust on, maybe - or just query based on the coords yourself (if you know the corners and the size, you can work it out).  It may be worth sharing the contents of that claimdata record in case anything stands out as unusual about it.


Looking at the DB code, it will nuke subdivisions if it can't find the parent claim (and, unverified, potentially if it can't load the parent claim because of a transient DB error, maybe?); it will however log that it is doing so, so if nothing was logged, that's unlikely to be the case.

Also, looking at how claims are stored, I see that `writeClaimToStorage` will delete any claim with that ID first, then call `writeClaimData` which will insert a new record.  Of course, if the latter fails, then the previous data will have been nuked, and the new record won't be created, so it's gone.  If that happened, though, it should be logged, e.g. "Unable to save data for claim at...".

Whatever the cause, it's definitely alarming that you're having claims disappear, particularly silently.

**Comment by RoboMWM** [comment]
Also, did this happen after you nabbed the "dev" version off of the maven repo? Both #135 and #99 have made changes to MySQL and subclaims. I really don't use subclaims myself nor MySQL, so I personally can't test these (at least not extensively), but they both reported things working okay from their tests. I hope these aren't the cause of your issues... (i.e. logs are going to be valuable)

**Comment by RoboMWM** [comment]
Any info on this? Were you using the "dev" versions when this occurred?

**Comment by TomLewis** [comment]
@RoboMWM 
I didnt even know there was a development build? where can I find that? 
I didnt get a chance to look into it further, but its happened again recently to an ancient claim of a players, so its not related directly to admin claims.

@bigpresh Man, I've always wondered the same thing, I came to the conclusion it was used for statistical purposes, or to keep a tally of all claims created for all time. Maybe it was put in for safety reasons to never have 2 IDs the same if someone started moving data around or something obscure.
My griefprevention_nextclaimid is **3517** This is unexpectedly low! I ordered my griefprevention_claimdata by ID and the highest ID of a claim is **72287**! This is very odd behaviour, should I set my nextid in nextclaimid to more than 72287?

Duplicate records, Running that query turned no results, I was expecting some TBH, my database is donkey years old over many developers of this plugin!

bigpresh you have given me a proper decent understanding of GriefPrevention so thanks for the full on write up.

I did ask the players that lost claims if they had sub-claims or if they changed anything, but both said they didnt have claims, hadn't updated anything, and both were massively old claims, well over 2/3 years old. I was wondering if it was a data type issue with the database schema, like the time reached X amount of time and died. My database is so old, the schema may not have been updated in all the version upgrades over the years. Let me also show you my structure I have.

```
CREATE TABLE `griefprevention_claimdata` (
  `id` int(15) NOT NULL DEFAULT '0',
  `owner` varchar(50) NOT NULL,
  `lessercorner` varchar(100) NOT NULL,
  `greatercorner` varchar(100) NOT NULL,
  `builders` text,
  `containers` text,
  `accessors` text,
  `managers` text,
  `parentid` int(15) NOT NULL DEFAULT '-1',
  `neverdelete` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `griefprevention_nextclaimid` (
  `nextid` int(15) NOT NULL DEFAULT '0',
  PRIMARY KEY (`nextid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `griefprevention_playerdata` (
  `name` varchar(50) NOT NULL DEFAULT '',
  `lastlogin` datetime DEFAULT NULL,
  `accruedblocks` int(15) DEFAULT NULL,
  `bonusblocks` int(15) DEFAULT NULL,
  `clearonjoin` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `griefprevention_playerdata_whitelisted` (
  `name` varchar(50) NOT NULL DEFAULT '',
  `lastlogin` datetime DEFAULT NULL,
  `accruedblocks` int(15) DEFAULT NULL,
  `bonusblocks` int(15) DEFAULT NULL,
  `clearonjoin` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

CREATE TABLE `griefprevention_schemaversion` (
  `version` int(15) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

```

**Comment by RoboMWM** [comment]
@FrozenBeard Jikoo linked to jitpack's maven repo as per https://github.com/TechFortress/GriefPrevention/pull/203#issuecomment-326749610 and I was wondering if you were using this non-released build (or compiled yourself, either way, was wondering if you're using a build other than what is tagged in releases). Two PR's have been merged that change the data structure a bit as I mentioned https://github.com/TechFortress/GriefPrevention/issues/207#issuecomment-327569461 and could be a probable cause for your issues, but I don't know if you are using a non-release build or not.

**Comment by TomLewis** [comment]
@RoboMWM No I am using  GriefPrevention version 16.7.1 , from the release page.

**Comment by TomLewis** [comment]
As an update to this, I have had a few super long term players also loose claims. Were talking claims that are 3+ years old here, from the ones that have been reported all claims that are disappearing are very old.

**Comment by bigpresh** [comment]
Apologies, I somehow missed replying to your previous question:

> My griefprevention_nextclaimid is 3517 This is unexpectedly low! I ordered my griefprevention_claimdata by ID and the highest ID of a claim is 72287! This is very odd behaviour, should I set my nextid in nextclaimid to more than 72287?

YES - very much so - otherwise, each time a new claim is created, it will get the ID of nextid + 1, and any existing claim with that ID will be deleted.

I'd love to see the "next ID" stuff auto-calculated rather than just stored, or at least sanity-checked on load (i.e. if the number is lower than the highest claim ID we've loaded, or just if there is a claim with that ID, then bail).

The puzzle is of course how your next claim ID got reset.  Given that the DB column it goes in is a int(15), it didn't overflow :)   I'll look at the code involved again, maybe it deletes first then inserts the new value, and if it lost DB connection or otherwise failed in between the two it'd leave no record, and then the next time it tries, it'll zero?

**Comment by TomLewis** [comment]
Jesus! I just checked since this post and my Next claim was ID 4266 so since this post 749 claims have been changed, which means most likely 749 claims have been overwritten. Its got to be that, as I checked my claims list and ordered by ID, the latest claim was still 72287! So you must be right! I have updated my Next claim to 72288.
There is no way I can fix this either.... This is a massive screw up!

Why the hell isn't it just an auto increment? 

For some reason my swap memory keeps filling up, no idea why I have plenty of spare RAM on my server, 16GB and only 8 is given to the MC server, and 512mb to the bungee, the OS, A Nginx web server and TS are running, not much else. atm its on 10.5gb/15.6gb. I wonder if that could cause it?

**Comment by TomLewis** [comment]
Server is running, maybe that's why, but I updated the MySQL nextid, added a new claim and it went down to 4267!! What the hell!
Edit. you have to shut the server down to change it. After changing it when the server was shutdown, it incremented properly when a new claim was created.

**Comment by RoboMWM** [comment]
>  or at least sanity-checked on load (i.e. if the number is lower than the highest claim ID we've loaded, or just if there is a claim with that ID, then bail).

This would work. We can't just auto-calculate, or addons that rely on unique ids for each claim will be confused if we re-use ids.

**Comment by bigpresh** [comment]
> Edit. you have to shut the server down to change it. After changing it when the server was shutdown, it incremented properly when a new claim was created.

Yeah, it keeps the current value in memory, and just writes it to the DB / file again each time it's incremented, as you found out.

What I did when I had this problem after running out of disk space:

* worked out the highest claim number which was affected, and the previous highest claim number
* `for 1..$highest_claim_trashed`, renamed it to `$num + $previous_highest`
* set next claim ID to the new highest number
* restored the old claims (`1..$highest_claim_trashed`) from my backups and dropped them in.

Of course, that's rather easier for flatfiles; for a database, if you don't have snapshot backups of SQL dumps or something,  that data may be gone :|

We definitely do need to fix this so it can't bite anybody else!

**Comment by TomLewis** [comment]
@bigpresh Even though I have over 752 claims overwritten just since I crated this ticket, and I have no idea when this started, Ive only had 5 players report claims disappearing. I do keep daily backups of my MySQL for the last 4 years, but Its going to be difficult to find out when this started to see when the data first started getting destroyed by GriefPreventioin. 
Database sizes are 2gb a pop, so im not too keen to start importing them with such little fallout.
Going to treat it as a "cleanup" exercise, since it started from the earliest of claims only players claims from 3-4 years ago would be affected.

**Comment by bigpresh** [comment]
@FrozenBeard Yeah, that's fair enough - would be a lot of work for probably very little benefit - the majority of claims lost are probably players who no longer play, indeed.

When I get a moment I'll look at the claim-loading code and see if I can add a sanity-check of the ID, unless someone else gets there first.

**Comment by TomLewis** [comment]
Thanks man, you saved my skin with that tip.

I think we need a simple ID displayed when people do their claimslist, so we know what claim is what. and having an option for admins to click the claimslist to teleport to the claims. Could be as simple as running /tppos and putting the left corner coordinates in, would be better if its possible to figure out its centre though!

I Have requested a few times that we have a proper full blown debug log for everything that happens, Claim resize, claim delete, claim create, claim expand, every event so we have a proper history log we can look back on, even better if its MySQL so then I can build a nice searchable GUI.

**Comment by RoboMWM** [comment]
Yea, all things planned for version 20. PRs will still be considered for the current/legacy version as well, it's just I don't want to waste my time and accidentally break stuff (as I already have in implementing/fixing/optimizing other things). Of course, I'm still maintaining 16.x until v20 arrives, it's just I've been incredibly busy for the past couple months (yea not a big surprise for most I know, but it was for me in this case - i.e. I've been far more busy than I expected to be, also evidenced in my profile :/ ), hopefully I'll have more time after a couple months.

**Comment by RoboMWM** [comment]
Not sure if I can get this in the legacy code, since it seems to rely on the existing ID being present when loading claims, in case it needs to "convert" any of them from some earlier format. I probably can do a check afterwards though. Not sure if the story is similar for MySQL...

**Comment by TomLewis** [comment]
I always shudder when I hear the word "Convert" in relation to a database and a minecraft plugin, I've not once had a fluid database convert in the history of running a minecraft server.
I have faith though @RoboMWM, if you need a test database to mess with mines probably the most "worn" of all, I've been through every single iteration of the plugin and all "upgrades" over the years, There's bound to be inconsistencies you couldn't emulate haha you can always have a copy to help trial testing :)

**Comment by RoboMWM** [comment]
The conversion I was mentioning was for some old flatfile format (apparently when claims were identified by something other than the id). I haven't yet poked in the MySQL class. Either way, unless we have the oddball user upgrading from some ancient version, this conversion isn't necessary anymore.

**Comment by TomLewis** [comment]
Thanks for the fix, could you also add the claim ID to be shown when you inspect a claim?
