### ISSUE TITLE
spam chat ban command

### ISSUE THREAD

**Issue by piroplayer55** [GriefPrevention/GriefPrevention#2073]
### Observed Behavior

i got ban in my server of spamming msg

### Expected Behavior

there should be some command for modifying spam chat ban 
for owner by doing this 
we can customize chat spam ban as he want .

### Reproduction steps

/spamchatban or 
/chatspamban

### Server version

```shell
1.20.1
```

### GriefPrevention version

```shell
all version
```

### Configuration

```yaml
.
```

### Plugin list

```shell
GriefPrevention
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by RoboMWM** [comment]
there is, look at the config.
