### ISSUE TITLE
Sign Notifications dont work with new 1.20 right click to edit signs function

### ISSUE THREAD

**Issue by TZ122** [GriefPrevention/GriefPrevention#2077]
### Observed Behavior

With the new 1.20 feature of right clicking and editing signs it does not trigger sign notifications for administrators with config option enabled.

### Expected Behavior

Editing a sign should trigger admin sign notifications

### Reproduction steps

Have two players online, one that has sign notifications on and one that does not
Place a sign
Right click the sign with the new 1.20 mechanic to edit it
Does not show up as a sign notification

### Stack trace or error log

```shell
N/A no error
```

### Server version

```shell
1.20.1
```

### GriefPrevention version

```shell
16.18.1
```

### Configuration

```yaml
N/A (Can attach if needed)
```

### Plugin list

```shell
Griefprevention
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
This and #2078 are likely Spigot not firing the SignChangeEvent. If you could, please use [EventDebug](https://www.spigotmc.org/resources/eventdebug.5940/) or [EventDebugger](https://www.spigotmc.org/resources/eventdebugger.82055/) to verify that the event is not being fired. If it is not, report to Spigot. The fully-qualified name of the event is `org.bukkit.event.block.SignChangeEvent`.
