### ISSUE TITLE
Sign Notifications dont work with new 1.20 Hanging Signs

### ISSUE THREAD

**Issue by TZ122** [GriefPrevention/GriefPrevention#2078]
### Observed Behavior

When players place a 1.20 hanging sign admins do not recieve sign notifications

### Expected Behavior

Admins should receive sign notifications when a player writes on a hanging sign

### Reproduction steps

Have two players online, one that has sign notifications on and one that does not
Place and write on a hanging sign
Does not show up as a sign notification

### Stack trace or error log

```shell
N/A no errors
```

### Server version

```shell
1.20.1
```

### GriefPrevention version

```shell
16.18.1
```

### Configuration

```yaml
N/A (Can attach if needed) Admin sign notifications are enabled.
```

### Plugin list

```shell
GriefPrevention
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
https://github.com/TechFortress/GriefPrevention/issues/2077#issuecomment-1604440785

**Comment by TZ122** [comment]
Seems this was unrelated to GP. Sorry about that!
