### ISSUE TITLE
Claim List Other Bug?

### ISSUE THREAD

**Issue by Buckmanfu** [GriefPrevention/GriefPrevention#208]
### What behaviour is expected:
add griefprevention.claimlistother to permissions file

moderator able to use /claimslist [player] or /claimlist [player]

### What behavior is observed:
In order for a non-op to use either command, I had to explicitly add both griefprevention.claimslistother AND griefprevention.claimlistother 

### Spigot/Craftbukkit/Paper and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
GriefPrevention-16.7.1
CraftBukkit version git-Spigot-65e8124-8bf06d6 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by RoboMWM** [comment]
`/claimlist` is an alias of `/claimslist`. Only one of those permissions actually applies (the other does nothing). See the [documentation](https://github.com/TechFortress/GriefPrevention/wiki/Permissions) for the list of permissions.

Update: just noticed that the permission is incorrectly listed on the commands page (it's correct on the permissions page). Thanks for prompting me to check it though.

**Comment by Buckmanfu** [comment]
I tried both individually, figuring one was a typo, but it only worked when I explicitly defined both in the permissions file. 

disregard... tried it on another perms group just now... and it's working... I must have fat fingered something earlier.
