### ISSUE TITLE
Auto-chest private does not privates nearby blocks

### ISSUE THREAD

**Issue by Vynderman** [GriefPrevention/GriefPrevention#21]
Version 14.7, Spigot 1.9.4 I set:
- InitialBlocks: 1369 (If it is zero auto private is not created, 1369 = 37x37 (18+18+1=37))
- AutomaticNewPlayerClaimsRadius: 18

But when someone places chest he gets private with only chest and all blocks above (Blocks under the chest are not privated and nearby blocks are not privated too). /Claim still works good.
What I should to do to get what I want?

**Comment by RoboMWM** [comment]
Have you tested other values? Anything in the server log? How about if you gave them more initialBlocks? Also, is the claim made near another claim?

Also, `/version` and `/version GriefPrevention` would be handy.

**Comment by Vynderman** [comment]
Yes I tested. Logs says nothing. In all world I have only one private (/claim in same point will make "normal" private). And I gave different initialBlocks like 9999999 or 0 or 1369 (what I need).

This server is running CraftBukkit version git-Spigot-798f32d-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT). GriefPrevention version 14.7.

**Comment by RoboMWM** [comment]
Have you tried different radii? Does this happen with the latest version?

**Comment by Vynderman** [comment]
I updated plugin to latest version and it ran on 1.9.4 (i was surprised), then I tried to place chest and private was made normally (I used default config) and THEN I changed this options:
- ExtendIntoGroundDistance: 0 (Was 5)
- InitialBlocks: 1369 (Was 100)
- AutomaticNewPlayerClaimsRadius: 18 (Was 4)
- MinimumWidth: 0 (Was 5)

After this I restarted server and got same problem - chest does not privates nearby blocks.

**Comment by RoboMWM** [comment]
>  updated plugin to latest version and it ran on 1.9.4 (i was surprised), 

Yes it will run, until it attempts to handle polar bears, and will spit out an error related to setPortalCooldown each time anyone joins

I tested with your settings - and I'm getting a 37x37 claim with the latest version on 1.10.2. Could you try testing with _one_ config change at a time? That way we can figure out which config option is doing it.

**Comment by RoboMWM** [comment]
> Blocks under the chest are not privated 

If you set

> ExtendIntoGroundDistance: 0

Then of course no blocks will be protected under the chest, until the player starts digging/placing below it.

**Comment by Vynderman** [comment]
Im not sure about how to works this system, but I changed _only_ one line:
- ExtendIntoGroundDistance: 0

to
- ExtendIntoGroundDistance: 256

And got normal private. Im not sure about that it is a solution, maybe bug happens time by  time?

**Comment by RoboMWM** [comment]
Um, your prior comment stated that you changed four options. Anyways, as per documentation (which will eventually be migrated to the repo wiki):

> Claims.ExtendIntoGroundDistance: 5  
> 
> How far into the ground a new claim should extend from the golden shovel location. If the golden shovel is used at two different heights, the lower value will be used in conjunction with this variable. To guarantee all claims run all the way to bedrock, use a very large number. The default doesn't sink to bedrock because that would effectively claim valuable ore that the player placing them claim hasn't discovered yet. Please note! As a player digs or builds underneath his claim, his claim automatically sinks lower with him. Thus, mine shafts and basements are safe from grief even if you set this variable at a small value.

https://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/#w-claim-limits
