### ISSUE TITLE
Major Siege Bug

### ISSUE THREAD

**Issue by whoshenry** [GriefPrevention/GriefPrevention#210]
### What behaviour is expected:
Cannot open wooden doors or fence gates whilst challenging someone to a siege.
### What behaviour is observed:
When attacker challenges someone to a siege, the attacker can right click wooden doors, trapdoors and fence gates and walk straight through whilst holding down 'W'. In chat is says "you do not have permission to interact" along with the message "you cannot teleport out of a besieged area". It is when the teleport messages appears that the player can just walk straight through.
### Steps/models to reproduce:
Steps above ^^^

### Spigot/Craftbukkit/Paper and GriefPrevention version:
CraftBukkit version git-Spigot-65e8124-79e55b6 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
16.7.1

### Stack trace/error (if applicable)

```
Paste entire stack trace inside here

<bigpresh removed contents of messages.yml as not relevant>
```

```yml
Paste config inside here
```

**Comment by bigpresh** [comment]
Curious.  Do you have problems with wooden doors/trapdoors being openable outside siege conditions?

Do you have similar problems with buttons/levers/chests not being protected?

What other plugins do you have active?

I find it odd that you're getting a message about teleporting at the same time.

**Comment by whoshenry** [comment]
I don't have the problem outside of siege conditions, it works fine there.

Buttons, Levers and Chests are protected. It's just doors and fence gates, something people can walk through to gain access.

Plugin list (nothing immediately stands out as a problem):
```
PandorraBounty, WhosFaking, FurnaceNotify, MobEggSpawnerBlocker, EnchantsPlus, PlugMan, FarmLimiter, AutomaticInventory, ThisLogMustDie, ChangeBackItem, CheckNameHistory, FunPerks, Top, CommandSync, AsyncWorldEditInjector, Skript, CommandSyncDataDeleter, ChatControl, RandMan, ProtocolLib, Multiverse-Core, mcMMO, Lores, MoneyMobs, GroupManager, PlaceholderAPI, ParticleTrails, SignMagic, ScheduledCommands, EpicWorldGenerator, CoreProtect, dynmap, WorldEdit, AdminFun, CreativeControl, Trash, CrackShot, WorldBorder, SkQuery, AnvilPatch, BuycraftX, Votifier, AutoSaveWorld, LibsDisguises, AsyncWorldEdit, EffectLib, NoFlyPvp, CS-CoreLib, HoloDrops, Vault, AutoAnnouncer, HolographicDisplays, VoteParty, ChestCommands, Multiverse-NetherPortals, MyCommand, ShopGUIPlus, mcMMOAction, CommandSigns, PowerlessLamps, Citizens, ColoredTablist, CrazyCrates, Trading, Sentry, DailyBonus, WorldGuard, BungeePortals, skRayFall, Slimefun, BossShop, Essentials, ExtraGear, HeadDatabase, Dynmap-WorldGuard, Skellett, CrackShotPlus, ColoredTags, DiscordSRV, XPboost, ExoticGarden, Backpack, GriefPrevention, SavageDeathChest, CMI, MythicMobs, EssentialsKitChest, EssentialsGeoIP, CommandNPC, LimitedCreative, TitleManager, Jobs, DeluxeChat, EssentialsChat, GAListener, PlayerShopGUIPlus, ArmorStandTools, ProRecipes, EssentialsProtect, LeaderHeads, Dynmap-GriefPrevention, EssentialsAntiBuild, EssentialsSpawn, WorldGuardExtraFlags, LiquidTanks, SharpSK, Quests, SelectionVisualizer
```
It only occurs when the teleport message appears, also another interesting thing to note, I tried to 
 pass through someone's claim as an Op and I couldn't (which is normal) but I didn't get the teleport message and it worked perfectly, I was unable to walk through the doors. It seems players who don't bypass the teleport out of a besieged area can glitch through doors.

**Comment by bigpresh** [comment]
Wow, that's a lot of plugins :)

I'd be inclined to test it with all other plugins disabled, briefly, to determine whether it's an interaction with some other plugin (although none of them stand out to me as a "ah, that's quite possibly the culprit"...

I'll see if I can reproduce this on my test server as soon as I get a moment and can borrow an assistant to be sieged.

**Comment by whoshenry** [comment]
Ok thanks, I can help if you'd like to try and get this fixed asap.

**Comment by whoshenry** [comment]
I just tested this with just Grief Pevention and a permissions manager and it still happened :(

**Comment by bigpresh** [comment]
Right, that's very strange indeed.

That message, `Messages.SiegeNoTeleport`, is only fired in response  to a `PlayerTeleportEvent` event caught by `onPlayerTeleport` in `PlayerEventHandler.java` - I see nowhere else it can be triggered from.  So, *something* is attempting to initiate a teleport.

From a quick look, the only cases where GP will attempt to teleport a player are:

* If they were stuck in a nether portal - there'll be a log message about them being rescued from it
* in response to the `/trapped` command, by PlayerRescueTask - that logs too

So, I'm curious why a `PlayerTeleportEvent` event is triggering.

**Comment by whoshenry** [comment]
Not sure. Is this something you can look at and fix? Sieges are a vital part of the server I have and with this pretty major bug it's not good for the players.

**Comment by bigpresh** [comment]
Yeah, I'll have a further dig and see what I can work out.  Hopefully I can reproduce it on my test server, then I can at least try out fixes against it :)

Had it been working alright for you for a while, then suddenly started doing this? Anything installed or upgraded etc just before it started happening?

**Comment by whoshenry** [comment]
No, it's always been happening. I don't think it was ever working correctly.

The interesting thing though is that players who are OP, it doesn't happen to them. Like I said in the original comment, maybe because they have something that bypasses them teleporting into and out of a besieged area?

**Comment by whoshenry** [comment]
I just tried to find a permission node to allow a player to bypass the teleporting into and out of a besieged area to test it but I can't find one, is there one?

**Comment by bigpresh** [comment]
> I just tried to find a permission node to allow a player to bypass the teleporting into and out of a besieged area to test it but I can't find one, is there one?

Indeed there is - 
```
369:    griefprevention.siegeteleport:
370:        description: Players with this permission can teleport into and out of besieged areas.
```

**Comment by whoshenry** [comment]
Yes that is the issue, when the player doesn't have the bypass permission, they can pass through wooden doors if they spam right click and keep walking through.

When they do have the permission bypass, they can't get through.

**Comment by whoshenry** [comment]
Would you like to have some help in testing this?

**Comment by bigpresh** [comment]
When I've had a bit of time to spare so I can configure siege mode on my test server and give it a try, I'll give you a shout if you're around, as I think it'll require two online players to test it, and I only have one MC account; not sure how it'd behave if I put the server in offline mode, as a lot of stuff works off the UUID as far as I recall.

**Comment by whoshenry** [comment]
Ok great thanks.

Leave a comment on here so I can see on my email when you're testing and if you need me.

**Comment by bigpresh** [comment]
Not going to get a chance to test this tonight, sorry.  Spun up a separate empty test server with GP on, but have problems at work to firefight, so won't be able to do it tonight.

**Comment by whoshenry** [comment]
No problem. Just let me know. I'm in Greece FYI for timings.

**Comment by whoshenry** [comment]
Have you had a chance to look into this at all?

**Comment by whoshenry** [comment]
Sorry to bother @bigpresh but I'm eager to get this fixed for my server, can we test this sometime soon?

**Comment by RoboMWM** [comment]
Ok, just took a look at the code, seems the issue is that a teleportation is called when these issues occur. Not by GP, but GP cancels it. 

As to what is calling this teleport... not sure. I'll probably create a debug build, since my assumption is that vanilla would just cancel the movement and tell the client this... 

If it's an anticheat setting back, I guess CB could be internally firing a teleport? Not really sure... I also do not know the internals of AAC (nor are they all that [friendly towards developer requests...](https://github.com/konsolas/AAC-Issues/issues/948#issuecomment-336323331))

I'll release a debug build here in the comments shortly. Rename the `zip` to a `jar` after downloading.

**Comment by RoboMWM** [comment]
The following debug build will use GP's debug messages to print the teleport's cause as well as the distance (squared) when GP cancels a teleport due to a claim being in siege. Let me know your test cases and results.
[GriefPrevention.zip](https://github.com/TechFortress/GriefPrevention/files/1384898/GriefPrevention.zip)

**Comment by RoboMWM** [comment]
The following debug build will use GP's Admin logging messages (which should print to console, and to GP's log, if you have it configured to do so) to print the teleport's cause as well as the distance (squared) when GP cancels a teleport due to a claim being in siege. Let me know your test cases and results. I would also include tests cases with and without anticheat plugins.
[GriefPrevention.zip](https://github.com/TechFortress/GriefPrevention/files/1384900/GriefPrevention.zip)

**Comment by whoshenry** [comment]
Thanks so much for helping fix this @RoboMWM - I have put this on my test server now and I will run some tests and report back.

I will run tests on spamming right click to a wooden door and going through as well as breaking the bottom of a door and being able to go into the claim.

**Comment by whoshenry** [comment]
Is there something I'm meant to change in the config regarding the logging to get a console error?

I am doing the bug but nothing is being printed in the console.

**Comment by whoshenry** [comment]
Ok I have enabled Debug in the config but nothing is being printed whatsoever when I glitch through a door.

**Comment by RoboMWM** [comment]
It logs to admin activity (since I don't recall if debug logging goes to console, but I know admin activity always does).

If you're testing, you need to deop yourself/remove the respective gp siege permissions. It should print a log message if you're getting a "permission denied" message for teleporting in siege'd areas. Also confirm you're using the debug version with `/version GriefPrevention`

**Comment by whoshenry** [comment]
Am I being stupid here? Where is Admin Activity? I can't find it in any of the Grief Prevention folders?

I got an ingame "You cannot teleport out os besieged areas" message when I glitch through the doors, no console logging at all.

GriefPrevention version 16.7.1-debug

**Comment by whoshenry** [comment]
Ok I have enabled the Admin Activity in the config and I still get no log anywhere.

**Comment by whoshenry** [comment]
Ok this is all I got:
19:39 UNKNOWN
19:39 Distance squared: 0.03261748096099452

**Comment by RoboMWM** [comment]
And you tested both with and without anitcheat plugins installed? (Or better yet, with just GP installed)? If so, then I'm suspecting vanilla's responsible for and will add a check to ignore the `unknown` teleportation cause.

**Comment by whoshenry** [comment]
Yes I tested with what you said, no anticheat and just GP.

**Comment by whoshenry** [comment]
Any update on this @RoboMWM what more testing needs to be done?

**Comment by RoboMWM** [comment]
Oof, I got super busy - I hope you noticed that I marked this for 16.8. I think from the info you provided I had a fix in mind.

**Comment by whoshenry** [comment]
Ok thanks.

**Comment by RoboMWM** [comment]
Let me know if it's resolved; here's a copy of the plugin with the fix (change the `.zip` to `.jar`):
[GriefPrevention.zip](https://github.com/TechFortress/GriefPrevention/files/1576529/GriefPrevention.zip)
