### ISSUE TITLE
PlayerQuitEvent with PlayerProfile

### ISSUE THREAD

**Issue by SrMonsterYT** [GriefPrevention/GriefPrevention#2100]
### Observed Behavior

error: https://mclo.gs/ik5zly5

### Expected Behavior

no error

### Reproduction steps

I don't know

### Server version

```shell
This server is running Paper version git-Paper-64 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 12c9700)
You are running the latest version
Previous version: git-Paper-60 (MC: 1.20.1)
```

### GriefPrevention version

```shell
GriefPrevention ve500f5f
```

### Configuration

```yaml
https://mclo.gs/fTz6VRy
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by RoboMWM** [comment]
where'd you download version `ve500f5f`?

**Comment by Jikoo** [comment]
I assume they meant e500f5f, which is the most recent PR because Appveyor built it last. Really wish Appveyor had a master branch only view to link people.

Looks like a Paper bug due to the recent banlist changes. https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/648196070e5a1f035c3691870c691c20e44b3439

**Comment by RoboMWM** [comment]
Imma guess you downloaded from appveyor. 

~~Seems like, in addition to the testing you put in, that this issue occurs due to some plugin improperly creating the player object or something, prolly due to a protocol plugin.~~ Jikoo sniped me lol

**Comment by SrMonsterYT** [comment]
yes I download recent versions from this site, isn't it yours?

https://ci.appveyor.com/project/RoboMWM39862/griefprevention

**Comment by Jikoo** [comment]
This is a Paper issue, please subscribe to notifications for PaperMC/Paper#9455 for updates.

> yes I download recent versions from this site, isn't it yours?
> 
> https://ci.appveyor.com/project/RoboMWM39862/griefprevention

Appveyor also is used to verify that PRs build. You downloaded a build of a PR that has not been approved, so no, that is not an official build.

**Comment by wpmidia** [comment]
The same problem here!

**Comment by RoboMWM** [comment]
This is a paper bug that has been fixed, if you are having this issue, please update Paper or Purpur
