### ISSUE TITLE
Cacti damage Protected Pets outside land claims

### ISSUE THREAD

**Issue by iNko97** [GriefPrevention/GriefPrevention#213]
### What behaviour is expected:
Consistently with suffucation being disabled for Protected Pets, a player should not be able to damage protected pets placing a cactus and pushing it into it.

### Steps/models to reproduce:
Spawn a wolf, tame wolf, get other player to place and push wolf into cactus, kill wolf.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
GriefPrevention version 16.7.1
This server is running CraftBukkit version git-Spigot-d5dfb24-ed8c725 (MC: 1.12) (Implementing API version 1.12-R0.1-S...

**Comment by RoboMWM** [comment]
Need config and world this occurs in - as wolves are not protected in worlds with PvP enabled (since players would be otherwise defenseless against wolves.)

Btw, I think I recall the reason for wolves being protected against environmental hazards is because Big_Scary observed that they had horrendous pathing/teleporting - so this was to protect against vanilla game mechanics causing death to pets, not to protect against the intentions of other players.

**Comment by iNko97** [comment]
All forms of pvp are disabled on my server, I just noticed that all tameable pets with owner were only killable by untrusted players with cactus, (Dropping gravel onto them does nothing, placing lava or fire near them does not damage them, potions don't harm them; I have yet to test intentional drowning) which seemed inconsistent. Will send the config of the server if it's needed.

(Doing further testing, will update)
Tested all animals belonging to Spigot class Tameable, they don't suffer any environmental damage (Fire, Lava, Suffucation from material) except drowning and cactus.


 PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: false
    AllowFlintAndSteelNearOtherPlayers: false
    ProtectPetsOutsideLandClaims: true
