### ISSUE TITLE
Do not destroy blocks

### ISSUE THREAD

**Issue by Bear228** [GriefPrevention/GriefPrevention#2133]
### Observed Behavior

Creepers and tnt do not blow up blocks both on the territory and behind it

### Expected Behavior

That creepers and tnt will destroy blocks outside of private

### Reproduction steps

-

### Stack trace or error log

```shell
-
```

### Server version

```shell
Welcome to Mohist ! - Mohist Developement Group - 1.20.1-294, Java 61.0
```

### GriefPrevention version

```shell
Последняя 1.20.1
```

### Configuration

```yaml
Только ваш плагин
```

### Plugin list

```shell
GriefPrevention
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by bigpresh** [comment]
Have you tried disabling the `BlockSurfaceExplosions` config setting?

**Comment by RoboMWM** [comment]
Please provide your config.yml as the template has asked for.

**Comment by Jikoo** [comment]
Closing due to lack of response - OP is a new account, don't think we're getting one.
