### ISSUE TITLE
Protected pets griefing

### ISSUE THREAD

**Issue by iNko97** [GriefPrevention/GriefPrevention#214]
### What behaviour is observed:
Players are able to "grief" by making horse farms (or any tameable pet farm) and running them in other player's claimed areas, leaving them. Removing such pets is always a struggle, because they cannot be ridden away since they are protected, and often the only solution is to build a water stream that leads outside the claim (or kill them with cactus). The first is very painful since the player is forced to remove huge parts of his builds just to move that pet out.

### Suggestion:
Add some command to safely and easily remove other player's protected pets from our own claimed land.

**Comment by RoboMWM** [comment]
If there isn't already an option (I think there is?) then one should be made. Otherwise, setting the world as a PvP world in GriefPrevention's config should automatically make all pets and animals outside of the owner's claim unprotected.

**Comment by iNko97** [comment]
I did a quick search trough all the settings and could not find such command...

**Comment by RoboMWM** [comment]
If the world is a PvP world, then pets outside of the owner's claim are not protected and should be able to be ridden by other players.
