### ISSUE TITLE
API Afk detection

### ISSUE THREAD

**Issue by MrArcane** [GriefPrevention/GriefPrevention#216]
### What behaviour is expected:
No claim blocks gained per player
### What behaviour is observed:
inconsistent event 
### Steps/models to reproduce:
_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_

### Spigot/Craftbukkit/Paper and GriefPrevention version:
SPIGOT: http://prntscr.com/gms2wk
GP: v16.7.1
## INFO ##
So i'm trying to detect when a player goes afk to stop claim blocks from coming in by using "AccrueClaimBlocksEvent", I have no idea how to use it for just 1 player though. If you could Help/PM me that would be much appreciated, Thank you.

**Comment by RoboMWM** [comment]
GP already has its own AFK detection, albeit it's simplistic. Also can't help if you don't provide code or info/debug info. That being said, this belongs in the spigot discussion since it's a downstream issue (i.e. likely a problem on your end).

**Comment by MrArcane** [comment]
@EventHandler
   private void AccurueClaimBlocks(AccrueClaimBlocksEvent e) {
       Player p = e.getPlayer();
       if (afk.get(p) >= time) {
           sendChat(p, "No claim blocks for you.");
           System.out.println(p.getDisplayName() + "'s  afk time is: " + afk.get(p) + "and is now not gaining CB!");
       }
   }

Debug message: [14:04:45 INFO]: MrArcane's  afk time is: 11 and is now not gaining CB!
I'm not using a compatible plugin, i'm using my own.

"time" is just a int in my config file and it's set to 5, sometimes the event would fire other times it would not. I just need general help about doing this. Thank you.

**Comment by RoboMWM** [comment]
Yikes, sysout.

Anyways, the event is fired every 10 minutes. I'm not sure if it fires if GP detects the player is AFK.

Either way I don't think this is your issue. You aren't using the event as a timer (which you shouldn't) so not sure why you need it to be "consistent" anyways.
