### ISSUE TITLE
Add permission to staff use command: /trustlist

### ISSUE THREAD

**Issue by comonier** [GriefPrevention/GriefPrevention#218]
i need just to help my staffs to help newbie players....
just a permissions to staff group
to use command /trustlist
on players claims... (without have any trust on claim)

my staffs are players too.... so they cant have any other permission...

**Comment by comonier** [comment]
ty for replay, there is any change to add that permission on next update? xD

**Comment by RoboMWM** [comment]
do you not want this feature anymore?

**Comment by TomLewis** [comment]
At present the staff has to have /IgnoreClaims to do change a claims trust, Which is technically the best solution, as you should not be giving staff access to be able to edit whos on the trustlist, as they could just add themselves or an alt to cause damage, which is just /IgnoreClaims.

The key here is staff management not permissions. In this case, only high level admins should have IgnoreClaims.
