### ISSUE TITLE
[bug] Siege Triggers speed detection in AAC

### ISSUE THREAD

**Issue by TomLewis** [GriefPrevention/GriefPrevention#219]
This is a really odd one, but its constant, The anti Cheat plugin AAC tracks hacked clients, so strange things like super fast players will get kicked etc.
Now there is a bug with Siege that triggers and kicks players via AAC for "speed". I have no idea why Siege would cause a player to trigger speed, but it does.

**Comment by TomLewis** [comment]
This needs to be fixed as a priority.
Velocity is also being triggered, whatever siege is doing at some point that teleports players or whatever is causing AAC to trigger.

**Comment by RoboMWM** [comment]
Unless this proves to be a separate issue, I'm assuming it's related to it trying to teleport the player. #210

**Comment by CeIebrimbor** [comment]
Sounds like he is looking for a `no-punish-on-kick` option.

**Comment by RoboMWM** [comment]
No it doesn't, nowhere does he complain about the sieger losing because he was kicked by AAC, he just didn't want AAC to trigger. As per 210, the bug was caused because GP was blocking corrective vanilla teleports.
