### ISSUE TITLE
Player last seen date not used for claim expiration

### ISSUE THREAD

**Issue by Jikoo** [GriefPrevention/GriefPrevention#22]
### What behaviour is expected:

GP will use data from Bukkit to ascertain whether or not a player has been on within claim expiration limit. I propose the elimination of `PlayerData#getLastPlayed()` entirely - it shouldn't be used, as it isn't reliably updated. This [isn't a new issue](https://dev.bukkit.org/bukkit-plugins/grief-prevention/?comment=9186) and was supposed to be fixed in f935806b45. 
### What behaviour is observed:

f935806b45 addressed only new player expiration, not expiration via configured time limit ([CleanupUnusedClaimTask.java#L64](https://github.com/TechFortress/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/CleanupUnusedClaimTask.java#L64)). In the event of an error ([several consecutive errors, actually](https://github.com/TechFortress/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/FlatFileDataStore.java#L604)), an empty new PlayerData is returned. The blank file counts as never having logged in, and all claims are deleted.
### Steps/models to reproduce:

Configure GP run claim cleanup task and cause an exception reading the data file. To easily replicate, set file permissions so the user running the server cannot read the file.
### Spigot/Craftbukkit/Paper and GriefPrevention version:

Spigot git-Spigot-047f737-9558f31
GriefPrevention version 15.3
### Stack trace/error (if applicable)

Only vaguely relevant, my problem is not really with GP's handling of IO issues.

```
java.io.FileNotFoundException: plugins/GriefPreventionData/PlayerData/11a99891-8e4f-4711-a534-ab6499898ab1 (Too many open files)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at com.google.common.io.Files$FileByteSource.openStream(Files.java:126)
    at com.google.common.io.Files$FileByteSource.openStream(Files.java:116)
    at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:435)
    at com.google.common.io.CharSource.getInput(CharSource.java:94)
    at com.google.common.io.CharSource.getInput(CharSource.java:65)
    at com.google.common.io.CharStreams.readLines(CharStreams.java:344)
    at com.google.common.io.Files.readLines(Files.java:741)
    at com.google.common.io.Files.readLines(Files.java:712)
    at me.ryanhamshire.GriefPrevention.FlatFileDataStore.getPlayerDataFromStorage(FlatFileDataStore.java:613)
    at me.ryanhamshire.GriefPrevention.CleanupUnusedClaimPreTask.run(CleanupUnusedClaimPreTask.java:40)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
### GriefPrevention config.yml (if applicable)

Mostly default, relevant section included:

```
GriefPrevention:
  Claims:
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 28
      AllClaims:
        DaysInactive: 150
```
### Plugin list (if applicable):

I have a very good idea which plugin caused too many files to be open, I don't believe GP to be at fault.

**Comment by RoboMWM** [comment]
> f935806 addressed only new player expiration, not expiration via configured time limit (CleanupUnusedClaimTask.java#L64). 

Ummmmm....

`ownerInfo` is an OfflinePlayer... unless you meant to link to another line?

**Comment by RoboMWM** [comment]
> I propose the elimination of `PlayerData#getLastPlayed()` entirely 

Seems like it's already gone.

Perhaps you mean `PlayerData#getLastLogin()` ?

**Comment by RoboMWM** [comment]
Hmm, would like to see the rest of that error, since if it can't load up the playerdata for the claim owner, wouldn't it be passing a null UUID when attempting to use `Bukkit#getOfflinePlayer()` in the next line?

**Comment by Jikoo** [comment]
> ownerInfo is an OfflinePlayer... unless you meant to link to another line?

Argh, right you are.

> would like to see the rest of that error

That's it, I'm afraid.

> if it can't load up the playerdata for the claim owner, wouldn't it be passing a null UUID when attempting to use Bukkit#getOfflinePlayer() in the next line?

In this case, being flatfile, I believe all claims are loaded when the plugin loads. The UUID being used is fetched from a claim being checked. That seems inefficient, when you thing about it - wouldn't it be better to check all players for whom there are data files rather than check each claim's owner, as each player might have several dozen claims?

At any rate, sorry to have wasted your time - the same FileNotFound due to too many open files causes the player's .dat file to be unreadable, and I'm 90% sure without actually checking that Bukkit uses its last modified date or something along those lines for the player's last login. Default last login is 0, so of course it isn't within the correct duration. Doing a little bit of headdesking here for not realizing that sooner.

**Comment by Jikoo** [comment]
Oh double damn it, doesn't 5d4ccdca20 break existing flatfile saves? I'm causing all kinds of grief here.
Specifically, GP's player data file format is rigid, in that the first line is the last login date, the second line is the accrued claim blocks, third is bonus. With the removal of reading the first line, existing files will read 1 line early, resetting accrued blocks and converting all accrued blocks to bonus blocks.

Really sucks that there's no identifier for what line's what. Should just throw an iterator.next() call in there, yeah? [Here](https://github.com/TechFortress/GriefPrevention/commit/5d4ccdca206ccc839346be865aaeabca44795873#diff-d515f6d1575cb9a104befb348637fb9cL617), that is.

**Comment by RoboMWM** [comment]
Yea, I tried to make sure I still kept a blank line to be added and read. Missed that, thanks.

**Comment by RoboMWM** [comment]
> Default last login is 0, so of course it isn't within the correct duration. Doing a little bit of headdesking here for not realizing that sooner.

Ok, so should I do a check to see if `ownerInfo.getLastPlayed() == 0`?

**Comment by RoboMWM** [comment]
> That seems inefficient, when you thing about it - wouldn't it be better to check all players for whom there are data files rather than check each claim's owner, as each player might have several dozen claims?

Yes, that does seem rather inefficient. Not sure why he's checking random claims vs. a random player. However, I think the reasoning behind this is that people can set the expiration date far beyond what GP caches for PlayerData by default (it only caches PlayerData of players that have logged in within the last 90 days) - whereas all claims are cached. However, it is getting the claim owner anyways, cached or not - I guess his method is the more "RAM efficient" method. (This is also probably why he denied checking the last login date of trustees, since he'd have to load an indeterminate amount more PlayerData.)

How would you go about this?

Decided to migrate this topic over to a new issue: #24

**Comment by RoboMWM** [comment]
@Jikoo, in case you missed it:

> Default last login is 0, so of course it isn't within the correct duration. Doing a little bit of headdesking here for not realizing that sooner.

Should I do a check to see if ownerInfo.getLastPlayed() == 0?

**Comment by Jikoo** [comment]
Oops, I did miss that.

> Should I do a check to see if ownerInfo.getLastPlayed() == 0?

That would definitely be useful. If their last played is 0, they're either currently online during their first play session or there's been an issue with loading the player data. Either way, probably best to not delete their claims.

I'd suggest adding that check to [CleanupUnusedClaimPreTask.java#L45](https://github.com/TechFortress/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/CleanupUnusedClaimPreTask.java#L45), seems like the place it belongs.
