### ISSUE TITLE
Claim by Sponge

### ISSUE THREAD

**Issue by DarkDragonkz** [GriefPrevention/GriefPrevention#221]
### What behaviour is expected:
Good morning after the closing of our server we noticed that the claims of most users had changed name instead those of the staffer there are there could tell how to solve and make the claims you have them owners, and tells the users that the claim belongs to sponge even if they have permissions are not recognized the name of the claim
### Spigot/Craftbukkit/Paper and GriefPrevention version:
GirefPrevention 1.10.2-4.0.0.328
Paste config inside here
# 4.0.0
# # If you need help with the configuration or have any questions related to GriefPrevention,
# # join us at the IRC or drop by our forums and leave a post.
# # IRC: #griefprevention @ irc.esper.net ( http://webchat.esper.net/?channel=griefprevention )
# # Forums: https://forums.spongepowered.org/t/griefprevention-official-thread-1-10-1-11-1-12/1123
# 

GriefPrevention {
    bans {
        banReasons {}
    }
    claim {
        # The list of slashcommands requiring access trust when in a claim.
        accesstrust-commands=[]
        # Radius used for auto-created claims. Set to -1 to disable.
        auto-claim-radius=4
        # Whether survival claims will be automatically restored to nature when auto-deleted.
        auto-nature-restore=false
        # Whether to enable the bank/tax system for claims. Set to true to enable.
        bank-tax-system=false
        bank-transaction-log-limit=60
        # Limit on how deep claims can go.
        claim-max-depth=0
        # The mode used when creating claims. (0 = Disabled, 1 = Survival, 2 = Creative)
        claims-mode=1
        # The interval in minutes for restoring blocks in an expired claim. Set to 0 to disable. Note: This only supports vanilla blocks. Use with caution if using custom biomes.
        cleanup-task-interval=5
        # Send players manuals on claim creation.
        deliver-manuals=false
        # How far below the shoveled block a new claim will reach. Set to 255 if you want to always extend to bedrock.
        extend-into-ground-distance=255
        # The item used to investigate claims with a right-click.
        investigation-tool="minecraft:stick"
        # The item used to create/resize claims with a right click.
        modification-tool="minecraft:golden_shovel"
        # The specific hour in day to apply tax to all claims.
        tax-apply-hour=12
    }
    economy {
        # Cost to purchase a claim block. set to zero to disable purchase.
        claim-block-cost=0.0
        # Return on a sold claim block. set to zero to disable sale.
        claim-block-sell=0.0
    }
    flags {
        # The default flag settings used when an admin claim is created.
        default-admin {
            block-break=false
            block-place=false
            collide-block=false
            collide-entity=false
            command-execute=true
            command-execute-pvp=true
            enter-claim=false
            entity-damage=true
            entity-riding=true
            entity-spawn=true
            entity-teleport-from=true
            entity-teleport-to=true
            exit-claim=true
            explosion=false
            explosion-surface=false
            fire-spread=false
            interact-block-primary=false
            interact-block-secondary=false
            interact-entity-primary=false
            interact-entity-secondary=true
            interact-inventory=false
            interact-item-primary=true
            interact-item-secondary=true
            item-drop=true
            item-pickup=true
            item-spawn=false
            item-use=true
            liquid-flow=false
            portal-use=true
            projectile-impact-block=false
            projectile-impact-entity=false
        }
        # The default flag settings used when a basic claim is created.
        default-basic {
            block-break=false
            block-place=false
            collide-block=false
            collide-entity=false
            command-execute=true
            command-execute-pvp=true
            enter-claim=false
            entity-damage=true
            entity-riding=true
            entity-spawn=true
            entity-teleport-from=true
            entity-teleport-to=true
            exit-claim=true
            explosion=false
            explosion-surface=false
            fire-spread=false
            interact-block-primary=false
            interact-block-secondary=false
            interact-entity-primary=false
            interact-entity-secondary=true
            interact-inventory=false
            interact-item-primary=true
            interact-item-secondary=true
            item-drop=true
            item-pickup=true
            item-spawn=false
            item-use=true
            liquid-flow=false
            portal-use=true
            projectile-impact-block=false
            projectile-impact-entity=false
        }
        # The default flag settings used for towns.
        default-town {
            block-break=false
            block-place=false
            collide-block=false
            collide-entity=false
            command-execute=true
            command-execute-pvp=true
            enter-claim=true
            entity-damage=true
            entity-riding=true
            entity-spawn=true
            entity-teleport-from=true
            entity-teleport-to=true
            exit-claim=true
            explosion=false
            explosion-surface=false
            fire-spread=false
            interact-block-primary=false
            interact-block-secondary=false
            interact-entity-primary=false
            interact-entity-secondary=true
            interact-inventory=false
            interact-item-primary=true
            interact-item-secondary=true
            item-drop=true
            item-pickup=true
            item-spawn=false
            item-use=true
            liquid-flow=false
            portal-use=true
            projectile-impact-block=false
            projectile-impact-entity=false
        }
        # The default flag settings used for wilderness.
        default-wilderness {
            block-break=true
            block-place=true
            collide-block=true
            collide-entity=true
            command-execute=true
            command-execute-pvp=true
            enter-claim=true
            entity-damage=true
            entity-riding=true
            entity-spawn=true
            entity-teleport-from=true
            entity-teleport-to=true
            exit-claim=true
            explosion=true
            explosion-surface=true
            fire-spread=false
            interact-block-primary=true
            interact-block-secondary=true
            interact-entity-primary=true
            interact-entity-secondary=true
            interact-inventory=true
            interact-item-primary=true
            interact-item-secondary=true
            item-drop=true
            item-pickup=true
            item-spawn=true
            item-use=true
            liquid-flow=true
            portal-use=true
            projectile-impact-block=true
            projectile-impact-entity=true
        }
        # A list of flags standard users can manage in their claims with the /cf, /cfg, and /cfp commands.
        # Note: All flags in this list will be used to determine which user permission to check such as 'griefprevention.user.flag.block-break'.
        user-claim-flags=[
            block-break,
            block-place,
            collide-block,
            entity-riding,
            explosion,
            explosion-surface,
            fire-spread,
            interact-block-primary,
            interact-block-secondary,
            interact-entity-primary,
            interact-entity-secondary,
            interact-item-primary,
            interact-item-secondary,
            item-drop,
            item-pickup,
            item-use,
            portal-use,
            projectile-impact-block,
            projectile-impact-entity
        ]
    }
    general {
        # Enable sign notifications for admins.
        admin-sign-notifications=false
        # List of whisper commands to eavesdrop on.
        admin-whisper-commands=[]
        # Enable whisper notifications for admins.
        admin-whisper-notifications=false
        # Whether whispered messages will broadcast to administrators in game.
        admin-whispers=false
        # Whether chat should be monitored and filtered by rules.
        chat-rules-enabled=false
        # Whether pistons are limited to only move blocks located within the piston's land claim.
        limit-pistons-to-claims=false
        # Whether players can build trees on platforms in the sky.
        limit-sky-trees=true
        # Whether trees should be prevented from growing into a claim from outside.
        limit-tree-growth=false
        # The max claim inspection block distance. (Default: 100)
        max-claim-inspection-distance=100
        # How many players can share an IP address. (Default: 3)
        max-players-per-ip=5
        # Whether players' dropped on death items are protected in non-pvp worlds.
        protect-item-drops-death-non-pvp=true
        # Whether to ban accounts which very likely owned by a banned player.
        smart-ban=false
    }
    logging {
        # Log admin activity.
        admin-activity=false
        # How many days to keep logs in storage.
        days-stored=7
        # Log social activity.
        social-acitivity=false
        # Log suspicious activity.
        suspicious-activity=true
    }
    # List of migrators that convert other protection data into GP claim data.
    # Note: These migrators will NOT change or delete your data. It simply reads and creates new data for GriefPrevention.
    migrator {
        # Set to true to enable Polis data migrator.
        # Note: All Polis data will be converted into basic claim data. Town balance will transfer to leaders.
        polis=false
        # Set to true to enable RedProtect data migrator.
        # Note: All RedProtect data will be converted into basic claim data.
        red-protect=false
    }
    playerdata {
        # The rate to multiply each accrued claim blocks total by. 
        # Set to a value greater than -1 to enable. (If you use defaults, recommended start value 256)
        # Note: This is only run one time to migrate player claimblock data to new system.
        # Each chunk is worth 65,536 blocks in the new system compared to 256 in old.
        migration-town-block-rate=-1
        # Whether player data should be stored globally. False will store all data per world.
        use-global-storage=true
    }
    pvp {
        # Whether a player can drop items during combat to hide them.
        allow-combat-item-drops=false
        # How long combat is considered to continue after the most recent damage.
        combat-timeout=15
        # Whether to make newly spawned players immune until they pick up an item.
        protect-fresh-spawns=true
        # Whether player's dropped on death items are protected in pvp worlds.
        protect-item-drops-death=false
        # Whether players may fight in admin-owned land claims.
        protect-players-in-adminclaims=false
        # Whether players may fight in player-owned land claims.
        protect-players-in-claims=false
        # Whether players may fight in subdivisions of admin-owned land claims.
        protect-players-in-subdivisions=false
        # Whether players may fight in wilderness.
        protect-players-in-wilderness=false
        # Whether to kill players who log out during PvP combat.
        punish-logout=true
        # Whether or not pvp anti-grief rules apply.
        rules-enabled=true
    }
    spam {
        # IP addresses which will not be censored.
        allowed-ips=[]
        # Whether or not to ban spammers automatically.
        autoban-offenders=false
        # Cooldown period for death messages (per player) in seconds.
        death-message-cooldown=60
        # Whether or not to monitor for spam.
        enable-spam-monitor=true
        # How long players must wait between logins. combats login spam.
        login-cooldown=60
        # the list of slash commands monitored for spam,
        monitor-commands=[]
    }
    thread {
        # The number of threads to use for GP's executor. (Default: 1)
        executor-threads=1
    }
    town {
        # Whether survival towns will be automatically restored to nature when auto-deleted.
        auto-nature-restore=false
        # If true, requires a town to be owned for MCClans.
        clan-require-town=true
        # The interval in minutes for restoring blocks in an expired town. Set to 0 to disable. Note: This only supports vanilla blocks. Use with caution if using custom biomes.
        cleanup-task-interval=5
        # The required amount of funds to create a town. (Default: 0)
        # Note: This requires an Economy plugin.
        creation-cost=0.0
        # How far below the shoveled block a new claim will reach. Set to 255 if you want to always extend to bedrock.
        extend-into-ground-distance=255
        # Limit on how deep towns can go.
        max-depth=0
    }
}

**Comment by bigpresh** [comment]
I... don't quite understand what you're trying to say here.

> the claims of most users had changed name instead those of the staffer there are there could tell how to solve and make the claims you have them owners, and tells the users that the claim belongs to sponge even if they have permissions are not recognized the name of the claim

... what do you mean "tells the users that the claim belongs to sponge"?

You said:

> GirefPrevention 1.10.2-4.0.0.328

That doesn't look like a GP version - is that the Sponge version?  What's the GP version you're using?

If you can describe the problem a bit better with full details (e.g. what messages are displayed might help) we may be able to figure it out.

Most importantly, though: this is the repo for the Bukkit/Spigot GriefPrevention plugin; I think you need to be reporting it on the Sponge version, which appears to be https://github.com/MinecraftPortCentral/GriefPrevention at a quick glance.  (It's a shame that the Sponge fork doesn't have a different name.)
