### ISSUE TITLE
Siege Glitch - Breaking Bottom of Doors and Teleport Through

### ISSUE THREAD

**Issue by whoshenry** [GriefPrevention/GriefPrevention#222]
### What behaviour is expected:
Breaking bottom of door and you cannot get through during a siege
### What behaviour is observed:
Break the bottom of any door, wooden or iron, hold W and you glitch through and you can enter the player's claim during a siege.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
Spigot 1.12.2 - Grief Prevention 16.7.1

I am not sure if this is relatable to Issue #210 - it sounds like it might be.

**Comment by TomLewis** [comment]
I reported this before, its a major issue, there is STILL a siege bug where if you siege from above a base you can be teleported down into it.
There is another siege bug where as its teleporting you all over the place it triggers AAC, so the players kicked.

**Comment by whoshenry** [comment]
Yeah I was hoping to get this sorted asap but it doesn't look like it's a priority which is a shame as sieges are a large part of the server.

**Comment by RoboMWM** [comment]
Not so much not being a priority but rather something I don't use and thus can't test very easily (especially that I'm busy this semester, not much activity as usual as you can see on my profile).

**Comment by RoboMWM** [comment]
Also doesn't help when github's being stupid and not indexing this repo or whatever https://i.imgur.com/Jtcg0Iu.png

**Comment by RoboMWM** [comment]
You guys have a lot of siege reports that all kind of relate to the same thing (which you guys seem to get, but keep making new reports anyways ¯\\\_(ツ)_\/¯ )  so I'm going to post in #210 to keep all the information together. (Actually, this ticket is a duplicate of that one).

**Comment by whoshenry** [comment]
I think you mean #210 not #220.

**Comment by RoboMWM** [comment]
Wow rip me :( Thanks for correction.
