### ISSUE TITLE
PlayerPortalEvent high resource usage

### ISSUE THREAD

**Issue by workbenchmc** [GriefPrevention/GriefPrevention#223]
### What behaviour is expected:
Lower resource usage for the PlayerPortalEvent.

### What behaviour is observed:
Very high resource usage for the PlayerPortalEvent

### Steps/models to reproduce:
I don't really have detailed instructions on how to reconstruct the issue, it just seems to be a normal occurrence on my server. The only other plugin I have installed that has anything to do with portals is the AdvancedPortals plugin, but I don't think that's causing the issue.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
CraftBukkit version git-Spigot-93e20b3-31d3159 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
GriefPrevention version 16.7.1

Here's a picture from the pasted timings report:
![screen shot 2017-10-17 at 8 53 25 pm](https://user-images.githubusercontent.com/32890729/31700664-ccf7e1ba-b37f-11e7-80aa-3af9a797c1a0.png)

**Comment by RoboMWM** [comment]
There's a reason why we ask for the config. Disable the portal build check which you enabled if you want to see this go down.
