### ISSUE TITLE
Disable /ignore so another plugin can use that command...

### ISSUE THREAD

**Issue by mrcoffee1026** [GriefPrevention/GriefPrevention#227]
### What behaviour is expected:
I have Three plugins battling for the use of this command.  It would be fine for this one to win... if this plugin also handled /tp requests, but since it does not...  I need an "off" switch for this, so that essentials /ignore wins.
### What behaviour is observed:
Currently, /ignore isn't functional for any of the 3 plugins... I've tried altering a lot of settings but nothing has helped the situation.
### Steps/models to reproduce:
GriefPrevention, EssentialsX, ChatControl Pro

### Spigot/Craftbukkit/Paper and GriefPrevention version:
CraftBukkit git-Spigot-d21162c... Version 1.12.2-R-0.1-SNAPSHOT
GriefPrevention 1.6.7.1

### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here
```

**Comment by Jikoo** [comment]
Use your [commands.yml](https://bukkit.gamepedia.com/Commands.yml) to override GP.
```yaml
aliases:
  ignore:
    - myotherplugin:ignore $1-
```

**Comment by mrcoffee1026** [comment]
yes thank you... figured that out i guess before i wrote the ticket even... but didn't realize i had to restart before it would take effect  (essentials config instead of commands.yml, but same thing accomplished).  Thanks again.
