### ISSUE TITLE
ClaimExpiration Task will load chunks

### ISSUE THREAD

**Issue by NO-UUID** [GriefPrevention/GriefPrevention#2292]
### Observed Behavior

https://github.com/GriefPrevention/GriefPrevention/blob/14ce8e6001a04a434590d2cca787da8dc603ada1/src/main/java/me/ryanhamshire/GriefPrevention/CleanupUnusedClaimTask.java#L114

getPlayerInvestmentScore() will load chunks and potentially cause lag

### Expected Behavior

Not sure, maybe we could consider removing this or move to Paper's async chunk loading system, both solutions will have downsides tho.

### Reproduction steps

N/A

### Server version

```shell
Paper 1.20.4
```

### GriefPrevention version

```shell
Latest
```

### Configuration

```yaml
Claim expiration enabled, I think that's the only setting that is related to this report.
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by NO-UUID** [comment]
I guess the alternative solution would be to disable deleting unused claims which can be done via config.

**Comment by Jikoo** [comment]
We could also delete claim expiration from v17 and leave it to an addon since we're stripping out features. https://github.com/GPAddons/GPClaimExpiration mostly fills the void already, though it doesn't do nature restoration.

**Comment by QarthO** [comment]
It's only loading the chunk to check the restore nature conditions right?

If we strip that out and leave it to addons, we can still keep claims expiring and just have it strictly unclaimed. Not change anything in the world

**Comment by Jikoo** [comment]
That particular one also checks "investment score" which is supposed to check if the player has put down sufficient blocks. This was set to only happen in creative worlds for performance reasons, apparently: ce6bddcd49b26f20b6a4df1a383d64496ea78abe

It loads every chunk in the claim once for the score, then a second time to do nature restoration if the claim is deleted.
