### ISSUE TITLE
which permission level can use claim explosions

### ISSUE THREAD

**Issue by 1UnderTheSun** [GriefPrevention/GriefPrevention#2306]
### Observed Behavior

may i suggest /claimexplosions / /claimexplosion only be able to be toggled by someone who is either the claim owner or with explicit permissions, at the moment it can be toggled with just normal claim members and you gather that would be pretty bad with normal trusted members turning it on and griefing with creepers, etc.

### Expected Behavior

/claimexplosions and /claimexplosion should only be toggleable from the claim owner or people with explicit permissions

### Reproduction steps

step 1. claim owner /trust user1 (build trust)
step 2. user1 types /claimexplosions OR /claimexplosion
step 3. user1 then blows up the claim owner's claim
step 4. claim owner cries

### Server version

```shell
This server is running Paper version 1.20.6-137-master@bd5867a (2024-06-04T21:04:28Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT) You are 1 version(s) behind Download the new version at: https://papermc.io/downloads/paper Previous version: 1.20.6-124-0fcf3e3 (MC: 1.20.6)
```

### GriefPrevention version

```shell
16.18.1
```

### Configuration

```yaml
dunno
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
See #618
