### ISSUE TITLE
People getting untrustes

### ISSUE THREAD

**Issue by BopMooCow23** [GriefPrevention/GriefPrevention#2314]
### Observed Behavior

I trusted my friend with all perms and then for some reason when i was kicked he lost his claim trust, even when i logged back on.

### Expected Behavior

The /trust stuff should of stayed

### Reproduction steps

1. do /trust
2. leave claim/game
3.  done

### Stack trace or error log

```shell
not server owner
```

### Server version

```shell
not server owner
```

### GriefPrevention version

```shell
not server owner
```

### Configuration

```yaml
not server owner
```

### Plugin list

```shell
not server owner
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Jikoo** [comment]
Without more information it's basically impossible to help you. There could be any number of reasons why your claim modifications didn't persist. You said you were kicked, but did you time out from the server? If your own connection to the server was failing, then maybe the command never got received. If it did go through but the server crashed, maybe the claim didn't save successfully.

If this is something you can replicate and isn't just a spotty connection, you'll need to contact your server admin for error logs.

**Comment by RoboMWM** [comment]
Well, ask the server owner, maybe he has some sort of configuration that does this.
