### ISSUE TITLE
Towny/Griefprevention overlap

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#237]
### What behaviour is expected:
I expect that one plugin will override the other.
### What behaviour is observed:
If someone has a town and a random person comes and claims over part of their town neither the town nor the claim owner can build/break/open. 
### Steps/models to reproduce:
claim a town with towny, then claim over it with GP or do it the other way around. Neither the town owner nor the claim owner can break things. 

### Spigot/Craftbukkit/Paper and GriefPrevention version:
spigot 1.12.2 build70
GP version 16.7.1 

I suggest adding a few lines of code or something that allows server owners to toggle towny/factions protection on/off so if its set to true or "on" then it will now allow the use of claiming when inside a factions/towny claimed area.

**Comment by RoboMWM** [comment]
Duplicate of #10 

Basically this is a job for an addon, since both plugins protect regions and thus assume they are the sole plugin used for region protection (as this is the usual case).

> I suggest adding a few lines of code

Probably will be more than that, especially with towny.

**Comment by ghost** [comment]
Sorry for the dupe I didnt see it. But I talked to the towny dev and they said it was a thing for GP cause its their tool/plugin. I understand some servers only use one or the other but many servers like mine use both.

**Comment by RoboMWM** [comment]
> they said it was a thing for GP cause its their tool/plugin. 

Translation: I don't want to deal with integration, they can instead.

Yea I'm not touching towny - I've already heard a lot of horror stories trying to get it to work with maven (and I've heard their own build script is broken), but if someone wants to build an addon that bridges the two, that'd be perfect.
