### ISSUE TITLE
Addons for GP disappeared 

### ISSUE THREAD

**Issue by onovozhenov** [GriefPrevention/GriefPrevention#2392]
### Observed Behavior

Previously we could find GP addons in Addons category on wiki. Now all of them disappeared. We need GPAccruals but it simply disappeared and we are unable to find it for 1.20.6-1.21 versions of Minecraft - [GPAccruals](https://github.com/TechFortress/GriefPrevention/wiki/Addons#gpaccruals)

Could you please kindly advise on where we could find this plugin or another with similar features of different amount of blocks earned by different groups of players?

### Expected Behavior

It has disappeared 

### Reproduction steps

1. Searched on google and GP wiki

### Server version

```shell
1.20.6
```

### GriefPrevention version

```shell
Latest
```

### Configuration

```yaml
No
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by QarthO** [comment]
Addons are now listed on the Addons category in the GitHub discussions. 
https://github.com/GriefPrevention/GriefPrevention/discussions/categories/addons

You can find GPAccruals here: https://github.com/GriefPrevention/GriefPrevention/discussions/2075

**Comment by onovozhenov** [comment]
Thank you!

**Comment by RoboMWM** [comment]
Curious what wiki you checked. Sounds like I should put a page directly in the documentation linking to it.
