### ISSUE TITLE
Delete available and bonus blocks for players who have been banned

### ISSUE THREAD

**Issue by Cassolotl** [GriefPrevention/GriefPrevention#240]
### What behaviour is observed:
A player who is banned still has all their available and bonus claim blocks attached to their identity, and those blocks can't be revoked using, for example, `/AdjustBonusClaimBlocks <username> 0` when they've not logged in for a while.

It would be convenient if a player who has been banned could have their claim block allowance deleted when they are banned, so that their claims can expire regardless of the `ExceptWhenOwnerHasTotalClaimBlocks` and `ExceptWhenOwnerHasBonusClaimBlocks` setting in config.
### What behaviour is expected:
N/A
### Steps/models to reproduce:
N/A

### Spigot/Craftbukkit/Paper and GriefPrevention version:
[23:40:40] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-65e8124-963b19c (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
[23:40:40] [Server thread/INFO]: Checking version, please wait...
[23:40:41] [Thread-218/INFO]: You are 73 version(s) behind
[23:41:36] [Server thread/INFO]: GriefPrevention version 16.7.1

### Stack trace/error

N/A

### GriefPrevention config.yml (if applicable)

N/A

### Plugin list (if applicable):

N/A

**Comment by RoboMWM** [comment]
The reason for this is the same as in #238 

If you wish to remove this info you can just delete their file in the playerdata folder (filename is UUID).

Ideally, if you're banning players, you probably should auto-execute these commands as well - but at least in the case of inactive players, it might be better to use an offline utility. I'll see about forking and making a separate version that just tries to load all players into memory if desired I suppose.

**Comment by Cassolotl** [comment]
>If you wish to remove this info you can just delete their file in the playerdata folder (filename is UUID).

Okay, I can do this, thank you. It's good to know I can do this without breaking anything. :)

>Ideally, if you're banning players, you probably should auto-execute these commands as well

Yes, hence me asking for automation! People (like me) won't always remember to do this, and then the player will become "inactive", and then they'll have to either know that deleting their player data file is okay or they'll come here asking for help. Having the plugin delete remaining available and bonus blocks might save some trouble for you, and it would definitely save some trouble for admins, I think.

**Comment by RoboMWM** [comment]
> Yes, hence me asking for automation!

Probably best left to an addon. I personally would use bukkit's built-in `commands.yml` or MyCommand to automate a ban action.

**Comment by Cassolotl** [comment]
Alright, thanks for the advice. I don't know how to do that, so I will stick to deleting playerdata files, I think.

And if you do change the plugin to allow us to [delete all claims and available and bonus claim blocks for inactive players](https://github.com/TechFortress/GriefPrevention/issues/238#issuecomment-353733761), I think then I would probably be sorted. :)

Thank you for your hard work!

**Comment by RoboMWM** [comment]
https://bukkit.gamepedia.com/Commands.yml

You can setup an alias for ban to run the minecraft:ban command, as well as running deleteallclaims and any other commands when you execute `/ban` E.g.
```yml
  ban:
  - minecraft:ban $$1
  - deleteallclaims $$1

**Comment by Cassolotl** [comment]
I have no idea what you just said. :D It's okay, I'm just not very techy, I'll manage without. :) I appreciate it though!

**Comment by RoboMWM** [comment]
Checkout the link - there's a commands.yml in your server, and that's the documentation to use it to set your own command aliases.
