### ISSUE TITLE
Bug with flag to prevent people from entering claim.

### ISSUE THREAD

**Issue by Timco307** [GriefPrevention/GriefPrevention#2413]
### Observed Behavior

When you hop on a boat and you go inside a restricted claim, it lets you but in the chat, it gives you a warning saying you can’t go in this area even though you can still go in it but when you get out of the boat or somebody breaks your boat then you get kicked out where you first started to enter the claim.

### Expected Behavior

Claims should check if there is an entity like a boat or animal that is rideable and if it’s not the owner of the claim, not let them enter the claim.

### Reproduction steps

.

### Stack trace or error log

```shell
.
```

### Server version

```shell
.
```

### GriefPrevention version

```shell
.
```

### Configuration

```yaml
.
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

**Comment by Evidentsinger14** [comment]
GP doesn’t restrict players from entering claims. Sounds like GPFlags. Report to them.

**Comment by Jikoo** [comment]
As stated above, GP doesn't have flags. If you're having an issue with an addon, you should report the issue to the addon directly.
