### ISSUE TITLE
BlockIdsExplodable:

### ISSUE THREAD

**Issue by cosemansj** [GriefPrevention/GriefPrevention#244]
I have some problems using BlockIdsExplodable
If i add blocks in the config to BlockIdsExplodable its give always an error that u need to use a DEV bukkit id but i already tried STONE and 1 and it always gives the same error. 
Can you help me what i am doing wrong? 
Thank you

**Comment by RoboMWM** [comment]
Please fill out the template that you deleted. We need that info.
