### ISSUE TITLE
suggestion, updating the new command

### ISSUE THREAD

**Issue by sirlinium** [GriefPrevention/GriefPrevention#245]
Hello,

Would it be possible to update the list of commands here:
https://dev.bukkit.org/projects/grief-prevention/pages/command-and-permissions-reference

with the new 
/restrictsubclaim - modifies subclaim trustlist to not inherit the parent trustlist 

thanks !

**Comment by RoboMWM** [comment]
The documentation has been moved to the wiki here: https://github.com/TechFortress/GriefPrevention/wiki

Some reasons for this is use of markdown (though devbukkit does support it, it seems to be restricted/not implemented properly? At least the headers/fonts never really worked for me that well), and is, IMO, cleaner and neater to look at - especially with the customizable sidebar.

The documentation that's current on devbukkit uses their weird wikicreole format (I think that's what it's named) and is a pain to manage, but is left as-is while we transfer everything to here (though most of it has been moved over by now).

**Comment by Jikoo** [comment]
Bukkit uses HTML now that Curse has fully taken it over, but the WYSIWYG editor is pretty crap.

**Comment by sirlinium** [comment]
many thanks for your answer !
