### ISSUE TITLE
Can I add more claim amount based on rank?

### ISSUE THREAD

**Issue by SaltedBiscuit** [GriefPrevention/GriefPrevention#246]
### What behaviour is observed:
I have not noticed a way to make certain player ranks have a max amount of claim space.
### What behaviour is expected:
Is there a way that players can have more space to claim based on their given rank?
### Steps/models to reproduce:
Example: Guest can  claim 64 blocks where as a Member can claim 1024 blocks.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Spigot version: 1.12.2-r0.1
GP version: 16.8

**Comment by RoboMWM** [comment]
See #18
