### ISSUE TITLE
[Suggestion] Filter /me command from people who are ignored

### ISSUE THREAD

**Issue by frost-byte** [GriefPrevention/GriefPrevention#247]
Suggestion

If someone is ignored, also ignore emotes or /me commands from that person

**Comment by RoboMWM** [comment]
Not easy to do, since this is a command. I already do something myself in my own addon, but however you do it you'd effectively be setting up the format yourself.

**Comment by RoboMWM** [comment]
Actually this should be filtered by default(?), unless I'm thinking of /tell
