### ISSUE TITLE
Witches can apply potions to (and specifically kill) claimed animals.

### ISSUE THREAD

**Issue by gnubufferoverflows** [GriefPrevention/GriefPrevention#25]
### What behaviour is expected:

Witches should not be able to kill villagers or other animals since they are claimed. In certain cases, players can aim witches at mobs to get them killed. If a player cannot kill an animal, a witch shouldn't be able to either.
### What behaviour is observed:

Witches can apply status effects to mobs.
### Steps/models to reproduce:

Although I didn't have a screenshot of it, all you need is a villager in a fenced in area and a witch. All you have to do is get the witch to throw a potion at the villager by getting it at the right angle.

An example (less witch) would look like this. Everything in the picture is claimed, and villagers cannot be killed without build trust:

https://imgur.com/a/do1ym
### Spigot/Craftbukkit/Paper and GriefPrevention version:

Spigot: git-Spigot-a9631d2-56183c67 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

GP: 15.2.3
### Stack trace/error (if applicable)

N/A

Paste entire stack trace inside here
N/A
### GriefPrevention config.yml (if applicable)

N/A
### Plugin list (if applicable):

N/A

**Comment by RoboMWM** [comment]
Could you also test to see if it's possible to kill animals via potions thrown from a dispenser?

**Comment by RoboMWM** [comment]
Note to self: 
- [x] treat villagers like animals
- [x] Simply remove animals from effected entities instead of canceling event altogether
