### ISSUE TITLE
Driving boat through lily pads in someone else's claim destroys them

### ISSUE THREAD

**Issue by lunarcoffee** [GriefPrevention/GriefPrevention#250]
### What behaviour is observed:
Driving a boat through lily pads in another player's claim will destroy the lily pads.
### What behaviour is expected:
The lily pads will not be destroyed
### Steps/models to reproduce:
1) Have someone claim some lily pads.
2) Have someone else drive a boat through the claim.
### Spigot/Craftbukkit/Paper and GriefPrevention version:
Spigot for MC 1.12.2, latest GriefPrevention version (as of report).
### Stack trace/error
None.
### GriefPrevention config.yml (if applicable)
Default, nothing changed.
### Plugin list (if applicable):
Multiverse-core, tpa, Warps

**Comment by RoboMWM** [comment]
Unsure if it's possible to identify who the driver of the boat is, or if it's even possible to identify why the lilypad was broken.

**Comment by lunarcoffee** [comment]
Hm... true. Well.

**Comment by Jikoo** [comment]
Relevant event is the EntityChangeBlockEvent per [SPIGOT-1762](https://hub.spigotmc.org/jira/browse/SPIGOT-1762).

There are no checks for vehicles/riders done in the [handler for the EntityChangeBlockEvent](https://github.com/TechFortress/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/EntityEventHandler.java#L122-L210).

Here's a quick snippet preventing block changes by vehicles if the driver doesn't have build permissions. Just a warning, I wrote it here in the editor, so it may contain mistakes.
```Java
if (event.getEntity() instanceof Vehicle && !event.getEntity().getPassengers().isEmpty()) {
    Entity driver = event.getEntity().getPassengers().get(0);
    if (driver instanceof Player) {
        Block block = event.getBlock();
        if (GriefPrevention.instance.allowBreak((Player) driver, block, block.getLocation()) != null) {
            event.setCancelled(true);
        }
    }
}
```

**Comment by RoboMWM** [comment]
Thanks! Saved me some time having to set up a test environment to get the correct event that's fired.
