### ISSUE TITLE
Grieving bug with a sign.

### ISSUE THREAD

**Issue by kuohsuanlo** [GriefPrevention/GriefPrevention#254]
I found a serious grieving bug.

Any blocks that under a sign is breakable by anyone.

as example, the glass is breakable although it would say "you don't have the build permission right here."
https://i.imgur.com/rs33ExF.png

**Comment by bigpresh** [comment]
From the template you deleted when raising the issue:

### Spigot/Craftbukkit/Paper and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.

What versions are you running?

Can't reproduce on my server.

**Comment by kuohsuanlo** [comment]
[06:02:28] [Server thread/INFO]: [GriefPrevention] Loading GriefPrevention v16.7.1
[06:02:25] [Server thread/INFO]: Starting minecraft server version 1.12.2 (Paper)

I'll switch to 16.8 and try it again.

**Comment by RoboMWM** [comment]
I can't reproduce this, try with just GP installed?

**Comment by kuohsuanlo** [comment]
It is caused by the incompatible issue with DungeonsXL.

Don't need to activate any function of DXL. 
Just install and with default setting.

**Comment by RoboMWM** [comment]
Thanks for investigating. Bug is with DungeonsXL as I know they do with stuff with signs, and since GP doesn't care for signs when checking a block break - it simply checks if it's within a claim.
