### ISSUE TITLE
Disabling claiming in a certain area.

### ISSUE THREAD

**Issue by epikpython** [GriefPrevention/GriefPrevention#261]
Is there any way to disable the ability to claim in a certain area? I would assume this could be done by worldguard somehow. Any help would be appreciated.

**Comment by bigpresh** [comment]
Simplest: make an admin claim in that area - then nobody else can claim there.  You could of course give public build permissions with `/trust public`, if you want people to still be able to build there but just not claim.

**Comment by RoboMWM** [comment]
See bigpresh's answer.
