### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by AwokenToad** [GriefPrevention/GriefPrevention#263]
Im Getting this error in my console, in 1.8.8 with ViaVersion 
how can i fix this 
https://pastebin.com/bqsDRAUu

**Comment by RoboMWM** [comment]
1.8.8 is not supported. Please update, or downgrade GP.

**Comment by AwokenToad** [comment]
1.6.7 work ?

**Comment by AwokenToad** [comment]
1.8.7

**Comment by AwokenToad** [comment]
What 1.8 versions are supported?

**Comment by bigpresh** [comment]
> What 1.8 versions are supported?

Each release on https://github.com/TechFortress/GriefPrevention/releases should show the Minecraft versions it's known to work with.  https://dev.bukkit.org/projects/grief-prevention/files also displays the game version for each GP version.

1.8.x is ancient, so recent GP versions won't support it.  GP 13.9.1 looks to be the most recent GP that will.
