### ISSUE TITLE
Supported Versions

### ISSUE THREAD

**Issue by AwokenToad** [GriefPrevention/GriefPrevention#264]
What 1.8 versions are supported?

**Comment by bigpresh** [comment]
> What 1.8 versions are supported?

Each release on https://github.com/TechFortress/GriefPrevention/releases should show the Minecraft versions it's known to work with.  https://dev.bukkit.org/projects/grief-prevention/files also displays the game version for each GP version.

1.8.x is ancient, so recent GP versions won't support it.  GP 13.9.1 looks to be the most recent GP that will.
