### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by LordDWT** [GriefPrevention/GriefPrevention#27]
### What behaviour is expected:

Normal console load
### What behaviour is observed:

https://ghostbin.com/paste/6x68e
### Steps/models to reproduce:

Load server
### Spigot/Craftbukkit/Paper and GriefPrevention version:

[20:32:57 INFO]: GriefPrevention version 15.3.1
[20:32:57 INFO]: JDynmapGriefPrevention version 2.5.1
[20:32:57 INFO]: Shows Griefprevention claims and extended info on Dynmap.
[20:32:57 INFO]: Website: http://goo.gl/5lI8Mh
[20:32:57 INFO]: Author: jahangir13

> version
> [20:33:00 INFO]: This server is running CraftBukkit version git-Spigot-047f737-744e1a1 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
> [20:33:00 INFO]: Checking version, please wait...
> [20:33:01 INFO]: You are running the latest version
### Stack trace/error (if applicable)

https://ghostbin.com/paste/6x68e

**Comment by RoboMWM** [comment]
Are you sure that's it? Would like to see more of the server log.

**Comment by LordDWT** [comment]
Here ya go.  Full log on fresh load.

https://drive.google.com/file/d/0B4sHRhCiqyNJb19uWEpJaHdIU1k/view?usp=sharing

**Comment by RoboMWM** [comment]
Hmm, not sure what I did when compiling this. Go ahead and try the "Java 7" version.

**Comment by RoboMWM** [comment]
Thanks, fixed. Go re-download.

**Comment by LordDWT** [comment]
Downloaded 15.3.  Problem resolved.
