### ISSUE TITLE
Dupe bug with sticky piston?

### ISSUE THREAD

**Issue by ScuroK** [GriefPrevention/GriefPrevention#274]
I use the latest official version of grief prevention from spigot.

Today a player tryed to control a sticky piston (inside claim) with a lever (outside of claim)
He attached some gold ore to the sticky piston.

after he found the laver wasnt working he broke the sticky piston and it turned into a gold ore.
it was not a ghost block and he was able to give me the duped item.

i was not able to reproduce it myself but maybe someone else here expirienced the same bug?

**Comment by RoboMWM** [comment]
well, including the info requested that you deleted would help too.

**Comment by RoboMWM** [comment]
Closing issue due to no response and invalid ticket format (lacks necessary information to determine problem).
