### ISSUE TITLE
Flags (Resurrected)

### ISSUE THREAD

**Issue by ShaneBeee** [GriefPrevention/GriefPrevention#278]
hey @RoboMWM 
I was going to message you on spigot about this, but you have private convos turned off.
Anyways I know myself and plenty of others have been saddened that the FLAGS addon has been removed. So, I found the source code and resurrected it. 
I just wanted to let you know in the event you want to put a link to it here, bukkit, spigot. Might help people who are in need of that find it a bit easier
https://www.spigotmc.org/resources/griefprevention-flags.55773/

**Comment by RoboMWM** [comment]
This is probably best suited for the GP discussion thread. Anyways, there's already a link on spigot to the source code, but sure, if you keep it maintained and all I can add a link to yours, that'd be great! Do note however that there is a PvP bug with the current version. Details (and a posted fix, iirc) were on its related discussion thread, but I either can't find it or it's been deleted along with the resource.

**Comment by RoboMWM** [comment]
It seems like these guys have an active and maintained fork. Perhaps try asking them if you can collaborate with them in posting a published resource to spigot (or maybe they already have)? https://github.com/DmitryRendov/GriefPreventionFlags

(There's also https://github.com/ArtNRG/GriefPreventionFlags but it seems like he only added a single feature (as it is forked from the above) and his repo is somewhat messed up.)

**Comment by ShaneBeee** [comment]
Ah sweet, Ok I will do that, thanks!
