### ISSUE TITLE
Suggestion: sophisticate Multiverse Settings

### ISSUE THREAD

**Issue by david-bla** [GriefPrevention/GriefPrevention#280]
Hey, first I'd like to __thank you__ for this work! 🥇 

It would be awesome to have the opinion to tune the behavior of GriefPrevention.
To turn features per world / per region (WorldGuard) on or off.

This would also be a good way to give server admins the possibility to maybe use a Minigame Plugin that key functions would be prevented by GriefProtection.

Thank you in advance.

**Comment by RoboMWM** [comment]
Part of this is considered for version 20. Would ideally like to avoid multiple configs or making a complicated config though for the base plugin though.

> This would also be a good way to give server admins the possibility to maybe use a Minigame Plugin that key functions would be prevented by GriefProtection.

Sounds hacky and unnecessarily complex use-case. Sure on the naïve admin side it can be a quick fix to something but would be unmaintainable (i.e. changing/relocating area, etc.
