### ISSUE TITLE
Narrowing down a crash cause

### ISSUE THREAD

**Issue by Cobwebster** [GriefPrevention/GriefPrevention#281]
Hey,

We're trying to figure out which plugin is causing this issue,

[resolved]

anyone experiencing this issue with girefprevention or a similar plugin?

**Comment by RoboMWM** [comment]
GP doesn't modify chunks async, only reading chunk snapshots and it's for whether it should auto-extend a claim. And idk if that's even done async. Also you probably shouldn't just copy paste this all over the place without any pertinent info, it'll just be considered spam.
