### ISSUE TITLE
add placeholder info so we can use the Gp on scoreboard

### ISSUE THREAD

**Issue by mc-syrus-survival** [GriefPrevention/GriefPrevention#285]
### What behaviour is observed:
_What you saw_ just not able to use GP on the scoreboard
### What behaviour is expected:Id like be able to see the number of claims I, the player has, and whose claim, I, the player am in
_What you expected to see_as mentioned above
### Steps/models to reproduce:
_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_

### Spigot/Craftbukkit/Paper and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___

### Stack trace/error

```
Paste entire stack trace inside here (don't remove the backticks!)
If not applicable, paste server.log at gist.github.com and paste the link here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here (don't remove the backticks!)
```

**Comment by Jikoo** [comment]
https://github.com/pixar02/Expansions adds a GriefPrevention hook available through PAPI. I believe the same hook is also available through PAPI's ecloud system.
