### ISSUE TITLE
Request: option to use WE for auto restore nature

### ISSUE THREAD

**Issue by ScuroK** [GriefPrevention/GriefPrevention#286]
Could you allow us to use worldedits //regen for automatic nature restauration instead of GP?

Because worldguards regen looks nicer. GP's restoration sometimes causes very weird patches in the landscape. especially in deserts. and it does not plant any trees etc.

thats why i would like to see a config  option to let worldedit regenerate expired claims instead.

possible?

**Comment by RoboMWM** [comment]
WorldEdit just regenerates the chunk via Bukkit. So it's not WorldEdit's.

GP specifically doesn't do this; Big_Scary provided these reasons on the plugin description page specifically regarding using vanilla's chunk regeneration:
>Never accidentally changes blocks inside land claims.
>No chunk regeneration (it's dangerous for technical reasons).
>Fixes bad chunk generations, like floating islands. It will be better than new.

**Comment by ScuroK** [comment]
@RoboMWM 
Yah but GP's regeneration create holes underground, and other weird things like stone patches in deserts etc. it just doesnt look like nature at all
