### ISSUE TITLE
/home in other worlds

### ISSUE THREAD

**Issue by dezzistone** [GriefPrevention/GriefPrevention#29]
im using 1 5 3

im just unsure of how to connect worlds if thats the word?
Basically i have a survival world which i use the grief prevention plugin /home works in the linked end and nether but i created a new world for resources and i want people to be able to do /home in the resourceworld and go back to the survival world

**Comment by RoboMWM** [comment]
GriefPrevention does not handle the /home command, nor has any such functionality.
