### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jer3m01** [GriefPrevention/GriefPrevention#299]
Typo at DataStore line 1565
`this.addDefault(defaults, Messages.BuySellNotConfigured, "Sorry, buying anhd selling claim blocks is disabled.", null);`
`anhd` 

---> `and`
`this.addDefault(defaults, Messages.BuySellNotConfigured, "Sorry, buying and selling claim blocks is disabled.", null);`

**Comment by RoboMWM** [comment]
Yes I've seen that typo but never bothered to find and fix it, go ahead and PR if you want to fix it now c:

**Comment by jer3m01** [comment]
Sure :)

**Comment by RoboMWM** [comment]
Closed in #305
