### ISSUE TITLE
More blocks for Vip users

### ISSUE THREAD

**Issue by ledevmacedo** [GriefPrevention/GriefPrevention#30]
Hello, it is possible to define more blocks to VIPS users? Is there any permission or setting to set it?

**Comment by RoboMWM** [comment]
There is a way to do this currently with the fasteraccrual/moreblocks/idk some permission that's listed in the config, but I will be removing this feature and make it available to addons instead.

**Comment by ledevmacedo** [comment]
What allowed to set more blocks for VIP members?

**Comment by RoboMWM** [comment]
The permissions are specified in the config, just prepend `griefprevention.` to it and there's your permissions.
