### ISSUE TITLE
Setup and Configuration doean't give and examples on how to install this plugin/mod

### ISSUE THREAD

**Issue by the-webguys** [GriefPrevention/GriefPrevention#301]
### What behaviour is observed:
Setup and Configuration doesn't give instructions on where to put the .jar file or if there is anything else used, such as Forge
### What behaviour is expected:
I expect to find some instructions on how to install this
### Steps/models to reproduce:
Open this page: https://github.com/TechFortress/GriefPrevention/wiki/Setup-and-Configuration

### Spigot/Craftbukkit/Paper and GriefPrevention version:
Just visit this page: https://github.com/TechFortress/GriefPrevention/wiki/Setup-and-Configuration

Not trying to be funny, but I have no idea how to install this and your Setup and Configuration really should have instructions on how to use the .jar file

### Stack trace/error

```
Paste entire stack trace inside here (don't remove the backticks!)
If not applicable, paste server.log at gist.github.com and paste the link here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here (don't remove the backticks!)
```

**Comment by RoboMWM** [comment]
This is a bukkit plugin. Instructions are on the respective bukkit/spigot pages where this plugin is formally "published" and distributed.

Feel free to add instructions to the wiki or readme if you wish.

**Comment by RoboMWM** [comment]
Instructions on how to install plugins are on the bukkit/spigot pages, respectively - which is where this plugin is published. As I already mentioned, if you wish to include these instructions here as well, feel free to add to the wiki.
