### ISSUE TITLE
Pistons lagging

### ISSUE THREAD

**Issue by ChanceSD** [GriefPrevention/GriefPrevention#307]
This isn't really a bug report but more of a possible performance improvement. I'm on GP version 16.8.
So here is what i find pretty often on my timings report (using Paper)
https://i.imgur.com/T4znH1A.png
Clearly the problem is some player is using a ton of pistons which he shouldn't, however the time GP consumes compared to other plugins is huge. So i ran a worldguard profile and got this: https://i.imgur.com/XbZUWCA.png

I didn't look much into the code but a possible solution could be changing [this](https://github.com/TechFortress/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/GriefPrevention/BlockEventHandler.java#L577) and [this](https://github.com/TechFortress/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/GriefPrevention/BlockEventHandler.java#L584) to check the player UUID instead as it seems to be already stored in the [Claim](https://github.com/TechFortress/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/GriefPrevention/Claim.java#L48) object so likely to be quicker than calling getOwnerName() twice. And i don't think getting the player name really matters in this case.  
I didn't check all but there might be more places where a change like this could possibly be made to improve performance. The BlockPistonExtendEvent listener also seems to use it.

Another possible solution could be to have a similar cache to [this one](https://github.com/TechFortress/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/GriefPrevention/GriefPrevention.java#L3158) but from UUIDs to player names but i like the first solution better to be honest.

**Comment by RoboMWM** [comment]
Please provide a link to the actual, full timings report.

**Comment by RoboMWM** [comment]
Until this is updated with the full timings report there's nothing I can do since the information shown here is very limited.
