### ISSUE TITLE
Claim-only mode for building and mining

### ISSUE THREAD

**Issue by Polyr** [GriefPrevention/GriefPrevention#309]
I suggest that a command be implemented that prevents you from building and mining in unclaimed territory. This would be useful, for example, in projects that involve mining out a large area where you only want to dig out the area that you have claimed as opposed to accidentally griefing and having to replace excess broken blocks that border the claim.

**Comment by RoboMWM** [comment]
Please see wiki, there is such a feature. SurvivalRequiringClaims
