### ISSUE TITLE
Feature Request: /Fly in claims with permission

### ISSUE THREAD

**Issue by Darkweasam** [GriefPrevention/GriefPrevention#310]
Hey, I just read "feature request? Report it on the issue tracker" So I guess this is the place I need to post what I am looking for
Title is pretty self explainatory, I want to give some players /fly within their OWN region only (my server has level-up system, would be a good stuff to unlock at higher levels)

**Comment by bigpresh** [comment]
My initial thoughts:

* Checking this might be quite expensive - checking claim access on every movement event, for instance, would probably be very inefficient
* What would happen when they reach the edge of their claim?  Players accidentally going out of their claim boundary and plummeting to the ground, whilst potentially amusing, probably wouldn't be popular.  I suppose it could cancel their x/z movement and put them at a hover, perhaps.

I suspect this is something that would be better handled by a plugin, personally.

**Comment by Darkweasam** [comment]
If you leave your claim then the plugin does /fly which turns it off for the player and removes the permission to use /fly in that world, in their claim, they would be granted permission again

**Comment by RoboMWM** [comment]
Already a flag in GriefPrevention flags, an addon
