### ISSUE TITLE
Claim Depth reset.

### ISSUE THREAD

**Issue by NullCase** [GriefPrevention/GriefPrevention#312]
This has occured at least 4x since I set claim depth to ExtendIntoGroundDistance: 1

I have been experimenting to find out what causes this problem. So far I haven't had any luck.

The top level claim's depth is being reset for land claims which have subclaims when ExtendIntoGroundDistance is 1. 

The subclaims have a different depth than the top level claim. 

When claim depth resets, builds underground are becoming unclaimed.

**Comment by NullCase** [comment]
OK, so if all blocks within a land claim are removed... then anyone can build inside that claim. easy to test in The End.

So i think i know what's causing this depth reset. And i will test it tomorrow (when i have time)

If all blocks within a subclaim are removed, i think that's causing the depth of the top level claim to change.

**Comment by NullCase** [comment]
I switched it back to default,  ExtendIntoGroundDistance: 5

Still the claim has reset once since then. very strange.

**Comment by NullCase** [comment]
text comparing my old config and current one... they're exactly the same, so i haven't changed the config in months (after reverting to ExtendIntoGroundDistance: 5)

So I started considering more things.

It looks like you updated subclaims to have /claimexplosions permit block breaking for withers.

That update occurred roughly when this first started happening for me.

**Comment by RoboMWM** [comment]
> It looks like you updated subclaims to have /claimexplosions permit block breaking for withers.

Not that I'm aware of. Might want to check with @jacob1 though.

**Comment by Jikoo** [comment]
2f5a2eea9c

**Comment by RoboMWM** [comment]
> 2f5a2ee

This build has not been released.

**Comment by RoboMWM** [comment]
Anyways, afaik the extendIntoGround check is a task, and determines the lowest "player-type" block (i.e. a non-natural block). This task is run async iirc after acquiring the chunks within a claim to check to extend. I'm not sure what other things may trigger this, but it should update the claim's depth as listed in its data.

**Comment by Jikoo** [comment]
>This build has not been released.

Ah, so used to just grabbing whatever whenever, my bad.

**Comment by NullCase** [comment]
OK, player-type blocks extend the claim. 

Inside this particular claim there are shulker boxes, quartz stairs, hoppers, comparators, stained glass, lapis blocks, redstone lanterns. 

It seems like some of these would be player-type blocks.

The claim data yml shows the Y coordinate within this claim is 0 (presently) but the claim is working properly for the moment.

**Comment by NullCase** [comment]
Still a mystery. How could subclaims cause claim depth to reset?

**Comment by RoboMWM** [comment]
Would be nice if you filled out the template before deleting it. Unsure of steps to reproduce - when does it happen? When you create a subclaim? When you build in it?

**Comment by TomLewis** [comment]
Sub-claims have always caused weird things to happen, sometimes all sub claims will just vanish. I have also had this depth reset itself. I will ask about my community to see if someone knows how to reproduce it, i'm sure we figured it out years ago and reported it, getting a bit old for the memory to pick these things up now! haha

**Comment by NullCase** [comment]
I deleted the template this time. Next time I won't though. Cool?

I'm unsure how to reproduce this. It first happened after I changed ExtendIntoGroundDistance to 1. It happened 4 times on the same land claim with this configuration.

So I changed it back to ExtendIntoGroundDistance: 5. It happened one time after that.

And "What" happens is basically that the claim's depth is reset to 60. Some of the subclaims start at 65 and permit the use of a Nether wart farm.

This has not recurred recently, but it's very weird. I'm sorry, I don't understand it that well.

**Comment by NullCase** [comment]
Closing this because it's not been an issue for two years. After two years of trying to reproduce this, claims have been fine.

**Comment by NullCase** [comment]
GriefPrevention version 16.13.0-0f82170

Claim Depth reset showed up again today. I don't know how this caused the claims depth to reset, but here's a few steps.

- land claim depth extend into ground is default (5 blocks)
- First, I created a subclaim and resized it using /extendclaim commands.
- I removed blocks from within the subclaim, basically digging out part of a chunk.
- I resized the subclaim again, making it smaller using /extendclaim -16
- I continued working and later noticed the land (edit: below surface in the top level claim) had become unclaimed... (after an unfortunately large amount of damage from withers :)

To re-extend the depth, I just placed some blocks down near Y=5.

edit: included that extend into ground is default 5 blocks.

**Comment by RoboMWM** [comment]
interesting, subclaims strike again

**Comment by NullCase** [comment]
As a theory to test, is it possible that creating a new subclaim (and then placing items within it) redefines the topClaim's depth? Almost like the subclaim says "my depth is not yet defined" but the topLevelClaim asks the subclaim for a new depth?

**Comment by RoboMWM** [comment]
Hmm, I think resizing the claim is what probably re-adjusts the lower y-level(?) If so, then this can happen with normal claims too.

Or it could be subclaims resetting to the parent claim's lower y level.
