### ISSUE TITLE
Allow untrusting in subclaims

### ISSUE THREAD

**Issue by OffLuffy** [GriefPrevention/GriefPrevention#314]
I've noticed on a few servers that an additional plugin is required in order to have some claim setups work (with reasonable effort).

This would seem possible as an add on provided that GriefPrevention's API lets you override whether or not a player has permission to do certain actions, and ideally if the API would allow you to modify the output of /trustlist when within a subclaim. I would rather like to see something like this implemented in the core, however, as it would fill a nice hole in functionality.

For example, if you have a claim which you need someone trusted, but you want a small portion of it (say a chest room) to remain private, then the player would need to have a plugin like Lockette to lock individual chests and doors.

Of course you can claim, then subclaim everything you want them to have access to, but if you just want to negate a small area, then you're liable to make several subclaim jigsaw pieces and needing to run /trust several times.

My suggestion would be to either allow /untrust to be used to negate a trust within a subclaim, or to perhaps have another command to the same end. Ideally, a subclaim would initially inherit it's parent's permissions as per usual, and a separate trust list for the subclaim could determine whether or not to override it. For the claim owner's convenience, it would likely be best to note in the chat that you're modifying a subclaim if so, so that if they attempt to untrust someone, they don't accidentally retain that trust in other parts of the claim.

**Comment by Jikoo** [comment]
You can use `/restrictsubclaim` to prevent a subclaim inheriting its parent's trust list.

**Comment by OffLuffy** [comment]
Doesn't seem like the most intuitive way, but it certainly seems to fill the functionality hole. Thanks!
