### ISSUE TITLE
TNT can destroy player's claim 

### ISSUE THREAD

**Issue by Danielh101** [GriefPrevention/GriefPrevention#318]
### What behavior is observed:
When a player puts 's TNT on the outside of the player's claim and destroys the inside of the outside claim. 
### What behavior is expected:
Does not destroy the inside which claimed of the outside of the claim 
### Steps/models to reproduce:
- 1
![image](https://user-images.githubusercontent.com/15858417/43059114-94f44ce2-8e10-11e8-8190-daafbea87036.png)
- 2 
![image](https://user-images.githubusercontent.com/15858417/43059145-b1fab8c6-8e10-11e8-85a6-35738a1efefe.png)

### Spigot/Craftbukkit/Paper and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paper 1.12

### Stack trace/error

```
Paste entire stack trace inside here (don't remove the backticks!)
If not applicable, paste server.log at gist.github.com and paste the link here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here (don't remove the backticks!)
```

**Comment by RoboMWM** [comment]
Missing information requested in template.

**Comment by RoboMWM** [comment]
Closing issue due to no response, also cannot reproduce.
