### ISSUE TITLE
error with 1.13

### ISSUE THREAD

**Issue by ozm8** [GriefPrevention/GriefPrevention#325]
Here is an warn/error with grief prevention for spigot 1.13: https://pastebin.com/7Mb4vfsX

**Comment by johnfriedrich** [comment]
try this version fixed by md_5 for now:
https://github.com/SpigotMC/SpigotCraft/blob/master/plugins/GriefPrevention.jar

**Comment by DocShell** [comment]
Error while making a claim on Spigot 1.13.  I have used both versions, the one on profile and it happens when using md_5's also.

https://pastebin.com/xbTNLb5n

**Comment by RoboMWM** [comment]
@i9hdkill I'm pretty sure that's the same released 16.8 version. Anyways, duplicate of #319
