### ISSUE TITLE
[1.13] Throwing trident at GP protected mob causes projectile to be destroyed

### ISSUE THREAD

**Issue by gnubufferoverflows** [GriefPrevention/GriefPrevention#330]
### What behaviour is observed:
When you throw a trident at a protected mob, the trident is destroyed. This only happens when you throw the trident in an area where you do not have building permission. Since tridents are not disposable like arrows, this behavior is incorrect.
### What behaviour is expected:
When you throw a trident at a protected mob, the mob is not damaged, but the trident stays as normal so the person who threw it can pick up it. 
### Steps/models to reproduce:
This is how I was able to reproduce the bug:
As a server operator, create an admin claim and spawn some animals in the claim. Give yourself a trident, deop yourself, and go into survival mode. Then, throw the trident at one of the animals in the claim. The trident projectile will be removed.

### Spigot/Craftbukkit/Paper and GriefPrevention version:

`[16:34:07 INFO]: This server is running CraftBukkit version git-Spigot-69774b3-8592585 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[16:34:07 INFO]: You are running the latest version
version griefprevention
[16:34:13 INFO]: GriefPrevention version 16.8
`

### Stack trace/error

https://gist.github.com/Dogeveloper/7f31f1b9b677af815d511ee12ad1f074

### GriefPrevention config.yml (if applicable)
N/A

### Plugin list (if applicable):
PopulationDensity
GriefPrevention
GraviTree (doesn't run, doesn't work)
WorldEdit (doesn't run, doesn't work)

**Comment by NullCase** [comment]
Tested this in 16.9 alpha. Same result as before.

**Comment by RoboMWM** [comment]
Yea, as expected, since I haven't touched this yet, thanks though.

**Comment by RoboMWM** [comment]
So GP deletes the projectile to prevent endless bouncing between protected animals. Short of outright excluding tridents, not sure of a good way to do this, other than possibly just flat out returning the trident to the player. Any ideas?

**Comment by NullCase** [comment]
Returning the trident sounds pretty good.

That seems consistent with block placing or torch placing, where the item is not lost and your inventory count remains the same.

**Comment by RoboMWM** [comment]
Block placement is not the same as firing a projectile.

**Comment by RoboMWM** [comment]
Probably the best thing would be to track how many times it bounces, something I'll look at for version 20. That or perhaps use Paper's API or similar to make it pass through an entity instead of just bouncing off.

**Comment by NullCase** [comment]
Consistent policy I mean. I don't know anything about coding.

**Comment by gnubufferoverflows** [comment]
@RoboMWM couldn't you just move the trident entity back to the player, that way it doesn't infinite bounce? I think if you offset the trident location enough the trident won't hit the player.

**Comment by Dogeveloper** [comment]
Another option would be to make it so the trident hits the mob, but any damage/knockback is negated.

**Comment by RoboMWM** [comment]
> couldn't you just move the trident entity back to the player

What would this accomplish?

**Comment by gnubufferoverflows** [comment]
@RoboMWM So I wrote a method which removes the trident and gives the item back to the player. It should solve the infinite bounce issue. What's the catch? It references NMS code through Reflection. I realize that getting a trident as a itemstack should be a simple thing to do, but there doesn't seem to be any methods to do it outside of NMS (at least that I know of, but I've done some pretty extensive looking around). But that's the Spigot API for ya. That way when someone hits a protected entity with a trident you can cancel it, and then use the code to remove the trident and give it back to the player, so no infinite bounce. Btw this code should work in theory for all Projectiles, not just tridents.
```
	private void returnTrident(Trident t, Player p) {
		try {
			//get the nms item stack for this trident.
			Object entityThrownTrident = t.getClass().getMethod("getHandle").invoke(t);
			Method itemStackMethod = entityThrownTrident.getClass().getDeclaredMethod("getItemStack");
			itemStackMethod.setAccessible(true);
			Object nmsItemStack = itemStackMethod.invoke(entityThrownTrident);
			//now, get the Bukkit itemstack.
			String bukkitVersion = Bukkit.getServer().getClass().getName().split("\\.")[3];
			Class<?> craftItemStackClass = Class.forName("org.bukkit.craftbukkit." + bukkitVersion + ".inventory.CraftItemStack");
			ItemStack tridentItemStack = (ItemStack) craftItemStackClass.getMethod("asBukkitCopy", nmsItemStack.getClass()).invoke(craftItemStackClass, nmsItemStack);
			//remove trident entity and give the itemstack back to the player.
			t.remove();
			p.getInventory().addItem(tridentItemStack);
		}
		catch(Exception e) {
			e.printStackTrace();
		}
	}
```

**Comment by RoboMWM** [comment]
Thanks! Probably best to be in an addon for any reflection/NMS stuff since the project thus far has solely stuck to the Bukkit API though.

What would be ideal is making it passthrough animals after the first bounce so it still hits a block to be picked up (and is the behavior of tridents anyways, in contrast to arrows which are consumed).

**Comment by NullCase** [comment]
tested this in the latest release.

tridents bounce and land when thrown at pets (parrots for example) but still vanish when thrown at other protected mobs (sheep, cows, skeleton horses).

**Comment by NullCase** [comment]
this appears to be solved in the latest release.
