### ISSUE TITLE
Feature Request/AddOn based on playtimes

### ISSUE THREAD

**Issue by JaguarJo** [GriefPrevention/GriefPrevention#331]
Sorry if this is in the wrong place, but the GP page on Spigot said to post feature requests here, so... here we go.

I'm wondering if we could hook into each player's playtime and run a console command at configured benchmarks. I'm not a developer so if this just isn't feasible, just tell me that and I won't get hurt feelings. I admire the work you guys do on this stuff.

### Steps/models to reproduce:
So basically it would work like this:

We've already got players accruing claimblocks with playtime. I'm hoping we can add a hook, config section, something, to that playtime that will run console commands at configurable intervals. For instance after 3 hrs playtime, run command /give {player} diamond 1. After 24 hrs playtime, run command /AdjustBonusClaimBlocks 100, /say "You've just earned 100 bonus claimblocks!". Etc.

I hope to use it as a ranking system (running a pex group set command), but it could also just be an automated reward system. Yes, I know ranking plugins exist that can work with playtime, but they all seem to have more bloat than we need and since 1.12 we haven't been able to find one that even works right. And yes, timed reward plugins also already exist, but they all seem to require player interaction to get the reward and we can't use that. We don't need fancy GUIs or sign interactions. I just want a fully automated setup and with GriefPrevention already logging playtime, it seems logical to just tap into that.  Maybe it's more complicated than I think it is, idk.  If it makes more sense to make this as an add-on rather than a part of GP's main config, maybe call it GP Rewards? Seems catchy enough for other people to use it a lot.

And if this already exists somewhere, please point me in the right direction. So far everything we've tried adding to the server is broken or extremely bloated and prone to conflicts. Thanks for your time.

**Comment by TomLewis** [comment]
Use Autorank https://www.spigotmc.org/resources/autorank.3239/

**Comment by RoboMWM** [comment]
Yea, there's many plugins out there that can run commands on playtime and etc.

**Comment by JaguarJo** [comment]
Autorank is what we used before 1.12. It stopped working and was becoming bloated with every update. Thanks anyhow, I'll keep looking. Edit: Seems Autorank was just updated this week and it works with our server again. Sorry to bother y'all.
