### ISSUE TITLE
[Solved!] Compile OR Download?

### ISSUE THREAD

**Issue by LeeAutore** [GriefPrevention/GriefPrevention#338]
I'm a plugin developer, and am familiar with building in Eclipse, but struggling to get GriefPrevention loaded into Eclipse, or compiled some other way.  All of the downloads appear to be dated in December, and I'd like the changes that you talented people have been working on.  ;)

If I'm missing something, where I can download a compiled version, let me know... otherwise, if anyone has some "quick and dirty" instructions for compiling (Eclipse or Command Prompt on Ubuntu Linux or MacBook)... I'd certainly appreciate the help!

**Comment by bigpresh** [comment]
It's a Maven project, so with Maven installed you should be able to say, off the top of my head, `mvn package`.

**Comment by RoboMWM** [comment]
That or find a way to import as a maven project. I've briefly used eclipse and never with maven, so I don't know what to do there, but I know IntelliJ can.

**Comment by LeeAutore** [comment]
Thanks to both of you!  I didn't figure out how to import using Eclipse, but once I knew to build using Maven, I was all set!  Thanks!
