### ISSUE TITLE
[1.13] Right clicking on stripped logs (or other 1.13 blocks) with a stick returns "That's too far away" when in range.

### ISSUE THREAD

**Issue by gnubufferoverflows** [GriefPrevention/GriefPrevention#339]
### What behaviour is observed:
When you right click on a stripped log with a stick to see if that block is claimed, you see "That's too far away", regardless of how close you are to said stripped log. I've also tested this with sea grass and you get the same issue, so I assume this bug is with all 1.13 blocks.
### What behaviour is expected:
When you right click on a stripped log, it tells you if that block is claimed or not, as long as you are in range of said block.
### Steps/models to reproduce:
1. Place down some stripped logs.
2. Right click on them with a stick
3. You should see "That's too far away" regardless of range.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
[15:32:00 INFO]: This server is running CraftBukkit version git-Spigot-69774b3-8592585 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[15:32:00 INFO]: Checking version, please wait...
[15:32:00 INFO]: You are 22 version(s) behind
>version GriefPrevention
[15:32:14 INFO]: GriefPrevention version 16.8

### Stack trace/error
N/A

### GriefPrevention config.yml (if applicable)

N/A

### Plugin list (if applicable):
GriefPrevention
PopulationDensity

**Comment by RoboMWM** [comment]
Hmm, my guess is that 1.12 and earlier-compiled plugins will return a null block/material when a 1.13 block is the target block.

**Comment by RoboMWM** [comment]
Should be fixed in https://github.com/TechFortress/GriefPrevention/releases/tag/16.9.alpha, close this issue if that's the case.

**Comment by NullCase** [comment]
It looks fixed, however there are some framerate issues. Kind of spamming right click to display the claim hits FPS much harder than in 1.12.2

**Comment by RoboMWM** [comment]
FPS issue being tracked in #349
