### ISSUE TITLE
1.13

### ISSUE THREAD

**Issue by Yukylyu** [GriefPrevention/GriefPrevention#342]
Hi I have this error in 1.13  
When a player wants to make a claim

https://pastebin.com/2PbVcW5d

**Comment by RoboMWM** [comment]
Duplicate of #319

**Comment by RoboMWM** [comment]
Stupid mobile site can't delete but I guessed and that's not the correct issue this is a duplicate of. If someone can link the correct one that'd be appreciated.

**Comment by Jikoo** [comment]
#329 and #332

**Comment by RoboMWM** [comment]
Duplicate of #329

Thanks Jikoo
