### ISSUE TITLE
Cannot delete claims

### ISSUE THREAD

**Issue by lukastrkan** [GriefPrevention/GriefPrevention#345]
Hi, I am unable to delete mine or other players claims by running /deleteallclaims <nickname>. Console always return that player has no claims.

MC version: 1.12.2 (Automaton modpack)
Forge version: 14.23.4.2705
Sponge version: 1.12.2-2705-7.1.0-BETA-3361
GriefPrevention version: 1.12.2-4.3.0.646

### Plugin list:
![image](https://user-images.githubusercontent.com/19746629/43699179-023110e0-994e-11e8-9e2b-0a5fea0aa504.png)

Thanks

**Comment by Jikoo** [comment]
This is GP for Bukkit, not Sponge.

**Comment by gnubufferoverflows** [comment]
Yeah, the Spigot version is quite a bit different from the Sponge version.

**Comment by gnubufferoverflows** [comment]
Sponge version is here: https://github.com/MinecraftPortCentral/GriefPrevention

**Comment by TomLewis** [comment]
Wow that version has 

- WECUI support
- A superior claim info system https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Claiminfo
- proper debugging https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Debugging
- Town claims https://github.com/MinecraftPortCentral/GriefPrevention/wiki/Claim-Types

We haven't had any updates/new features to the Spigot version in, well years :(

**Comment by RoboMWM** [comment]
And IMO, a whole ton of other not-so-simple features. It's basically not GP in code, design, or feature set.
