### ISSUE TITLE
Claim visualizations lag the 1.13 client

### ISSUE THREAD

**Issue by NullCase** [GriefPrevention/GriefPrevention#349]
### What behaviour is observed:
Crashed game when searching for local claims with shift+click (with stick).
### What behaviour is expected:
No game crash.

### Steps/models to reproduce:
Make lots of claims, shift + click facing them in different directions

### Spigot/Craftbukkit/Paper and GriefPrevention version:
git-Paper-105 (MC: 1.13)

### Stack trace/error

The game crashed whilst rendering block entity
The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: Cannot get property blv{name=facing, clazz=class ep, values=[north, south, west, east]} as it does not exist in Block{minecraft:glowstone}

**Comment by RoboMWM** [comment]
Idk how `Player#sendBlockChange` differs in 1.13, but see if this build makes any difference: https://github.com/TechFortress/GriefPrevention/releases/tag/16.9.alpha

**Comment by NullCase** [comment]
It makes a difference. The game isn't crashing using the same method.

So i shift+click and ~100 land claims come up. Now instead of crashing the framerate drops to ~0 for a second.

And then when I single click a claim frames drop again but only when updating all those land claims to restore the previous blocks (grass, planks, stone, logs, whatever... instead of the gold blocks & glowstone)

**Comment by RoboMWM** [comment]
Sounds like a (new?) client issue, unless someone can point out what GP is doing wrong in `Visualization`.

**Comment by RoboMWM** [comment]
Took a quick look at Visualization, don't see anything out of the ordinary so... not really sure where to start diagnosing this issue. Maybe it only happens with some blocks? Not sure, especially since I know next to nothing about the client.

**Comment by RoboMWM** [comment]
Yea, all I can see is a straight conversion to 1.13. Only difference here is instead of receiving a Material enum and data value, it instead receives a BlockData, which I'd presume would have similar information. So would be best to see if you can test other cases (the other visualization types) and whether size, ability to actually see it (i.e. underground), etc., affect the lag or not.

**Comment by NullCase** [comment]
maybe a block name issue? just crashed today while visualizing claims in the nether.

The game crashed whilst rendering block entity
The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: Cannot get property bmd{name=facing, clazz=class eq, values=[north, south, west, east]} as it does not exist in Block{minecraft:iron_block}

**Comment by RoboMWM** [comment]
Thing is if it's a client issue then there isn't much I can do. Try seeing if others are crashing - would expect more reports if this were not an isolated case.

**Comment by NullCase** [comment]
Other players are reporting the same crash. It seems like this problem is easily reproducible in The Nether by creating subclaims and clicking toward the 'iron block' which appears when visualizing the claim.

What's interesting is that the old crash which reported an issue with "glowstone" no longer reports any issue with glowstone. After your fix the glowstone problem went away. Now it's always iron_block.

I don't know, as you say it seems like a console thing. Still, here's the full crash report. I included two.

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 10/09/18 08:53
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property bmd{name=facing, clazz=class eq, values=[north, south, west, east]} as it does not exist in Block{minecraft:iron_block}
	at bkz.c(SourceFile:95)
	at cwb.a(SourceFile:71)
	at cvz.a(SourceFile:148)
	at cvz.a(SourceFile:128)
	at cud.a(SourceFile:693)
	at ctx.b(SourceFile:966)
	at ctx.a(SourceFile:875)
	at ctx.a(SourceFile:749)
	at cfs.c(SourceFile:850)
	at cfs.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bkz.c(SourceFile:95)
	at cwb.a(SourceFile:71)

-- Block Entity Details --
Details:
	Name: minecraft:chest // bjk
	Block: Block{minecraft:iron_block}
	Block location: World: (-3,112,3), Chunk: (at 13,7,3 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Block: Block{minecraft:iron_block}
	Block location: World: (-3,112,3), Chunk: (at 13,7,3 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at cvz.a(SourceFile:148)
	at cvz.a(SourceFile:128)
	at cud.a(SourceFile:693)
	at ctx.b(SourceFile:966)
	at ctx.a(SourceFile:875)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [cti['NullCase'/1330, l='MpServer', x=40.85, y=111.00, z=-7.80]]
	Chunk stats: MultiplayerChunkCache: 195, 195
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (49,67,1), Chunk: (at 1,4,1 in 3,0; contains blocks 48,0,0 to 63,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 78606 game time, 17166606 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 22 total; [anh['Zombie Pigman'/3456, l='MpServer', x=45.50, y=78.00, z=10.50], anh['Zombie Pigman'/3457, l='MpServer', x=39.66, y=40.00, z=39.68], anh['Zombie Pigman'/3459, l='MpServer', x=56.50, y=37.00, z=-47.50], anh['Zombie Pigman'/3462, l='MpServer', x=75.50, y=60.88, z=-35.50], anh['Zombie Pigman'/3463, l='MpServer', x=74.50, y=97.00, z=5.50], anh['Zombie Pigman'/3464, l='MpServer', x=66.50, y=86.00, z=29.50], apk['Minecart with Chest'/3421, l='MpServer', x=-11.49, y=115.06, z=-20.50], apk['Minecart with Chest'/3422, l='MpServer', x=-11.49, y=116.06, z=-19.50], anh['Zombie Pigman'/3424, l='MpServer', x=4.50, y=64.88, z=-33.50], api['Boat'/3425, l='MpServer', x=3.38, y=113.00, z=-42.91], apj['Minecart'/3435, l='MpServer', x=3.49, y=111.00, z=15.51], aoa['Fritzl'/3436, l='MpServer', x=3.49, y=111.00, z=15.51], cti['NullCase'/1330, l='MpServer', x=40.85, y=111.00, z=-7.80], anh['Zombie Pigman'/3446, l='MpServer', x=31.50, y=32.00, z=-29.50], anh['Zombie Pigman'/3447, l='MpServer', x=29.47, y=32.00, z=-23.71], anh['Zombie Pigman'/3449, l='MpServer', x=29.74, y=90.17, z=-9.60], anh['Zombie Pigman'/3450, l='MpServer', x=19.50, y=112.00, z=-24.23], anh['Zombie Pigman'/3451, l='MpServer', x=26.50, y=77.00, z=9.78], anh['Zombie Pigman'/3452, l='MpServer', x=28.50, y=78.00, z=37.50], anh['Zombie Pigman'/3453, l='MpServer', x=32.50, y=82.00, z=-24.50], anh['Zombie Pigman'/3454, l='MpServer', x=32.50, y=82.00, z=-20.50], anh['Zombie Pigman'/3455, l='MpServer', x=37.30, y=82.00, z=-33.20]]
	Retry entities: 0 total; []
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at crf.a(SourceFile:418)
	at cfs.b(SourceFile:1815)
	at cfs.a(SourceFile:403)
	at net.minecraft.client.main.Main.main(SourceFile:144)

-- System Details --
Details:
	Minecraft Version: 1.13.1
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 197202896 bytes (188 MB) / 523501568 bytes (499 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	Launched Version: 1.13.1
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 397.93, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz





---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 10/09/18 09:00
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property bmd{name=facing, clazz=class eq, values=[north, south, west, east]} as it does not exist in Block{minecraft:iron_block}
	at bkz.c(SourceFile:95)
	at cwb.a(SourceFile:71)
	at cvz.a(SourceFile:148)
	at cvz.a(SourceFile:128)
	at cud.a(SourceFile:693)
	at ctx.b(SourceFile:966)
	at ctx.a(SourceFile:875)
	at ctx.a(SourceFile:749)
	at cfs.c(SourceFile:850)
	at cfs.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bkz.c(SourceFile:95)
	at cwb.a(SourceFile:71)

-- Block Entity Details --
Details:
	Name: minecraft:ender_chest // bjs
	Block: Block{minecraft:iron_block}
	Block location: World: (-6,112,4), Chunk: (at 10,7,4 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Block: Block{minecraft:iron_block}
	Block location: World: (-6,112,4), Chunk: (at 10,7,4 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at cvz.a(SourceFile:148)
	at cvz.a(SourceFile:128)
	at cud.a(SourceFile:693)
	at ctx.b(SourceFile:966)
	at ctx.a(SourceFile:875)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [cti['NullCase'/5596, l='MpServer', x=5.70, y=112.50, z=-17.37]]
	Chunk stats: MultiplayerChunkCache: 224, 224
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (49,67,1), Chunk: (at 1,4,1 in 3,0; contains blocks 48,0,0 to 63,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 87227 game time, 17175227 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 46 total; [cti['NullCase'/5596, l='MpServer', x=5.70, y=112.50, z=-17.37], anh['Zombie Pigman'/5250, l='MpServer', x=-29.50, y=67.00, z=-34.50], anh['Zombie Pigman'/5251, l='MpServer', x=-17.39, y=118.00, z=18.70], anh['Zombie Pigman'/5636, l='MpServer', x=1.50, y=75.00, z=-44.50], ajy['Parrot'/5252, l='MpServer', x=-12.81, y=112.50, z=-28.33], apk['Minecart with Chest'/5253, l='MpServer', x=-11.49, y=115.06, z=-20.50], anh['Zombie Pigman'/5637, l='MpServer', x=-0.50, y=75.00, z=-46.50], apk['Minecart with Chest'/5254, l='MpServer', x=-11.49, y=116.06, z=-19.50], anh['Zombie Pigman'/5639, l='MpServer', x=6.50, y=75.00, z=-47.50], api['Boat'/5256, l='MpServer', x=3.38, y=113.00, z=-42.91], anh['Zombie Pigman'/5640, l='MpServer', x=51.50, y=76.00, z=18.50], anh['Zombie Pigman'/5641, l='MpServer', x=51.50, y=76.00, z=20.50], ama['Item Frame'/5257, l='MpServer', x=3.50, y=114.50, z=-1.97], anh['Zombie Pigman'/5642, l='MpServer', x=40.50, y=77.00, z=21.50], ama['Item Frame'/5258, l='MpServer', x=4.50, y=114.50, z=-1.97], anh['Zombie Pigman'/5643, l='MpServer', x=41.50, y=77.00, z=23.50], ama['Item Frame'/5259, l='MpServer', x=5.50, y=114.50, z=-1.97], anh['Zombie Pigman'/5644, l='MpServer', x=38.50, y=77.00, z=24.50], ama['Item Frame'/5260, l='MpServer', x=5.50, y=113.50, z=-1.97], anh['Zombie Pigman'/5645, l='MpServer', x=41.43, y=78.00, z=11.81], ama['Item Frame'/5261, l='MpServer', x=4.50, y=113.50, z=-1.97], anh['Zombie Pigman'/5646, l='MpServer', x=51.57, y=46.00, z=18.68], ama['Item Frame'/5262, l='MpServer', x=3.50, y=113.50, z=-1.97], anh['Zombie Pigman'/5647, l='MpServer', x=39.50, y=32.00, z=22.50], ama['Item Frame'/5263, l='MpServer', x=4.50, y=112.50, z=-1.97], anh['Zombie Pigman'/5519, l='MpServer', x=25.50, y=67.00, z=-57.50], ama['Item Frame'/5264, l='MpServer', x=3.50, y=112.50, z=-1.97], anh['Zombie Pigman'/5520, l='MpServer', x=25.50, y=67.00, z=-56.50], ama['Item Frame'/5265, l='MpServer', x=5.50, y=112.50, z=-1.97], apj['Minecart'/5266, l='MpServer', x=3.49, y=111.00, z=15.51], aoa['Fritzl'/5267, l='MpServer', x=3.49, y=111.00, z=15.51], anh['Zombie Pigman'/5277, l='MpServer', x=11.49, y=112.00, z=-26.85], anh['Zombie Pigman'/5280, l='MpServer', x=37.30, y=82.00, z=-33.20], anh['Zombie Pigman'/5281, l='MpServer', x=32.50, y=82.00, z=-24.50], anh['Zombie Pigman'/5282, l='MpServer', x=38.50, y=84.00, z=-14.83], anh['Zombie Pigman'/5297, l='MpServer', x=31.57, y=82.00, z=-24.93], anh['Zombie Pigman'/5298, l='MpServer', x=29.50, y=82.00, z=-18.50], anh['Zombie Pigman'/5304, l='MpServer', x=51.50, y=84.00, z=-23.50], anh['Zombie Pigman'/5305, l='MpServer', x=52.50, y=84.00, z=-24.50], anh['Zombie Pigman'/5611, l='MpServer', x=52.50, y=101.00, z=13.50], anh['Zombie Pigman'/5612, l='MpServer', x=26.50, y=36.00, z=20.50], anh['Zombie Pigman'/5613, l='MpServer', x=24.50, y=36.00, z=21.50], anh['Zombie Pigman'/5614, l='MpServer', x=40.50, y=79.00, z=9.50], anh['Zombie Pigman'/5615, l='MpServer', x=36.50, y=79.00, z=4.50], anh['Zombie Pigman'/5616, l='MpServer', x=37.50, y=79.00, z=4.50], anh['Zombie Pigman'/5247, l='MpServer', x=-21.50, y=70.00, z=-44.50]]
	Retry entities: 0 total; []
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at crf.a(SourceFile:418)
	at cfs.b(SourceFile:1815)
	at cfs.a(SourceFile:403)
	at net.minecraft.client.main.Main.main(SourceFile:144)

-- System Details --
Details:
	Minecraft Version: 1.13.1
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 196394184 bytes (187 MB) / 523501568 bytes (499 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	Launched Version: 1.13.1
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 397.93, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

**Comment by NullCase** [comment]
Optifine 1.13.1 pre-1 solves this problem.

**Comment by RoboMWM** [comment]
Using vanilla 1.13.1 client, I wasn't able to get my client to crash. Tried rightclicking the iron block and shift rightclicking. My framerate did drop a little (~47 fps, I lock to 60fps) which I'm guessing is because of the block updates the client is rendering, as well as the lighting of the glowstone(?) So this is either a problem with the client, a problem with the computer, or a problem that's exacerbated with a slow computer.

Claims with subclaims will send more block updates to the client than just a normal claim, shift+rightclick will also send more than just a single claim's outline.

**Comment by NullCase** [comment]
More block updates yep. And the guys were crashing with just a single right click, but NOBODY has crashed in this way while using Optifine. SO... seems like a client issue. 

I'm curious if the client crashes when rendering an "iron block" which somehow has data that the iron block should not have (like a sign with a bunch of writing on it).

In our subclaims there's a sign with writing that's a corner in a subclaim. Well that suddenly becomes an an iron block which has this sign-related data.... I'm wondering how the client deals with that. It looks like the bug report says "this ain't cool."

I doubt it's slow computers. Lots of my crowd are very invested in high end gear. But yeah, lots of possibilities before considering other info.

**Comment by RoboMWM** [comment]
> Well that suddenly becomes an an iron block which has this sign-related data....

Very good find. Will see if I can reproduce this.

**Comment by RoboMWM** [comment]
> In our subclaims there's a sign with writing that's a corner in a subclaim. Well that suddenly becomes an an iron block

Can you send a screenshot of this? Putting a sign where an iron block should be just causes the iron block to appear below the sign. Probably an output of `/version` as well.

**Comment by NullCase** [comment]
As for screenshots, I'll try tomorrow.

If it's not this, it might be worth creating a subclaim & then resizing the claim so the subclaim is 'outside it' and inside another claim.

Because claims will retain that info and it shows up on (for instance) dynmap.

Still, it's a client issue for sure. One of our players update to Optifine beta version early on. They've never experienced the lag.

**Comment by NullCase** [comment]
I don't know if it'll help with reproduction, but if you hop on our server and go to The Nether, then start right clicking your stick you'll probably crash.
