### ISSUE TITLE
Small request | Question.

### ISSUE THREAD

**Issue by Remski01** [GriefPrevention/GriefPrevention#35]
Is there an way to change the message for /plot delete and /plot clear?

Both commands have the same message. Is there an way to give both commands an different message?

This is because both commands do not do the same thing.

/plot clear remove everything in the claim.

/plot delete remove everything **and delete owner from the claim**.

**Comment by RoboMWM** [comment]
GriefPrevention does not have any `/plot` commands. Perhaps you meant to post on the PlotSquared issue tracker?
