### ISSUE TITLE
Can't Drop Items

### ISSUE THREAD

**Issue by Traylon** [GriefPrevention/GriefPrevention#350]
### What behaviour is observed: Item not dropping
_What you saw_
### What behaviour is expected: Item dropping
_What you expected to see_
### Steps/models to reproduce:
_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_

### Spigot/Craftbukkit/Paper and GriefPrevention version: Using Spongeforge, latest GriefPrevention
___This can be found by running `/version` and `/version GriefPrevention` on your server.___

### Stack trace/error

```
Paste entire stack trace inside here (don't remove the backticks!)
If not applicable, paste server.log at gist.github.com and paste the link here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here (don't remove the backticks!)
```

### Plugin list (if applicable):
Nucleus
LuckPerms
Spongeforge

**Comment by Jikoo** [comment]
This is not GP for Sponge, you want the version maintained by MCPC.
