### ISSUE TITLE
[1.13] Fish mobs can be picked up in claimed areas.

### ISSUE THREAD

**Issue by gnubufferoverflows** [GriefPrevention/GriefPrevention#353]
### What behaviour is observed:
When you try to pick up a fish in a claimed area, permission to do should be denied unless you have containertrust or build trust.
### What behaviour is expected:
Picking up a fish mob doesn't remove water, but does remove the claimed mob.
### Steps/models to reproduce:
As an op, create an admin claim with a pool of water, and put some fish in said water. Now, deop yoursefl and grab a water bucket. Pickup the fish mob.

### Spigot/Craftbukkit/Paper and GriefPrevention version:

>version
[18:04:15 INFO]: This server is running CraftBukkit version git-Spigot-2b0e71c-15da706 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[18:04:15 INFO]: Checking version, please wait...
[18:04:16 INFO]: You are 2 version(s) behind
>version GriefPrevention
[18:04:21 INFO]: GriefPrevention version 16.9.alpha

### Plugin list (if applicable):
GriefPrevention
PopulationDensity

**Comment by Aerodog** [comment]
I second this motion. Save the fishies! You can definitely nab someone's fish.

Also: You can't pick up fish with an empty bucket and trying to use an empty bucket to collect water and a fish at the same time will make it appear to the client as though a fish had been collected, although it had not.

**Comment by RoboMWM** [comment]
Is there any event for this, or is it just ye ol PlayerInteractEvent?

**Comment by gnubufferoverflows** [comment]
I was able to make a monitor for this with PlayerInteractAtEntityEvent, and checking to see if PlayerInteractAtEntityEvent.getRightClicked is instance of Fish. The only issue is that it also fires when someone right clicks on a fish in any case, but you can use it cancel someone from picking up a fish. I think to fix this you just check to see if the item in hand is a water bucket, but not sure if that will catch all cases.

**Comment by RoboMWM** [comment]
If you can, use the EventDebug plugin to see what events fire. I don't have a 1.13 server for testing quite yet.

**Comment by gnubufferoverflows** [comment]
I tried the above on a 1.13 test server, and it seems to have worked.

**Comment by RoboMWM** [comment]
Have you seen if any event other than the PlayerInteractEvent fires with EventDebug?

**Comment by gnubufferoverflows** [comment]
No, these are the two events that fired:
``[22:24:18 INFO]: [EventDebug] Event fired: PlayerInteractAtEntityEvent
getClickedPosition: 0.1118433028459549,0.2915952205657959,-0.25
isCancelled: false
getHand: HAND
getRightClicked: CraftTropicalFish
getPlayer: Mrawesomecookie
[22:24:18 INFO]: [EventDebug] Event fired: PlayerInteractEntityEvent
isCancelled: false
getHand: HAND
getRightClicked: CraftTropicalFish
getPlayer: Mrawesomecookie
``

**Comment by RoboMWM** [comment]
This only applies to `Fish`, not any `WaterMob`, correct?

**Comment by gnubufferoverflows** [comment]
@RoboMWM only fish can be bucketed up, so yes.
