### ISSUE TITLE
[1.13] TnT can be ignited without building permission (but no explosive damage is done, so in most cases this bug isn't game-breaking)

### ISSUE THREAD

**Issue by gnubufferoverflows** [GriefPrevention/GriefPrevention#356]
### What behaviour is observed:
TNT can be ignited using flint and steel, or a flame arrow (I haven't tested other methods) in an area where the player does not have permission to build. Note that the TnT doesn't actually do explosion damage unless /claimexplosions is turned on.
### What behaviour is expected:
When someone tries to ignite TnT in a claimed area, that event is cancelled unless the player has build trust.
### Steps/models to reproduce:
Make an admin claim with TnT, then ignite it as a non-op.

### Spigot/Craftbukkit/Paper and GriefPrevention version:

[03:24:06 INFO]: GriefPrevention version 16.9.alpha
>version
[03:24:07 INFO]: This server is running CraftBukkit version git-Spigot-2b0e71c-15da706 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[03:24:07 INFO]: Checking version, please wait...
[03:24:08 INFO]: You are 10 version(s) behind

**Comment by RoboMWM** [comment]
Huh, apparently this is also possible in 16.8. Not sure if this was ever prevented at all. That being said, animals and other entities inside the claim are protected as well.

**Comment by gnubufferoverflows** [comment]
Yeah, the issue is that some people use TnT as a decoration material in their builds, which a griefer can ignite and remove.

**Comment by Ridog** [comment]
This issue is still present in the latest version of grief prevention when using a flame bow and I just encountered it on my PaperMC 1.16.1 server.
