### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by HYDR0DADDI** [GriefPrevention/GriefPrevention#366]
Hey, love the plugin. It's great. However, I think it would be better if I could choose what is protected by the plugin. For example, maybe I want blocks to be protected but I want people to be able to open doors and chests without being /trusted

**Comment by Jikoo** [comment]
`/containertrust public`
Unless you're talking about some sort of server-wide thing, which mostly defeats the point of GP imo.

**Comment by RoboMWM** [comment]
See Jikoo's comment. You can also grant `/accesstrust public` for just access to doors.

**Comment by HYDR0DADDI** [comment]
I was thinking a server side thing. I want players to have an extra layer of carefulness. They would have to keep doors closed so noone could take their stuff.

**Comment by RoboMWM** [comment]
For chests, set `PreventTheft` or similar in the config to false. Wooden doors can be opened by anyone by default.
