### ISSUE TITLE
Jumping on turtle eggs spams chat

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#373]
### What behaviour is observed:
Jumping on turtle eggs spams chat with "You don't have XXX's permission to build here"
https://imgur.com/A3U3ix0
### What behaviour is expected:
No output, like jumping on crops.
### Steps/models to reproduce:
Claim area with turtle egg in it. Have another user jump on it.
### Spigot/Craftbukkit/Paper and GriefPrevention version:
Paper version: git-Paper-a3677899 (Aikar's beta async version for 1.13.1)
GP version: 16.9

**Comment by RoboMWM** [comment]
I really wish spigot fired an event like they do for crops for this action... but nope, it's just a PlayerInteractEvent.

**Comment by Jikoo** [comment]
I kinda wish GP used hotbar messages or had a cooldown system on warnings. I get relatively large percentage of my (admittedly small) playerbase making complaints about spam when holding shovels and the like, would be nice to have a baked-in solution for all of that.

**Comment by RoboMWM** [comment]
That's the idea behind DeniedMessageEvent (will be something akin to GPSendMessageEvent in v20); you can use that event to send messages your way.
