### ISSUE TITLE
[request] [for pay] /claimexpire delay <days>

### ISSUE THREAD

**Issue by NullCase** [GriefPrevention/GriefPrevention#374]
Hi RoboMWM (or anyone interested to earn some money).

Now that 16.9 is out, it seems like you may be ready to make some $$$ for coding.

### I'd like to pay you to create a single command feature/add-on to GriefPrevention.

Here is what I have in mind. (example)

- A player logs off. Lets say their land claims expire in 60 days (listed in the config).
- I type the new command: **/claimexpire delay 30**
- Now, their land claims expire in 60 days _*after*_ 30 days.
- The player logs in one day later and logs off.
- Now, their land claims expire in 60 days _*after*_ 29 days.
- The player logs in 29 days later and logs off.
- Now their land claims expire in 60 days (as _normal_).

Suppose instead at day 15 I type **/claimexpire delay 30** (again)

- Now, their land claims expire in 60 days _*after*_ 45 days.

My goal is to be able to delay the claim expire countdown process by a specified # of days. And to specify the # of days using a single command. And for successive uses of the command to add days.

I can pay you for your time to build this add-on/ feature for GriefPrevention.

**Comment by NullCase** [comment]
It seems like theres one more bit: a check for players.

Something like **/claimexpire check**

And this would say "your claims will expire after X days of inactivity" where X = total delay days + config setting for perm claims (in this case 60 days).

So if I do /claimexpire delay 30 _AND_ config for perm claims is 60 days
_and then_ i do /claimexpire check
_the result_ "Your Land Claims will expire after 90 days of inactivity."

But as in the past, your suggestions & recommendations are really valuable.

**Comment by RoboMWM** [comment]
Implemented here: https://www.spigotmc.org/threads/requests-for-robomwm.293977/page-11#post-3163486
