### ISSUE TITLE
Issue With Claiming

### ISSUE THREAD

**Issue by codster6789** [GriefPrevention/GriefPrevention#375]
### What behaviour is observed: Apon looking to claim an area, the first position is set however apon setting the second it disallows you to do so. I thought it was an McMMO issue as it's not compatible possibly but, found even /claim <radius> didn't work with the plugin.
_What you saw_
### What behaviour is expected:
_What you expected to see_
### Steps/models to reproduce:
_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_

### Spigot/Craftbukkit/Paper and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___

### Stack trace/error

```
Paste entire stack trace inside here (don't remove the backticks!)
If not applicable, paste server.log at gist.github.com and paste the link here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here (don't remove the backticks!)
```

**Comment by RoboMWM** [comment]
A+ report.

**Comment by codster6789** [comment]
Apologies for such invalid report, iPad had been acting up whilst using the site, accidentally submitted the report.
