### ISSUE TITLE
[Feature][For Pay] VillagerTradingRequiresContainerTrust: true/false

### ISSUE THREAD

**Issue by NullCase** [GriefPrevention/GriefPrevention#378]
New option where players can use /containertrust to permit trading with villagers (without permitting them to be killed).

The existing option _VillagerTradingRequiresPermission: true/false._ means claim owners can extend trade permissions but only while extending full /trust, which is a big risk.

My goal is to pay you for a feature which solves that problem. I want a feature where a player can do /containertrust and players are permitted to trade with but NOT kill the villager.

Accidents happen after all.

**Comment by tsiedsma** [comment]
I’d get in on this too if you make a new command /villagertrust that only allows villager trades and still respects the container trust setting

**Comment by NullCase** [comment]
OK, /villagertrust

That sounds good too. It would resolve some confusion about which one to use.

**Comment by tsiedsma** [comment]
Happy to split the bill on this one!

**Comment by NullCase** [comment]
split the bill?

**Comment by tsiedsma** [comment]
Pay half the cost of this for pay feature request!

**Comment by NullCase** [comment]
i don't know, it seems like a whole new type of trust might add a lot to the cost.

**Comment by tsiedsma** [comment]
If containertrust is just modified to protect the life of a villager that’s fine, but would love to know the cost difference for adding a new trust level since that will make the most sense.

I’m not afraid to pay a dev for their time adding things outside the scope of the original project.

**Comment by NullCase** [comment]
That's a very generous offer @lhdev. It really is.

/villagertrust is a very nice way to implement this proposal.

What if we wait to hear about costs from @RoboMWM or perhaps someone else who decides to take on this project?

**Comment by RoboMWM** [comment]
Hmm, I just guessed that this was the case, I guess not. Because trade offers change the state of a villager just like any other inventory transaction, this should be included in /containertrust, not build trust.

If you want a separate /villagertrust you can make that request on my [requests thread.](https://www.spigotmc.org/threads/requests-for-robomwm.293977/)

> but would love to know the cost difference for adding a new trust level since that will make the most sense.

Other than new command, need to store this trust level, in a manner similar to /permissiontrust - would need to alter database structure if doing directly in GP or otherwise. Since this is more of a flag, IMO doesn't fit within GP itself but addons can do it.

**Comment by NullCase** [comment]
It sounds like /containertrust for villager trading is not only easier than /villagertrust but it's also the way it was intended to work.

do i have that right?

**Comment by RoboMWM** [comment]
If I'm reading the code correctly, this is the intended behavior.


```java
//if the entity is an animal, apply container rules
        if((instance.config_claims_preventTheft && (entity instanceof Animals || entity instanceof Fish)) || (entity.getType() == EntityType.VILLAGER && instance.config_claims_villagerTradingRequiresTrust))
        {
            //if the entity is in a claim
            Claim claim = this.dataStore.getClaimAt(entity.getLocation(), false, null);
            if(claim != null)
            {
                if(claim.allowContainers(player) != null)
```

**Comment by RoboMWM** [comment]
Can you test if /containertrust is sufficient? It should be...

**Comment by NullCase** [comment]
it works exactly as described. I don't know how I messed that up.

Don't worry, I have a long list of development targets. On to the next one.
