### ISSUE TITLE
[Developer Help] Any ideas why Chat not cancelled when player hasn't move?

### ISSUE THREAD

**Issue by masagameplay** [GriefPrevention/GriefPrevention#379]
When player joins the server, chat should be cancelled before the player has moved. I've using my own BungeeCord network plugins (MaSuite) and I've tried to cancel sending messages from Spigot to Bungee with Messaging Channels but it won't cancel message sending if [GriefPrevention cancels the event](https://github.com/BigScary/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java).  
(https://i.imgur.com/rH6I53q.png)
This works with WorldGuard send-chat flag but not with GriefPrevention

```
@EventHandler(priority = EventPriority.HIGHEST, ignoreCancelled = true)
    public void onMessage(AsyncPlayerChatEvent e) {
        e.setCancelled(true);
        Player p = e.getPlayer();
        ByteArrayDataOutput output = ByteStreams.newDataOutput();
        output.writeUTF("MaSuiteChat");
        output.writeUTF(p.getName());
        output.writeUTF(e.getMessage());
        p.sendPluginMessage(this, "BungeeCord", output.toByteArray());
    }
```

**Comment by RoboMWM** [comment]
Listen at lower priority than GP... It listens at lowest so also make sure you loadbefore it

**Comment by RoboMWM** [comment]
Or don't ignore if canceled.
