### ISSUE TITLE
[Request] Disable more then only the horse protection.

### ISSUE THREAD

**Issue by Remski01** [GriefPrevention/GriefPrevention#381]
Hello.

Could you add that we can also disable that Claims protect Llama's and donkey's? Currently it only can disable the horse protection with ProtectHorses: to false. 

I ask this because we have an seprated plugin for Horse's, Llama's and Donkey's as it have more options. However, currently it conflict with GP as it also tries to protect Llama's and Donkey's.

Thanks

**Comment by RoboMWM** [comment]
I'm 72% sure there's a duplicate of this floating in here somewhere

**Comment by Remski01** [comment]
Maybe you mean https://github.com/TechFortress/GriefPrevention/issues/292 but he talks about a list. However i talk about 2 specific mobs. As the other mobs should be protected by GP.

**Comment by RoboMWM** [comment]
Closed by https://github.com/TechFortress/GriefPrevention/commit/3e1e058001feb4a3868f0b554928db237b5fe5de
