### ISSUE TITLE
make claimmodifiedevent cancellable

### ISSUE THREAD

**Issue by hafarooki** [GriefPrevention/GriefPrevention#383]
most of the time you probably want it to cancel it

**Comment by 112RG** [comment]
Is this still wanted?

**Comment by hafarooki** [comment]
people using that event are most likely still looking to cancel it

**Comment by 112RG** [comment]
What are you looking to do when canceling it? The event is really just a notification that a claim has changed.

**Comment by hafarooki** [comment]
.... stop people from claiming/expanding their claim?

**Comment by Jikoo** [comment]
Closed by #942
