### ISSUE TITLE
I cant buy claimblocks, when i use /buyclaimblocks it says that you have reached at you claim block limit you cant purchase more...

### ISSUE THREAD

**Issue by felipeleite5w** [GriefPrevention/GriefPrevention#385]
### What happened:
_What you saw_
error
### What you expected:
_What you expected to see_
claimblocks
### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1. /buyclaimblocks
2. Step 2.
3. ???
4. Profit!

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: Thermos 1.7.10-1614.58
Paste of `/version GriefPrevention`: CB 1.7.9-R0.2

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

If not applicable, paste the server.log at gist.github.com and paste the link here.
```

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks.

```

**Comment by RoboMWM** [comment]
You're using an addon that restricts claim block purchasing. Base GP doesn't stop this. Include plugin list please.

**Comment by RoboMWM** [comment]
Oh, I see you're using an ancient version of spigot (and probably an ancient version of GP too)

**Comment by felipeleite5w** [comment]
i do not use spigot, I use Thermos

I dont use any addon that do this

**Comment by RoboMWM** [comment]
I can't speak for older versions of GP, sorry. I do know that recent versions (at least the last couple years) "buy" bonus claimblocks, which are unrestricted.

**Comment by felipeleite5w** [comment]
i know, it happens just with one player!
