### ISSUE TITLE
Flowerpot griefing

### ISSUE THREAD

**Issue by x1p** [GriefPrevention/GriefPrevention#386]
It is possible to steal flowers out of the pot inside claims.

Griefprevention 16.11.3
WorldGuard v7.0.0-SNAPSHOT;1749-a6261b9

**Comment by x1p** [comment]
Exists too in GP 16.11.4

**Comment by RoboMWM** [comment]
This is a client glitch as I'm sure I already fixed this a while ago. If you relog into the server you'll find that the flower pot hasn't been griefed.

Unless of course spigot 1.13 changed that stuff, which they may have. So I'm going to need all the ticket info that you deleted.

**Comment by x1p** [comment]
No it's not a client glitch. The item is indeed in the inventory and is droppable.

**Comment by x1p** [comment]
https://www.youtube.com/watch?v=AFinGEj4M1Y

**Comment by mirolm** [comment]
It is indeed possible to do that. I just tried it on my server with latest GP.

@RoboMWM Note that it is impossible to break the pot, but possible to pickup the sappling / flower from the pot. You cannot return it back tho, because it says you need administrator / claim owner rights. 

It does not prevent you to get the item from the pot, but blocks you from returning it back. Maybe a check on pickup from pot is missing.

```
This server is running CraftBukkit version git-Spigot-f6a273b-7a2f486 (MC: 1.13.1)
[GriefPrevention] Loading GriefPrevention v16.11.4.dev
```

**Comment by x1p** [comment]
thank you for confirming

**Comment by RoboMWM** [comment]
Ok, thank you mirolm for providing reproduction and details. x1p you can't just delete the issue template, it exists for a reason.

**Comment by 112RG** [comment]
The bug seems to be happening because when right-clicking the flower in the pot, the material isn't FLOWER_POT. The material is now POTTED_{wood type}_SAPPLING

**Comment by RoboMWM** [comment]
Thanks. I'm guessing a Tag could be used here? Or better yet an event (but I doubt there is such)?

**Comment by 112RG** [comment]
I have a PR adding all the materials. Is there a better way todo it than that?

**Comment by RoboMWM** [comment]
Probably using this tag. https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Tag.html#FLOWER_POTS
