### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by bacondedo** [GriefPrevention/GriefPrevention#39]
Hi I've heard great things about your plugin and want to get it for my server but idk the download process i down loaded it and i opened it and i clicked on folder and folder and folder idk if i did something wrong I'm on a mac desktop to so ya pls email me back with the steps from the beginning if possible thank u:)

**Comment by RoboMWM** [comment]
it's a jar file, it's no different than any other plugin...

**Comment by RoboMWM** [comment]
Download the jar from here... https://github.com/TechFortress/GriefPrevention/releases/tag/15.3
