### ISSUE TITLE
Seperate Villagers From Chests

### ISSUE THREAD

**Issue by Jerethkhan** [GriefPrevention/GriefPrevention#391]
Container access and villager trading should be separated into different permissions. Villagers are not containers and players needing to give permissions to trading mechanics to the public should not have to open chest access as well.

**Comment by RoboMWM** [comment]
Config, `VillagerTradingRequiresPermission`

**Comment by Jerethkhan** [comment]
That still makes it an all or nothing solution, but I suppose it's good enough for now.

**Comment by bigpresh** [comment]
I can definitely see that it would be nice for trading with villagers to still require permission, but to be able to grant that permission seperately to container access.  I wonder if another trust level and command (`/tradetrust` or whatever) would just add complexity & confusion for the majority of users, though.

**Comment by Jerethkhan** [comment]
It confused me to find out villagers were considered containers. Even if it was something wider than /tradetrust and went with /mobtrust and included killing passives, sheering/dying sheep, riding horses/pigs, trading, dressing llamas. etc that would add tons of new options and not really be confusing.

**Comment by RoboMWM** [comment]
Villagers are considered containers because it is possible to exhaust trades from a villager. I.e. they act as some sort of a "locked chest" of items so to speak, that you unlock with trades.
