### ISSUE TITLE
[Question] Data in files

### ISSUE THREAD

**Issue by glorying16** [GriefPrevention/GriefPrevention#393]
What information is stored into what files? Say if I were to want to keep the claim blocks a player has, but not the claims themselves. Are they stored in two locations that I could delete one and not the other?

**Comment by RoboMWM** [comment]
Yes. 
PlayerData for claim blocks
ClaimData for claims.

**Comment by glorying16** [comment]
For future reference, is there a way to purge the player data files after so long of inactivity? And if not is that a feature that could be added?

**Comment by RoboMWM** [comment]
In an addon, if you desire. 

PlayerData for inactive players aren't loaded after 90 days (now configurable).
