### ISSUE TITLE
can't unmute player, and other failures to disable spam filter

### ISSUE THREAD

**Issue by rcalderoni** [GriefPrevention/GriefPrevention#395]
I'd like to run GP without ANY spam filtering, no language filter, etc
I have a player that already was muted because of testing the disabling of this feature...

We have spam set to false, and even went as far as deleting all words from the banned words text file.
Still, he remains muted, tried doing /softmute on and off for him, no change. Also the softmute text file is EMPTY, so I wonder if there is some other mechanism that is muting him? As admin I can see his chats as (muted) but nobody else can see his chats.

I also noticed that with spam set to false it still was blocking words from the banned words file, is there not a way to disable ALL chat related filtering/spam features? I only want the in-game block protection feature, not any kind of chat filtering or censorship.

To me, if I disable spam then there should be no more spam controls, no muted people, etc.
We are going to have to attempt to redo all our claims and delete all plugin data to try and fix this.

**Comment by rcalderoni** [comment]
Actually think I may have found something to start with: https://github.com/TechFortress/GriefPrevention/blob/4a9d62c78f7b6e08850b67414830bd99688720a1/src/main/java/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java

I think this check happens regardless if SPAM is turned on or off, meaning the only true way to bypass is for me to give the spam permissions individually:

`//troll and excessive profanity filter
		else if(!player.hasPermission("griefprevention.spam") && this.bannedWordFinder.hasMatch(message))`

**Comment by RoboMWM** [comment]
If bannedwords is blank then it sounds like something else has him muted, or is being /ignored. Either way, you need to fill out the issue template that you deleted.

**Comment by rcalderoni** [comment]
Not sure what “issue template that you deleted” means.

**Comment by Jikoo** [comment]
>Not sure what “issue template that you deleted” means.

When you make an issue, there're 2 options presented, bug report and feature request. Bug report includes the text from [this template](https://raw.githubusercontent.com/TechFortress/GriefPrevention/master/.github/ISSUE_TEMPLATE/bug-report.md).

**Comment by rcalderoni** [comment]
ah maybe it’s a recent change with github because this is all I got when making a new issue: https://imgur.com/a/LuKYtzf

anyways I think I can bypass this for now by setting that spam permission for all users, but I could also make a PR so that it will bypass that filter/mute check when global spam filter is turned off, does it make sense that if spam is disabled then all filtering would also be disabled?

**Comment by RoboMWM** [comment]
> does it make sense that if spam is disabled then all filtering would also be disabled?

Yea that makes sense. 

Still curious for the /version and /version GriefPrevention and what steps to reproduce this issue, because I find it interesting that you cannot remove the /softmute

**Comment by rcalderoni** [comment]
Ok I made a few changes and a PR, it builds but needs review and a second pair of eyes before testing, you may find something wrong with it that I didn't consider, for example we may want to alert the admin that if they attempt to softmute when SPAM feature is disabled it won't work (which in my opinion should be a feature of SPAM only anyways, doesn't make sense to me that GP without SPAM just has a mute feature thrown in, especially considering there are other plugins that handle this and we don't want them to conflict).

https://github.com/TechFortress/GriefPrevention/pull/396

**Comment by RoboMWM** [comment]
This issue's purpose will be completed when the primary features are properly separated sometime during the updates to v20.
