### ISSUE TITLE
Sources don't compile, dependencies require authentication

### ISSUE THREAD

**Issue by klugemonkey** [GriefPrevention/GriefPrevention#397]
Compilation fails to download dependencies from https://repo.codemc.org/repository/maven-public due to authorization.

Should be able to compile sources without having to have an account to access dependencies.

16.11.4 sources.

**Comment by RoboMWM** [comment]
It didn't need authentication before... and I don't see anything in my log about it wanting authentication. Perhaps you have some SSL issues? Paste maven log.

**Comment by 112RG** [comment]
This error seems tobe just for you. Maybe post a build log if you would like help fixing.

**Comment by RoboMWM** [comment]
codemc is apparently a public maven repo for MC plugins, so yea, likely just you and SSL certs not working or something. Can't tell without a build log.
