### ISSUE TITLE
POM group is not consistent

### ISSUE THREAD

**Issue by klugemonkey** [GriefPrevention/GriefPrevention#398]
POM file has group as "me.ryanhamshire", should probably be "me.ryanhamshire.GriefPrevention" since main is "me.ryanhamshire.GriefPrevetion.GriefPrevention".

**Comment by RoboMWM** [comment]
I've seen many plugins like this? Afaik, the artifactId is the project name, which is what the last package name is. The main class is after that.

**Comment by 112RG** [comment]
I would close this as groupId should be "me.ryanhamshire" and artifactId should be "GriefPrevention" Main class doesn't matter the groupId is the folder it is in. Can be seen in AskyBlock pom.xml
