### ISSUE TITLE
SubClaims permission trouble

### ISSUE THREAD

**Issue by cindyker** [GriefPrevention/GriefPrevention#40]
### What behaviour is expected:
SubClaims should have separate permissions from the main claim.  Allowing players to be added to the subclaim that have no permissions for the main claim. 

### What behaviour is observed:
SubClaims now require the added player have permission on the main claim, in order to use the subclaim. 

### Steps/models to reproduce:
_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_

### Spigot/Craftbukkit/Paper and GriefPrevention version:
GP: 15.3
Spigot: 1.10.2

### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here
```

**Comment by RoboMWM** [comment]
Hmm, this wasn't the case before? I'm not sure when this changed, last I recall Big_Scary doing any subclaim changes was at least many months ago.

**Comment by cindyker** [comment]
According to my players... its different. I hadn't updated GP in a while. So its quite possible it changed in an update months and months ago.  :)

**Comment by RoboMWM** [comment]
Do they need the equivalent permission in the main claim (i.e., is /accesstrust on main claim not sufficient to obtain /trust access to their subclaim?)

I don't use subdivisions myself, so reproduction steps/a video might help speed up the process for me at least to determine what's going on and/or test with older versions, if I need to do so.

**Comment by RoboMWM** [comment]
Do you have any idea what GP version you updated from?

**Comment by RoboMWM** [comment]
Was the last version you used back in May? https://www.spigotmc.org/search/22712386/

**Comment by RoboMWM** [comment]
@cindyker was not able to reproduce. Could you provide steps to reproduce?

**Comment by matcracker** [comment]
In my server works perfectly, who is trusted in a subclaim, he isn't trusted in the main claim
