### ISSUE TITLE
Skript & GriefPrevention Hook

### ISSUE THREAD

**Issue by SaltyAimbOtter** [GriefPrevention/GriefPrevention#402]
### What happened:
Some startup errors
Console was completly spammed by "PlayerMoveEvent could not be passed"
Console was completly spammed by the "PlayerTeleportEvent could not be passed"
### What you expected:
No spam xD

### Steps to reproduce:
1. Download Skript 2.3-beta1 (version before also spams)
2. Download GriefPrevention
3. M O V E
4. RIP Console
### Server and GriefPrevention version:
This server is running CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
GriefPrevention version 16.11.4

### Stack trace/error or server log

``
https://gist.github.com/SaltyAimbOtter/3024872926cd2893f7cc3684cd59ca41
https://gist.github.com/SaltyAimbOtter/36f059db2f8d9838b0923efbfbee3a5e
https://gist.github.com/SaltyAimbOtter/39d7712c9df93d9a28c7f81dd9b56315
```

### GriefPrevention config.yml

```
There is no config.yml O.O
```

**Comment by 112RG** [comment]
Looks like this is an error on their side.
Maybe also not having a config file

**Comment by RoboMWM** [comment]
Looks like an issue with Skript's GP integration. They can comment here if they need to.

**Comment by ShaneBeee** [comment]
Looking at the error, it looks like the issue is running 16.11.4 on a Spigot 1.12.2 server.

**Comment by RoboMWM** [comment]
That could actually be the case - GP is probably disabled at this point or didn't enable properly, and thus any methods called on it will likely be null.
