### ISSUE TITLE
[request] WorldEdit selection to delete all claims inside the selection.

### ISSUE THREAD

**Issue by TomLewis** [GriefPrevention/GriefPrevention#412]
I have asked this many times before, so it may sound similar.

I want to be able to mass-cleanup claims that need deleting, without having to delete each one by bloody one, its the most tedious pain in the ass ever.

If there are 100 claims in an area that need removing and the same area regenerating, you have to manually find every single claim and do /deleteclaim on it, MY GOD this takes so long (5 years doing this) 

What would be SOOO much more efficient is being able to make a selection in WorldEdit and any claim inside of that gets removed with /deleteclaim**s**, threw an s on the end there for multiple claims, then i can just keep that selection selected and do a //regen for WE.

bam done.

**Comment by ArtNRG** [comment]
And it will be nice if will be the command to count how many claims are inside WE selection. It will help much while cleaning the wilderness to avoid accidental deletion of some claimed area.

**Comment by 112RG** [comment]
As posted on the RestoreNature issue. Something like this can be done. Not sure yet how intensive it will be to get all claims inside a region but will take a look. Would you want a single command to delete and regen? Like /claimcleanup which deletes all claims inside a WE selection and regens the area.

I guess its upto @RoboMWM. But I think this could be done with an addon to GP.

An example would be to just use the same logic that GP uses when checking canBuild() in WorldGuardWrapper

**Comment by ArtNRG** [comment]
Ok, it doesn't matter how it will be implemented if it will work. How about creating the complex GP addon for survival server with GP claims? I have a few ideas about it and seems @FrozenBeard will find them usefull too and will add his own ideas, of course. 
Where can we discuss all of this? Seems like GP issues isn't best place for discuss the separate addon.

**Comment by 112RG** [comment]
Not sure can either be IRC or a Discord server

**Comment by ArtNRG** [comment]
Discord is OK for me. Please send me DM or friend request: Art_NRG #4900

**Comment by ArtNRG** [comment]
@FrozenBeard please send me any message in discord too, I'll try to add you in the group chat.

**Comment by TomLewis** [comment]
Sounds awesome to me, Would definitely like the commands separate. @ArtNRG whats your discord username?

**Comment by ArtNRG** [comment]
@FrozenBeard Art_NRG #4900

**Comment by 112RG** [comment]
Made https://github.com/112madgamer/GriefPreventionUtilities

**Comment by TomLewis** [comment]
😁 yes!
