### ISSUE TITLE
Most recent commit for 1.12 servers?

### ISSUE THREAD

**Issue by RyanHecht** [GriefPrevention/GriefPrevention#414]
Just to confirm, is release 16.8 (commit 05497b7b6a2b693302c41a79c98ff60c3757837e) the most recent commit that we should be using with 1.12 servers?

Thanks again, this is an excellent plugin and I'm looking forward to hooking into it.

**Comment by RoboMWM** [comment]
Yes, 16.8 is for 1.12.2, and was what I was using until I finally transitioned to 1.13
