### ISSUE TITLE
Modify cooldown for Siege

### ISSUE THREAD

**Issue by CeIebrimbor** [GriefPrevention/GriefPrevention#415]
The cooldown for sieging a player is locked to 1 hour, which could be used in very annoying fashion if it becomes a waiting game.

I would like to be able to configure this, either with config option or Admin command that would set/save the new cooldown length.

**Comment by TomLewis** [comment]
I requested this years ago lol
Another siege issue https://github.com/TechFortress/GriefPrevention/issues/219

**Comment by RoboMWM** [comment]
Don't see how this is related to 219 which was a bug...?
