### ISSUE TITLE
Neutral mobs aren't able to be hit from claim owner or machines

### ISSUE THREAD

**Issue by ehmitchell3** [GriefPrevention/GriefPrevention#416]
### What happened:
Mob crusher or claim creator cannot attack neutral mobs from vanilla or animania. No chat error comes up.

### What you expected:
All neutral/mob entities should be able to be hit by claim owner.

### Steps to reproduce:
Claim and swing.

### Server and GriefPrevention version:
griefprevention-1.12.2-4.3.0.639
MC 1.12.2

### Stack trace/error or server log

n/a
```

### GriefPrevention config.yml

https://gist.github.com/ehmitchell3/55c29e4dad274ef5ee5835d717dbe5a7

### Plugin list (if applicable):

https://docs.google.com/spreadsheets/d/e/2PACX-1vTkZG-t1afcKNyPPTd79sOlgnGVQOXTaO1UWjjIIoDbKO0bV9cuLQ1wmEhuDokIxWMJPJbpd8msj6y4/pubhtml

**Comment by RoboMWM** [comment]
> griefprevention-1.12.2-4.3.0.639

You're using some other version of GP, which is not the official one. I'm guessing it's the sponge one.

**Comment by RoboMWM** [comment]
Just saw your config, that's definitely not the bukkit version of GP. And wow, the sponge GP looks about as complicated as Towny, lol.
