### ISSUE TITLE
Siege Mode Easy Bypass

### ISSUE THREAD

**Issue by CeIebrimbor** [GriefPrevention/GriefPrevention#421]
During Siege(combat), defending players are able to access beds (sleep). When a player is in a bed, they are invincible. This is a pretty serious workaround for an otherwise bulletproof system that BigScary created.

I would request/recommend blocking bed interaction during siege(combat), just being careful not to disable other interactions like eating n' such.

Siege really is awesome...just need to plug this loophole.

**Comment by CeIebrimbor** [comment]
I think this might be considered more serious as it allows a player to escape from PvP in general. Not just Siege. It's just more serious in Siege since a player has time to react and get to their bed.

**Comment by TomLewis** [comment]
Siege needs a complete overhaul, there's so many issues. I have a good idea of how it should work. I will have to give this bug a test.

**Comment by CeIebrimbor** [comment]
I am not aware of any other notable bugs. The system is pretty clean. Do you have any known @FrozenBeard?

**Comment by RoboMWM** [comment]
From #spigot IRC

> ScruffyRules: RoboMWM, Near the pillow is a tiny hitbox
> ScruffyRules: causes them to take damage and hop out of bed
> ScruffyRules: Unless that has been changed.

> ScruffyRules: I think when the hitbox debug menu was added was when I first saw what it looked like
> ScruffyRules: it's like .2 of a block or something, I can't remember, it's been so long. lol
