### ISSUE TITLE
Server crashing randomly 1.12.2

### ISSUE THREAD

**Issue by lorentedford** [GriefPrevention/GriefPrevention#427]
At first i thought this might be a spigot issue but everyone is saying check with Grief prevention here is what i got..

https://pastebin.com/PuuhC72R

Java Version is
```
AMP@gaming-server:~/.ampdata/instances$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3, mixed mode)
AMP@gaming-server:~/.ampdata/instances$
```

Here is my post at 
https://www.spigotmc.org/threads/spigot-server-crashing-dont-understand-these-crash-reports.349095/#post-3233759

Here is my grief prevention config.
https://pastebin.com/qi7NE5pw

**Comment by RoboMWM** [comment]
You deleted the template but at least all of the info is in the full log you pasted.

~~In the watchdog thread dump, the line is only doing a hashmap get call, and unless there's something very wrong with Java there's no reason why code would hang at this call. https://github.com/TechFortress/GriefPrevention/blob/05497b7b6a2b693302c41a79c98ff60c3757837e/src/me/ryanhamshire/GriefPrevention/DataStore.java#L544-L547~~

~~It's likely something else is at play - I can't say what for sure. Try testing with just GP installed, or half the plugins installed, etc.~~

**Comment by RoboMWM** [comment]
Mk electronicboy pointed out the other async thread calling this method, which is the cleanup task. This probably was never caught since most servers don't use (and I recommend against) MySQL storage; and those that do have good connections so it doesn't hang.

As for your spigot thread, it's likely that your MySQL server, or your connection to it, is slow/bad. And thus revealing all these bad async behaviors.

**Comment by RoboMWM** [comment]
I guess I could backport this fix for 16.8 if spigot/paper still formally supports 1.12.2, but not sure how to release it. Probably will do so with another GP update, which may be a while since one was recently released a week or so ago.

**Comment by lorentedford** [comment]
Yeah not sure at this point what is going on.. Here is my latest file now.. I almost think grief prevention is now out of the picture in my last log file.. Got any ideas how to take my database out of the mysql that it has been using for two years and revert it to the plugin folder database files?

https://pastebin.com/keWKQEpg

**Comment by RoboMWM** [comment]
Same issue it looks like.

**Comment by RoboMWM** [comment]
To reiterate, I just fixed this but only in the latest (unreleased) version, which is for MC 1.13 and later. I may also backport this fix to GP version 16.8, but will do so alongside the latest GP update.

**Comment by Darkweasam** [comment]
Is that fixed version out already for 1.12.2? The connection with MySQL seems fine to me and noone of other plugins I been using for months ever had an issue like this

**Comment by lorentedford** [comment]
I have my servers up and running and things are fine! Thank you all so very much and sorry for the late reply! On this topic! I assumed since it was closed that I didn't need to reply! Again can't thank you all enough!

**Comment by RoboMWM** [comment]
@Darkweasam network connections can be unstable from time to time due to any number of causes. Just because it's been working fine for months doesn't mean it will/has worked 100% perfectly the entire time.

**Comment by Darkweasam** [comment]
This happened for the 2nd time today, hosting said there is no problem with the connection

Here is a link to the hosting status
https://status.pebblehost.com/r/e566e998db7cdeab2a3eb08cf1cef30f/
everything is on 100.0000%

**Comment by RoboMWM** [comment]
Again, this has nothing to do with any form of extended downtime.
