### ISSUE TITLE
Configurable fireSpread in claims

### ISSUE THREAD

**Issue by ShaneBeee** [GriefPrevention/GriefPrevention#428]
Hello

So recently someone suggested for me to add a [noFireSpread](https://github.com/ShaneBeee/GriefPreventionFlags/issues/19) flag in GPFlags.
I wrote it all up and then realized, even if i turn off fire spread protection in the GP config:
```
  FireSpreads: true
  FireDestroys: true
```
fire will spread in the wild but not in claims.
Would it be possible to add an option in the claims department for fire spread?
I know I know this sounds totally insane, but maybe someone wants fire spread on their server in claims?!? 
The person who suggested this said they wanted fire to spread in claims, but not in certain claims (ie: admin claims)

Thanks for reading 👍

**Comment by RoboMWM** [comment]
I suggested this as well years ago. Someone can PR this, already have a plan to address this as part of the "naturalgrief" toggle in v20 (similar to /claimexplosions but includes more than just explosions)

**Comment by TomLewis** [comment]
I also requested this years ago 😆

**Comment by ShaneBeee** [comment]
Okay, I PR'd It :)

**Comment by ShaneBeee** [comment]
Im closing this since it was taken care of :)
