### ISSUE TITLE
Potential 1.11 EntityDamageByEntity issue maybe

### ISSUE THREAD

**Issue by RoboMWM** [GriefPrevention/GriefPrevention#43]
https://i.imgur.com/Q8r9ryA.png

Might just be a matter of compiling plugin with 1.11 API

**Comment by RoboMWM** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/diff/src/main/java/org/bukkit/event/entity/EntityDamageByEntityEvent.java?until=dd1c703c9ff5fcaf625b479c5f800489663fc746

We need to _ensure_ we're using the 1.11 API when _compiling._ Can also explicitly cast to double, though this is a bandaid.

This includes clearing maven repos... `mvn dependency:purge-local-repository`

**Comment by ghost** [comment]
Robo, I'm confused. Have you fixed this issue? I am having this bug on my server, and found it is caused by using any weapon with a fire/flame enchant.

**Comment by RoboMWM** [comment]
Are you using version 16-RC1? (See releases)

**Comment by ghost** [comment]
I'm using PaperSpigot, actually. It is my understanding that this was an issue within Spigot, and that it has been fixed, so PaperSpigot will have to implement the same fix?

**Comment by RoboMWM** [comment]
I meant GP version 16-RC1, not paper or spigot

**Comment by ghost** [comment]
16-RC1 appears to have fixed the issue.
