### ISSUE TITLE
Confirmation for abandoning claims

### ISSUE THREAD

**Issue by ArZorMC** [GriefPrevention/GriefPrevention#431]
While i'm sure many people only abandon claims when they need to, i think it would help avoid any possible mistakes if you have to confirm /abandonclaim and definitely  /abandonallclaims.
Maybe along with that a bold warning message in chat.
Would love to see this as a safety feature, especially to avoid mistakes with players new to GP.

**Comment by RoboMWM** [comment]
This already exists in an addon, ClaimslistClassifier.

**Comment by ArZorMC** [comment]
Is there an official list of add-ons somewhere, searching both spigot and search engines for ClaimslistClassifier yielded no results.
Just a curiosity, why have this as a addon rather than a config option? Would be nice to not have to have an extra plugin for such a small feature

**Comment by RoboMWM** [comment]
There's a lot of small, but unnecessary features people would like. Maybe this will be something in v20, idk. ClaimslistClassifier is a not-officially-released-but-available-for-download plugin made by me upon request. https://github.com/RoboMWM/ClaimslistClassifier/
