### ISSUE TITLE
Claims are still able to be griefed

### ISSUE THREAD

**Issue by Tugadi** [GriefPrevention/GriefPrevention#434]
Alright so basically I plugged and played. Testing it with the LuckPerms plugin giving permissions to create, abandon and trust. This all worked wonderfully yet seemed to good to be true. Further, into the server we grew players were saying that they were still able to break others blocks and access their belongings. Now checking the perms I saw that everything was fine, so I was adding flags in my claim to test it but it appeared that no matter how I did it with the block-break and other flags it transfered to the whole world not just the claim. Confused and lost I tried everything from another server owner to videos and wiki's. I just wish to fix this to protect those on the server. If I could recieve help or offer any more information I would love it. Thank you!

**Comment by bigpresh** [comment]
What type of world are you using?  Have you made sure that the world type in the config matches that?

Have you tried it without the LuckPerms plugin, in case that interferes (maybe it listens at a higher priority than GP and uncancels events that GP cancelled?)

**Comment by RoboMWM** [comment]
>  so I was adding flags in my claim to test it 

No flags exist in the official GP version. You're using some other version (probably the sponge variant).
