### ISSUE TITLE
GriefPrevention & Worldguard

### ISSUE THREAD

**Issue by LukeZurg22** [GriefPrevention/GriefPrevention#437]
Griefprevention is not working with worldguard even though it had seemingly worked prior...
Here is the console error which is from the tests me and the condemner have been working on.

https://pastebin.com/5HbdByHM

The diamond block when starting to claim works but i cannot resize nor finish claiming a claim, this is a major issue within my server and need some extra eyes on this.

**Comment by RoboMWM** [comment]
Update GP

And don't delete the issue template next time.
