### ISSUE TITLE
Claims unwanted removed

### ISSUE THREAD

**Issue by MonkvanNederland** [GriefPrevention/GriefPrevention#44]
### What behaviour is expected:
1. Command /claimslist shows list of claims.
2. Accurate amount of claimblocks.
3. Not removing my claims.

### What behaviour is observed:
1. Command /claimslist shows a double list of claims.
2. Inaccurate amount of claimblocks.
3. Removed one of my claims.

### Steps/models to reproduce:
1. Joining server and used /claimslist: ![2016-11-22_10 48 43](https://cloud.githubusercontent.com/assets/15655037/20539524/979796ce-b0f5-11e6-9b3f-ffacbefd8aa0.png)
2. I noticed one claim was missing. I checked the locations of my claims and indeed one was gone.
3. I left the server and rejoined, followed by /claimslist: ![2016-11-22_10 49 30](https://cloud.githubusercontent.com/assets/15655037/20539551/ae64856a-b0f5-11e6-83e4-befc63837211.png)

As you can see the numbers don't add up in the first screenshot. Second screenshot is correct, but still my claim is gone. This happend to more of our player.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
This bug occurred on Paper-889, 905 and currently 916, with GriefPrevention debug, 15.3 and currently 16.3.

### Stack trace/error (if applicable)
I checked the console logs and here it is; my lovely claim being removed after a server restart xD
I did had one small subclaim, but i don't remember who had trust (maybe an inactive player?)

[05:25:56] [Server thread/INFO]: [GriefPrevention] Loading GriefPrevention v16.3
[05:26:41] [Server thread/INFO]: [GriefPrevention] Enabling GriefPrevention v16.3
[05:26:41] [Server thread/INFO]: [GriefPrevention] Finished loading configuration.
[05:26:41] [Server thread/INFO]: [GriefPrevention] Removing orphaned claim subdivision: Location{world=CraftWorld{name=world},x=1239.0,y=21.0,z=-2671.0,pitch=0.0,yaw=0.0}
[05:26:41] [Server thread/INFO]: [GriefPrevention] 5016 total claims loaded.
[05:26:42] [Server thread/INFO]: [GriefPrevention] Customizable messages loaded.
[05:26:42] [Server thread/INFO]: [GriefPrevention] Successfully hooked into WorldGuard.
[05:26:42] [Server thread/INFO]: [GriefPrevention] Finished loading data (Database Mode).
[05:26:42] [Server thread/INFO]: [GriefPrevention] Boot finished.

### GriefPrevention config.yml (if applicable)
http://hastebin.com/siwadeyusu.php

### Plugin list (if applicable):
Let me know if you need more info.

- Monk -

**Comment by RoboMWM** [comment]
Are you using sql or flatfile storage

**Comment by RoboMWM** [comment]
Seems to be an issue only with those who use SQL storage... https://github.com/TechFortress/GriefPrevention/blob/9ec083703819a8ec3e62091c4a6158df2bc17580/src/me/ryanhamshire/GriefPrevention/DatabaseDataStore.java#L350

So, who knows when I'll get to this... my guess is that perhaps the parent claim wasn't loaded?

But, I guess a better question is, was this indeed an orphaned subdivision? (I don't use subdivisions, so I'm not too familiar with them at the moment.)

**Comment by MonkvanNederland** [comment]
Thank you for the fast reply! We are running sql, and yes it was the subdivision that was removed. This took the whole master claim with it :P

**Comment by RoboMWM** [comment]
>  This took the whole master claim with it :P

Well, sounds more like the master claim never existed, hence why the _orphaned_ subdivision disappeared.

Can you try to reproduce? And if successful, please outline steps.

**Comment by MonkvanNederland** [comment]
Ah yes, that sounds logical. English is not my native language, sorry for misunderstanding "orphaned".
We'll do our best to reproduce and find more info on the issue :)

**Comment by RoboMWM** [comment]
Going to assume the issue was indeed an orphaned subdivided claim. Comment here if you're able to reproduce otherwise.
