### ISSUE TITLE
Where to place Spawner mob is false ?

### ISSUE THREAD

**Issue by tiphilou17** [GriefPrevention/GriefPrevention#441]
Hello, Im admin on my server, i have GriefPrevention/Vault/UltraPermission/WorldGuard and i search why i have this message when i want place spawner : "You are not allowed to place this spawner" people can help me please

**Comment by RoboMWM** [comment]
Not a GP issue, GP doesn't have such a message nor filters any specific blocks.

Also you deleted the issue template, don't do that and fill it out next time.
