### ISSUE TITLE
I need help with Grief Prevention and Grief Prevention Flags

### ISSUE THREAD

**Issue by MrBuushy** [GriefPrevention/GriefPrevention#442]
Basically, I have a spawn area and it is claimed with the flags (NoMonsterSpawns and NoMobDamage) and I also made a sub-claim for pig spawners and they spawn but I don't know how to make the sub-claim claimed and let players kill the mobs

**Comment by RoboMWM** [comment]
Not sure what you mean by "make the sub-claim claimed" if it's a subclaim...?

Also, I don't maintain GP flags.

**Comment by MrBuushy** [comment]
> Not sure what you mean by "make the sub-claim claimed" if it's a subclaim...?
> 
> Also, I don't maintain GP flags.

yeah i forgot to remove the "Claimed" but i thought you created the GP plugin and this GP flags plugin says from the creators of GP

**Comment by RoboMWM** [comment]
Yes, originally created by BigScary, who created GP. I didn't inherit anything except GP and PopulationDensity when BigScary left. (Though I have updated AutomaticInventory and GraviTree upon request.) Idk who's fork you're using.

**Comment by MrBuushy** [comment]
> Yes, originally created by BigScary, who created GP. I didn't inherit anything except GP and PopulationDensity when BigScary left. (Though I have updated AutomaticInventory and GraviTree upon request.) Idk who's fork you're using.


Who's fork I'm using? also can't you ask him for it?

**Comment by RoboMWM** [comment]
> Who's fork I'm using?

Idk, where did you download it from?

> also can't you ask him for it?

I don't use it nor want to maintain it. And there are already people who are maintaining it.

**Comment by RoboMWM** [comment]
Here are the forks of that plugin. Some forks are published on spigot, others aren't. https://github.com/bigscary/griefpreventionflags/network

**Comment by MrBuushy** [comment]
> Here are the forks of that plugin. Some forks are published on spigot, others aren't. https://github.com/bigscary/griefpreventionflags/network

like which developer? made the 1 im using?

**Comment by bigpresh** [comment]
We can't tell you whose fork you're using - you're the one using it, you need to determine that.  Where you downloaded it from would likely tell you.  The version number of the plugin *may* give you a clue, if the developer of the fork you're using has been doing proper releases etc - but that might not work.

Either way, this isn't something we can help you with, sorry.
