### ISSUE TITLE
Inclusion of signs, buy, sell, trade, repair from EssentialsX in admin claims.

### ISSUE THREAD

**Issue by ShawnDaGeek** [GriefPrevention/GriefPrevention#447]
We set up and admin claimed spawn and added a few signs from EssentialsX for buy, sell, trade.  It seems even with **/accesstrust public** and **/containertrust public** we are still unable to use the signs, anvils, crafting bench, enchanting table, furnace or Villagers.  If this is intended i am hoping to have these items or even just signs included in the commands.
If it is not intended and they should be accessible could someone please show me the way.

**Comment by RoboMWM** [comment]
Yea, sounds like you dun goof'd something. Probably vanilla spawn protection.

**Comment by ShawnDaGeek** [comment]
You are so awesome let me tell you, seems when we updated to most recent ver. of spigot our server.properties was set back to default.  Thank you again.
