### ISSUE TITLE
Animals are not protected at all

### ISSUE THREAD

**Issue by Snewmy** [GriefPrevention/GriefPrevention#448]
### What happened:
Players can freely kill other claimed animals

### What you expected:
That animals should be protected

### Steps to reproduce:
Any player can just go up and kill somebody elses animals

### Server and GriefPrevention version:
Paste of `/version`: This server is running Paper version git-Paper-405 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: GriefPrevention version 16.11.5

### GriefPrevention config.yml
https://hasteb.in/ipomotik.yaml
```yml

**Comment by RoboMWM** [comment]
Check your config, you changed something.

`    ProtectCreatures: false`
