### ISSUE TITLE
Access to villagers in adminclaims.

### ISSUE THREAD

**Issue by ShawnDaGeek** [GriefPrevention/GriefPrevention#449]
Just wondering if villagers could be included in adminclaims with either /accesstrust public, or /containertrust public.  Or if there is a way with out Trust, if i could be pointed in right direction.

**Comment by RoboMWM** [comment]
It is /containertrust, and yes see config to allow access without trust.

**Comment by ShawnDaGeek** [comment]
Thanks but with containertrust villagers still throw Admin owns this message, and will not allow them to access.  
`    CreationRequiresWorldGuardBuildPermission: false
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: false`
I will try to figure it out i guess or just let players know villagers in adminprotected spawn are decore only.

**Comment by RoboMWM** [comment]
Does it work in normal claims?
