### ISSUE TITLE
Can't claim anything

### ISSUE THREAD

**Issue by taku-nm** [GriefPrevention/GriefPrevention#45]
### What behaviour is expected:
Claiming
### What behaviour is observed:
/griefprevention:claim --> "An internal error occurred while attempting to perform this command"
Holding a golden shovel --> Nothing happens
### Steps/models to reproduce:
CraftBukkit 1.8.7
/griefprevention:claim --> Error

### Spigot/Craftbukkit/Paper and GriefPrevention version:
This server is running CraftBukkit version git-Bukkit-8f0f4ed (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)

GriefPrevention v16.4 

### Stack trace/error (if applicable)

(read from below)

22.11 22:06:23 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
22.11 22:06:23 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:540) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:23 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:632) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:23 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:23 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:683) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:23 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:23 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:23 [Server] INFO at me.ryanhamshire.GriefPrevention.EquipShovelProcessingTask.run(EquipShovelProcessingTask.java:41) ~[?:?]
22.11 22:06:23 [Server] INFO at me.ryanhamshire.GriefPrevention.GriefPrevention.getItemInHand(GriefPrevention.java:3586) ~[?:?]
22.11 22:06:23 [Server] INFO java.lang.NoSuchFieldError: OFF_HAND
22.11 22:06:23 [Server] WARN Task #26 for GriefPrevention v16.4 generated an exception
22.11 22:06:20 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
22.11 22:06:20 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:540) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:20 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:632) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:20 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:20 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:683) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:20 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:20 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:20 [Server] INFO at me.ryanhamshire.GriefPrevention.EquipShovelProcessingTask.run(EquipShovelProcessingTask.java:41) ~[?:?]
22.11 22:06:20 [Server] INFO at me.ryanhamshire.GriefPrevention.GriefPrevention.getItemInHand(GriefPrevention.java:3586) ~[?:?]
22.11 22:06:20 [Server] INFO java.lang.NoSuchFieldError: OFF_HAND
22.11 22:06:20 [Server] WARN Task #25 for GriefPrevention v16.4 generated an exception
22.11 22:06:13 [Server] INFO ... 15 more
22.11 22:06:13 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:13 [Server] INFO at me.ryanhamshire.GriefPrevention.GriefPrevention.onCommand(GriefPrevention.java:1057) ~[?:?]
22.11 22:06:13 [Server] INFO at me.ryanhamshire.GriefPrevention.DataStore.createClaim(DataStore.java:802) ~[?:?]
22.11 22:06:13 [Server] INFO at me.ryanhamshire.GriefPrevention.Claim.<init>(Claim.java:310) ~[?:?]
22.11 22:06:13 [Server] INFO Caused by: java.lang.NoSuchFieldError: BEETROOT_BLOCK
22.11 22:06:13 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
22.11 22:06:13 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:540) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:13 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:632) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:13 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:13 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:676) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:13 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:13 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
22.11 22:06:13 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
22.11 22:06:13 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:13 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:13 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:13 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:939) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:13 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1079) [craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:13 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:621) ~[craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:13 [Server] INFO at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) ~[?:?]
22.11 22:06:13 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit1-8.jar:git-Bukkit-8f0f4ed]
22.11 22:06:13 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'claim' in plugin GriefPrevention v16.4
22.11 22:06:13 [Server] ERROR null
22.11 22:06:13 [Server] INFO otaku1101 issued server command: /claim

### GriefPrevention config.yml (if applicable)

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    freebuild: -1
  Claims:
    Mode:
      freebuild: Creative
      world_nether: Disabled
      world_the_end: Disabled
      world: Disabled
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 2000
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 200
    CreationRequiresWorldGuardBuildPermission: false
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      freebuild: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

### Plugin list (if applicable):
Plugins:
PermissionsEx
PerWorldPlugins (GP is allowed)
WorldEdit
ModifyWorld
Essentials
EssentialsSpawn
EssentialsChat
Mulitverse-Core
GriefPrevention

**Comment by bigpresh** [comment]
Invalid - 16.4 is only compatbile with MC 1.10 and 1.11, you're trying to use it on 1.8.7

13.9.1  is the latest version compatible with 1.8.x

**Comment by lukas1101** [comment]
YEES ! Thanks xD

**Comment by MrPowerGamerBR** [comment]
(It would be great if GriefPrevention supported 1.8... would be easier for me, I wouldn't need to "backport" the latest GriefPrevention to work on 1.8 (which isn't a lot of changes tbh, most of them are due to the materials that doesn't exist in 1.8))

But hey, probably this won't happen.

**Comment by RoboMWM** [comment]
> (It would be great if GriefPrevention supported 1.8... would be easier for me, I wouldn't need to "backport" the latest GriefPrevention to work on 1.8 (which isn't a lot of changes tbh, most of them are due to the materials that doesn't exist in 1.8))

Feel free to PR your changes - provided that the methods for previous versions is clean and doesn't make this project any more monstrous than it already is (it does need a bit of refactoring, but I don't have the time for that right now).

**Comment by MrPowerGamerBR** [comment]
@RoboMWM "clean"

*closes tab because my fork isn't clean at all*
