### ISSUE TITLE
not letting people claim land

### ISSUE THREAD

**Issue by jacobvdl** [GriefPrevention/GriefPrevention#451]
### What happened:
it would not let players create claims

### What you expected:
_What you expected to see_

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. claim 1 corner of the land
2. it dosent let you select the other corner

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
1.12
16.7.1

### Stack trace/error or server log
it dosent make any logs when that happens
```
Paste entire stack trace right here inside these backticks.

If not applicable, paste the server.log at gist.github.com and paste the link here.
```

### GriefPrevention config.yml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    Ocean: -1
    map: -1
  Claims:
    Mode:
      world: Survival
      world_nether: Disabled
      map: Survival
      world_the_end: Disabled
      Ocean: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 2000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
      Ocean: false
      map: false
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

```yml

Paste the config.yml right here inside these backticks.

```

### Plugin list (if applicable):
CoreProtect, WorldEdit, AdminFun, FirstJoinPlus, GreatKits, Essentials, ClearLag, TuxTwoLib, PlugMan, Votifier, TrollGUI, WorldGuard, Multiverse-Core, ProtocolLib, iDisguise, MaxBans, Sudo, EssentialsProtect, EssentialsChat, EssentialsGeoIP, WelcomeWarpSigns, PermissionsEx, TrollBoss, mcMMO, StaffChat, Vault, EssentialsSpawn, GriefPrevention, MCWild, EnjinMinecraftPlugin, AntiXRay, MultiInv, AntiCheatReloaded, HolographicDisplays, SilkSpawners, Citizens, AdvancedAchievements, CrazyAuctions, SuperbVote, CratesPlus, MyPet, Jobs, MinigamesLib, MGMobEscape, MGSplegg

**Comment by RoboMWM** [comment]
You didn't paste the config.yml inside the backticks.

Anyways, in what world are you attempting to claim?

**Comment by jacobvdl** [comment]
im trying to claim in the main world

**Comment by RoboMWM** [comment]
What is the name of the main world.

**Comment by jacobvdl** [comment]
World

**Comment by RoboMWM** [comment]
Try with just GP installed. Also provide full output of `/version`

**Comment by jacobvdl** [comment]
it works on my test server

**Comment by jacobvdl** [comment]
the version screenshot: https://i.ibb.co/MRY9MJD/Capture.png

**Comment by jacobvdl** [comment]
i can give you access to the server because my hoster allows access control

**Comment by RoboMWM** [comment]
Sounds like a plugin conflict then. Some plugin is interfering I guess.
