### ISSUE TITLE
Issue's with auto claim deleting and /claimlist

### ISSUE THREAD

**Issue by Remski01** [GriefPrevention/GriefPrevention#452]
### What happened:
Issue's with auto claim deleting and /claimlist

### What you expected:
That the claim get removed and /claimlist works properly.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1.
2. Step 2.
3. ???
4. Profit!

### Server and GriefPrevention version:
Paste of `/version`: Paper 1.13.2 (build 456)
Paste of `/version GriefPrevention`: GriefPrevention v16.11.5

### Stack trace/error or server log
None.

Paste entire stack trace right here inside these backticks.

If not applicable, paste the server.log at gist.github.com and paste the link here.
```

### GriefPrevention config.yml

https://pastebin.com/PkhVV9dq

Paste the config.yml right here inside these backticks.

```

### Plugin list (if applicable):

So, the issue's are as fellow:

1, GP does not delete the claim as it should, it have been set to 181 days. the user is 186 days offline.
2, the user does not exsist in /claimblocks while there is a claim of her and she is in the playedata file with some interesting value's.

As example, the limit have been to 99999 in the config. This also in the playadata file of that user and that is quite coincidence. See https://pastebin.com/twgmhxxj

**Comment by RoboMWM** [comment]
Claim expiration happens slowly, and it depends on how many claims you have total and how long the server is running for one session.

You can make this check execute faster by reducing the rate value in the advanced config section. You can also increase the amount of days a player may be inactive before their data is no longer loaded automatically on boot in the same section.

You can also enable debug logging in GP to see if it's checking claims for expiration.
