### ISSUE TITLE
Protecting Wolves in Claims

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [GriefPrevention/GriefPrevention#454]
Adding a feature to allow protecting dogs in claims. Maybe also a feature to allow players to kill dogs IF they are attacked by them. But that 2nd part isn't absolutely necessary.

**Comment by ghost** [comment]
Dogs are already protected if they are tamed. But, allowing them to be killed if they attack should be added, if it isn't already, in my view. @RoboMWM do you have thoughts on this one?

**Comment by PiggiesGoSqueal** [comment]
Err multiple of my players have reported dogs not being protected in claims.

**Comment by RoboMWM** [comment]
In PvE worlds wolves are protected, in PvP worlds they are not since players would be defenseless if attacked by invincible wolves.

**Comment by ShaneBeee** [comment]
Just a thought but could you possible do it if the dog is angry via Wolf#isAngry()?
This way protecting dogs in claims that are currently not a threat to the player?

Something along these lines (sorry I just whipped this up quick for testing)
```java
else if (tameable instanceof Wolf) {
	if (!tameable.getOwner().equals(event.getEntity())) {
		if (!((Wolf) tameable).isAngry()) {
			event.setCancelled(true);
			String ownerName = GriefPrevention.instance.getServer().getOfflinePlayer(ownerID).getName();
			String message = GriefPrevention.instance.dataStore.getMessage(Messages.NoDamageClaimedEntity, ownerName);
			if(attacker.hasPermission("griefprevention.ignoreclaims"))
				message += "  " + GriefPrevention.instance.dataStore.getMessage(Messages.IgnoreClaimsAdvertisement);
			if(sendErrorMessagesToPlayers) GriefPrevention.sendMessage(attacker, TextMode.Err, message);
			return;
		}
	}
}
```

**Comment by RoboMWM** [comment]
@ShaneBeee if that works when a player attacks another player (thus "commanding" the wolf to attack the player), then that would work as a PR.

**Comment by ShaneBeee** [comment]
I'll do some testing this evening, and make sure all aspects of it works, then I'll submit a PR. 
I could probably do a check also for the target of the dog... making sure only the player currently being targeted can attack the dog and not another player.

**Comment by RoboMWM** [comment]
Closed in https://github.com/TechFortress/GriefPrevention/commit/522d2255485936f5574febb1c4410d6aafbbffcd
