### ISSUE TITLE
ClaimCreateEvent fired when resizing a claim

### ISSUE THREAD

**Issue by WesternIcelander** [GriefPrevention/GriefPrevention#455]
### What happened:
1. User resizes his/her claim.
2. ClaimCreatedEvent fired followed by ClaimModifiedEvent.

### What you expected:
Only ClaimModifiedEvent should have fired, not ClaimCreatedEvent

### Steps to reproduce:
1. Resize a claim.
2. ClaimCreatedEvent fired followed by ClaimModifiedEvent.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`:
This server is running CraftBukkit version git-Spigot-518206a-a838286 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`:
GriefPrevention version 16.11.5

### Stack trace/error or server log

```
not applicable
```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```
did not modify config.yml, it's default.
```

### Plugin list (if applicable):
- GriefPrevention
- TerritoryParticles - A plugin I'm developing to draw particles around claimed territory. (Not available to the public at this time)

**Comment by RoboMWM** [comment]
This is initially why I did not want to add this event, because what GP does internally is delete and re-create the same claim. I guess I should've explicitly asked for #344 to be tested before merging.

@Narimm

**Comment by WesternIcelander** [comment]
Though, I do observe the correct behaviour (no ClaimCreatedEvent, only a ClaimModifiedEvent) when a player extends their claim further into the ground by building below the originally claimed area.  You only get an unexpected ClaimCreatedEvent when resizing a claim using the golden shovel.

**Comment by 112RG** [comment]
So you want the ClaimCreatedEvent to not fire when resizing the claim?

**Comment by WesternIcelander** [comment]
Since internally a claim is deleted and recreated to do a resize, technically a new claim is being created and nothing is really being modified.

My proposed fixes:

Fix A:
- Get rid of ClaimModifiedEvent
- Add an enum CreateReason {NEW, MODIFIED} to ClaimCreatedEvent
- Fire ClaimDeletedEvent on the old claim.

Fix B:
- Change the internal behaviour so it does modify the claim rather than recreate it with changes.
- Don’t fire ClaimCreatedEvent when resizing.

**Comment by 112RG** [comment]
I don't understand the proposed fixes to the issue you stated. From what you said, in the beginning, the problem was a ClaimCreatedEvent is being fired when resizing a claim.

The fix I thought for this was to not fire a ClaimCreatedEvent when resizing

**Comment by WesternIcelander** [comment]
Yes, the problem _is_ that two events are being fired when a player resizes a `Claim`.

However, GP's internal behaviour is to create a new `Claim`, copy everything over from the old `Claim` with the changes on the new `Claim`, then delete the old `Claim`.  The end result is we have a whole new `Claim` object, with the old one being discarded.  This is why a `ClaimModifiedEvent` doesn't really make sense in the first place, unless the behaviour is changed so that the existing `Claim` is modified rather than replaced.

Barring `new Throwable().getStackTrace()` and checking which class and method fired the event (which may be unreliable), there is no way to tell whether or not the first event, the `ClaimCreatedEvent`, is actually fired due to a `Claim` being resized, unless a `CreateReason` enum is added (like I proposed in Fix A).

**Comment by 112RG** [comment]
Okay, I see the problem. I am not sure the importance of this to be fixed since some work would be needed for this to behave correctly also with the codebase already being as bad as it is. I don't think I will take this on since legacy is mainly maintained for bugs or plugin breaking problems.

But I see that you have an understanding of the issue so feel free to PR.

**Comment by WesternIcelander** [comment]
Fixed in #461.
