### ISSUE TITLE
Cant disable in creative world

### ISSUE THREAD

**Issue by JHarris12345** [GriefPrevention/GriefPrevention#456]
Hey, regarding grief prevention. There seems to be an error. I have a world called creative. I want to disable GP in this world however, whenever I change the config to disabled, it always changes it back to creative after a reload / restart. Here is an example:

  Claims:
    Mode:
      Creative: Disabled
      world_the_end: Disabled
      world: Survival
      world_nether: Disabled

After reload it will become

  Claims:
    Mode:
      Creative: Creative
      world_the_end: Disabled
      world: Survival
      world_nether: Disabled

**Comment by RoboMWM** [comment]
Try a server restart, not a reload. GP does not automatically re-add missing entries, or remove any unless the world somehow doesn't exist when it loads.

Also, please fill out the template you deleted.

**Comment by RoboMWM** [comment]
If you still have issues please reply here, else assuming this is fixed on your end.
