### ISSUE TITLE
Worldguard Region Whitelist

### ISSUE THREAD

**Issue by EHAndrew** [GriefPrevention/GriefPrevention#458]
I would like to see a WG region whitelist feature. Currently there is no way to have claims within one region and not in another. CreationRequiresWorldGuardBuildPermission doesn't seem to work, and there is no documentation on how it _should_ work. I was told to disable WG integration or use admin claims, which for many reasons aren't going to work for me.

**Comment by RoboMWM** [comment]
Server logs reveal stuff, but there's a PR for WorldEdit's new API. It's just a pain since me4502 change the API without changing the version, so no matter what we do or not do it's going to break for some people.
