### ISSUE TITLE
"borrowing" WorldEdit CUI Code for Claims markings

### ISSUE THREAD

**Issue by Romaq** [GriefPrevention/GriefPrevention#46]
### What behaviour is expected:
_Lines like WorldEdit CUI_
### What behaviour is observed:
_Glowstone, Gold blocks, sometimes above and out of visible sight, sometimes on the bottom against The Void_
### Steps/models to reproduce:
_Any time a claim or subclaim is selected for editing._

Feature suggestion, or possibly something that could be opened up in the future. WorldEdit will throw a "/we cui" call on login to initiate handshaking, invisible to the players. It would help GP boundaries if it could intercept the "/we cui" call and use the code from WorldEdit for selection boundaries to send edge vectors to the LiteLoader WorldEditCUI found on https://github.com/Mumfrey/WorldEditCUI.

I understand things are busy and it isn't likely, but as my wife reminds me I don't get told "no" unless I ask. :)

**Comment by RoboMWM** [comment]
Yea, particles would be nice and something I suggested long ago.

However, particle API, iirc, is only in spigot API (not that huge of a deal, but GP has always been built against CB, so it's best to preserve this compatibility wherever possible).

Also something to note - you cannot select such particles, so it's only partly useful for simply visualizing the claim. (And I think particles have a limited range of visibility?)

**Comment by Romaq** [comment]
The interface is the same as when you can now use F3+G (Show me chunk borders). The F3+G version does block occluding, so you can not see the vector lines through any obstruction. The "WorldEdit CUI" version IGNORE occlusion, so if you select a chunk (//chunk, if I recall) you will see the chunk selection floor to ceiling, and the same with any other selection.

I am not clear on the details, but I *think* vector lines in the display code are handled differently from particle effects. You would not select the vector lines. Even in WorldEdit (or F3+G, for that matter) you would not 'select' the boundaries, the boundaries are simply for visualizing a selection (or the chunk, as the case may be). I would have to confirm, but I don't believe the "particles" setting would have any impact on the vector display.

Since "vector display" appears to be built-in with Vanilla, perhaps the API is available in CB. That is WAY outside my expertise. And, of course, the only purpose of this is "how big is my claim? How deep?" Selection would of course still have to be done by the gold spoon. But in terms of showing the extent of a claim, it would be a HUGE improvement over the "gold/ diamond/ pumpkin/ glowstone at top-block level" method used, especially as it can be "non-occluding".

I don't think vector selection is worth diverting much attention to on its own. You would ONLY be serving a very small audience who happens to be using LiteLoader plus WorldEdit CUI. That is, *unless* you stumbled upon how to trigger this effect in an un-modded client. I think it highly unlikely an un-modded client would allow a server to trigger "vector lines". Given the potential "audience" of the change, on its own vector selection display simply isn't worth it. But for admin/ staff/ WorldEdit users, it would be one hell of a godsend if you stumbled upon a way to throw this in while working on something else, or if you required the method for some *other* needful project.

**Comment by Romaq** [comment]
I just came across https://www.spigotmc.org/resources/selection-visualizer.22631/ which would "help", and it claims it works with /gp. I'm going to test it and annoy the author of *that* plugin to see if they would check WorldEdit CUI support. This would improve the plugin he's using and make the whole thing his problem, rather than yours. I prefer a situation in which a problem is someone else's problem rather than mine. :)

If you are in a position to test the Selection Visualizer, perhaps it is one to recommend as a /gp add-on, and that would effectively close this ticket.

**Comment by RoboMWM** [comment]
Wait, WE CUI doesn't require a client mod?

**Comment by Romaq** [comment]
F3+G is vanilla, does not require a client mod to display vector lines WITH occlusion, so it is just part of how Vanilla MC 1.11 works.

WorldEdit normally does not display vector lines. To see vector lines (appears very simular to F3+G), you must install LiteLoader (client side mod) plus the WorldEdit CUI mod for Liteloader found here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292886-worldeditcui

So for this feature to be useful, players that want it would have to install LiteLoader plus the LiteLoader mod found on the above link. But having done so, WorldEdit selection regions appear in vector line format regardless of distance and without occlusion.

Again, I think people using LiteLoader are pretty much the minority. A sizable chunk of support on my server goes to helping players set up and use LiteLoader, but once they do they are all in love with VoxelMap's LiteLoader mod. For *my* players, getting them to install WorldEditCUI would be trivial, but I don't know how large the audience for GP would make use of it beyond admin. "Some" servers consider use of LiteLoader at all a "cheat" and forbid it to everyone except "staff", of course. Mostly because it is not usually detectable and can be modded "very" cheaty.

On my server, I have a "don't know, don't ask, don't care" policy as long as it isn't being used to HARM another player. And my wife really loves the VoxelMap. But yeah, having non-occlusive vector selection display of claims would be "WHERE HAVE YOU BEEN ALL MY LIFE" helpful. I did send a note to the dev of Selection Visualizer. My "feel" of the situation is that this would really be up his alley if it were a part of that plugin.

**Comment by BillyGalbreath** [comment]
I currently use Pl3xSUI to visualize claims with particle effects. It was originally designed to be a server side replacement for WorldEdit CUI. The only problem with it right now is when a lot of claims (shift click with stick) or very large claims are visualized is _can_ cause some lag. I am working out the lag with that, though. (requires GP 16.5+)

http://ci.dwdg.net/view/Pl3x/job/Pl3xSUI/

However, I can make a GriefPrevention specific addon to tell WorldEdit CUI what to draw. The only limitation with WE CUI is you can only view 1 cuboid at a time, so shift clicking to see all visuals will not work with the client mod.

**Comment by Romaq** [comment]
And here I am, I was not even aware of the "multiple GP Claim selection" option existed, but I'll have to try it and see how it displays. :) As an end-user, I'd be quite happy just to see "a" selection appear as a vector cuboid.

As far as multiple selections go, or the irregular selections that /sv provides, perhaps there is a "generally useful" way to handle this so it is not a "do something special for GP Claims users."

What may be possible is to ask Mumphry if the WorldEdit CUI mod, and by extension the  "/we cui" handshake be made vector API for the server to communicate selection info "not necessarily WorldEdit." He may have an opinion on a better way to go about that, but while we are juggling this, there is a Villager Marker mod that is both a plugin and a LiteLoader mod to visualize village size, the spawn box for Iron Golems and a line between each village door and the village center, all with occluding vector. It does allow for villages to overlap, and Villager Marker will display each "Iron Golem spawn box" separately as seen in this video: https://www.youtube.com/watch?v=1h0dn9XPhY4. Multiple selection display is possible, and even in WorldEdit a polygonal region will display as "multiple selection box pillars" with lines connecting them to show the outline of the selected polygonal region.

If Mumphry would have an idea on a good approach, perhaps vector information display could be made a generally useful tool for /sv. As I recall from using both Towny and Factions, the "map display in chat" feature still kinda sucked. /sv with particle display helps, but /sv with vector display might solve lag issues with particle display and be more effective for those using LiteLoader and at least WECUI.

**Comment by BillyGalbreath** [comment]
Sorry it took so long. been busy with work and simply forgot all about this..

Here you go:

Builds: https://downwithdestruction.net/jenkins/job/GPWECUI/
Source: https://bitbucket.org/BillyGalbreath/gpwecui

There are no commands, no permissions, and no configs. It simply adds WECUI visualizations when claim visuals show from GP.
