### ISSUE TITLE
Spigot page links to bigscarygaming.com which has expired

### ISSUE THREAD

**Issue by WesternIcelander** [GriefPrevention/GriefPrevention#463]
It would appear that Big Scary no longer owns bigscarygaming.com

Go to ->
https://www.spigotmc.org/resources/griefprevention.1884/

Scroll down and find "Spoiler: Big_Scary's other projects (Not maintained by RoboMWM)" and click on it.

Click on any link that goes to bigscarygaming.com

You might get a page with advertising, or you might get one of those fake "virus detected" or "flash needs an update" messages that trick unsuspecting users to call a number/download the real virus.  (random)

**Comment by RoboMWM** [comment]
Guess he let the domain expire.

**Comment by RoboMWM** [comment]
Fixed. You can doublecheck if you want.
