### ISSUE TITLE
Tekkit Legends Crashing

### ISSUE THREAD

**Issue by JRL21** [GriefPrevention/GriefPrevention#47]
### What behaviour is expected:
To have to be trusted on land to break blocks
### What behaviour is observed:
When I right click with a dark matter tool in a claimed plot player FPS drops and the whole server freezes and players time out.
### Steps/models to reproduce:
If you use a fully powered dark matter tool like a pickaxe on ore that is in claimed land you will drop FPS and the server will freeze up in the console and players will time out. To start the server I have to spam stop until it goes through and then start it.

### Spigot/Craftbukkit/Paper and GriefPrevention version:
7.7 Grief Prevention KCauldron 1.7.10-R0.1-SNAPSHOT (MC: 1.7.10)

### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here
```
http://pastebin.com/JiK91jD7
### Plugin list (if applicable):
AutoMessage
BanItem
BuycraftX
ClearLag
EnjinMinecraftPlugin
Essentials
Grief Prevention
HolographicDisplays
PermissionsEx
SignShop
Tekkit_Toolkit
VoteRoulette 
Votifier 
WorldEdit
WorldGaurd

**Comment by RoboMWM** [comment]
Yea that's an ancient version of bukkit and GP. Only suggestion I have is to add the blocks to the mods section of the config. Otherwise you might need to find a developer to fork and maintain an older version for you.
