### ISSUE TITLE
LightningStrikeEvent error

### ISSUE THREAD

**Issue by Victor75007** [GriefPrevention/GriefPrevention#472]
### What happened:
_What you saw_

My server is simple 1.13.
I get some error, when thunder and lightning is have in the world.
"could not pass event LightningStrikeEvent to grief prevention v.16.11.5"

I use the GriefPreventionFlags too. 

Error:
https://pastebin.com/V2N1p2Ss

**Comment by RoboMWM** [comment]
Update spigot
