### ISSUE TITLE
Water in Waterlogged Blocks not GP protected.

### ISSUE THREAD

**Issue by NullCase** [GriefPrevention/GriefPrevention#473]
### What happened:
Able to remove water source blocks from waterlogged blocks.

### What you expected:
GP protected water source blocks.

### Steps to reproduce:
claim waterlogged block, have non-owner try to remove it.

### Server and GriefPrevention version:
Paper version git-Paper-510 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
GriefPrevention version 16.11.5

**Comment by RoboMWM** [comment]
I'm assuming you meant an untrusted player was able to do this, took me a few seconds to figure out what the actual issue was.

**Comment by RoboMWM** [comment]
Steps to cause a block to be waterlogged? (No, I haven't played much on 1.13 yet, at least not with the new stuff.)

**Comment by NullCase** [comment]
place a water source block inside a:

stair, slab, trap door, fence, fence gate, ladder, sign

I might be forgetting a few. basically non-full blocks which usually produced a submerged air-gap are now filled with water. I don't know if doors are still an exception to that.

**Comment by RoboMWM** [comment]
Can water be placed into such claims causing the water to be logged? Also, how does a player remove the water - with a bucket as per normal?

**Comment by NullCase** [comment]
Cannot place water on claimed land to produce a waterlogged block (or otherwise).

Water was removed with a bucket.
