### ISSUE TITLE
/trust public does not work!

### ISSUE THREAD

**Issue by nikich700** [GriefPrevention/GriefPrevention#475]
I am running a Mincraft Bukkit server for 1.13. I have installed GriefPrevention and already used /adminclaims to claim a territory for spawn. Soon I realised that commands as /trust public do NOT WORK! They send messages to the chat, but players still can not destroy or build anything! What shall I do, help me please!

**Comment by RoboMWM** [comment]
Please fill out the template you deleted.

**Comment by 112RG** [comment]
Please close this issue

**Comment by RoboMWM** [comment]
Migrated to #476
