### ISSUE TITLE
Color codes do not work in messages.yml

### ISSUE THREAD

**Issue by Camadillo** [GriefPrevention/GriefPrevention#479]
Title basically explains it. I try to use color codes in the messages file, and it gives me an error in console upon reload: 

`expected alphabetic or numeric character, but found &(38)`

If I need to do something else to get the massages custom colored, tell me. If color is not already implemented, thennnnnnnnnnnnnn it should probably be added, for extra customization.

**Comment by Jikoo** [comment]
Make sure your YAML is correct. Sounds like your messages aren't wrapped in double quotes, yielding parsing issues when using non-alphanumeric characters in strings, but it's hard to tell with such a small snippet of the error.

GP (poorly) [supports color codes](https://github.com/TechFortress/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/GriefPrevention/DataStore.java#L1686) using `$` apparently.

**Comment by Camadillo** [comment]
Using $ instead of a & worked! A bit odd to me, but hey at least it works! Thank you @Jikoo !
