### ISSUE TITLE
Piston protections cause some TPS loss

### ISSUE THREAD

**Issue by NullCase** [GriefPrevention/GriefPrevention#481]
### What happened:
50% of tick, High TPS usage for BlockPistonRetractEvent with low event count.
63% TPS loss by operating 3 slime block sweepers which use pistons.

When this event is being called often it causes high lag. It's generally not used that much except with some farm designs. One of the guys built a slime block sweeper mob farm and it just crushes the server's TPS when turned on.

https://timings.aikar.co/?id=4d9e44a49be941ed97ead2c2b4f974a5

### What you expected:
Lower TPS usage. 

### Steps to reproduce:
1. Make a spammy piston inside a land claim.
2. Observe.

### Server and GriefPrevention version:
Paper 1.13.2 git-paper-523
GP 16.11.5

Or, paste the server.log at gist.github.com and paste the link here: 

**LimitPistonsToLandClaims: false**

```
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world: Survival
      world_nether: Survival
      world_the_end: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 0
    Claim Blocks Accrued Per Hour:
      Default: 0
    Max Accrued Claim Blocks:
      Default: 1000000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: -1
    ExtendIntoGroundDistance: 5
    MinimumWidth: 2
    MinimumArea: 4
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_AXE
    Expiration:
      ChestClaimDays: 60
      UnusedClaimDays: 60
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 2147483647
        ExceptWhenOwnerHasBonusClaimBlocks: 2147483647
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: false
    PortalGenerationRequiresPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/tell;/global;/local;/w;/msg;/r;/t
    WhisperSlashCommands: /tell;/pm;/r;/w;/t;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
    Logout Message Delay In Seconds: 10
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksPurchaseCost: 100.0
    ClaimBlocksSellValue: 100.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: false
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: false
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 6
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: false
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 365
  Abridged Logs:
    Days To Keep: 14
    Included Entry Types:
      Social Activity: false
      Suspicious Activity: false
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

```

**Comment by RoboMWM** [comment]
Pistons can fire up to 6 or so events in a single tick. Also, Paper made a change to fire the retract event for sticky pistons - reasoning behind that was apparently the retract event was supposed to only be called for sticky pistons in Bukkit, but somehow that behavior changed and only non-sticky pistons call the retract event. Paper devs considered reverting the change, but weren't sure of the implications of plugins that might be relying on this bugged behavior, and thus just made it apply for both.

That being said, it's only using ~28% of the tick. Not ideal, but not terrible either.

I'll see what can be done to optimize in v20.

**Comment by Bobcat00** [comment]
I'm seeing the same problem, it's even worse with piston retract events.  Timings under 1.12.2 with GP 16.8 show a whopping 675 usec per retract event, dropping my TPS down to 14.  In comparison, other plugins use no more than 10 usec.  I made a fork with a 1.12.2 branch that adds a new config parameter CheckPistonMovement (default true).  If false, the entire extend/retract event processing is skipped.  Solves my problem.

A better approach might be to check when pistons are placed to make sure the head can't extend into a land claim.  If players are really concerned about piston griefing, they could make their claims with a one block buffer around them.  Then pistons pushing a block could only go one block into the claim.  Then get rid of the extend/retract event handlers, or at least make it configurable.  Not ideal, but the lag in the present implementation is unacceptable.

**Comment by bigpresh** [comment]
I'm a little puzzled that you're seeing such performance impact from this.  I have a base with loads of pistons, often firing banks of 10-20 at a time, and not had any problems.  I also know that some people on my server have a nether mob farm which uses some piston & slime block sweeper contraptions, and that doesn't seem to have any adverse effect either.

**Comment by Bobcat00** [comment]
One of my players built an automated pumpkin farm.  When a pumpkin grows, it triggers a redstone torch + redstone dust + piston loop that runs until the torch burns out,  It looks to me that the loop activates 8 times for one pumpkin.  So that's 16 piston operations.  But he has these in rows of 9, and when the torch is reactivated, it also activates the torch two blocks away (I really don't understand how that happens).  So we have 16*9=144 piston operations every time a single pumpkin grows.  And he has row upon row upon row of these.  So the TPS goes down to 14.  If I get rid of the claim, the TPS stays at 20.

Another thing I don't understand is that the retract events seem to fire repeatedly for a single retraction, or at least many more times than the extend event.  Here's what I got from running timings:

`GriefPrevention v16.8`
`     BlockPistonExtendEvent      Time:     648390455  Count:  15924  Avg:  40717`
`     BlockPistonRetractEvent  Time: 139000151429  Count: 205664  Avg: 675860`

Besides the fact that the average processing time for a retract event is 675 usec, you can also see that there are 13 times as many retract events as extend events.  So that makes a bad situation 13 times worse.

If you could shed some light on what is happening, I would appreciate it.

**Comment by RoboMWM** [comment]
Please include timings link.

**Comment by RoboMWM** [comment]
> A better approach might be to check when pistons are placed to make sure the head can't extend into a land claim.

This fails to account for a variety of things, such as slimeblocks.

**Comment by NullCase** [comment]
I too noticed that retract events are more numerous than extend events. Seems interesting.

**Comment by NullCase** [comment]
@bigpresh Do you use Paper?

Regarding the sweeper, it's worth a note that the '3 sweepers' mentioned fire way faster than traditional observer block sweepers. Observer ones have been OK.

Actually, idk if this counts but it seems like the clock wants to fire the piston even faster than it actually is.

**Comment by Bobcat00** [comment]
> Please include timings link.

I use CraftBukkit 1.12.2, so that's all the timings we get.  It shows the time for the extend event is 40 usec and the time for the retract event is 675 usec.  The timings above were run for 5:35 or 335 seconds.  So the total time of the extend event was 0.19% of the total and the retract event was 41.5% of the total.

**Comment by NullCase** [comment]
Some follow up:

It seems that pistons do not always cause this event to lag up a storm. Recently one of the guys built a piston heavy wither skeleton farm. lots of pistons that are active all the time.

The farm normally does not cause lag problems, however after running the farm for a while without incident the farm suddenly 'flipped' and that block piston event started causing loads of lag. It happened when one player logged off.

In the timings report: normal use for a long time, then 6 players drops to 5 and lag spikes.

https://timings.aikar.co/?id=9ba885fc012d4ee0a87742b94581d76b#timings

So I just stopped the farm & started it again. The Piston event lag vanished.

https://timings.aikar.co/?id=b8cd23b736f442f5a258ef4e303e3605

**Comment by NullCase** [comment]
Adding info: Piston lag reappared today. I simply repeated the above. This time the lag persisted. So, inconsistent results here.

It's clear that

a) the event doesn't always cause lag.

b) when it appears it can vanish without a server restart (as above, stop/starting the farm) **but** 

c) that solution isn't working consistently.

https://timings.aikar.co/?id=92979c8e150143f3ac14f916f7f648be

**Comment by Bobcat00** [comment]
Can you tell if the lag occurs because:
1. A piston event was firing repeatedly when only once would be expected, or
2. The time GriefPrevention takes to process the event has increased?

**Comment by NullCase** [comment]
It sounds like you're wondering about the more specific cause. I don't know, but those are both good questions.

What do you suggest as a way to get good answers? Because idk how to code but @RoboMWM usually finds a way to deal with me OK. :D

**Comment by NullCase** [comment]
Here's a fresh timings report. https://timings.aikar.co/?id=9882efaf5d0e41e795b70276c0254198

The same farm is running. It's probably been going non-stop since yesterday. No piston lag. Server is at 20 TPS but at 43 ms per tick its pretty full.

What if the server gets overloaded and once it's overloaded ... for some reason this event is backlogged? Could that be a thing?

Because I understand spigot is supposed to just 'skip stuff' if the server gets full, but maybe this event is never skipped?

**Comment by Bobcat00** [comment]
Just noticed your timings post.  I see 42 piston retract events for each piston extend event.

The per event timing doesn't look bad at all.  Are you sure these pistons are in a claim and that GP is enabled in the world?

**Comment by NullCase** [comment]
GP enabled in the world and pistons inside the claim. Yep.

The mismatch you've noticed in retract/extend events is interesting. It seems like a good place for hints about whats going on.

**Comment by Bobcat00** [comment]
I have over 200 claims. I wonder if that makes the checks take longer.

**Comment by RoboMWM** [comment]
> I have over 200 claims. I wonder if that makes the checks take longer.

No unless they're all next to each other in the same chunks

**Comment by NullCase** [comment]
The sweepers have slime blocks. about 9 per sweeper.

It seems like that matches up well with the # of extend events per retract event. I don't know.

Here's a new timings report.

https://timings.aikar.co/?id=8952e10a6e32416b955cf30da5195401

**Comment by NullCase** [comment]
OK, reloading the area fixed the glitched out event.

So the event was going like above. we unloaded the area. loaded it back up and the event is gone.

**Comment by Bobcat00** [comment]
So the BlockPistonExtendEvent took 29 msec for GP to process it, then it got better after you restarted the server?

**Comment by NullCase** [comment]
just reloaded the area. left, came back.

no server restart. just moved to another location until it was unloaded.

**Comment by NullCase** [comment]
i don't know if this helps, but we've learned a few more things.

1) reloading the area works every time since figuring that bit out. Just leave until it unloads. come back. its fine.

2) The pistons are glitching out about once per day.

**Comment by NullCase** [comment]
Setting `LimitPistonsToLandClaims: true` (from false) appears to solve this problem. Testing now and will post back with results in a few days.

**Comment by NullCase** [comment]
`LimitPistonsToLandClaims: false` seems to be the problem, because it's fine now when using the default setting / 'true'

What do you figure is causing this setting to produce piston event lag?

**Comment by RoboMWM** [comment]
Big_Scary had that option to default to true for this performance reason. Pistons outside of land claims need to check if they're affecting something that's in a claim. Having them flat out disabled avoids the need to perform this check.

**Comment by Bobcat00** [comment]
But that means pistons won't work at all outside of a claim, correct?

**Comment by NullCase** [comment]
@bobcat00 that's correct.

@roboMWM Do you think the way it's implemented is the best solution available?

In case it's not the best, I'm ready to fund some development work on GP for 1.14. This and #546 are both interesting to me.

What's next for you and what do you need before considering work on these two issues?

**Comment by MithrandirCraft** [comment]
> I'll see what can be done to optimize in v20.

So considering this is the main ticket refering to this issue, and it's closed, have any improvements been implemented for v20?

**Comment by RoboMWM** [comment]
The ticked was closed due to pulling a PR adding the config option, as referenced in the closing notification. #671
