### ISSUE TITLE
no support mmoitems abilities (damage animals)

### ISSUE THREAD

**Issue by Yukylyu** [GriefPrevention/GriefPrevention#483]
Hello, grief prevention doesn't block the abilities of mmoitems, i can use a shulker attack, the animals take damage from falling, or for example "corrupt" wither effect of mmoitems does damage despite the warning of grief prevention.
**plugin mmoitems:**
https://www.spigotmc.org/resources/mmoitems-90-item-options-60-abilities-item-edition-gui.39267/
**abilities mmoitems:**
https://www.spigotmc.org/wiki/ability-list-i/
https://www.spigotmc.org/wiki/ability-list-ii/
https://www.spigotmc.org/wiki/ability-list-iii/
**video:**
https://www.youtube.com/watch?v=NXIu-gdfjlc&feature=youtu.be

**Comment by RoboMWM** [comment]
Will take a look at video later. Please include the other information in the template you deleted.

**Comment by Yukylyu** [comment]
is it possible to correct this? otherwise I would have to make worldguard claims :(

**Comment by RoboMWM** [comment]
Oh, you added more info. I guess GitHub doesn't notify on any edits.

So the plugin needs to either add compatibility with GP or fire its own events. GP can't block something if it doesn't know what happened.

If it fires projectiles, it could set the source as the player who fired them. Or if it's direct, the entity#damage has an overload for setting the source entity.

---

Also, afaik that's not a proper use of the spigot wiki, those pages should be removed... (I could be entirely wrong on this though; if I am, I'm not sure of the reasoning behind why plugin documentation should exist on a server mod wiki.)

**Comment by Jikoo** [comment]
>Also, afaik that's not a proper use of the spigot wiki

I believe that's how Spigot opted to handle additional plugin pages with their resource system, a lot of plugins seem to do it.
