### ISSUE TITLE
Naming claims

### ISSUE THREAD

**Issue by BaronyCraft** [GriefPrevention/GriefPrevention#485]
This is a thing that has irked me for quite a while - when you have more than a few claims, remembering which is which in /claimslist is hard. I'd like to have a /claimname command that can give the current claim a name, and which is shown in /claimslist next to the claim position/size info.

This could also be a nice addition to any dynmap plugins so they can actually show a name for a claim, especially in admin-claims so admins can tell people what an area is about.

I already implemented this in my fork, but the load/save code is in FlatFileDataStore only, not DatabaseDataStore, as I'm not using that. I'm happy to implement it in DatabaseDataStore as well, and send you a pull request - however, I don't want to bother if you think this shouldn't be in the plugin and won't merge it anyways. So, please tell me if you're interested in me finishing this?

**Comment by RoboMWM** [comment]
I've already made an addon for this, ClaimslistClassifier.

Unsure what you mean by the load/save code.
