### ISSUE TITLE
Lag spike (split out from #468)

### ISSUE THREAD

**Issue by bigpresh** [GriefPrevention/GriefPrevention#486]
https://timings.aikar.co/?id=3cdd0e1f998443a3a58d336bf9634874
My server crashes almost every single day at almost the same time, luckily it didnt crash it this time so I could make a timings report

Thu, 21. Feb 2019 19:24:28 EST 
Tue, 19. Feb 2019 19:18:44 EST 
Mon, 18. Feb 2019 19:28:45 EST 
Sun, 17. Feb 2019 19:24:31 EST 
Sat, 16. Feb 2019 18:55:20 EST 
Fri, 15. Feb 2019 19:29:53 EST ...

Here is log
https://pastebin.com/1ZJj09nf

P.S Actually I am unsure if this is the same thing and should I've made a new issue form instead of replying to this

_Originally posted by @Darkweasam in https://github.com/TechFortress/GriefPrevention/issues/468#issuecomment-466749709_

**Comment by bigpresh** [comment]
I don't see anything in the timings that really suggests that GriefPrevention is to blame here.

I do see that quite an amount of time was being spent ticking entities.

**Comment by Darkweasam** [comment]
I am certainly sure that you didnt move the blue slide dots to see the correct timings part

Please move those small dots to the correct time of the timings, here I attached a screenshot of what I am talking about: https://i.imgur.com/MLOPORY.png

**Comment by RoboMWM** [comment]
This was the result of a user running /abandonallclaims, and I guess some of these claims are in creative worlds so they trigger a cleanup task.

Since this is also a data operation, this also points to a slow SQL connection/server.

**Comment by RoboMWM** [comment]
There's nothing different in here than in #468 other than this one is the result of a command instead of an event, iirc. Not sure why #468 was closed if it wasn't resolved, no idea why we would be opening a new one.
