### ISSUE TITLE
Prevent Negative Claim Blocks

### ISSUE THREAD

**Issue by BiGUNMAN** [GriefPrevention/GriefPrevention#497]
### What happened:
You can transfer a claim to a friend via the transferclaim command and get the person into negative claim blocks. 

### What you expected:
A config option that prevents players from transferring claims to other players that don't have enough claim blocks.

### Steps to reproduce:
1. Create a claim that is larger then the amount of claim blocks another player has.
2. Transfer the claim to that player with less claim blocks then the claim being transferred.
3. Player now has negative claim blocks.

**Comment by RoboMWM** [comment]
Transferclaim is an admin command. An addon can provide this if you wish.
