### ISSUE TITLE
TNT protection based on rank

### ISSUE THREAD

**Issue by vntqmm** [GriefPrevention/GriefPrevention#5]
Hello, being totally stoked about how user-friendly this plugin was, i went ahead and bought GP Flags.

Now I’m wondering if it is possible to have TNT protective claims for some ranks and others not (let's say donors get tnt protection but regular players do not - so maybe trough permissions?), with GP and GP Flags plugins?

If so, could you please let me know how?

Kind regards

**Comment by RoboMWM** [comment]
I have a feeling I responded to this... but the comment isn't here. Ugh.

Anyways, I stated that `/claimexplosions` is currently a temporary toggle that resets when the player disconnects (for good, hopefully obvious reasons). Making this persistent in GriefPrevention itself would call for database changes.

It is possible to override GriefPrevention's TNT protection via another plugin, and it'd probably be the best way to implement this request, considering that there are no persistent "flags" in GriefPrevention itself other than the "global" ones in the config.

Please note that I do not currently maintain the GriefPrevention Flags plugin. [I may take it on in the future if life allows for it.](https://www.spigotmc.org/threads/griefprevention.35615/page-151#post-1906977)

**Comment by vntqmm** [comment]
Aw - I'm sorry to hear that it's only a temporary flag. - Thanks a bunch for the help answer, I'll definitely look for a compatible plugin that can handle the TNT protection and works with GP.

Would you suggest i talk to the person who maintain GP Flags for this as well - maybe they will have another idea?

Kind regards

**Comment by RoboMWM** [comment]
Yes, post in the discussion section for that plugin.

Alternatively, you could also post a request for other developers to make this addon.

(btw, the temporary toggle is due to "what if a player forgets to turn it off when they log out?")
