### ISSUE TITLE
GriefPrevention startup error. Claim data loading issue

### ISSUE THREAD

**Issue by aljaxus** [GriefPrevention/GriefPrevention#50]
### What behaviour is expected:
Clear console on startup

### What behaviour is observed:
An error on startup, while loading claims data (i suppose)

### Spigot/Craftbukkit/Paper and GriefPrevention version:
CraftBukkit version git-Spigot-e000104-4cb3258 (MC: 1.9.2)
GriefPrevention v14.7

### Stack trace/error (if applicable)
http://hastebin.com/ebebibitor.sql

### GriefPrevention config.yml (if applicable)
http://hastebin.com/yihayewuha.php

### Plugin list (if applicable):
http://hastebin.com/ubudowidav.lisp

**Comment by RoboMWM** [comment]
`2016-12-06 16:20:12 | GriefPrevention: 1638.yml java.lang.NullPointerException`

Claim file 1638 is corrupted. I'm going to guess your hard drive was full at one point. Please either delete or fix this file.

**Comment by aljaxus** [comment]
Thank you for reply. 
I did figure that out the next time i checked the database and the error.

Have a nice day.
   Lazos~
