### ISSUE TITLE
Grief Prevention overriding plot squared

### ISSUE THREAD

**Issue by animeshirk** [GriefPrevention/GriefPrevention#503]
upon relogging onto the server after claiming a plot using /plot claim from the plot squared plugin the user is no longer able to edit the plot due to grief prevention even though it is still claimed by them.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. have both plot squared (haven't tested any other plot plugin yet) and grief prevention installed
2. claim a plot using the /plot claim command
3. relog and try to break blocks
4. If it worked correctly (well......incorrectly I guess) then it will say that you can not build here unless you claim some land first and will provide a link to a video describing how to claim land

GriefPrevention version 16.11.6

### Plugin list (if applicable):
bPermissions
Essentials
GriefPrevention
Hubthat
LaggRemover
Multiverse-Core, inventories,nether portals, and portals
NoCheatPlus 
vault
worldedit
plotSquared
WorldGuard

**Comment by RoboMWM** [comment]
Disable GP claims for that world, see config and set world to `Disabled`.

See wiki for more documentation.
