### ISSUE TITLE
Incorrect credit in recent release 16.11.6

### ISSUE THREAD

**Issue by WesternIcelander** [GriefPrevention/GriefPrevention#504]
There's a problem with a credit on the following pages:
https://github.com/TechFortress/GriefPrevention/releases/tag/16.11.6
https://www.spigotmc.org/resources/griefprevention.1884/update?update=267870
https://dev.bukkit.org/projects/grief-prevention/files/2683452

where @sigurdur (not me) was credited instead of @Siggi88 (that's me!)

The display name on my GitHub account is Sigurdur, so I can see how this has caused confusion.  Thanks in advance for fixing this!

**Comment by sigurdur** [comment]
I have changed my displayed name slightly so this is less likely to happen again in the future.

**Comment by WesternIcelander** [comment]
@sigurdur My name is Sigurður too, I was just lazy to switch to Iceland keyboard layout to type the ð LOL

**Comment by RoboMWM** [comment]
Oops, sorry! I think I was using the Github Desktop client when typing up the release (which shows the commit author name not github username) and must've put that. Thanks for letting me know.
