### ISSUE TITLE
Grief Prevention not creating any files

### ISSUE THREAD

**Issue by TastyBoii** [GriefPrevention/GriefPrevention#509]
I downloaded it and put it into my plugins folder on my Spigot 1.8 server. I reloaded the server multiple times, but grief prevention hasn't worked, nor has it created any config files. When i do /plugins in the game, grief prevention shows. Whenever I do a command, it says an internal error occurred. I'm guessing this is because there are no config files. Any solutions? ( I've tried re-downloading it)

**Comment by RoboMWM** [comment]
Use an older, 1.8-compatible version of GriefPrevention if you wish to run an older server.
