### ISSUE TITLE
Java warning on boot

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#510]
On boot while running Vault 1.7.1 and GriefPrevention 16.11.6 on PaperSpigot 607 I get this warning, the plugin does not seem to be affected and is working as intended.

https://hastebin.com/utacejuzov.cs

**Comment by 112RG** [comment]
This looks like it has nothing to do with GriefPrevention, and is coming from Vault

**Comment by Jikoo** [comment]
WorlEdit actually, but yeah, not a GP issue.

>`com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable`

**Comment by ghost** [comment]
Interesting, disabling GP or Vault mitigates this issue, I'll do some more testing.

**Comment by RoboMWM** [comment]
> disabling GP or Vault

Is it really either or? My guess is that it "goes away" if you disable vault. Nothing in here would indicate GP does anything, and GP only interacts with vault for economy.

Also missing the template you deleted.

**Comment by ghost** [comment]
Apologies for my ignorance, thanks for clearing that up.
