### ISSUE TITLE
Trident lightning does damage to players and mobs in a claim

### ISSUE THREAD

**Issue by ZepsiZola** [GriefPrevention/GriefPrevention#514]
When a player will channeling throws a trident at a mob or player in a protected claim, the lightning strikes and does damage. This shouldn't be the case as it allows griefers to kill other people's animals/mobs inside a player's claim even though the player's mobs should be protected inside their claim.

**Comment by RoboMWM** [comment]
Please fill out template that you deleted, particularly GP version
