### ISSUE TITLE
Administrator claim permissions not working

### ISSUE THREAD

**Issue by HeyaGlitz** [GriefPrevention/GriefPrevention#522]
### What happened:
Can't add permission groups to administrator claims

### What you expected:
A help page for that command

### Server and GriefPrevention version:
Server version: Paper version git-Paper-493 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) 
GriefPrevention version: 16.11.6

### Stack trace/error or server log
None needed, I think so

### GriefPrevention config.yml
Default

### Plugin list (if applicable):
EssentialsX
BetterRTP
ChatColor2
ChestShop
CoreProtect
CratesPlus
GriefPrevention
LaggRemover
MineableSpawners
PEX
Staff+
Sudo
Vault
setspawn
Worldedit-bukkit-7.0.0-beta-05

**Comment by RoboMWM** [comment]
What did you try? Did you resolve this issue?

**Comment by HeyaGlitz** [comment]
Yeah I'm just dumb, as always :)
/containertrust public
the administrator permission thingy isn't a thing though and may confuse people

**Comment by RoboMWM** [comment]
Hmm, I'm not sure if you can trust a specific permission node. If you can, you'd have to wrap it in square brackets e.g. `/trust [permission.node.here]` (including the square brackets). Don't know what you mean by "administrator permission thingy" though.

Thanks for responding!
