### ISSUE TITLE
adjustclaimblock command broken (1.14)

### ISSUE THREAD

**Issue by Kirikoza** [GriefPrevention/GriefPrevention#523]
### What happened:

When I tried giving myself or other players additional claim blocks the command gets stuck on the choosing player portion. For instance, I'll type /AdjustBonusClaimBlocks Kirikoza , but it doesn't allow me to type in an amount of blocks. Even after pressing space it assumes i'm still typing in a player name, so even when I type the full command /AdjustBonusClaimBlocks Kirikoza 10,000 , it assumes " 10,000" is part of the player name, thus leaving the command incomplete and nonfunctional. This happens with the /acb version of the command and when typed in the command block.

### What you expected:

I expected the command would work and I would be able to set claim block amounts for people.

### Steps to reproduce:

1. Step 1. Download v 16.11.6 to a 1.14 sever
2. Step 2. Try the command /AdjustBonusClaimBlocks to see if it works for you

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 1.14
Paste of `/version GriefPrevention`: 16.11.6

Note: I'm using the most up to date version of GP that I could find, i don't know if there's a dev build available. This is all using the 1.13.2 version of the mod on a 1.14 server so I was prepared to face some bugs.

**Comment by RoboMWM** [comment]
Try without a comma in the number.

Also fyi, reproduction steps should be as specific as possible, I.e. The exact command as inputted in the chat box.

**Comment by Kirikoza** [comment]
> Try without a comma in the number.

ok admin delete this post commas aren't allowed
