### ISSUE TITLE
Claiming in Nether only extends to y=128

### ISSUE THREAD

**Issue by dooshiifox** [GriefPrevention/GriefPrevention#526]
### What happened:
Claiming things doesnt happen above the roof bedrock level in the Nether, at least with pistons.

### What you expected:
Pistons moving when given a redstone pulse.

### Steps to reproduce:
1. Create a claim in the nether. It could be on the ground or above the bedrock,
2. Place a piston above the bedrock.
3. Give power to the piston.
4. Nothing happens.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: This server is running CraftBukkit version git-Spigot-1eece4f-fe1100c (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: 16.11.5

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

[Default config.yml except for enabling claims in the Nether]

```

**Comment by RoboMWM** [comment]
And this works if GP is disabled?

**Comment by dooshiifox** [comment]
yes, all usual things will function with it off

**Comment by NullCase** [comment]
does it move if you enable pistons outside claims?

Because we have claims above the bedrock with pistons, but pistons are permitted to move outside and the claims do extend >128.

**Comment by RoboMWM** [comment]
Looked at the code, did a search on nether, and didn't find anything that has any height-specific things for pistons anywhere. I'll eventually try testing myself when I spin up a server where I don't have void damage occurring at the nether ceiling.

**Comment by Jikoo** [comment]
Please reproduce using new piston settings - piston logic has been entirely rewritten.
