### ISSUE TITLE
Claimlist teleport

### ISSUE THREAD

**Issue by LogGits** [GriefPrevention/GriefPrevention#527]
Could you add a way to teleport to the claimlist location by clicking on it.

**Comment by RoboMWM** [comment]
I believe this is already available in the ClaimClassifier addon.

**Comment by TomLewis** [comment]
@LogGits https://github.com/RoboMWM/ClaimClassifier

**Comment by RoboMWM** [comment]
Thanks for linking. (I was on phone so wasn't able to do that when I commented.)

Hmm, I should really get that published.
