### ISSUE TITLE
My server crashed because of someone running /abandonallclaims

### ISSUE THREAD

**Issue by ZeroThinking420** [GriefPrevention/GriefPrevention#53]
### What behaviour is expected:
Server was running fine before the crash, however it is important to note that I'm still running an old version of GriefPreventionFlags (version 4.5.2 for 1.10+ Servers), I really need some of the functions of GPFlags so I took the risk and left it running anyways.
### What behaviour is observed:
So I was just sitting in-game on my server then next thing I'm kicked because the connection timed out.
After looking at console it appeared that GriefPrevention was the cause of my server crashing, I say this due to the error that i'll post below but also because of the commands that had recently been run before the server crash. 

Here is the link to the error in pastebin, for some reason the link wouldn't work properly so you may have to copy/paste it into your browser...

http://pastebin.com/gwEGn4sC

**Comment by ZeroThinking420** [comment]
@RoboMWM

**Comment by RoboMWM** [comment]
FYI, tagging me won't notify me any more than just posting an issue.

Secondly, this is not a GriefPrevention Flags issue. I need you to get the version of GriefPrevention as specified in the issue template `/version GriefPrevention`

**Comment by ZeroThinking420** [comment]
This is a rather urgent problem, for now I've used worldguard to block /abandonclaim and /abandonallclaims in order to allow players to play on the server while I fix the issue and hopefully prevent it from happening again.

**Comment by ZeroThinking420** [comment]
My version of GriefPrevention is...

>version GriefPrevention
[02:55:48 INFO]: GriefPrevention version 16.4



Also here is a list of my plugins...

[03:01:11 INFO]: Plugins (30): CoreProtect, AsyncWorldEditInjector, GroupManager, Chairs, WorldBorder, BuycraftX, Lockette, ProtocolLib, AsyncWorldEdit, iDisguise, Stargate, ZephCore, OrePlus, FlyCheck, Vault, WorldEdit, Admin-Chat-Channel, NoirFly, Essentials, WorldGuard, iDisguiseAdditions, VanishNoPacket, EssentialsChat, PhatLoots, NoirlandAutoPromote, BankOfNoir, EssentialsSpawn, GriefPrevention, NoirGuilds, GriefPreventionFlags



See the link below for screenshots of the subdevison that EFFX was standing in when he ran abandonallclaims...

http://imgur.com/a/ljFsT

**Comment by ZeroThinking420** [comment]
Is there any other info you need at the moment?

**Comment by RoboMWM** [comment]
So, my guess is that there's an issue with your server operating system (in this case, whatever Linux OS you're using). It's hanging on this line: https://github.com/TechFortress/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/FlatFileDataStore.java#L586

Apparently Java is hanging when it calls File#exists. I'd google/bing/whatever those keywords (java hanging on File#exists)

**Comment by ZeroThinking420** [comment]
Ok, thank you for you help.

**Comment by RoboMWM** [comment]
Did you resolve this issue?

**Comment by RoboMWM** [comment]
@ZeroThinking420 just pushed out a fix which may have been related to this issue.
