### ISSUE TITLE
Ravagers can break blocks inside of claims.

### ISSUE THREAD

**Issue by Moobuttt** [GriefPrevention/GriefPrevention#530]
Currently Ravagers are able to break blocks inside of claims. I have the most recent version of GriefPrevention on my server, and it works just fine on 1.14 aside from this particular issue as far as I've seen. But I think it's definitely worth an update to fix this issue.

**Comment by RoboMWM** [comment]
Ok but you should still fill out the template...

**Comment by Moobuttt** [comment]
My apologies, no template was given for the option I chose. (Between bug and enhancement/request, I believe it was. I chose enhancement/request.)

I can edit if needed.

**Comment by RoboMWM** [comment]
> I chose enhancement/request

Oh, is this not a bug?

**Comment by Moobuttt** [comment]
Nope, not a bug. I don't consider it one at least since the most recent version of GP (at the time I submitted this originally) was not made with some of the new 1.14 features in mind. So I figured it'd just be something to add to it once you were working on the next updates.

At the time I had noticed a few people mentioning that GP worked perfectly fine with 1.14 and had seen no mention of Ravager's ability to break blocks inside claims, so I wanted to bring your attention to it via a request. Sorry for any confusion! If you need any more info let me know.

**Comment by RoboMWM** [comment]
If a new thing in 1.14 breaks intended functionality of GP, it should be considered a bug. Since I have no idea what ravagers are or what players can do with them, can you explain what the issue is here?

**Comment by Moobuttt** [comment]
Alright, I'll keep that in mind if I submit anything in the future then.

Here's some context: Ravagers are a new hostile mob introduced as a part of village raids. In these raids, there are waves of pillager type mobs that spawn in the area surrounding a village in an attempt to attack said village. Each wave is activated by the defeat of the previous wave of spawned mobs. Ravagers begin spawning around wave 2 or 3. These raids will result in these mobs spawning inside of any area within a range of 0-1024 blocks, claimed or not.

As far as the actual issue goes: Ravagers can destroy plant based blocks while chasing any mob it is hostile toward, which would leave any structure made of these types of blocks (leaf block bushes/fences, farms, etc) open to damage. Here's a list of what they can break (as well as their wiki page in general, I assume that may be helpful overall) https://minecraft.gamepedia.com/Ravager#Behavior

Ravagers are also rather large mobs that move fairly quickly, so the grief they can deal can get to be pretty extensive if someone led one into claimed land. I've attached some screenshots of the type of damage they can do. I hope this helps!

![2019-06-12_21 55 17](https://user-images.githubusercontent.com/50687681/59398154-242e4d80-8d5d-11e9-9591-30c5bc552eca.png)
![2019-06-12_21 55 44](https://user-images.githubusercontent.com/50687681/59398156-255f7a80-8d5d-11e9-9b7d-9d2f4654a0cf.png)
![2019-06-12_21 55 46](https://user-images.githubusercontent.com/50687681/59398157-25f81100-8d5d-11e9-8327-5d96fcf3bc91.png)

**Comment by RoboMWM** [comment]
Alright, thanks. I guess the event they fire isn't exactly similar to enderman when they pick up blocks or players/entities trampling crops so this is interesting.

**Comment by Jikoo** [comment]
They call the [EntityChangeBlockEvent](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/EntityRavager.patch#17), same as endermen. GP's [handling](https://github.com/TechFortress/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java#L132) for this special cases certain entity types and interactions due to the number of scenarios where the event is fired. Personally, I would prefer to see a config option added along with this.
