### ISSUE TITLE
Restore Nature sucks water from nearby oceans?

### ISSUE THREAD

**Issue by lordrius** [GriefPrevention/GriefPrevention#535]
Hi!

I'm trying GriefPrevention's restore nature command and it sucks nearby water from the sea...

https://i.imgur.com/6AzhfDx.png

Is anything i can do to fix it?

Using GriefPrevention 16.11.6 along with Paper 1.14.2. No plugins.

Many thanks!

**Comment by RoboMWM** [comment]
since worldgen changed in 1.13 restorenature hasn't been the same. Some efforts were made to fix some of it.

**Comment by RoboMWM** [comment]
Discussion moved to #543
