### ISSUE TITLE
killing using fireworks inside claim

### ISSUE THREAD

**Issue by ArtNRG** [GriefPrevention/GriefPrevention#538]
### What happened:
An untrusted player can kill someone using fireworks inside a claim.

### What you expected:
An untrusted player can't kill players using fireworks inside a claim.

### Steps to reproduce:
1. Create a claim, build there the box with the low roof and stay there.
2. Use an untrusted player to kill the owner.
Screenshot: https://i.imgur.com/Z0jAu0L.jpg

### Server and GriefPrevention version:
Paper version git-Paper-571 (MC: 1.13.2)
GriefPrevention version 16.11.6

**Comment by RoboMWM** [comment]
> [09:05:55] cities7: RoboMWM: disabled pvp in server.properties. explosions from rockets fired in crossbows apparently still damages people. dumb mojang

I guess I could go ahead and modify vanilla behavior. Ergh.

**Comment by RoboMWM** [comment]
After spending half an hour attempting to craft a firework that actually does damage, I discover that the resulting explosion does not have a source set. Thus this may be impossible to implement without making players completely invulnerable to any firework explosions...

**Comment by RoboMWM** [comment]
Unless if the source contains the actual firework entity, then it may be possible to obtain the who fired the firework...

**Comment by ArtNRG** [comment]
@RoboMWM we can block firework firing in the claimed area if the player isn't trusted and if there is someone near who can be damaged by the explosion. Same logic as blocking lava buckets near players.

**Comment by RoboMWM** [comment]
Idk how that's gonna work for crossbows.

**Comment by Vimppura** [comment]
Btw fireworks can also be used to kill animals inside land claims. And also players can be killed with just firework OR a crossbow equipped with one, even tho pvp is disabled in the whole world. (Just to clarify things, didn't want to create new ticket for similar issue)

We have 
Server: git-Paper-126 (MC: 1.14.3)
GP: 16.11.6

**Comment by RoboMWM** [comment]
Ya, was mentioned in IRC, but yea perfectly acceptable here since it's the same issue.

**Comment by RoboMWM** [comment]
Idk if the explosion sources the firework entity that caused it, and if so, if it's even possible to determine if that rocket was fired and by whom.

If someone can figure that out that'd be helpful

**Comment by NullCase** [comment]
I dont know if this helps @ArtNRG but this issue is being worked on by @elmhoe here: https://github.com/ElmHoe/PVPToggle/issues/10

We've worked on PVPtoggle for a couple of years. It's crazy light weight. And its what I use.

**Comment by zedwick** [comment]
I don't know what your thoughts are about having Paper-specific fixes, but Paper has an API for getting the player who launched/fired a firework.

https://github.com/PaperMC/Paper/blob/ver/1.14/Spigot-API-Patches/0045-Fireworks-API-s.patch#L30
https://github.com/PaperMC/Paper/pull/2358 <-- Fixed to provide source when fired from crossbow

**Comment by RoboMWM** [comment]
For this project I've been sticking to just the Bukkit API, as that has been its dependency historically. Thanks for the info though, will be useful for perhaps an addon.

Looking at the patch, it seems to just get an entity that's being boosted when consuming a firework (e.g. while flying an elytra)?

**Comment by zedwick** [comment]
That’s getBoostingEntity. Above that is getSpawningEntity.

**Comment by RoboMWM** [comment]
Ah I see, no javadocs for that method
