### ISSUE TITLE
Does Grief Prevention actually block world edit if show tell me how because mine doesn't

### ISSUE THREAD

**Issue by Willmaster04** [GriefPrevention/GriefPrevention#54]
I expected Grief Prevention to block world edit because it could be used as a malicious greifing tool in the wrong hands an be very dangerous
 
I saw that Grief Prevention actually allowed one of my players to remove part of spawn with commands with no issues for the griefer

I run the latest version of Spigot with a 16.4 version of Grief Prevention

 I haven't touched the new Grief Prevention config

Here is the plugin list
https://images.discordapp.net/.eJwNyMENwyAMAMBdGAC7pgTINoggEjXBCDvqo-ru7T3vY-55mtXsqkNWgO2QwnOzojxzq7Yxt7PmcYgtfEFWzWW_alcB8g9MjgKlsHi_oKN_RYcuPhMmwhgiRrj7q_O729Gb-f4AB2gi4g.F7dGVuSkY_vFDVEwou0As6Cqu_k

I hope you can tell if there is a way to block world edit on the admin claims thank you in advance for your help

**Comment by Jikoo** [comment]
GP doesn't block WorldEdit, no standard vanilla actions are required to use it. You're after an add-on plugin such as [WorldEditRegions](https://www.spigotmc.org/resources/worldeditregions.448/).

**Comment by RoboMWM** [comment]
> I expected Grief Prevention to block world edit because it could be used as a malicious greifing tool in the wrong hands an be very dangerous

The GriefPrevention plugin only does what is stated in the plugin overview page (and what's in this repo obviously). It doesn't manage permissions for you; it won't stop you if you decide to give op/worldedit permissions to everyone...
