### ISSUE TITLE
/trust public to select group and not a player named publiclystark

### ISSUE THREAD

**Issue by GhostSavag3** [GriefPrevention/GriefPrevention#541]
### What happened:
Trying to use /trust public command but I have a player on my server whose name is publicystark. Won't allow public to be used. 

### What you expected:
/trust public to trust the group public. 

=

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Paste of `/version GriefPrevention`:

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

**Comment by RoboMWM** [comment]
Hmm, I wonder if it's doing a `getPlayer` instead of `getPlayerExact`

**Comment by RoboMWM** [comment]
Can you please paste the GriefPrevention and server version as requested in the template?
