### ISSUE TITLE
griefprevention.notignorable not working properly

### ISSUE THREAD

**Issue by plasticblues** [GriefPrevention/GriefPrevention#55]
### What behaviour is expected:
Player A should ignore Player B and Player B should ignore Player A
### What behaviour is observed:
Player A is ignoring Player B but Player B can still send PMs to Player A
### Steps/models to reproduce:
/separate Player A Player B

### Spigot/Craftbukkit/Paper and GriefPrevention version:
This server is running CraftBukkit version git-Spigot-f950f8e-0a6a5cb (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)

GriefPrevention version 16.4

### Stack trace/error (if applicable)

No Stacktrace

### GriefPrevention config.yml (if applicable)
```
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world: Survival
      world_the_end: Survival
      world_nether: Survival
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 1000
    Claim Blocks Accrued Per Hour:
      Default: 500
    Max Accrued Claim Blocks:
      Default: 27000000
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 5
    ExtendIntoGroundDistance: 256
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 27000000
      UnusedClaimDays: 27000000
      AllClaims:
        DaysInactive: 27000000
        ExceptWhenOwnerHasTotalClaimBlocks: 27000000
        ExceptWhenOwnerHasBonusClaimBlocks: 27000000
      AutomaticNatureRestoration:
        SurvivalWorlds: true
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: false
    PortalGenerationRequiresPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 0
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: true
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: false
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: true
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: false
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: true
  BanCommandPattern: litebans:ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 180
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

### Plugin list (if applicable):
Plugins (24): WorldEdit, VoteRoulette, OpenInv, LogBlock, PermissionsEx, ClearLag, XrayInformer, WorldBorder, BuycraftX, Vault, Votifier, VoteParty, WorldGuard, ProtocolLib, eZProtector, Orebfuscator4, Essentials, EssentialsChat, LiteBans, EssentialsSpawn, GriefPrevention, Statz, WorldGuardExtraFlags, Autorank
```

**Comment by plasticblues** [comment]
Another note, I have griefprevention ignore overridden to essentials ignore as players are still able to ignore players with the griefprevention.notignorable permission, not sure why but it is possible, I only use seperate as a staff side command, not sure if that could be causing this.

**Comment by RoboMWM** [comment]
Please do not remove the formatting marks. These help make things like the config.yml look a bazillion times nicer when you paste it in.

> Another note, I have griefprevention ignore overridden to essentials ignore as players are still able to ignore players with the unignoreable permission, not sure why but it is possible, I only use seperate as a staff side command, not sure if that could be causing this.

Can you please rephrase this? I'm not exactly sure what you're asking about here...

**Comment by plasticblues** [comment]
Sorry about the formatting I just copy pasted, next time I'll make sure the formatting is in tact.

> Can you please rephrase this? I'm not exactly sure what you're asking about here...

When a permission group has the griefprevention.notignorable permission players are still able to /ignore a player in that permission group, this also applies when the permission is directly assigned to the player. When a player ignores someone with the above stated permission the player with the permission or the player in a group with said permission cannot send the player a message. It acts as if the griefprevention.notignorable permission is not assigned. I hope that makes sense.

However this is another problem entirely, if you like I can make another bug report for it as well.

Thank you and I hope you're able to squash the /separate bug :). If you need any further information about either bug let me know and I will try to provide it.

**Comment by RoboMWM** [comment]
What's weird is that even just an /ignore on one end should also stop both players from messaging each other as well...

> When a permission group has the griefprevention.unignorable permission players are still able to /ignore a player in that permission group, this also applies when the permission is directly assigned to the player. 

Eh, keep it here for now. If you can also run some tests (with just spigot and GP) that would help.

**Comment by Jikoo** [comment]
>I have griefprevention ignore overridden to essentials ignore

To clarify, when you use /ignore, it uses /ignore from Essentials? GP doesn't support Essentials' ignore, you'll need to use GP's ignore function for GP's separate function to work.

If you're having trouble with Essentials' /ignore overriding GP's /ignore, add an alias to your commands.yml:
```yaml
aliases:
  ignore:
  - griefprevention:ignore $1-

**Comment by plasticblues** [comment]
> To clarify, when you use /ignore, it uses /ignore from Essentials? GP doesn't support Essentials' ignore, you'll need to use GP's ignore function for GP's separate function to work.

We are using seperate as an admin side command and essentials ignore as a player side command so basically when we need to forcibly separate 2 parties a mod can run separate (griefprevention), when a player wishes to ignore another player they use ignore (essentials). Are you saying it must be one or the other meaning to make separate work I must use GP ignore throughout?

**Comment by plasticblues** [comment]
> Eh, keep it here for now. If you can also run some tests (with just spigot and GP) that would help.

Definitely I can start up my local test server, I have 2 accounts I can have logged in on said test server. What exactly do you need me to do? Just test functionality and be sure that griefprevention.notignorable works without any other plugins correct?

**Comment by plasticblues** [comment]
Alright so after doing some tests I can conclude 2 things here:
A. My initial bug report (/separate), this has to do with something interfering with griefpreventions ignore command, most likely it being essentials and they way I have that configured, however:

B. A player can still ignore (using the griefprevention ignore command not the essentials one) a player with the griefprevention.notignorable permission which is troublesome.

The main focus should now switch to fixing the griefprevention.notignorable permission being fixed as at least on my server a player should not be able to /ignore a member of staff.

The plugins I used to run this test are:
[00:49:38 INFO]: Plugins (2): PermissionsEx, GriefPrevention

I also gave the default /tell command to all players (both of my accounts) to test this, Player A has the griefprevention.notignorable permission, Player B can ignore Player A, Player A can now no longer send messages to Player B even though Player A is set to not be ignored in permissions.

Edit: Also the afformentioned unignorable permission is actually griefprevention.notignorable.

Edit2: I just verified after switching back to griefpreventions ignore system separate now works, this is on my live server, HOWEVER I also verified on my live server that players can still ignore me even though I inherit the griefprevention.notignorable permission from a lower group, this is also the case if I assign the permission directly to myself so its not a permission system issue it has to do with the griefprevention.notignorable permission.

If there is any further information needed please let me know.

**Comment by Jikoo** [comment]
>We are using seperate as an admin side command and essentials ignore as a player side command so basically when we need to forcibly separate 2 parties a mod can run separate (griefprevention), when a player wishes to ignore another player they use ignore (essentials). Are you saying it must be one or the other meaning to make separate work I must use GP ignore throughout?

>I also verified on my live server that players can still ignore me even though I inherit the griefprevention.notignorable permission from a lower group, this is also the case if I assign the permission directly to myself so its not a permission system issue it has to do with the griefprevention.notignorable permission.

Essentials' ignore won't respect GP's unignorable permission, so if you're interested in that feature, you either need to use GP's ignore or find a way to do that with Essentials. Based on your GP-only test it does seem that you've found a bug with it though, assuming your permissions are set up properly.

**Comment by plasticblues** [comment]
> Essentials' ignore won't respect GP's unignorable permission, so if you're interested in that feature, you either need to use GP's ignore or find a way to do that with Essentials. Based on your GP-only test it does seem that you've found a bug with it though, assuming your permissions are set up properly.

One thing I can try later is using a fresh permission file and giving my 2 accounts the proper permissions to run the test. But I do think this is a bug with GP. When I get time later today I'll run the above test to be 100% sure.

**Comment by RoboMWM** [comment]
Just to clarify, the ignore system in Essentials is entirely separate from the ignore system in GP. They do cause a similar effect, but the two systems do not communicate with each other. Hence why I am asking for tests only with GP installed (and a permissions handler I suppose). Any conclusions that you come to from observations on your live server may be incorrect due to confusing the two systems.

**Comment by plasticblues** [comment]
> Just to clarify, the ignore system in Essentials is entirely separate from the ignore system in GP. They do cause a similar effect, but the two systems do not communicate with each other. Hence why I am asking for tests only with GP installed (and a permissions handler I suppose). Any conclusions that you come to from observations on your live server may be incorrect due to confusing the two systems.

Robo, please read up 3 posts from your newest post, I have already run the test with just GP and PEX and posted my conclusion above. I've also re-posted it below

>Alright so after doing some tests I can conclude 2 things here:
?A. My initial bug report (/separate), this has to do with something interfering with griefpreventions ignore command, most likely it being essentials and they way I have that configured, however:
>B. A player can still ignore (using the griefprevention ignore command not the essentials one) a player with the griefprevention.notignorable permission which is troublesome.
>The main focus should now switch to fixing the griefprevention.notignorable permission being fixed as at least on my server a player should not be able to /ignore a member of staff.
>The plugins I used to run this test are:
>[00:49:38 INFO]: Plugins (2): PermissionsEx, GriefPrevention
>I also gave the default /tell command to all players (both of my accounts) to test this, Player A has the griefprevention.notignorable permission, Player B can ignore Player A, Player A can now no longer send messages to Player B even though Player A is set to not be ignored in permissions.
>Edit: Also the afformentioned unignorable permission is actually griefprevention.notignorable.
>Edit2: I just verified after switching back to griefpreventions ignore system separate now works, this is on my live server, HOWEVER I also verified on my live server that players can still ignore me even though I inherit the griefprevention.notignorable permission from a lower group, this is also the case if I assign the permission directly to myself so its not a permission system issue it has to do with the griefprevention.notignorable permission.

If there is any further information needed please let me know.

**Comment by plasticblues** [comment]
Alright so I've literally tested with just the following permissions now on a fresh file just to be sure that I'm not doing anything wrong (Plugins used for this test, Griefprevention and PEX):
```yml
groups:
  owner:
    permissions:
    - griefprevention.notignorable
  neophyte:
    permissions:
    - minecraft.command.tell
    - griefprevention.ignore
schema-version: 1
users:
  a6af5caf-f42f-400c-b6c2-1835827cf64b:
    group:
    - owner
    - neophyte
    options:
      name: Ikith
  dfc1cb12-4aae-417f-b891-e8a64e1290e7:
    group:
    - neophyte
    options:
      name: Flightdancer
```

The player flightdancer is still able to /ignore Ikith even though Ikith has the griefprevention.notignorable permission. From what I can tell this is a bug in griefprevention.

**Comment by plasticblues** [comment]
I hate to bother, but is there any news on this issue/any further information I need to give to get this bug worked out faster?

**Comment by RoboMWM** [comment]
I haven't had time to test at the moment nor look through the code just yet.

> to get this bug worked out faster?

If someone else could take a look through the code and comment here or PR that'd help too.

**Comment by Jikoo** [comment]
An aside: The PlayerEventListener, along with several other classes, is a hellhole of spaces and tabs. I'd really love to see the entire project autoformatted for some consistency to make it less awful to read. GitHub exacerbates the issue; tabs are 8 spaces here, though pretty much everywhere else they're 4.
I've taken the liberty of formatting the relevant snippet the way I like things for readability.

[PlayerEventHandler.java#L201-L227](https://github.com/TechFortress/GriefPrevention/blob/9e4db8fb3e25fa4ba25f62e2f471b092a45837e0/src/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java#L201-L227)
```java
//based on ignore lists, remove some of the audience
// Jikoo comment: Sender must be ignorable for recipients to be removed
if (!player.hasPermission("griefprevention.notignorable")) {
    Set<Player> recipientsToRemove = new HashSet<Player>();
    PlayerData playerData = this.dataStore.getPlayerData(player.getUniqueId());
    for (Player recipient : recipients) {
        // Jikoo comment: Recipient must be ignorable to be removed
        if (!recipient.hasPermission("griefprevention.notignorable")) {
            if (playerData.ignoredPlayers.containsKey(recipient.getUniqueId())) {
                // Jikoo comment: Ignored players removed
                recipientsToRemove.add(recipient);
            } else {
                PlayerData targetPlayerData = this.dataStore.getPlayerData(recipient.getUniqueId());
                if (targetPlayerData.ignoredPlayers.containsKey(player.getUniqueId())) {
                    // Jikoo comment: Ignoring players removed
                    recipientsToRemove.add(recipient);
                }
            }
        }
    }

    recipients.removeAll(recipientsToRemove);
}
```
The code may not be clean (I'd really prefer liberal use of `continue` instead of such heavy indentation) but it does appear to do exactly what it's supposed to.

* Unignorable sender skips recipient removal entirely
* Unignorable recipients always receive the message
* Ignored recipients are removed
* Recipients ignoring the sender are removed

I have not yet performed any actual testing because I'm way too busy playing every version of Doom I can in a row.

**Comment by RoboMWM** [comment]
> along with several other classes, is a hellhole of spaces and tabs

I've tried to keep it consistent with tabs (which is what I believe the majority of the code is), but idk what IntelliJ ends up doing unfortunately. Obviously refactoring these classes would be nice, but something I don't have the time to do at the moment. I'm trying to do it slowly as I go about updating various parts of the code. PRs welcome, however!

**Comment by Jikoo** [comment]
>PRs welcome, however!

If you're open to me running an autoformatter over the project, I'd be happy to add that to my big list of things to do during downtime, it's very quick and easy when linewrap isn't involved. It'd definitely cause a huge diff with a bunch of fluff though.
If yes, what style do you prefer? Braces on a new line? Tabs, like you said. Character limit per line before wrapping, if any? I generally go with 100 as a rough guide and then manually edit, but that does take much longer - the autowrap can make some pretty weird choices sometimes, and there's a lot to look over. Import organization? There are a thousand and a half options. If you have an example of how you want things to look like that might be easier than trying to communicate every last little tweak.

Edit: Oh yeah, and newlines. Git is supposed to clean out Windows' \r, but a lot of clients don't. I didn't actually check if GP is full of \n\r or just \n, but if it is, want that fixed up or just left as-is?

**Comment by RoboMWM** [comment]
Yea, I do newline braces.

Idk for line wrapping, hopefully there aren't too many long lines in the code?

I'm fine with either spaces or tabs. I'm assuming IntelliJ uses spaces though(?)

Idk for imports, generally fine to be left as-is for now. Would like to remove some wildcard imports at some point.

If you want to clean out extra line formatting tabs feel free to do so. The less extra stuff, the better.

**Comment by RoboMWM** [comment]
Ran through the code - `/separate A B` effectively causes A to `/ignore B`.
Looking at the code that handles whisper commands, it checks both the ignore list of the sender and receiver.

Also it seems that while it may be possible to successfully execute /ignore on a player with `griefprevention.noignorable,` their messages will still be heard (both whisper and normal chat messages).
