### ISSUE TITLE
1.14.x Trapdoor,Chest,Furnac,Door bug.

### ISSUE THREAD

**Issue by successed** [GriefPrevention/GriefPrevention#552]
fixed.

**Comment by RoboMWM** [comment]
Please do not delete issues, instead comment your solution in case others run into the same issue.

> What happened:
> in the claim other players oven, crates, trap doors, doors used.
> What you expected:
> http://prntscr.com/o3sk9t
> i have used worldguard version:
> WorldGuard 7.0.1 Beta 1 (MC 1.14+ ONLY)
> GP version: '16.11.6'
> GriefPrevention config.yml
> [config.zip](https://github.com/TechFortress/GriefPrevention/files/3305493/config.zip)


> Plugin list (if applicable):
> http://prntscr.com/o3smtq
