### ISSUE TITLE
Killing Polar Bears inside claims

### ISSUE THREAD

**Issue by x1p** [GriefPrevention/GriefPrevention#553]
Polar bears, kept inside claims can be killed by random players

Sure, I can understand that polar bears can be aggressive towards players, but are normally not aggressive, if not attacked. Polar bears are often kept as a pet.

This makes them vulnerable to grieving, creating disappointed players.

**Comment by RoboMWM** [comment]
Polar bears are not considered animals by Bukkit (spigot). Their neutral/attack when provoked is similar to pigmen.

Players on my server even keep hostile mobs as pets, and build proper structures to protect them.

Also, in PvP-enabled worlds, even wolves aren't protected (although this is a special case).

**Comment by x1p** [comment]
I listen to players and their logic.
It would be very nice if bears could be protected. I hope a workaround can be found.

**Comment by Jikoo** [comment]
Addressed by 766b34a - as long as the polar bear is not attempting to attack a player, attacking it will follow the same rules as passive animals.
