### ISSUE TITLE
Overlapping claims of two players

### ISSUE THREAD

**Issue by lemafor** [GriefPrevention/GriefPrevention#555]
### What happened:
I was informed about interesting situation with overlapping claims of two players. 

### What you expected:
Not to create the first claim on other player's claim.

### Steps to reproduce:
1) On the server is player Adam, who has his claim. 
2) Adam gives a trust to new player Bart, who has no claim. 
3) Bart places a chest on Adam's claim. 
4) Bart's claim is created on Adam's claim. 
5) Adam can't resize his claim because of overlapping. 

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
[21:03:47 INFO]: This server is running CraftBukkit version git-Spigot-1a3504a-a46fdbc (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[21:03:47 INFO]: This is a final build for 1.13.2. 

Paste of `/version GriefPrevention`:
[21:04:16 INFO]: GriefPrevention version 16.11.6

**Comment by RoboMWM** [comment]
I don't think your issue is correct. GP doesn't allow for and can't handle overlapping claims.

If the player does not have a claim, it will automatically create one on their first placed chest (outside of a claim). You can disable this functionality in the config.

**Comment by Jikoo** [comment]
GP sends the success message even if claim creation fails when the initial freebie claim size is set to 0. Could you paste your config?
