### ISSUE TITLE
Grief Prevention Strange Error

### ISSUE THREAD

**Issue by giuliotoplad** [GriefPrevention/GriefPrevention#557]
Minecraft Server: 1.12.2 Paper

Grief Prevention: 16.8

Error Log: https://pastebin.com/JgDgAGEH

I know it's an old version of Grief Prevention, but I have this Error in my Console that I can't solve and I don't know if it can damage the Server.

Above I put the Log where I managed to find this Error.

**Comment by Jikoo** [comment]
Error is caused when the teleport occurs for GP's portal rescue task. The abridged log line prior successfully prints the location to rescue the player to, but the exact same code on the next line fails to retrieve the same location. The location is not supposed to be removed from metadata until the following line. This is either an issue with the server's metadata implementation or your copy of GP. Based on the fact that the line numbers don't quite match up in that stack trace [(L797 is in reality L798)](https://github.com/TechFortress/GriefPrevention/blob/05497b7b6a2b693302c41a79c98ff60c3757837e/src/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java#L797-L799) I would be inclined to point the finger at your copy of GP. Try re-downloading 16.8. If it still doesn't work, unfortunately you're SOL, that's the downside of using outdated software.

This won't cause any issues aside from the portal rescue task not actually rescuing players if they log out during the rescue timer. Can't say whether or not normal rescue would fail, rescue on login should not be failing in the first place.

**Comment by giuliotoplad** [comment]
Ok, too bad because I've been using Grief Prevention for a long time and it's a shame.
Is there anything I can do to get help?

**Comment by RoboMWM** [comment]
> Is there anything I can do to get help?

Redownload version 16.8.

Looking at your very small history it seems that you had a similar issue with another plugin not too long ago.

**Comment by giuliotoplad** [comment]
OK, but I think this Error will return.
I say this because I believe it was me in the past who had this Error again.
I would like to give advice for future versions of Grief Prevention.
I would advise you to focus instead only on new versions of Minecraft even on old ones, in the sense of making the Plugin compatible for more versions of Minecraft.
It's just a tip, then do whatever you want.

**Comment by RoboMWM** [comment]
If this error returns, it's because something has corrupted your plugin jars again. Has nothing to do with supporting older MC versions or not. Perhaps some malware or otherwise?

Also, why does your log not have timestamps? Copy from `logs/latest.log`

**Comment by giuliotoplad** [comment]
I didn't think you want the entire Log, here they are the whole Server Log when the Error was spotted.
The Server was stopped by me because I didn't know how to resolve this Error.
Log: https://pastebin.com/EkAg5R95

**Comment by RoboMWM** [comment]
Thanks for the log, that helps a lot because I can see the timestamps.

So it looks like there is an issue - as if it's attempting to rescue the person twice. I'm guessing it's because he's spending a lot of time within portals.

**Comment by giuliotoplad** [comment]
So what can I do?

**Comment by RoboMWM** [comment]
The error itself is mostly harmless. If there's an issue with a person stuck in the portal then comment that issue here.

**Comment by Jikoo** [comment]
Closing this - issue does not appear to occur on current versions of server/GP and is unlikely to cause issues.
