### ISSUE TITLE
Vanilla mobs not turning off

### ISSUE THREAD

**Issue by laylolli** [GriefPrevention/GriefPrevention#56]
have ran /cf entity-spawn minecraft:any false in both admin claims and player claim and with success turned off spawning of mobs even via eggs . but in wilderness it continues to allow spawning even went as far as /cf entity-spawn minecraft:animal.pig false and still spawned pigs. Plz help what do i do

**Comment by RoboMWM** [comment]
You must've found the wrong issue tracker, GriefPrevention does not have a /cf command nor manage mobs in this manner.
