### ISSUE TITLE
Small config option to adjust the duration that fresh spawns are protected for.

### ISSUE THREAD

**Issue by Orbytz** [GriefPrevention/GriefPrevention#560]
**As a** Administrator
**I suggest** an option to change the duration value that fresh spawns are protected for in the config, allowing a duration besides the preset 10 seconds.
**So that** I can give my players a better chance of escaping the spawn area via longer immunity.

(GriefPrevention is truely bulletproof as described, love your work.)

**Comment by RoboMWM** [comment]
They should be protected so long as they haven't picked up any items..?

**Comment by Orbytz** [comment]
Sorry for the late reply, miss read Github as I thought it said "protected for 10 seconds" where as it was "at least 10 seconds" 
My b

**Comment by RoboMWM** [comment]
No problem, thanks for responding.
