### ISSUE TITLE
Player can destroy claim bloc

### ISSUE THREAD

**Issue by Neiy0** [GriefPrevention/GriefPrevention#562]
Hello, i have 1 probleme with grief prevention and spigot 1.13.2, Players can claim ... BUT the players not trust can DESTROY bloc claim but can t place. Can you fix that plz?

**Comment by bigpresh** [comment]
You've deleted the issue template which requests information that would give us any hope of assisting you, but it's most likely a conflict with another plugin, it's not something to "fix" in GP.  (I'm assuming from your vague report that you're trying to say that an untrusted player could break blocks within a claim, but can't place blocks.)

**Comment by RoboMWM** [comment]
I think this might be a dupe of another issue with similar symptoms here

**Comment by RoboMWM** [comment]
An issue which was a plugin conflict

**Comment by Neiy0** [comment]
@bigpresh Yes, but i have reinstalle the plugin and the congif and i have already the bug... but the only plugin for protect is world guard... and its not him

**Comment by RoboMWM** [comment]
Duplicate of https://github.com/TechFortress/GriefPrevention/issues/528#issuecomment-492044036

is my guess

**Comment by RoboMWM** [comment]
duplicate of #528

**Comment by RoboMWM** [comment]
Duplicate of #528
