### ISSUE TITLE
Making "BreakableBlocks" to false but resets

### ISSUE THREAD

**Issue by MasterToRix** [GriefPrevention/GriefPrevention#565]
### What happened:
i have set "BreakableBlocks: false" but i can break blocks and it resets every time i reload the plugin, to make sure it was actually being saved i also changed "Claims.InitialBlocks" to 1500 to see if that would change, and yes that changed but i can still breaks blocks and i go to the config and it doesn't display flase it then continues to reset and say
"    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW"

### What you expected:
Not to be able to break blocks (placing block prevention does work just not breaking)

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1.
2. Step 2.
3. ???
4. Profit!

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Paste of `/version GriefPrevention`:
GriefPrevention version 16.8
Reason:
My server is 1.12.2

### Stack trace/error or server log
No error in server log

Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Plugin list (if applicable):

**Comment by RoboMWM** [comment]
This config option is for sieges. If it resets it means your config has a yaml error.
