### ISSUE TITLE
Adding perm so that players gain claimblocks as they rankup

### ISSUE THREAD

**Issue by EchocallingEarth** [GriefPrevention/GriefPrevention#566]
First I was unsure where to post this so I hope this is the best place. 

Question: Can I set it so that as a player ranks up their claimblocks increase?
We are using LuckPerms and I was thinking something like:

'griefprevention.claimblocks[10000]'
and at the next rank it could read the same or be adjusted to
 'griefprevention.claimblocks[10000]'

But the basic idea is that the player starts with 25,000 claimblocks at Mortal and when the y rank up to Achilles they have 35,000 claimblocks automatically

However this does not appear to be a perm setting. So the question is can this be done and how would I do it. 

Thanks in advance
~Echo

**Comment by RoboMWM** [comment]
There's an `/acb` command. 

There is also a way to add blocks to permission nodes but I strongly discourage using that.
