### ISSUE TITLE
Randomly deleted almost 500 claims

### ISSUE THREAD

**Issue by Spoonerj1** [GriefPrevention/GriefPrevention#567]
### What happened:
497 claims files were deleted. The server stopped with claims loaded, and then started with 0. 

### What you expected:
All claims to load normally.

### Steps to reproduce:
I literally have no idea. I didn't see that it had occurred until after the fact by several hours.I have managed to track down the logs when it did happen. And I was able to restore claims from a backup.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: spigot from buildtools, build 2404,  version 1.14.3-R0.1-SNAPSHOT for 1.14.3
Paste of `/version GriefPrevention`: GriefPrevention v16.11.6

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: https://gist.github.com/Spoonerj1/f2d706087ee71661387618f12bc138c0

### GriefPrevention config.yml

```
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    Casimir: -1
    Casimir_nether: -1
    Casimir_the_end: -1
  Claims:
    Mode:
      Casimir: Survival
      Casimir_the_end: Disabled
      Casimir_nether: Disabled
    PreventGlobalMonsterEggs: false
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 5500
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 120
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 21
      UnusedClaimDays: 45
      AllClaims:
        DaysInactive: 280
        ExceptWhenOwnerHasTotalClaimBlocks: 5501
        ExceptWhenOwnerHasBonusClaimBlocks: 1
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 10
    CreationRequiresWorldGuardBuildPermission: false
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: false
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      Casimir: true
      Casimir_nether: true
      Casimir_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 10.0
    ClaimBlocksSellValue: 8.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: false
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: false
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 180
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: true
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: true
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

```

### Plugin list (if applicable):
CoreProtect, CratesPlus, dynmap, LuckPerms, WorldEdit, GreifPrevention-Anti-Worldedit, SAML, PlaceholderAPI, VillagerOptimiser, AdditionsAPI, Votifier, ChestSort, ProtocolLib, WorldGuard, CSGO-CratesPlus, VotingPlugin, VanillaAdditions, Vault, GriefPrevention, BottledExp, CustomEnderChest, BuycraftX, DeathChestPro, Citizens, Shopkeepers, DiscordSRV, Parkour, CMI, Sentinel

**Comment by RoboMWM** [comment]
GP doesn't delete claims, except for expiration, which are always logged.

**Comment by Spoonerj1** [comment]
This is why I'm reporting the issue. Almost 500 claims were deleted. None of them were from inactive players. The plugin even continued naming them as if nothing had changed.

no one but me has access to delete files, and no one else has access to the commands to clear the claims either. I dont know what caused it, but I am trying to replicate it in a test server so I can provide more info.

**Comment by TomLewis** [comment]
I had GP delete THOUSANDS of claims, there is a massive ticket somewhere on this issues github, There is a bug in GriefPrevention where the table griefprevention_nextclaimid will not be in sync with the actual Claim ID's and when new claims are made it will overwrite your existing claim ID's starting from your first claims.
Whats even worse, is if you start a server up and your first claims are admin claims on your spawn, these will be the ones that get deleted!
So check your griefprevention_nextclaimid, see what number its at, then look at the latest ID of your griefprevention_claimdata. If your latest row ID in griefprevention_claimdata isn't 1 less than griefprevention_nextclaimid, then thats your issue.

**Comment by RoboMWM** [comment]
Nextclaimid would cause a gradual overwrite, and there is a check on startup for this too and will reset claim id to the smallest available id if it happens to collide with an existing IP (which is also logged).

**Comment by Spoonerj1** [comment]
I have been unable to replicate the issue that I saw. I will close the ticket until I can get more data. It doesn't seem to be the same as what FrozenBeard described. What I saw was probably caused by a bad shutdown, where GP wasn't able to save the claims data correctly and thus caused them all to be deleted. 
What's really odd is that it started the next claim at 501. When I opened the backup, claims 1-493 were all present, so in the end I only lost about 7 claims. 
If it happens again or I am able to replicate and get more info, I will reopen this.

**Comment by RoboMWM** [comment]
Yea, if the starting claim id hasn't decreased, then it definitely isn't the issue frozenbeard referenced. GP saves claims when modifications are made - only playerdata for logged-in players is saved on shutdown.

There is a command to mass-delete claims in a world which can only be run from console, so that's also a possibility.
