### ISSUE TITLE
Ideas for GP Protect event(s)

### ISSUE THREAD

**Issue by RoboMWM** [GriefPrevention/GriefPrevention#57]
Trying to figure out the best way to implement this...

It was suggested that GP should use events to allow addons to integrate and In order to allow other plugins to integrate with GP (and allow integrations such as those described in #10). GP already does this with a PreventBlockBreakEvent and PreventPvPEvent.

It seems most of the "API" methods are in GP's main class, though most of the checks call `DataStore#getMessage` when denying an action (since they return a not-null String if denied). I could have the event be called from here instead, and I'd be able to pass a Messages enum to help determine the reason. **(And this is currently the option I will be implementing, if I get no feedback about this.)**

I plan to use this API to send some messages through the Actionbar instead (via an addon). For my cases, for denied events, I'd simply `Player.sendActionBar(event.getMessage)`, then `event.setMessage("").` Setting message to `null` would allow the event - should this be allowed? Or should we simply make the event cancelable?

**Comment by Jikoo** [comment]
I think implementing Cancellable would make behavior much more consistent with Bukkit's design. It also makes it a little clearer which events can and cannot be cancelled - for example, visualization seems like it shouldn't be cancellable but the list of claims being visualized should potentially be modifiable. If you do want to use the message route, `Cancellable#isCancelled` could return `GPEvent#getMessage == null`, etc. I definitely like the idea of being able to remove the message without cancelling GP behavior.

Regarding additions, it might be nice to have a ClaimResizeEvent in addition to a ClaimCreateEvent, even though the current resize code would probably cause a ClaimCreateEvent to fire if added.

**Comment by RoboMWM** [comment]
>  If you do want to use the message route, `Cancellable#isCancelled` could return `GPEvent#getMessage == null`, 

Should the respective is/setCancelled methods then simply check/set event#getMessage to null instead of a new variable boolean?

**Comment by Jikoo** [comment]
>Should the respective is/setCancelled methods then simply check/set event#getMessage to null instead of a new variable boolean?

Sorry, I mixed my logic from what you'd said, I meant not null.

Seems reasonable to me so long as it's documented that setting the message null instead of an empty string will uncancel the event and vice versa. If both behaviors aren't desirable at once, a boolean would certainly do just as well. Depends on how you want to implement it internally - if a non-null message means cancelled, by all means. Otherwise, `event#isCancelled` instead of `event#getMessage != null` would be just as easy a check to perform.

**Comment by RoboMWM** [comment]
Oh, I just re-read what I quoted and that is what you were suggesting (although inversed).

Anyways, I see what you mean - but so far, that is how ProtectPvPEvent and ProtectBlockBreakEvent operate... so checking if said custom event is "cancelled" means GP won't cancel the event. The only plugin that I'm aware that uses this (other than one of my plugins) is GriefPrevention Flags.

So I could either maintain consistency and have this new event's cancel status determine if GP should act upon this event (canceling it), or I could deprecate the existing "protect" events and have the cancel status reflecting the (future) status of the event when it is fully processed by GP.

**Comment by Jikoo** [comment]
I vote deprecate, but only because there're always going to be people who can't read the docs and expect a null message to perform the same way as an empty message. Save yourself a future headache imo.

Would be nice to have anyone who's actively maintaining a more heavily used addon weigh in, my usage is mostly personal and is limited to chat and claim manipulation.

**Comment by RoboMWM** [comment]
So obviously firing an event from `DataStore#getMessage` is a bit limited in terms of determining exactly what GP is acting on (i.e. due to no "build" permission would cover building and destroying blocks, any sort of interaction with armor stands and item frames, etc.)

Question is: should I allow a plugin to "uncancel" GP's protection from here then (and instead appropriately name this something like GPMessageEvent)?

**Comment by matcracker** [comment]
I'm waiting a global event for ignore claim protection. PreventBlockBreakEvent, if cancelled, can only break but there isn't any other events for place or use!

**Comment by RoboMWM** [comment]
@matcracker If I do the global event in DeniedMessageEvent, I won't be able to expose anything more than it receives as parameters in `DataStore#getMessage` (i.e. I can _only_ give you a Messages enum, nothing else; no player, world, location, etc., since nothing else is used to call that method). Would that still be sufficient for your needs, or do you have a better idea of where such an event should be placed?

**Comment by matcracker** [comment]
No no, I was talking about PreventBlockBreakEvent. You can create a global event (i.e. PreventInteractEvent) called when a player interact in a claim, so, if cancelled, the player can interact else not. Then, you can edit PreventBlockBreakEvent and create other 2 events (PreventBlockPlaceEvent and PreventUseEvent) that extends PreventInteractEvent for give a good management of claim for GriefPrevention extensions :)

**Comment by RoboMWM** [comment]
Alright, so here's the primary question - what should the events be called and how should canceling work?

The current behavior with [PreventBlockBreakEvent](https://github.com/TechFortress/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/events/PreventBlockBreakEvent.java) and PreventPvPEvent 
- Canceled: If these events are canceled, GP will "allow" (i.e. take no action) on the event it was initially going to protect against. (Will return `null` for [allowBreak](https://github.com/BigScary/GriefPrevention/blob/9ec083703819a8ec3e62091c4a6158df2bc17580/src/me/ryanhamshire/GriefPrevention/GriefPrevention.java#L3328) and similar methods)
- These events pass the "inner" event (i.e. the BlockBreakEvent, BlockPlaceEvent, etc.)

~~@Jikoo suggests that the cancel implementation should be inversed - these events pass as canceled, and can be uncanceled to have GP "allow" the action. i.e. the cancel state of the event GP is calling should reflect what the "innerEvent" cancel state will be after GP processes the event. (If this is the case - then we also need to think of a better naming scheme other than Prevent-whateverEvent)~~

**Comment by Jikoo** [comment]
>@Jikoo suggests that the cancel implementation should be inversed - these events pass as canceled, and can be uncanceled to have GP "allow" the action. i.e. the cancel state of the event GP is calling should reflect what the "innerEvent" cancel state will be after GP processes the event. (If this is the case - then we also need to think of a better naming scheme other than Prevent-whateverEvent)

Er, I think we may have had some miscommunication at some point. The only time at which I believe I've suggested uncancelling an event was as an alternative to GP events which don't yet exist. Generally I consider uncancelling events to be relatively poor practice, Bukkit's system is less than helpful for discovering why something was cancelled in the first place.

Edit: Oh, nope, I was not clear at all in the first comments here, probably due to my logic inversion mistake. I'd prefer to see events start uncancelled unless there's a logical reason for it.

**Comment by RoboMWM** [comment]
I'm thinking of Billy's suggestion in IRC, to fire custom events for actions that occur via other event handlers. E.g., having a "GPBlockPlaceEvent" for any event that we deem involves a player "placing" a block (onEntityFormBlock with frostwalker, "sand cannons," placing paintings, etc.), a "GPBlockDestroyEvent" (explosions, crop trampling, destroying armor stands/item frames, etc.), etc.

If I do take this route (which would make things easier to track in my opinion, regarding what gets canceled or not since the code for actually canceling what happens in a claim would not be repeated multiple times for each Bukkit event), do we still need any of the "GPProtect" events? I'm thinking these events could instead just listen to the "GPWhateverEvent" events and see if they are canceled or not to determine if GP is taking action.

**Comment by RoboMWM** [comment]
Moving discussion to #63
