### ISSUE TITLE
Can't use Flint and Steel on players in a PVP world

### ISSUE THREAD

**Issue by Kruize1** [GriefPrevention/GriefPrevention#570]
### What happened:
Can't use Flint and Steel on players in a PVP world, "You can't start a fire this close to another player."  even though   ....

PvP:
    RulesEnabledInWorld:
      world: false

### What you expected:
Should be able to use Flint and Steel to set players on Fire , and no message should appear.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Ensure config is  
PvP:
    RulesEnabledInWorld:
      world: false
2.  Attempt to set another player on Fire with Flint and Steel
3.  Observe
4.  "You can't start a fire this close to another player."

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`:  This server is running Paper version git-Paper-146 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: GriefPrevention version 16.11.6

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

**Comment by RoboMWM** [comment]
if PvP rules are disabled, GP treats the world as a PvE world. No idea why but that's Big_Scary's design, iirc.

GP v20 will modularize these components so you can completely disable a component such as this.

**Comment by Jikoo** [comment]
A config option to toggle this behavior was added in 393aa273299fb8dc0aaaff5000a6d5302f700a47. Since you didn't provide that part of the PVP section, assuming you may have missed it because it was relatively new at the time. Set `GriefPrevention.PvP.AllowFlintAndSteelNearOtherPlayers.NonPvPWorlds` to true.
