### ISSUE TITLE
Item Frames in claims don't naturally break

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#573]
### What happened:
Item frames never drop even if there's no block behind them

### What you expected:
They should break once the supporting block is no longer there

### Steps to reproduce:
Place item frame
Remove supporting block
Item frame does not drop

### Server and GriefPrevention version:
Paste of `/version`: git-Paper-152 (MC: 1.14.4)
Paste of `/version GriefPrevention`: 16.11.6

### GriefPrevention config.yml

Default config

### Plugin list (if applicable):
Tested without any other plugins installed

**Comment by ghost** [comment]
Also happens with other hanging objects like paintings

**Comment by ghost** [comment]
Can't create a pull request for some reason but the issue can be solved by adding this
```		//allow physics breaking paintings/item frames if there's no parent block present
		if(event.getCause() == RemoveCause.PHYSICS) return;
```
to EntityEventHandler, onHangingBreak before explosion check

**Comment by RoboMWM** [comment]
Duplicate of some issue a couple years ago.

**Comment by ghost** [comment]
Well, I did provide a fix

**Comment by RoboMWM** [comment]
Yes I know. It was to remind myself to mark it as such so I can close that other issue too.

**Comment by RoboMWM** [comment]
Actually, it was an issue elsewhere, for the spigot test server. https://github.com/SpigotMC/SpigotCraft/issues/364
