### ISSUE TITLE
Protecting doors and trapdoors with /accesstrust

### ISSUE THREAD

**Issue by kaniesha** [GriefPrevention/GriefPrevention#581]
As an administrator and player, I'd like for doors to be added to the /accesstrust command or auto-protected and made into its own command such as /doortrust. Even with GP being anti griefing, it'd be nice to prevent players from intruding in areas I'd like them not to.

### Proposed Criteria
- Add doors and trapdoors to /accesstrust
- Or make a new /doortrust or similar that does the same.

**Comment by RoboMWM** [comment]
Already exists. See config.
