### ISSUE TITLE
Can't claim or anything 

### ISSUE THREAD

**Issue by vDitto187** [GriefPrevention/GriefPrevention#59]
### What behaviour is expected:
_What you expected to see_
### What behaviour is observed:
_What you actually saw_
### Steps/models to reproduce:
_This may include a build schematic, a video, or detailed instructions to help reconstruct the issue_

### Spigot/Craftbukkit/Paper and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___

### Stack trace/error (if applicable)

```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here
```

**Comment by bigpresh** [comment]
Er, you might need to actually fill in the template with some details, please :)  Re-open if you do so.  Without any information at all, there's nothing anyone can do to help.
