### ISSUE TITLE
TPS loss from GriefPrevention::Task: me.ryanhamshire.GriefPrevention.CheckForPortalTrapTask

### ISSUE THREAD

**Issue by Weasel-Beans** [GriefPrevention/GriefPrevention#592]
I noticed some TPS loss from this in Timings v2:

GriefPrevention::Task: me.ryanhamshire.GriefPrevention.CheckForPortalTrapTask (Single) avg(45.95ms per - 0.02ms/0.00 per tick)

Report: https://timings.aikar.co/?id=172990a455474cc49b223a89a7231955#plugins

Config: https://pastebin.com/g8d2fEVW

I think I'm using 16.12-alpha, but I could be wrong.

**Comment by ShaneBeee** [comment]
```
count(8)  total(0.03% 0.368s, 0.04% of tick)avg(45.95ms per - 0.02ms/0.00 per tick)
```
Theres 8 counts of this trying to tick. its taking 45.95ms per tick, but at 0.00 ticks (odd number) 
long story short, this plugin is NOT the cause of your TPS dropping
It appears like Polar Bears are causing most of your TPS drop

**Comment by RoboMWM** [comment]
This task only fired a grand total of two times during "lag" ticks of your timings duration, and was under 50ms. This is not responsible for any overall lag, and is not large enough to cause a spike either.

**Comment by Weasel-Beans** [comment]
Okay thank you for explaining, I guess I have an incomplete understanding of how to read Timings v2

**Comment by RoboMWM** [comment]
Yea - you want to look for suspects in the default view, not jump straight to the "plugins" section. I think aikar (the creator of timings) has a video on reading it.
