### ISSUE TITLE
Tridents destroy chorus flowers in claimed areas

### ISSUE THREAD

**Issue by niclimcy** [GriefPrevention/GriefPrevention#594]
### What happened:
Chorus flowers breaking in claimed areas from tridents.

### What you expected:
Chorus flowers not breaking.

### Steps to reproduce:
1. Another player grows chorus flower
2. Enter the other player's claim area
3. Use trident and aim at top of chorus plant
4. profit

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: This server is running Paper version git-Paper-175 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: GriefPrevention version 16.11.6

### Stack trace/error or server log
N.A.

Paste entire stack trace right here inside these backticks.
N.A.

### GriefPrevention config.yml
Default

### Plugin list (if applicable):
N.A.

### Video evidence:
https://streamable.com/28lqe

**Comment by RoboMWM** [comment]
Does it happen with 16.12.alpha?

**Comment by RoboMWM** [comment]
Hmm, seems to be a new 1.14 mechanic, as this doesn't happen in 1.13...

**Comment by RoboMWM** [comment]
according to eventdebug, the only relevant event that is fired is projectilehitevent… which isn't cancelable... No other block events occur...

**Comment by RoboMWM** [comment]
https://korobi.vq.lc/network/spigot/channel/paper-dev/logs/2019/07/04/#L476

**Comment by RoboMWM** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-5140
