### ISSUE TITLE
Sell Claims with Signs

### ISSUE THREAD

**Issue by RaulG7** [GriefPrevention/GriefPrevention#597]
**AS** Administrator
**I WANT** a feature
**BECAUSE** It may help a lot of players, I think its a very usefoul feature

My suggestion is make a way to sell the claims you have with a sign, for example something like this:

1) Place a sign in your claim:
> First line [Sell]
> Second line - Price
> Third line (optional) - Time (nothing = permannent)
2) If a player clicks the sign he will buy the claim land, that means the old owner wont have permissions and will transfer the claim to the user who bought it

This could be really usefoul for selling houses/subclaims

**Comment by TomLewis** [comment]
Look at AreaShop.

**Comment by RaulG7** [comment]
> 
> 
> Look at AreaShop.

Not working for 1.14 sadly

**Comment by RoboMWM** [comment]
This is literally GPRealEstate. https://github.com/RoboMWM/GPRealEstate

**Comment by RaulG7** [comment]
> 
> 
> This is literally GPRealEstate. https://github.com/RoboMWM/GPRealEstate

How do I Install that for my 1.14.4 server? I dont see any .jar

**Comment by Jikoo** [comment]
> How do I Install that for my 1.14.4 server? I dont see any .jar

They're in the releases tab like normal.

**Comment by RaulG7** [comment]
> 
> 
> > How do I Install that for my 1.14.4 server? I dont see any .jar
> 
> They're in the releases tab like normal.

I do not understand, I mean I click de github GPRealEstate and I dont see any releases tab, I dont know where to put those files and what to download

**Comment by Jikoo** [comment]
![image](https://user-images.githubusercontent.com/1353270/63640131-b3fc4c00-c66a-11e9-958a-c697e6209381.png)
https://github.com/RoboMWM/GPRealEstate/releases/latest
