### ISSUE TITLE
Grief Prevention not enabled on worlds imported with Multiverse

### ISSUE THREAD

**Issue by codespunk** [GriefPrevention/GriefPrevention#6]
I seem to recall this working before. Maybe it broke around 1.10?

When I import a world with Multiverse and try to do something with a shovel it says that the GriefPrevention is not enabled for this world. The world is also not listed in Comfig.yml -> GriefPrevention: -> Claims: until a server restart which defeats the purpose of being able to import at runtime.

Can this be fixed so that GriefPrevention properly recognizes new worlds without having to restart the server?

**Comment by RoboMWM** [comment]
`/version` and `/version griefprevention` please.

GriefPrevention is already set to load after Multiverse loads. It sounds like you're loading worlds after the server starts.

Before, GriefPrevention would use whatever claim mode the world's default gamemode was in for new worlds. This caused issues for servers like minigame servers which inadvertently enabled GP's PvP rules (or anti-PvP rules, depending on the PvP setting when created), and tons of other settings to be ignored. Now, it (rightfully) sets the claim mode to disabled on dynamically-loading worlds.

I know Big_Scary also had input on this when someone else requested this. If you can find it on the forum, great. It's late right now and I'll search it up later if you can't find it (once I find it then I can give you a better response/decision, on my end at least.)

However, I honestly believe you should reconsider what you're doing if you really require GP claims on dynamically-loaded worlds.

**Comment by codespunk** [comment]
As an alternative to a single-world server, I periodically import additional "small" worlds so that people will always have new places to explore.

I do this at runtime because it doesn't necessitate kicking everyone off for the import process as it's meant to be a background task that doesn't affect the existing players.

Please consider adding a new command that I can call to make GriefPrevention aware of a newly imported world. For example, "/gp enable <world>". This would actually be a useful feature regardless of my use case if I could explicitly enable or disable gp on specific worlds from a command rather than relying on disabling/enabling the entire plugin which invariably causes problems.

**Comment by RoboMWM** [comment]
> Please consider adding a new command that I can call to make GriefPrevention aware of a newly imported world. 

`/gpreload`

By the way, this only reloads a subset of the config, not the entire plugin. This subset includes world changes (adds new worlds, deletes missing ones) to the config, which is what you want.

**Comment by codespunk** [comment]
My previous proposal didn't appear as I had written it since I used '<' and '>'.

The syntax I was suggesting is:

`/gp <enable|disable> <world>`

This is less invasive than reloading the entire config. Since I will be executing the command from a script, I would rather not use something so heavy handed and reloading the config, event if it is a subset.

**Comment by RoboMWM** [comment]
`/gpreload` is not heavy-handed at all; if anything, it's far faster than importing a world...

**Comment by RoboMWM** [comment]
I'd also refer to Big_Scary's response to a similar request https://www.spigotmc.org/threads/griefprevention.35615/page-127#post-1539531

If these worlds have existing claims on them, then you _have_ to use `/gpreload`; there's no going around that. But if you're just importing worlds that don't have existing claims, then I suppose I could accept a PR for ~~`/gpenable <world>` which will run the respective code for loading the respective claim mode for that world~~ or better yet, a config option to restore the previous behavior of detecting new worlds and setting the appropriate claim mode. The idea is to avoid (if at all possible) copying-pasting already-existing code to fulfill this request, so if such a PR is made, hopefully it will be small...

**Comment by RoboMWM** [comment]
Closing due to 1) low priority and 2) not necessary (as `/gpreload` exists).
