### ISSUE TITLE
Establishing SSL connection

### ISSUE THREAD

**Issue by SrBedrock** [GriefPrevention/GriefPrevention#602]
**AS** a administrator
**I WANT** put in the settings an option to decide whether or not to use SSL
**BECAUSE** messages fill the log making reading difficult.

```
[00:44:37 WARN]: Sat Aug 31 00:44:37 EDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
```

**Comment by TheSenseiNL** [comment]
HOW about NOT being an ASS for an ADMIN and NOT use CAPS so much to DEMAND what you want but just do some GOOGLE-ing?!

DON'T be an ASSHOLE ADMIN but just use your BRAIN!

https://www.mkyong.com/mysql/mysql-establishing-ssl-connection-without-servers-identity-verification-is-not-recommended/
(This tells you how to use ?useSSL=false)

Better, be a REAL ADMIN and not just cary the name and INSTAL SSL on your database server!

**Comment by Jikoo** [comment]
> HOW about NOT being an ASS for an ADMIN and NOT use CAPS so much to DEMAND what you want but just do some GOOGLE-ing?!

That's the [request format](https://github.com/TechFortress/GriefPrevention/blob/master/.github/ISSUE_TEMPLATE/feature-request.md). I agree that a search would have solved the issue, but being inflammatory about it is unlikely to be productive.

**Comment by RoboMWM** [comment]
@TheSenseiNL This is part of the request format - and is there to summarize the "what" and "why" of a request. It's in bold and all caps so it's more visible. I could probably change it to just bold or italics. See https://content.pivotal.io/blog/how-to-write-well-formed-user-stories for more info.

Anyways @SrBedrock he does have the answer:

> https://www.mkyong.com/mysql/mysql-establishing-ssl-connection-without-servers-identity-verification-is-not-recommended/
(This tells you how to use ?useSSL=false)

**Comment by SrBedrock** [comment]
Thanks RoboMWM!
I thought I needed some internal code.
About the first comment, what a fucking asshole..
