### ISSUE TITLE
Trident on Item Frame

### ISSUE THREAD

**Issue by coco0325** [GriefPrevention/GriefPrevention#603]
### What happened:
If a trident on item frame in other's claim, it disappeared.

### What you expected:
Trident drops.

### Steps to reproduce:
Shoot a trident on item frame in in other's claim

### Server and GriefPrevention version:
PaperSpigot 1.14.4
GP 16.11.6

**Comment by RoboMWM** [comment]
What's the issue? I can't understand what you typed.

Try giving a list of steps of what happens and what you expect should happen.

Will also need config and world it's happening in.

**Comment by LuckyFish312** [comment]
This happened to me once, except I shot an arrow into an item frame, and I could not retrieve the arrow because it disappeared.
Edit: It's the same problem as this issue: https://github.com/TechFortress/GriefPrevention/issues/599 but with tridents instead of arrows shooting at item frame.

**Comment by RoboMWM** [comment]
So you're trying to retrieve the arrow you shot at the item frame? Cities7 (who hangs out on IRC) was not able to reproduce. Please post config and world it's happening in.

**Comment by LuckyFish312** [comment]
I'm not sure what world it happened in, it was a month or two ago. I'll try to see if I can get it to happen again.

**Comment by RoboMWM** [comment]
Please do try to make it happen again, and let us know the results here.

**Comment by RoboMWM** [comment]
Will reopen if can be reproduced.
