### ISSUE TITLE
RFTools Builder Quarry - Ignores GriefPrevention Claims

### ISSUE THREAD

**Issue by sbabudro** [GriefPrevention/GriefPrevention#606]
### What happened:
https://github.com/McJtyMods/RFTools/issues/1375

The RFTools builder is claimed to disregard the GPP claim boundaries. The developer of the RFTools mod additionally claims that his machine is not doing anything abnormal and that it is not his mod causing the problem.

I am not sure how to test any of this since I am just a player moderator without any advanced permissions on my server, but the admins refuse to include the RFTools builder on their server due to its ability to grief.

### What you expected:
GPP should prevent the builder from being able to modify blocks inside areas claimed by other players.

### Steps to reproduce:
1. Claim an area as Player_1
2. Use a builder block to quarry the same area as Player_2 (not trusted by Player_1)

### Server and GriefPrevention version:
Don't have access to this at the moment - on a library computer. When I get home I will try to remember to log in and provide this. (hopefully those commands are not disabled for users/moderators on the server or I will need to try and get the help of an admin.)

### Stack trace/error or server log
```
Paste entire stack trace right here inside these backticks.
```
See above
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

See above

### Plugin list (if applicable):

GPP, RFTools

**Comment by bigpresh** [comment]
Grief Prevention does not and cannot know about all other third party mods out there, so I don't think it's reasonable for GP's core to know how to block these actions.

Someone could quite well write an addon that would tie the two together, though.

**Comment by Jikoo** [comment]
If you're running Forge you're probably running GP for Sponge. You my have the wrong issue tracker. GP Sponge could be reasonably expected to intercept RFTools' world modifications.

**Comment by RoboMWM** [comment]
Looks like a forge plugin. Gonna assume you're running Sponge.

This ain't the plugin you're looking for, chief.
