### ISSUE TITLE
Help plz

### ISSUE THREAD

**Issue by Bullenz** [GriefPrevention/GriefPrevention#609]
Hello! i know very much servers that use this and its very good. But i cant. When i download the file nad restarting my server the folder with the other "files" doesent creates. plz help

**Comment by bigpresh** [comment]
Please don't delete the issue template which requests information that would allow us to actually help you, like what GP version you're trying to use, what exact server software version, any errors etc.

**Comment by Bullenz** [comment]
I'm using it on my spigot 1.13.2 survival server

Den ons 4 sep. 2019 17:05David Precious <notifications@github.com> skrev:

**Comment by bigpresh** [comment]
And you still haven't told us what Grief Prevention version you're using, or any log output, etc.

I'll close this ticket, please raise another when you're prepared to actually complete the issue template with the information requested, otherwise there's nothing we can do to help you.
