### ISSUE TITLE
Addon

### ISSUE THREAD

**Issue by bys1** [GriefPrevention/GriefPrevention#61]
Does GriefPrevention have some api with javadocs? I want to make an addon with the following:

- Get a claim by location.
- A way to get some Unique claim id to identify claims of save data for a specific claim.

**Comment by Jikoo** [comment]
Documentation? Good one. The easiest way to go about things in is to find a listener that probably uses what you want and read through that.

- `DataStore#getClaimAt(Location location, boolean ignoreHeight, Claim cachedClaim)`
This will return subdivisions first. If you don't have a cached claim, use null. Will return null if no claims are present.
- `Claim#getID`

**Comment by bys1** [comment]
How can I check whether a player has trust of accesstrust?

**Comment by Jikoo** [comment]
Consider looking over the relevant classes. It's [not hard to find](https://github.com/TechFortress/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/Claim.java#L449).

**Comment by bys1** [comment]
How do I check whether a player is respecting or ignoring claims?

**Comment by bigpresh** [comment]
> How do I check whether a player is respecting or ignoring claims?

Look through the code.  In particular the link @Jikoo provided in response to your last question, about 8 lines down, has the answer you're looking for.

Please use GitHub issues to report bugs or suggest features, not to expect to be spoon-fed.

**Comment by RoboMWM** [comment]
> Does GriefPrevention have some api with javadocs?

No Javadocs right now (except some on some of the events), but feel free to PR any or add to the wiki
