### ISSUE TITLE
Plz help

### ISSUE THREAD

**Issue by Bullenz** [GriefPrevention/GriefPrevention#611]
hello! i really want to use this plugin but it dosent work. when im downloading it the map or folder doesents creates, im using 1.13.2 spigot on my server and the version of the plugin is the latest?

**Comment by bigpresh** [comment]
As I said on the other tickets you raised, #608 and #609, please don't just delete the issue template, it's there for a reason and asks for information that helps us.  "it dosent work" (sic) doesn't give us anything to go on, and I don't know what you mean by "the map or folder doesents creates".

You need to install it like any other Spigot plugin - download the .jar file and place it in your `plugins` folder.  When you next start your Minecraft server, you should see a `GriefPreventionData` folder created under plugins containing a default config, and you should see some messages in your server log showing GriefPrevention loading.  If you see any error messages, please post them, as they might help us see what's going on.

You still haven't told us what version of the plugin you have, but if it's "the latest", that's 16.12.0 which very clearly states on [the releases page](https://github.com/TechFortress/GriefPrevention/releases) that "This release is compatible only with implementations of Bukkit 1.14 or higher" - so if you're trying to use that GP version, it won't work - you'll need to download [version 1.11.6](https://github.com/TechFortress/GriefPrevention/releases/tag/16.11.6) and try that.

**Comment by RoboMWM** [comment]
Sounds like you need help learning how to [setup a server](https://www.spigotmc.org/wiki/spigot-installation/)
