### ISSUE TITLE
How to turn off fully piston protection?

### ISSUE THREAD

**Issue by andris155** [GriefPrevention/GriefPrevention#612]
This protection break creative protected pistons. I want to disable this.
https://www.youtube.com/watch?v=OTWfgrd9lmw

The LimitPistonsToLandClaims: false setting not disabled this.

**Comment by RoboMWM** [comment]
Can you explain in text what feature you want? Following the template you deleted would've helped a lot.

**Comment by andris155** [comment]
I want to disable break piston if pull in block to claim.

**Comment by RoboMWM** [comment]
This'll be interesting to solve, since the piston logic is... kinda duplicated for the three separate events.

**Comment by RoboMWM** [comment]
Hi, gonna need more details since your video isn't accessible - going to need everything that's in the bug report template. Create a new issue to see the template.
