### ISSUE TITLE
WHY?

### ISSUE THREAD

**Issue by Bullenz** [GriefPrevention/GriefPrevention#614]
Hello! okey i have the folder with the config and everything but like people can open chest and build and all that but they CAN grief in the area. And i dont really know why. the version of the plugin is 16.11.6 and i have a 1.13.2 survival server:) dont really know what you need more to know

**Comment by bigpresh** [comment]
Please fill out the template, or stop raising tickets.  For e.g. the issue template asks for your GriefPrevention config which lets you control the plugin, but you've not included it, so we've no idea what you've told it to do.  Also, if you are going to open a ticket, *please* try to give it a descriptive title - "WHY??" is just of no use to anyone.

> but like people can open chest and build and all that but they CAN grief in the area.

I'm *guessing* that either the "but" should be an "and", or one of the "can"s should be a "can't" there, but it's not clear.

By default, with Survival mode claims enabled for a world, people can do anything they like *outside* of claims.  *Inside* a claim, they need accesstrust on that claim to open doors / fences etc and operate buttons/levers, containertrust to access inventory-containing items (e.g. chests, etc), and buildtrust (/trust) to place/break blocks.

When it comes to how to actually claim etc, https://www.youtube.com/watch?v=VDsjXB-BaE0 is an old but helpful video showing how it all works (that's the video you get a link to when you equip a golden shovel).
