### ISSUE TITLE
Glitched admin claim

### ISSUE THREAD

**Issue by boddahburnout** [GriefPrevention/GriefPrevention#632]
I have a shop area that is admin claimed and subdivided and it just locked up on me. If I /trust a player to a subdivision it shows they are trusted on the trust list but cannot build still. I am on the latest version of gp. Not sure all the info needed here I don’t have any errors to give, if I’m missing something let me know.

**Comment by RoboMWM** [comment]
> Not sure all the info needed here

Fill out the template you deleted.
