### ISSUE TITLE
Cant get Griefprevention in the server

### ISSUE THREAD

**Issue by Cobzer** [GriefPrevention/GriefPrevention#635]
Hello! I have some trouble downloading Griefprevention. I have put the file in plugins, and restarted the server, not once, not twice, but four times. I have removed the files, downloaded the files again ect. But whatever I do, The plugin never get in the /pl list, and cannot be used in the game. 

What I am doing wrong?

**Comment by Jikoo** [comment]
You're not providing any information about how to replicate your issue.

Server version? GP version? Logs?
Note that we need actual version numbers, "latest" is pretty much never useful.

**Comment by Cobzer** [comment]
You can see this as solved :)

Was google and found my answer after alot of looking

Den tors 3 okt. 2019 22:36Adam <notifications@github.com> skrev:

**Comment by Jikoo** [comment]
Okay. Would be helpful for others if you could detail your issue and fix in case they end up finding it in a search later.

**Comment by Cobzer** [comment]
I found,  as you was asking, that i had wrong version on the GP-Plugin.

I didnt know that a newet version wo would not work on a older client.


So dear people:)

If your client is 1.13, the plugin need to be in 1.13

Den tors 3 okt. 2019 22:48Adam <notifications@github.com> skrev:
