### ISSUE TITLE
/claimexplosion flag turned back off after server restart.

### ISSUE THREAD

**Issue by Jerethkhan** [GriefPrevention/GriefPrevention#641]
### What happened:
Whenever /claimexplosion is used to turn off explosion protection in a subclaim a server restart turns it back on. This is an issue for automated wither run farms.

### What you expected:
Toggled state of explosion protection saving through a reset.

### Steps to reproduce:
1. Make a subclaim.
2. Toggle /claimexplosion off in the subclaim
3. Restart server.

### Server and GriefPrevention version:
PaperMC build 645 (1.13.2)
 GriefPrevention 16.11.6

**Comment by RoboMWM** [comment]
This is intended behavior. /claimexplosions is a temporary flag that resets on owner logoff. This is especially useful in cases where the owner forgets to turn it off.
