### ISSUE TITLE
Auto expiration dosn't work

### ISSUE THREAD

**Issue by kaspamaspa** [GriefPrevention/GriefPrevention#644]
I set the expiration of a plot like this:
_Expiration:
      ChestClaimDays: 15
      UnusedClaimDays: 15
      AllClaims:
        DaysInactive: 16
        ExceptWhenOwnerHasTotalClaimBlocks: 10001
        ExceptWhenOwnerHasBonusClaimBlocks: 5000_

and it dosnt work. Non of the players can reach more then 10k blocks and almost no one have 5k bonus claim blocks and still I see everywhere claims that are unused for 20, 30, 40 days.

Did I set something wrong? 
Before I set the _DaysInactive_ to 16 it was set to 200. Could it cause the problem? 
I already restarted the server and it dosn't work.

[config.zip](https://github.com/TechFortress/GriefPrevention/files/3728732/config.zip)

**Comment by bigpresh** [comment]
It's my understanding that expiration happens periodically, so you'd not expect claims to disappear straight away, but to eventually be removed at some point after the cut-off is reached.

Looking at the code in the FindUnusedClaimsTask it appears that it's intended to fire once per minute, and check one claim each time it runs, so if there are lots of claims then it could take a long time for them to be reached and checked, but sooner or later they will.

**Comment by kaspamaspa** [comment]
Ok, thank you very much!
I'll wait then.
