### ISSUE TITLE
Lock Wooden Buttons

### ISSUE THREAD

**Issue by Kruize1** [GriefPrevention/GriefPrevention#655]
**As** a player and a server admin
**I want** to use Wooden Buttons on my claims, and have a choice as a server admin to protect Wooden Buttons from being activated by arrows.
**Because** I want to use Wooden Buttons, just like how I have the choice of using Wooden Doors (LockWoodenDoors).  I want to feel safe inside my claims and not have people use this as a loophole to get inside.

**Comment by RoboMWM** [comment]
I really should get on making that FAQ...

#193

**Comment by Kruize1** [comment]
In regards to 193,

You say this is Expected behavior, and Players should use stone buttons, similar to using iron doors.

However, you offer an option to allow Wooden Doors to be protected, which excludes the need to use Iron Doors. So I'm just asking for the same existing functionality and option that Wooden Doors have.

You mentioned, if we want to protect wooden buttons, we could use an addon with whatever behavior we desire, but no such addon exists for what you're describing. If one does, can you provide a link?

**Comment by Kruize1** [comment]
I also read the FAQ you made,

For this part "... I allow them outright because otherwise players would get a false sense of security, then feel violated when a clever griefer uses a workaround."

This is what currently happens. Players with their claims have a false sense of security, they think their claim is safe and no one can open their doors. However, Griefers are using this as a work around to enter other players homes and cause players grief.

I understand and respect where you're coming from, but we as server owners should have the choice to toggle this on/off this protection for wooden buttons in the config file, just like wooden doors.

**Comment by RoboMWM** [comment]
Not possible to determine if the owner pressed the button or players via projectile.

If no addon exists then you could request one, see the spigot services thread.
