### ISSUE TITLE
Typo in documentation that makes a command unusable

### ISSUE THREAD

**Issue by Cassolotl** [GriefPrevention/GriefPrevention#658]
### What happened:
_What you saw_

On this page: https://github.com/TechFortress/GriefPrevention/wiki/Commands

It says **/SetAccuredClaimBlocks**

The u and r in "accrued" are back to front. When used as presented this command fails. It needs to be edited to say **/SetAccruedClaimBlocks**, which works.

Thank you for maintaining good documentation generally, it's really helpful! :)

**Comment by RoboMWM** [comment]
Thanks. I used to have the wiki editable by anyone to fix these things but then too many idiots messed around with it.

**Comment by Cassolotl** [comment]
Ahh yeah, that's a hazard! I did check if it was possible to edit the wiki myself but I can very much understand why you'd want to limit editing to approved people. :)

**Comment by RoboMWM** [comment]
as an fyi, documentation will eventually be moved to GriefPrevention-Docs https://github.com/TechFortress/GriefPrevention-Docs which will accept edits via moderation in the form of pull requests.
