### ISSUE TITLE
Exploding Pistons?

### ISSUE THREAD

**Issue by KadeWolfe** [GriefPrevention/GriefPrevention#662]
Hello.
I am an operator on a server, and while I was not actually on during this event, two of my players reported to me that pistons were exploding. They were working fine in manually claimed and wilderness areas, but when they tried to use them in an area that was claimed from the auto chest claim, they exploded. We've never had this issue with Grief Prevention before this or before we installed your plugin, and we haven't installed any new plugins since we added Grief Prevention. I disabled the auto chest claiming, but this issue still occurred. Has this been a common issue, and is there any resolution to it? Also, is it possible for me to enable pistons in all areas claimed or unclaimed? Thanks!

-Kade

**Comment by bigpresh** [comment]
GriefPrevention contains some checks which can prevent pistons pushing blocks where they shouldn't, but it would simply cancel the event, not cause the piston to explode.

I suspect you have/had some other plugin that was interfering in odd ways.

If you're still seeing problems, please provide all the info requested in the issue template you deleted.
