### ISSUE TITLE
Sieging own claims though trusted players

### ISSUE THREAD

**Issue by SydMontague** [GriefPrevention/GriefPrevention#665]
### What happened:
It is possible to siege your own claim by sieging another player who is trusted on that claim.

### What you expected:
It shouldn't be possible to siege your own claim, like you can't siege yourself.

### Steps to reproduce:
1. Give any level of trust to a player on your claim
2. Move that player to the claim in question
3. /siege that player

**Comment by RoboMWM** [comment]
I had a wontfix label, but I've removed it since I seldom use it. Basically, my stance is that provided this is a bug, I'm not interested in fixing it since siege is going to be phased out of GP soon (and will be the responsibility of an addon). Anyone else is free to PR a fix though.

**Comment by Jikoo** [comment]
Closing in favor of #1143 - will be a topic for anyone stepping up to rewrite Siege.
