### ISSUE TITLE
Dispenser using bottle/sheers on beehive(s) do not work in a claim

### ISSUE THREAD

**Issue by csharptest** [GriefPrevention/GriefPrevention#674]
### What happened:
Dispensing bottle/sheers on a beehive spits out the sheers or empty bottle.

### What you expected:
Dispensing bottle/sheers on a beehive should result in honey bottle or honeycomb.

### Steps to reproduce:

1. Create a claim
2. Add beehive and bees
3. Wait for the honey
4. Place dispenser facing beehive (adjacent)
5. Place empty bottle or sheers into the dispenser
6. Trigger the dispenser

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
[21:01:21] [Render thread/INFO]: [CHAT] This server is running Paper version git-Paper-25 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)
[21:01:21] [Render thread/INFO]: [CHAT] Checking version, please wait...
[21:01:21] [Render thread/INFO]: [CHAT] Previous version: git-Paper-236 (MC: 1.14.4)
[21:01:21] [Render thread/INFO]: [CHAT] You are running the latest version
Paste of `/version GriefPrevention`:
[21:01:30] [Render thread/INFO]: [CHAT] GriefPrevention version 16.11.6

### Stack trace/error or server log
n/a
```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml
default
```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

**Comment by RoboMWM** [comment]
Update to 16.12.0, then update the issue if this is still present.

**Comment by NooblePrime** [comment]
> Update to 16.12.0, then update the issue if this is still present.

I'm having the exact same problem in 1.18. I'm using a dev build so it's understandable if a few things don't work perfectly but I do wanna bring this to your attention so it can be fixed. It's kind of ruining my automatic honey farm.

**Comment by Jikoo** [comment]
> I'm having the exact same problem in 1.18. I'm using a dev build so it's understandable if a few things don't work perfectly but I do wanna bring this to your attention so it can be fixed. It's kind of ruining my automatic honey farm.

Please raise a new issue - the information in this one is pretty old. Make sure your dispensers aren't crossing a claim boundary, that's the only situation I can think of where it would be appropriate for GP to block the dispenser action. An image with claims visualized would be helpful.
