### ISSUE TITLE
Latest release?

### ISSUE THREAD

**Issue by Cassolotl** [GriefPrevention/GriefPrevention#676]
[Github](https://github.com/TechFortress/GriefPrevention/releases), [Bukkit](https://dev.bukkit.org/projects/grief-prevention) and [Spigot](https://www.spigotmc.org/resources/griefprevention.1884/updates) all say the latest release is in September. Is that correct? I just updated my server to Spigot 1.15.1, and some things are broken with GriefPrevention, and I'd like to try updating the plugin before I report any bugs, in case they have already been fixed.

Thank you!

**Comment by RoboMWM** [comment]
Latest release is 16.12.0, so if there are issues not already reported please do so.

**Comment by Cassolotl** [comment]
Thanks, next up I'll check everything else is up to date, and then uninstall and reinstall GriefPrevention, and if the problem is still happening I'll report. :)
