### ISSUE TITLE
Jukebox "no permission" yet gives player disc

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#678]
### What happened:
When right clicking a jukebox in a protected claim without permission, a player has the disc dispensed out of the jukebox. A message is displayed saying "You don't have player's permission to use that."

### What you expected:
The message about no permission, and no disc.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Enter protected claim with no permission
2. Right click jukebox
3. Get message about no permission
4. Receive disc

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: Paper-236
Paste of `/version GriefPrevention`: 16.2.0

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

**Comment by RoboMWM** [comment]
> Paste of /version: Paper-236
> Paste of /version GriefPrevention: 16.2.0

?????????

**Comment by RoboMWM** [comment]
Can anyone verify if this is the case? Afaik all container access checks happen in PlayerInteractEvent, and `Jukebox` is one of the blocks that are checked. Maybe some other plugin is uncanceling the interact, or does the disc get ejected before interact? (Which would be very interesting.....)

**Comment by RoboMWM** [comment]
@SpacePuppeh can't reproduce. Disc remains in jukebox and music continues to play.
