### ISSUE TITLE
GP is loaded in through Sponge, but will not work

### ISSUE THREAD

**Issue by ammahieu** [GriefPrevention/GriefPrevention#681]
So the GP plugin shows in the succesfully loaded plugins in SpongeForge.
We have the right version, but it won't let us access the commands.
Whatever we do, the commands aren't recognized.

**Comment by RoboMWM** [comment]
This is a bukkit plugin.

**Comment by bigpresh** [comment]
The Sponge version of Grief Prevention can be found over at https://github.com/MinecraftPortCentral/GriefPrevention
