### ISSUE TITLE
Players can break blocks in claimed zones

### ISSUE THREAD

**Issue by PizzaRollsGod** [GriefPrevention/GriefPrevention#682]
### What happened:
Players can break claimed blocks

### What you expected:
All claimed blocks to be protected
### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Claim a zone
2. Have someone else who is not trusted in the claim come and break blocks
3. ???
4. Profit!

### Server and GriefPrevention version:
16.12.0-d4d7ac4
Paste the config.yml right here inside these backticks. Please do not use a paste service for this.
Config file is untouched

**Comment by RoboMWM** [comment]
Missing information. Have you tested with no other plugins installed? Powerranks is one of several that interfere due to poor design.

**Comment by PizzaRollsGod** [comment]
> Missing information. Have you tested with no other plugins installed? Powerranks is one of several that interfere due to poor design.

Powerranks is gone, do you know if FancyRanks has the same problem?

**Comment by RoboMWM** [comment]
I'd just use a permissions plugin like luckperms for "ranks" but idk. All depends if the plugin uncancels blockbreakevent. Easiest way to find out is to test.

**Comment by PizzaRollsGod** [comment]
We were just using it for a cosmetics thing so we'll just leave it without the ranks, thank you!
