### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by sirlinium** [GriefPrevention/GriefPrevention#69]
### What behaviour is expected:
server working well
### What behaviour is observed:
server crashed
### Steps/models to reproduce:
nothing special

### Spigot/Craftbukkit/Paper and GriefPrevention version:
This server is running CraftBukkit version git-Spigot-7d78b81-a867313 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

GriefPrevention version 16.5
(I updated the 19th from the previous version 16.4)

### Stack trace/error (if applicable)

The log is here:
http://pastebin.com/ZJ3kRmhR

### GriefPrevention config.yml (if applicable)

our config:
http://pastebin.com/z40GPgVK

### Plugin list (if applicable):
Plugins (13): CoreProtect, WorldEdit, Skript, PermissionsEx, EntityWatch, Vault, EntityDetection, Multiverse-Core, Essentials, EssentialsChat, Multiverse-Portals, EssentialsSpawn, GriefPrevention

Thank you for your help, 
Best

**Comment by ghost** [comment]
Same problem ! I have Skript, Vault, Wore protect and World Edit.

**Comment by sirlinium** [comment]
Okay, same crash this afeternoon:

console logs:
http://pastebin.com/TAEt1Njq

with the same version 16.5

Then I updated to 16.5.1 now

**Comment by RoboMWM** [comment]
@Wasabules Please update to 16.5.1, then tell me if you still get this issue.

**Comment by RoboMWM** [comment]
Future comments should be directed to #66
