### ISSUE TITLE
ADMINCLAIM PERMISSIONS

### ISSUE THREAD

**Issue by varnithian97** [GriefPrevention/GriefPrevention#690]
So no matter what permissions i add to the user/group 
-griefprevention.admin
-griefprevention.user

with these on, (and every permission included in page) I still cannot edit the flags on the admin claim created. no clue why but would love some insight to what pernmission gives complete admin controll. Since the griefprevention.admin doesnt.

I would really love some help because im not sure why it is doing this.

**Comment by RoboMWM** [comment]
there are no flags in GP itself.
