### ISSUE TITLE
/acb claim after taken away perm

### ISSUE THREAD

**Issue by LordAglet** [GriefPrevention/GriefPrevention#694]
### What happened:
My players can still do /acb {USERNAME} {AMOUNT} and it is messing with the system.
I tried taking away griefprevention.adjustclaimblocks but It still didn't work. I cant figure out a way to be able to take it away.

**Comment by zhPaul** [comment]
Which way are you revoking permissions?

**Comment by Jikoo** [comment]
Unfortunately, due to the number of variables involved, it's extremely difficult diagnose your permissions problem. Your best bet is to use a system such as LuckPerm's verbose mode that tells you real-time what permissions are being checked for whom and how they evaluate.
