### ISSUE TITLE
Owner of claim can't place, break or open chests. 

### ISSUE THREAD

**Issue by liscuate** [GriefPrevention/GriefPrevention#695]
### What happened:
A user made a claim but is not able to build, break or open chests in it, this happened to 2 users of my server. 

### What you expected:
That the user can place, break and open chests on their own claim. 

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: Spigot 1.14.4
Paste of `/version GriefPrevention`: 16.12.0

- [ ] Issue still occurs even if GriefPrevention is the only plugin running. 
- [x] Issue still occurs even after testing on a new server.

**Comment by RoboMWM** [comment]
Without any other information all I can suggest is that either another plugin is interfering, or vanilla spawn protection is.

**Comment by liscuate** [comment]
How to disable the vanilla spawn protection? In the server config file it is set to -1. Only thing I could think of would be WorldGuard but I don't know.

**Comment by liscuate** [comment]
It was indeed worldguard that was going crazy, all sorted now. :)

**Comment by RoboMWM** [comment]
Thanks for keeping us updated!
