### ISSUE TITLE
Bonus Claim bloc with permission is not display in /claimlist

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#70]
Hi,
I have a problem, if i do /claimlist , i don't see my bonus claim bloc :s 
Look: http://img11.hostingpics.net/pics/33817720161203215749.png

Thanks ;)

**Comment by RoboMWM** [comment]
> `+ 0 bonus`

Seems like it's showing your bonus blocks (which you seem to have none).

**Comment by ghost** [comment]
http://prntscr.com/dyipzm
I have the permission to boost my number of bloc (it's work).
(I have 10k of bloc because i have use the admin command to set that)

**Comment by bigpresh** [comment]
I can't reproduce this, with 16.5.1 on my test box; I see my existing bonus claim blocks, I added more with `/acb'` and the change was correctly reflected.

Does this happen for all your users?  If you use `/acb` to add claim blocks, are they then reflected in the output, or not?  Your screenshots don't appear to show you adding any bonus claim blocks, it just appears that you believe you should have some - perhaps you don't?

You say that you have the permission to boost your number of blocks, but the screenshot shows nothing of the sort, it shows only your accrual rates, which doesn't help.  Are you mistaking the "faster accrual" settings (which just let you gain the "blocks from play" a bit faster) with the bonus claim blocks (which are granted using the adjustclaimblocks /acb command) by any chance?

**Comment by BillyGalbreath** [comment]
His config in screenshot is from my GPAccruals addon, which doesnt touch bonus blocks.

**Comment by RoboMWM** [comment]
Oh, so in other words, not something related to bonus blocks or GP's core at all?
