### ISSUE TITLE
DeleteUserClaimsInWorld not working

### ISSUE THREAD

**Issue by Arthann** [GriefPrevention/GriefPrevention#718]
### What happened:
"DeleteUserClaimsInWorld world" returns "/DeleteUserClaimsInWorld <world>" in the console and doesn't remove any claims. DeleteClaimsInWorld works fine.

### What was expected:
All claims that are not adminclaims to be removed.

### Steps to reproduce:
1. Use DeleteUserClaimsInWorld in the console.

### Server and GriefPrevention version:
Paste of `/version`: [Server thread/INFO]: This server is running CraftBukkit version git-Spigot c574e08-37f32da (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: [Server thread/INFO]: GriefPrevention version 16.13.0

### Stack trace/error or server log

```
>deleteuserclaimsinworld
[00:55:27] [Server thread/INFO]: /DeleteUserClaimsInWorld <world>

```

### Debugging steps attempted

- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
well, you need to specify the world as the parameter.
e.g. `deleteuserclaimsinworld world`

**Comment by Arthann** [comment]
I'm sorry, this is the first time I created a bug report and it seems like I made a mistake with the console log paste.
I did in fact specify a world just as mentioned in the what happened section. And I used DeleteClaimsInWorld fine, which makes me believe that I'm not at fault here.

If you want to verify if this works, just try it out and you'll see.

DeleteClaimsInWorld works fine,
DeleteUserClaimsInWorld does not.

**Comment by Jikoo** [comment]
Looks like it was supposed to be handled [here](https://github.com/TechFortress/GriefPrevention/blob/956bdbc68897f40c617ae2db15ba4f5bc356dea7/src/main/java/me/ryanhamshire/GriefPrevention/GriefPrevention.java#L2112), but the code for DeleteClaimsInWorld got duplicated instead (Previous command handled is DeleteClaimsInWorld, see feedback messages).
May just be a simple correction of the string checked and method used, but I have to run out the door - can't check DataStore's available methods right now.
