### ISSUE TITLE
Option to configure minimum claim height

### ISSUE THREAD

**Issue by brr3** [GriefPrevention/GriefPrevention#719]
**As** an administrator
**I want** to be able to configure a minimum claim height
**Because** otherwise players that have access to many blocks can place a troll claim which is 1 block tall and has a huge area, completely unsuitable for protecting any build and preventing any other players from placing blocks in that area. Example: Player has access to a claim size of 100x100x100 = 1 000 000 blocks. 1 000 000 blocks can also be used for a 200x200x25 claim, a 400x400x6 claim, or a 800x800x1.5 claim. Hopefully, you can see the issue.

Forgive me if this is already possible to do, but from the short time I spent looking through the config, I could not find any such option.

**Comment by bigpresh** [comment]
A "claim which is 1 block tall" doesn't really make much sense - claim area when calculating claim blocks is 2D only - claims automatically reach to the sky and down to a certain depth (which automatically drops lower as you mine/build).

Supporting 3D claims has been discussed before, and it has always been rejected for various reasons including extra overhead when searching for claims, complexity in displaying/editing claims etc, especially if people were able to "stack" claims.

**Comment by brr3** [comment]
Ohh, sorry, I completely missed that when reading about the plugin. I thought the height was set by the user. Thank you for the quick reply!
