### ISSUE TITLE
Permissions not working!

### ISSUE THREAD

**Issue by LaxoLP** [GriefPrevention/GriefPrevention#721]
Every permission on my server is working, but not the grief prevention permission. I use griefprevention.user but they still cant claim anything.

**Comment by Jikoo** [comment]
That's because that is not a permission from GriefPrevention. You probably want `griefprevention.claims`.

**Comment by LaxoLP** [comment]
Still not working lol

**Comment by LaxoLP** [comment]
I dont get errors or anything. And every permission is working.

**Comment by LaxoLP** [comment]
I got it

**Comment by RoboMWM** [comment]
What happened?
