### ISSUE TITLE
Exempting /afk from duplicate message spam filtering

### ISSUE THREAD

**Issue by bigpresh** [GriefPrevention/GriefPrevention#724]
Players on my server have told me that, if they use `/afk` to manually mark themselves away, then `/afk` again to return, GP's spam prevention mutes the second one and it doesn't actually do anything (and if they continue to try, they get warned to be less spammy...)

I can reproduce it myself:

[21:12:53] [Server thread/INFO]: bigpresh issued server command: /afk
[21:12:54] [Server thread/INFO]: bigpresh issued server command: /afk
[21:12:54] [Server thread/INFO]: [GriefPrevention] Muted repeat message.

... and indeed the "repeated" `/afk` messages don't actually change AFK status.

Looking at the code, I think it would make sense to only consider the "identical to previous message" check if the "message" isn't empty - around https://github.com/TechFortress/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/GriefPrevention/SpamDetector.java#L53

Of course, I could just remove `/afk` from the list of `ChatSlashCommands`, but it does make sense to stop people from being able to be annoying to others by repeatedly going AFK and returning.

Maybe it should be handled differently, and still work, just not be broadcast to others if you've already gone/returned from AFK a few times recently?

**Comment by RoboMWM** [comment]
> I could just remove /afk from the list of ChatSlashCommands

`ChatSlashCommands` is intended to be used for commands that send messages, e.g. `/me`, `/broadcast`, etc.

I'd adjust `/afk` to not send to chat, which is how I use it in the server where I do use `/afk`, while still having the benefit of showing up as /afk in the /list and notifying anybody who /msgs the player

**Comment by bigpresh** [comment]
Hmm.  I thought `/afk` was in `ChatSlashCommands` in the default config, but having checked, it isn't.

Yeah, removing it from there and disabling AFK broadcast messages seems like the way to go, thanks!
