### ISSUE TITLE
SlimeFun - GriefPrevention Dupe Glitch

### ISSUE THREAD

**Issue by shaady91** [GriefPrevention/GriefPrevention#725]
Hi: 

One of our players just discovered this Dupe Glitch.

How it happens: When having an "Ender Talisman of the Miner" in your Enderchest, it multiplies your Drops everytime you mine any ore.

if a player has any Ore in their protected region, you can "Mine" that ore and the block won't break but you still get the mined Ore, as The Talisman is detecting you broke a block and it duplicates it. The duplicated ore only drops.

Here's a Screenshot just in case: [Dupe Image](https://imgur.com/a/poYZfVT)

**Comment by RoboMWM** [comment]
Please use the bug report template, and this is ultimately a Slimefun issue. GP 16.13 also adjusts the event handler priority to assist in resolving this issue, so try that first.
