### ISSUE TITLE
Permission node for higher accured claims per hour

### ISSUE THREAD

**Issue by JHarris12345** [GriefPrevention/GriefPrevention#726]
As a server owner I would like to see a permission node that can adjust how many claim blocks those people get per hour. I believe it will be a nice addition to my ranks and incentive to vote.

Optional questions:

**Is your feature request related to a problem? Please describe.**
No

**Describe alternatives you've considered**
There arent many for this

**Comment by Jikoo** [comment]
[GPAccruals](https://github.com/TechFortress/GriefPrevention/wiki/Addons#gpaccruals) exists, though I don't know that there's any documentation.

**Comment by RoboMWM** [comment]
Yes, that addon serves exactly that purpose. From what I've seen the config has well-documented comments.

**Comment by JHarris12345** [comment]
Well where is it in the config or documentation? I dont see it and would like to know how to give people bonus blocks per hour that isnt set in the config

**Comment by bigpresh** [comment]
Have a look at https://bitbucket.org/BillyGalbreath/gpaccruals/src/master/src/main/resources/config.yml

**Comment by JHarris12345** [comment]
Thanks, then what does this mean in the config. Your config guide really needs to be updated

![image](https://user-images.githubusercontent.com/46936647/75085693-8b72e300-5523-11ea-89d2-fbe4cd86258d.png)

**Comment by JHarris12345** [comment]
And also GPAccruals doesnt work. I have set the .fast perm to 150 per hour and .fastest to 200 per hour yet when you have the 200 per hour, you get 20 every 10 minutes, which is 120 per hour.... so not sure whats going on with that @RoboMWM

**Comment by RoboMWM** [comment]
> Your config guide really needs to be updated

This is not my addon, so file a bug report on that bitbucket there if you're having issues.

**Comment by JHarris12345** [comment]
What do you mean, its literally in your plugin @RoboMWM

**Comment by JHarris12345** [comment]
Also can you send me a link to where I would file an issue about GPAccruals please

**Comment by bigpresh** [comment]
> Also can you send me a link to where I would file an issue about GPAccruals please

If you go to the Bitbucket address I gave you, and click "Issues", you'd end up at:
https://bitbucket.org/BillyGalbreath/gpaccruals/issues?status=new&status=open

If I get a chance in the next few days I'll try reading the GPAccruals code and see if I can work out why you're seeing different rates, but no promises.

**Comment by RoboMWM** [comment]
> its literally in your plugin

it's literally not, you have to download a totally different jar. You can either create an issue on bitbucket or ping BillyGalbreath in the spigot thread.

**Comment by RoboMWM** [comment]
`AccruedIdlePercent` has nothing to do with GPAccruals. That config option affects how many claimblocks players receive when idle, which is default at 0%. Someone PR'd this option because he wanted idle players to still receive claimblocks, albeit at a reduced percentage.

If you have further questions about documentation please use a new issue.
