### ISSUE TITLE
Reduction in or option to remove bucket use warning

### ISSUE THREAD

**Issue by TheVillain14** [GriefPrevention/GriefPrevention#732]
After installing the plugin, I couldn't help but notice Console gets spammed heavily whenever someone uses a bucket of any kind, labelling it as suspicious. Every time it is used. So if someone is in a creative world for example, you can imagine it fills quite quickly. Perhaps a cooldown could be set and possibly modified on printing a warning in console? Or an option to disable this warning? Would be useful.

**Comment by RoboMWM** [comment]
closed in 7999da4e816dbe6c001a2d20f203cf89d4b48dc5
