### ISSUE TITLE
Add confirmation step for /abandonallclaims

### ISSUE THREAD

**Issue by NullCase** [GriefPrevention/GriefPrevention#745]
**As** a player/server operator
**I want** to change the command name or autocomplete option for /abandonallclaims
**Because** presently its the first option when typing "/a" and that's an autocomplete landmine.

Optional questions:

**Is your feature request related to a problem? Please describe.**
Autocomplete is newer than the /abandonallclaims command. As a result, something that may have been avoided when picking commands instead ends up being extremely easy to type by mistake.

**Describe alternatives you've considered**
I've tried not making mistakes and telling everyone not to make mistakes.

----
I don't know if this is worth solving. rn other dev targets have priority for funding/my time. Still, players were discussing, so here's an issue for future consideration. Basically someone made a mistake, abandoned all of their claims using autocomplete. That started the conversation.

**Comment by NullCase** [comment]
![autocomplete landmine](https://user-images.githubusercontent.com/32785664/76366829-7a86e780-6301-11ea-806f-0504bfc5dbb8.png)

**Comment by RoboMWM** [comment]
Not sure if this is possible at all, because GP doesn't implement any autocompleting. This is all on spigot.

It's probably that way because the 'a' in abandon**a**llclaims comes before 'c' in abandon**c**laim alphabetically

**Comment by RoboMWM** [comment]
I think there is another request to have confirmation for the command though, not sure.

**Comment by bigpresh** [comment]
Yeah, I definitely think adding a confirmation step would be a good idea here.

Whether that's with an extra argument you have to pass to say yes (which it prompts you to use if you didn't, i.e. you just tab-completed meaning `/abandonclaim`), or just remembering the first time you use the command and prompting you e.g. "If you run /abandonallclaims again, all your $claim_count claims will be deleted", and doing so if used again less than say 30 seconds from the last time you used it, I'm not sure.

**Comment by RoboMWM** [comment]
> Whether that's with an extra argument you have to pass to say yes

I like this idea much better than the latter suggestion (which is how it has been proposed before). Far less work to implement and less prone to errors.

**Comment by NullCase** [comment]
@RoboMWM OK, I like the idea of a confirmation step. Funding is available.

When: player types /abandonallclaims

Line 1: &eDid you want to abandon $claim_count claims? This cannot be undone.
Line 2: &eType /abandonallclaims again to confirm and delete your entire /claimlist.

(this formatting would match with messages when you select your claim tool)

And only if they retype then abandon all.

What if they don't want to confirm it? I'm imagining an autocomplete situation like:

/abandonallclaims
"Oh! i almost abandoned all of my stuff, just wanted to abandon this claim!"
/abandonallclaims
"Oops!"

**Comment by RoboMWM** [comment]
Busy at the moment, but I think there is something in ClaimClassifier, though I think it's only for abandonclaim probably? I think it works but idk cuz idk if the guy who requested it is still using it or not anymore. If that works as expected I would assume it wouldn't be much to duplicate that for this command (or just modify it to use this command)

**Comment by NullCase** [comment]
How about we take this up again when you're available. Duplicating that command to modify it sounds great.

I'm taking you time so just ignore this till later. In case it's worth mentioning... the ClaimClassifier abandonclaim confirmation worked when I tested it last. The text was unformatted, however.

**Comment by NullCase** [comment]
I am closing down and will not be funding further development work. As compensation for your hard work here I have sent some $$ to cover the costs incurred so far.
