### ISSUE TITLE
I made the server but have no perms

### ISSUE THREAD

**Issue by Idk-whatname** [GriefPrevention/GriefPrevention#748]
I just made a server but i only have access to the player commands even though I am the owner. I can't use vanilla commands either.

**Comment by bigpresh** [comment]
You've provided very little information, but that doesn't sound like a Grief Prevention issue.  You may want to look up some useful resources on how to configure a Minecraft server and whatever permissions system you're using.

**Comment by RoboMWM** [comment]
Here's something to help you get started:

Step 1: Perform `op <your Minecraft username here>` in console.
