### ISSUE TITLE
Villagers Interactions with claims

### ISSUE THREAD

**Issue by XoMiya-WPC** [GriefPrevention/GriefPrevention#755]
Villlagers are unable to break crops even if they are apart of the claim and this makes auto farms impossible.  In addition Villagers cant be infected by zombies for curing without removing their protection in the config which leaves the mvulnerable to griefing

**Comment by RoboMWM** [comment]
Please use the [bug report template](https://github.com/TechFortress/GriefPrevention/issues/new?assignees=&labels=Unverified+Bug&template=bug-report.md&title=)
