### ISSUE TITLE
ContainerTrust All not working

### ISSUE THREAD

**Issue by Nodws** [GriefPrevention/GriefPrevention#76]
### What behaviour is expected:
open containers
### What behaviour is observed:
not working
### Steps/models to reproduce:
admin claim spawn, place chest, /ct all
### Spigot/Craftbukkit/Paper and GriefPrevention version:
1.11
plugin version: 16.5

Works on other areas just not in world spawn

**Comment by Jikoo** [comment]
`spawn-protection` in server.properties prevents the usage of things like containers.

**Comment by Nodws** [comment]
Ok, --- I had spawn-protection to 16, turning it down to 0

**Comment by bigpresh** [comment]
Yep, that's it, edit it in server.properties, restart server.

I think you also wanted `/ct public`, not `/ct all`, right?

Can you confirm that all is well now and the ticket can be closed?

**Comment by Jikoo** [comment]
>I think you also wanted `/ct public`, not `/ct all`, right?

Both work, old documentation used a mix. I'd be very sad if either alias disappeared, seems like `public` is being pushed now but pretty much all of my older players use `all`.

**Comment by bigpresh** [comment]
>> I think you also wanted /ct public, not /ct all, right?

>> Both work, old documentation used a mix. I'd be very sad if either alias disappeared, seems like public is being pushed now but pretty much all of my older players use all.

Ah, fair enough :)

Anyway, is all OK now you edited server.properties and shrunk/removed the spawn-protection range?

**Comment by RoboMWM** [comment]
> seems like public is being pushed now but pretty much all of my older players use all.

Only reason why I push `public` is that `/untrust all` results in untrusting all people, instead of just untrusting the `public` group.

**Comment by Nodws** [comment]
Yes now its all working ;)
