### ISSUE TITLE
Consider placing a boat as ContainerTrust or AccessTrust

### ISSUE THREAD

**Issue by Sherris** [GriefPrevention/GriefPrevention#761]
Currently there is no way to allow a player to place a boat on water or ice inside a claim without granting that player full build trust, because the plugin considers placing a boat the same as placing a block.  This means that any player wishing to allow visitors to arrive & depart by boat can either expose a at least a few blocks to griefing or make it impossible for visitors to access boats.

Consider the example of an ice tunnel station. Players can be granted AccessTrust to push a button to call up a boat but cannot place the boat without also being granted access to break the line.

I propose that placing a should be a permission granted by ContainerTrust. This accomplishes the following:

- Gives players additional power over their claims by allowing new uses (transportation stops, for example)
- Minimizes additional complexity by not introducing another permission level
- Does not alter permissions for fully untrusted claims

Alternatives: My current alternative is to subdivide the claim so that a small number of blocks at publicly trusted. However this is less than ideal because 1) it exposes the transportation line itself and 2) it exposes every block in the Y column, which could cause issues if the required block is underground but now surface blocks are exposed to griefing/fire spread/explosions/etc

**Comment by RoboMWM** [comment]
Hmm, there are other issues that actually call for the opposite and want vehicles to be totally restricted in claims.

**Comment by Sherris** [comment]
Well, then maybe add a new command/permission? VehicleTrust? Would satisfy both.
