### ISSUE TITLE
Psi mod over rides the grief protection system

### ISSUE THREAD

**Issue by sprlmoon** [GriefPrevention/GriefPrevention#762]
The mod pack is ATM3 Remix version 1.5.2.  (https://www.curseforge.com/minecraft/modpacks/all-the-mods-3-remix/files/2857958)  After claiming the land where I wished to build, I left the server.  When I returned there was this: https://imgur.com/a/VLqcgpQ .  When the cursor was placed on it, it broadcasted that it was of the Psi mod.  The player that placed it stated when he fell in he realized that it was claimed and couldn't get out so he placed the 'blocks' to raise himself so he could walk out.
It's sad that people will find ways around grief protection.

**Comment by bigpresh** [comment]
GriefPrevention can't guarantee compatibility with other mods; at the end of the day if another plugin is intercepting events at a higher priority, or un-cancelling events which GP had cancelled to prevent an action, there's nothing GriefPrevention can do about that.
