### ISSUE TITLE
Plugin Update deleted the inventory of every player and unable to trust own Claims

### ISSUE THREAD

**Issue by smilebasti** [GriefPrevention/GriefPrevention#769]
Hi, i just got notified that the inventories of my players got deleted and is now empty. They also can not access their own chests also with the Trust command.

During i wrote this error above i rebooted and it worked fine again but is in my opinion still worth mentioning. 
GriefPrevention is the only plugin i am using on a normal Paper Server.

**Comment by RoboMWM** [comment]
GP doesn't do any inventory management, sorry. Maybe your server disk was full or something? Check your logs.
