### ISSUE TITLE
Cannot plant saplings on dirt

### ISSUE THREAD

**Issue by fordross** [GriefPrevention/GriefPrevention#77]
### What behaviour is expected:
Interact with dirt while holding a sapling, the sapling should take root

### What behaviour is observed:
The sapling briefly appears and is then returned to my inventory when planted on a dirt block.  If planted on a grass block, the sapling develops normally.

### Steps/models to reproduce:
Install GriefPrevention.  Observed behaviour becomes expected behaviour when this plugin is removed.  Find/create/place a dirt block.  Attempt to plant oak or spruce sapling

### Spigot/Craftbukkit/Paper and GriefPrevention version:
Vanilla Spigot build CraftBukkit version git-Spigot-0f17cfb-a0d5a84 (MC 1.11) with GriefPrevention version 16.5.1

### Stack trace/error (if applicable)
n/a
```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)
This should not be applicable here, and I apologise if it is - I will happily provide it on request.
```yml
```

### Plugin list (if applicable):
 CoreProtect, TTA, SquidHQ, NamedVaults, WorldEdit, PlaceholderAPI, PlayTimeRewardsRecoded, TuxTwoLib, Modifyworld, Votifier, gTab, WorldGuard, AutomaticInventory, mcMMOcredits, iConomy, PermissionsEx, EchoPet, FeatherBoard, TrophyHeads, mcMMO, GAListener, Vault, TokenManager, CmdSigns, PvAdd, Smelter, MultiInv, Essentials, SimpleRename, NoFlyZone, LiteBans, SilkSpawners, ASkyBlock, MobStacker, EssentialsChat, PlayerVaults, SuperVanish, BlueShop, Multiverse-Core, DeluxeChat, AncientGates, GriefPrevention, HolographicDisplays

**Comment by RoboMWM** [comment]
Actually, config is applicable here - there's a feature to prevent "sky tree" griefing when placing saplings on thin layers of dirt. Since I see you have skyblock plugins in place, I'm assuming you actually aren't testing on a vanilla world.

**Comment by fordross** [comment]
Got it, thanks very much for your expeditious reply - I'd gone through the config one line at a time and hadn't made the connection that it *might* be related.

I am running a skyblock server, but I also have (and tested) the issue in a vanilla world, because I do have the option for players to go there if they desire.  Could you possibly explain the logic behind why "sky trees" are only an issue when planted on dirt, but not on grass?  I'd be very curious to know more.

**Comment by RoboMWM** [comment]
Probably Big_Scary only accounting for dirt, which is a lot easier for griefers to acquire vs. grass blocks.
