### ISSUE TITLE
Error Messages when combined with ShopChest.

### ISSUE THREAD

**Issue by Weymouth87** [GriefPrevention/GriefPrevention#773]
### What happened:
Plugin Compatability issue with: https://www.spigotmc.org/resources/shopchest.11431/ 

When players use other player's shops that are set up within a claim, they are able to complete the action but are spammed with "you do not have "claim owner"'s permission to use that here!".

Have contacted the developer for ShopChest and theyve said the issue is with Grief Prevention as they cannot stop the throwback message.

### What was expected:
No message at all.

### Steps to reproduce:
Setup a shop with ShopChest within a user's claim, then have another user buy from the shop.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: Paper (102) 1.15.2
Paste of `/version GriefPrevention`: 16.13.0

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    homestead: -1
    homestead_nether: -1
    homestead_the_end: -1
    moon: -1
    shopping: -1
  Claims:
    Mode:
      homestead_the_end: Disabled
      homestead: Survival
      shopping: Survival
      homestead_nether: Disabled
      moon: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 3000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      homestead: true
      homestead_nether: true
      homestead_the_end: true
      moon: true
      shopping: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  CheckPistonMovement: true
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Plugin list (if applicable):
Plugins (59): ActionHealth, Advanced_Drop_Party, AdvancedAnnouncement, BetterBees, BetterRTP, ChatColor, ChatReaction, ClearLag, CMI, Coins, CommandSigns, CoreProtect, CustomRecipeAPI, DeepStoragePlus, DeluxeChat, DeluxeTags, Disenchant-2, Doorbells, EditableSign, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EssentialsXMPP, FurnaceNotify, Graves, GriefPrevention, HolographicDisplays, HolographicScoreboard, IngotBlock, LeaderHeadsRevamped, LuckPerms, LuckyBlock, MeltDown, Minepacks, MiniaturePets, MiningBlocks, MoonGenerator, MovingDevApi, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, MyDog, Parrots, PlaceholderAPI, PlugMan, ProtocolLib, RainbowBlocks, Referral, ShopChest, TabList, TreeGravity, UltraCosmetics, Vault, WorldBorder, WorldEdit, WorldGuard, zDiscord

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
I've designed [PrettySimpleShop](https://github.com/MLG-Fortress/PrettySimpleShop) in a way that avoids issues with nearly every protection plugin, including these messages.

In v20 the messages will be configurable by plugins (via an event, probably).

**Comment by Jikoo** [comment]
It is (now) possible to modify claim permissions by listening to the [ClaimPermissionCheckEvent](https://github.com/GriefPrevention/GriefPrevention/blob/b384806e18bbd870e53323c1e8ac719d32bb33d2/src/main/java/me/ryanhamshire/GriefPrevention/events/ClaimPermissionCheckEvent.java). The triggering event should be a PlayerInteractEvent for the case you're talking about, I assume. Setting the denial reason to null allows the action.

Going to close this though - plugin's last-supported version is 1.17, so I expect you have moved on to a different shop plugin.
