### ISSUE TITLE
Can't keep up!

### ISSUE THREAD

**Issue by ghost** [GriefPrevention/GriefPrevention#774]
### What happened:

freeze when someone connecting server

### What was expected:
_What you expected to see_

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1.
2. Step 2.
3. ???
4. Profit!

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`:  Paper #162 latest
Paste of `/version GriefPrevention`: latest

### Stack trace/error or server log

https://timings.aikar.co/?id=e6a9e02bcb79462d8b381ab54626ce17
```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Plugin list (if applicable):
 Plugins (49): AuctionHouse*, BetterBowTrails*, BossShopPro, Citizens, CMI, CMIEInjector*, ConsoleSpamFix, CoreProtect, CrateReloaded, CrazyEnchantments, DiscordSRV, eZProtector, FeatherBoard*, GriefPrevention, GUIPlus, LeaderHeadsRevamped, Matrix, mcMMO, mcMMOAction*, MessageFilter*, MoreVaultPlus, Multiverse-Core*, MVdWPlaceholderAPI*, PermissionsEx*, PlaceholderAPI, PlayerShops*, ProtocolLib, React*, SecurityVillagers, Shopkeepers, SkQuery, skRayFall*, Skript, TAB, TitleManager*, Towny, TownyChat, TradeMe, Vault, ViaVersion*, VoteParty, Votifier, VotingPlugin, VoxelSniper*, WorldBorder, WorldBorderPearlBlock*, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
Why is your timings so short? Don't ever do `/timings on` just paste. And after the server's been on for a while of course.
