### ISSUE TITLE
Players can be shot inside of their own claim by players outside of the claim

### ISSUE THREAD

**Issue by mo-rp** [GriefPrevention/GriefPrevention#777]
### What happened:
When I am inside of my claim, players who are outside of the claimed area can shoot me from outside (aka a PVP enabled area). This is annoying and frustrating because there are some idiots on the server who want to ruin it for me and kill me all the time.

### What was expected:
Them to try to shoot me and the arrow to deflect off of me, like it does when they are inside the claimed area

### Steps to reproduce:
1. Be inside of a claimed area
2. Tell someone to shoot you with an arrow from outside of your claimed area
3. You will get hit
4. you will fucking die

i dont own the server so i do not have access to the files or such

**Comment by RoboMWM** [comment]
yea, find an admin or produce a test case yourself would be helpful
