### ISSUE TITLE
[game breaking] GP gave a player over 100,000 acquired blocks & 

### ISSUE THREAD

**Issue by TomLewis** [GriefPrevention/GriefPrevention#78]
GriefPrevention 16.4
PaperSpigot: git-Paper-916 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT) 
Also Using ViaVersion for 1.11 clients

**Major issue:**
Out of the blue Grief Prevention gave one of my members (A staff member, No they cannot /acb!) 
93,505 acquired blocks, as though she had earned them by playing (the only time acquired blocks row should be updated!) I have used Grief Prevention for over 4 years and I have never seen anything like this, it not only gave her 93,505 Acquired Blocks, but it also changed the bonus blocks giving her 41337 bonus blocks. My formula is simple for Acquiring claim blocks, its 60 per hour, 1 per minute. 
No-one has access to adjust claim blocks apart from me, Nobody has access to the console, Nobody should be able to touch the acquired blocks at all, this is specifically why we have bonus blocks, to separate them from acquired! 

I looked at both the Grief Prevention log for the 25th and the Main server log for the 25th, I pulled out all records for the player that got her data changed, and I pulled all terms with "GriefPrevention" in there, nothing suspicious, just all normal GP things. (I wish the GP log would actually log GP actions).

User didn't notice until the 28th that her claim blocks were insanely high, but I kept going back through my backups to find the day it changed.

I scanned the DB for anyone else that had 200000 claim blocks, but nobody does, just incase there was a UUID error. 

I will happily give you my Server logs and GP logs, but not in public as I would like to protect my players messages (players know my github name!). I can PM it somehow?

Luckily I keep daily MySQL backups, the 25th is when all seemed fine, and she actually has her normal blocks, then fast forward to the 26th backup and you can see the jump.
25th (backup from 10am)
acquired blocks: 106495
bonus blocks: 67867

When something in Grief-prevention went wrong.
26th (backup from 10am)
acquired blocks: 200000
bonus blocks: 109204

This is a game breaking bug, if I can do any more research or scans for you to try and figure out where/why this happened, please do tell me how, as I need this to be fixed, this cannot happen again, im very lucky this happened to a staff member where they told me!

**Comment by bigpresh** [comment]
I can't see why this would just happen out of the blue for a single player, but it's concerning for sure.

You haven't used the issue template, so can you confirm a list of other plugins installed, in case there's any odd interactions?

Logs would  be useful - couldn't you just pipe through grep to remove all chat messages from it before attaching?  (e.g. 'grep -v "Chat Thread"` or similar?)  (Not certain what would be there - normal block accruals aren't logged, but perhaps whatever odd event caused this would have resulted in something logged, whether by GP itself or Spigot/Paper.

**Comment by TomLewis** [comment]
I agree its very concerning its done this out the blue for one player, and its not even though its an in-game command that's fired by accident as its effected the Acquired blocks, dramatically as well as the bonus blocks, I scanned the logs for any incident, the only thing I could possibly find, was that we had a crash due to still using groupmanger (I know, im going to replace it), so if GP does anything on a crash/shutdown that could effect somehow manipulating the MySQL data?
Plugin List:
```
Plugins (54): BetterBanner, ChunkSpawnerLimiter, GroupManager, TrapManager, PorteCoulissante, BanManager, AutomaticInventory, RetractableBridge, LagMonitor,
ViaVersion, AsyncWorldEditInjector, CoreProtect, dynmap, VoteRoulette, ChatControl, AutoMessage, NoSpawnerChange, Chairs, WorldBorder, BuycraftX, Votifier, ProtocolLib, NoCheatPlus,
AsyncWorldEdit, RedstoneClockDetector, Lottery, Vault, BottledExp, SignShop, Stats, MyCommand, PlayerHeads, WorldEdit, Essentials, FBasics, ScLoad, HeroBounty, SimpleClans,
ColoredTags, DiscordSRV, XPboost, EssentialsChat, Cannons, WorldGuard, EssentialsGeoIP, Skins, PvPManager, EssentialsSpawn, AreaShop, Autorank, GriefPrevention, Movecraft, Brewery,
Signs             
```
I will see if I can remove all in-game chat to send the server logs, it makes sending the GP logs pretty useless as they literally only record chat and when people get given claim blocks! I wish that was made a priority, getting solid data for the GP logs (pretty please!).

Thank you for replying @bigpresh I will play with grep.

**Comment by Pixiio** [comment]
We're also having this problem, please look at #95 . It seems to be an error with saving. Are you using flatfile or MYSQL?

**Comment by RoboMWM** [comment]
@FrozenBeard are you using permission groups for bonus blocks?

```
[14:16:10] ~RoboMWM: idk the relation between the two screenshots, but are you using any "permission groups" to give bonus blocks?
[14:16:39] Pixiio_: And yes, I do
[14:16:48] ~RoboMWM: well that complicates things a lot
[14:17:17] ~RoboMWM: because permissions aren't persistent, Big_Scary tries to add these on player join
[14:17:31] ~RoboMWM: right now, my suggestion is to not use those 
[14:17:52] Pixiio_: Oh.. Haha
[14:17:52] ~RoboMWM: same issue with the accrual limits and bonuses
[14:18:07] Pixiio_: What's up with the bonuses?
[14:18:19] ~RoboMWM: well, I removed that and that's handled by GPAccruals
[14:18:28] ~RoboMWM: but not the bonus permission block stuff
[14:18:44] CafeBabe: Correction, <RoboMWM> which is even more convoluted 
```

**Comment by TomLewis** [comment]
@Pixiio No Im using MySQL.
@RoboMWM I don't get what you mean by using permission groups for bonus blocks? the only way a player would get bonus blocks is via /acb <useraname> 100, What is this permissions system for it?

**Comment by RoboMWM** [comment]
Duplicate of #322
