### ISSUE TITLE
Players Claims are not working

### ISSUE THREAD

**Issue by KeticHD** [GriefPrevention/GriefPrevention#780]
My players are trying to make claims around the world. They are able to make claims but everyone can access them! help me!

**Comment by RoboMWM** [comment]
How is this a question when it sounds like a bug report

**Comment by KeticHD** [comment]
I am not sure if there is something I can do to fix this.. like is there something in the config I can do

**Comment by KeticHD** [comment]
> How is this a question when it sounds like a bug report

Is there a way I can fix this... the players are selecting their claims but people can still break their things

**Comment by KeticHD** [comment]
Fixed it

**Comment by RoboMWM** [comment]
How did you fix it

**Comment by MaxMaeder** [comment]
How did you fix it
