### ISSUE TITLE
Claim not going away after deleting plugin from plugin folder and trust not working

### ISSUE THREAD

**Issue by mchl055** [GriefPrevention/GriefPrevention#791]
**What happened:**
the trust command didn't work, i ran acces trust, container trust and normal trust and didn't get any error in chat or console. So i deleted the plugin without deleting the claim. 

**Issue:**
Now, the plugin is not in my plugins folder, nowhere in my server folder, but still can't people build, destroy, open doors, chests. 

I really want the plugin back, but i can't without a working trust command.

Pluginlist:
https://i.gyazo.com/a3e1c05963fb87dbae130efd52515e65.png
_**I'm using ultimateclaim because there is no better... If Grief Prevention works i will use it!_

**Comment by Jikoo** [comment]
If you're unable to build without GP installed, GP wasn't the cause of your issue in the first place. Make sure you're not being affected by vanilla's spawn protection.

**Comment by mchl055** [comment]
Update:

Installed GP again, removed UlimateClaims. tried AbandonAllClaims, not working because there are no claims. Still cant place destroy, open close etc.

**Comment by Jikoo** [comment]
Like I said, make sure vanilla's spawn protection isn't affecting you.

**Comment by RoboMWM** [comment]
As Jikoo mentioned, check spawn-protection (or similarly named) in `server.properties`. (That is the vanilla spawn protection.)
