### ISSUE TITLE
players can open iron doors by shooting buttons with bows

### ISSUE THREAD

**Issue by brianssixx** [GriefPrevention/GriefPrevention#792]
### What happened:

players can open iron doors by shooting buttons with bows

### What was expected:

that not to happen 

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1. make a iron door with a button to open it 
2. Step 2.
3. shoot the button
4. Profit! < yes lol

### Server and GriefPrevention version: 16.11.6
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Paste of `/version GriefPrevention`: 

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
Please see the FAQ. #752
