### ISSUE TITLE
Protect hostile mobs with nametags

### ISSUE THREAD

**Issue by fredagsguf** [GriefPrevention/GriefPrevention#796]
Hostile mobs with nametags can be killed inside claims, however i think this should be toggleable in the config.

**Is your feature request related to a problem? Please describe.**
people can grief iron farms and enderman farms.

**Comment by RoboMWM** [comment]
Guess I should add this to the FAQ too.

How do you propose players defend themselves against invulnerable, hostile mobs?

**Comment by fredagsguf** [comment]
I see what you mean, but most players who rename hostile mobs will have them caged in, and people can just run away if thats not the case - I haven't seen any hostile mob with a nametag on my server not in a cage of some sort.
Solution possibilities:
- add option pr claim.
- add config option, then the admin will make the choice and take its consequences.
- log to console and file when a player kills a nametagged hostile mob, maybe botify in chat to staff aswell?

**Comment by RoboMWM** [comment]
> but most players who rename hostile mobs will have them caged in, 

And that's what my players do, so other players can't harm them.

**Comment by fredagsguf** [comment]
Seems like you wanna add useless features like siege, not sure the exact reason but cool. You do you.

**Comment by RoboMWM** [comment]
Excuse me?

Anyone who uses siege knows that I don't really maintain that part of the plugin at all. Big_Scary added that years ago, but even he stopped using it as his server changed.

Your request is perfectly fine and easily doable in an addon, I was just curious about how well alternatives worked for you or not. Sorry for providing suggestions.
