### ISSUE TITLE
Isn't loading on server boot

### ISSUE THREAD

**Issue by Vehzx** [GriefPrevention/GriefPrevention#798]
### What happened:
On boot in the console I get the following error:
https://pastebin.com/1NKEVd5C

### What was expected:
The plugin load, although I managed to figure out that MoreVaultPlus is the reasoning for the error.

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. booting server with MoreVaultPlus plugin also

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: Paper 1.15.2 build version #225
Paste of `/version GriefPrevention`: The latest current build on spigot (16.13.0)

### Stack trace/error or server log

``` https://pastebin.com/1NKEVd5C
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```using the default config, since I am just trying to boot the plugin for the first time.

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Plugin list (if applicable):
MoreVaultPlus <---- reasoning to the error
GriefPrevention

### Debugging steps attempted

- [x] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by Vehzx** [comment]
Just to add on here, I contacted the MoreVaultPlus developer and it seems the plugin isn't getting any support, if this is an issue on their end (which i'm highly assuming this is) I'll just have to use a different vault plugin.

**Comment by Jikoo** [comment]
Please post the full logs. It's hard to help you track down the actual culprit with that little info. The logs clearly show you running additional plugins you didn't mention. The last IllegalStateException is thrown in a different area from what I remember, so your edits are also likely misleading.

Edit: 
> at com.github.hornta.wild.WildPlugin.<init>(WildPlugin.java:29) ~[?:?]

Had a look at that particular plugin's source, nothing near that line suggests it would attempt to enable a copy of GP. If you REALLY don't want to provide logs, make sure that plugin's okay - download a fresh copy or whatever.

Edit x2:
Actually, looks like it's shading in GP. There's your problem.

**Comment by RoboMWM** [comment]
Or use a better Wild plugin. https://www.spigotmc.org/resources/wilderness-tp.22853/

**Comment by Vehzx** [comment]
Thanks for the help guys but I ended up just switching vault plugin and everything runs smoothly now, appreciate it though.
