### ISSUE TITLE
So I installed the plugin to my server, but it will not show that it is installed or work?

### ISSUE THREAD

**Issue by AntiGravity78123** [GriefPrevention/GriefPrevention#805]
The answer to your question may exist in the wiki, go check that out first! 

Wiki: https://github.com/TechFortress/GriefPrevention/wiki

Otherwise, if you have a spigot account, you may have better luck posting in the discussion thread so people who follow the thread may see your question. https://www.spigotmc.org/threads/griefprevention.35615/page-311

Still no luck? Really? Then go ahead and ask here.

**Comment by RoboMWM** [comment]
Please use the bug report template
