### ISSUE TITLE
Summarize your question into a single sentence here

### ISSUE THREAD

**Issue by JennerPalacios** [GriefPrevention/GriefPrevention#806]
The answer to your question may exist in the wiki, go check that out first! 

Wiki: https://github.com/TechFortress/GriefPrevention/wiki

Otherwise, if you have a spigot account, you may have better luck posting in the discussion thread so people who follow the thread may see your question. https://www.spigotmc.org/threads/griefprevention.35615/page-311

Still no luck? Really? Then go ahead and ask here.

<details>
<summary><b>Is this plugin preventing players from spawning Withers? a lot of people have tried to spawn/fight the Wither but have failed to spawn it, I can't find this setting in the config, maybe is hardcoded?</b></summary>

</details>

**Comment by RoboMWM** [comment]
No, and how did you manage to butcher this template?
