### ISSUE TITLE
Players not getting their claimblocks per hour

### ISSUE THREAD

**Issue by NocturneNetwork** [GriefPrevention/GriefPrevention#807]
### What happened:
Players aren't getting their claimblocks per hour even though they have all the permissions and the claimblocks per hour is set to true in the config.

### What was expected:
I expected to see players get 200 claimblocks every hour.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Craftbukkit version git-Spigot-a03b1fd-fc318cc (MC: 1.15.2)
Griefprevention version 16.13.0

### GriefPrevention config.yml

`# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    admin: -1
  Claims:
    Mode:
      world_the_end: Disabled
      world_nether: Disabled
      world: Survival
      admin: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 1000
    Claim Blocks Accrued Per Hour:
      Default: 200
    Max Accrued Claim Blocks:
      Default: 2000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      admin: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  CheckPistonMovement: true
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 10
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: true
      Debug: true
      Muted Chat Messages: false
``yml

### Plugin list (if applicable):
Plugins (35): LuckPerms, AcceptRules, DoubleJump, PlaceholderAPI, SimpleRename, IP-Check, SpawnJoin, SmartBans, ProtocolLib, Multiverse-Core, CustomPolls, AlwaysDay, MVdWPlaceholderAPI, DeluxeTags, FastAsyncWorldEdit, AirBar, NoWeather, CustomHelp, CraftingStore, Vault, BungeeTabListPlus, BungeeTeleport, WorldEdit, Essentials, Scoreboard-revision, RankGrantPlus, HolographicDisplays, CommandPanels, WorldGuard, DeluxeChat, Citizens, SimpleAlias, CommandNPC, EssentialsSpawn, CratesPlus

### Debugging steps attempted

- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
Please see the FAQ on this.

> AFK players do not receive claim blocks (unless configured in the Advanced section of the config). Enable debug logs in the GP config to see information about accrued claimblock deliveries, which occur every 10 minutes.

**Comment by Jikoo** [comment]
In addition to what Robo said, you have configured the accrued claim block maximum to be 2000, meaning your players will achieve maximum claim blocks and stop gaining more after 5 hours of play.

**Comment by NocturneNetwork** [comment]
00:05 **Delivering** 33 blocks to jellyman47
00:05 **Delivering** 33 blocks to FatherDrag
00:05 jellyman47      : not the poor sheeps :O
00:05 DaddyPeppaBigPig: nooo
00:05 FatherDrag      : plz
00:05 FatherDrag      : I need ze banner
00:06 DaddyPeppaBigPig: nooooo
00:06 DaddyPeppaBigPig: i have wool
00:06 Looking for expired claims.  Checking data for eba3bdc6-6cf3-4f0c-9f21-50a315d9457f
00:06 FatherDrag      : oo
00:06 FatherDrag      : *hides with shep*
00:06 jellyman47      : make some fried sheep >:D
00:06 DaddyPeppaBigPig: NO
00:06 DaddyPeppaBigPig: bad
00:07 DaddyPeppaBigPig: smh
00:07 FatherDrag      : baa
00:07 DaddyPeppaBigPig: i gtg
00:07 jellyman47      : bbye kati
00:07 DaddyPeppaBigPig: i'll be back
00:07 FatherDrag      : i shear?
00:07 DaddyPeppaBigPig: no
00:07 DaddyPeppaBigPig: i threw wool
00:07 FatherDrag      : where
00:08 Looking for expired claims.  Checking data for ac0fbf42-8e2f-4437-b128-11cb8e9dac68
00:08 jellyman47      : imma take a break see ya later
00:08 FatherDrag      : take care
00:09 Looking for expired claims.  Checking data for 60de76ce-ffd4-443d-8179-55ec7bc11664
00:10 Looking for expired claims.  Checking data for a6d3b1e6-23d3-4c4e-b65c-571f8b12ca70
00:11 Looking for expired claims.  Checking data for fec476ac-cb2b-4dfe-b89a-28415c0dd526
00:12 Looking for expired claims.  Checking data for 283de971-a90e-421b-9b80-961a17455489
00:13 Looking for expired claims.  Checking data for acb6f1b6-35eb-4933-a7c8-2b4ec0a77be9
00:13 FatherDrag has more claimed land than blocks available.  Adding blocks to fix.
00:13 FatherDrag Accrued blocks: 1830 Bonus blocks: 0
00:13 Total blocks: 1797 Total claimed area: 1974
00:13 world: x-909, z892 // world: x-868, z938 = 1974
00:13 New accrued blocks: 1974
00:13 New total blocks: 1974
00:13 FatherDrag Accrued blocks: 1974 Bonus blocks: 0 Group Bonus Blocks: 0
00:13 Total blocks: 1974 Total claimed area: 1974
00:13 Remaining claim blocks to use: 0 (should be 0)
00:14 Looking for expired claims.  Checking data for 36219680-694d-4d92-9651-463426e4516a
00:15 Looking for expired claims.  Checking data for 28aeba90-3c9b-4753-9d42-c4b61c1cfd4b
00:16 Looking for expired claims.  Checking data for dc611ebd-0611-4420-88eb-b92912f281cb
00:17 Looking for expired claims.  Checking data for 82758136-a80f-4f7c-a9c6-d4149182d6b6
00:19 Looking for expired claims.  Checking data for 6ffc4f01-3d5f-391f-8e69-43e8a69ced39
00:20 Looking for expired claims.  Checking data for 8281a21d-7db3-4163-ab3f-b88feb865f26
00:22 Looking for expired claims.  Checking data for 897874a5-afdc-4942-a04a-e21ba984ceb2
00:23 Looking for expired claims.  Checking data for 77c68e46-f640-4978-8b43-3206d3e4e07f
00:25 Looking for expired claims.  Checking data for 4f6f3497-bbf3-477b-aba2-3d9db5bef1da
00:26 Looking for expired claims.  Checking data for c7dff83f-b596-4c03-a717-9e6074c403e9
00:27 Looking for expired claims.  Checking data for 2fb1d366-3157-4305-a8cb-99bd1b5d4cdf
00:28 Looking for expired claims.  Checking data for 0f1b28ae-7e45-4ca6-b11f-f440fc25b15b
00:29 Looking for expired claims.  Checking data for af16cfbb-348e-4cf5-9b1e-bc4ebc95a5a4
00:30 Looking for expired claims.  Checking data for 2a249477-6f39-4785-971c-674e4d6c3aa8
00:32 Looking for expired claims.  Checking data for eba3bdc6-6cf3-4f0c-9f21-50a315d9457f
00:34 Looking for expired claims.  Checking data for ac0fbf42-8e2f-4437-b128-11cb8e9dac68
00:35 Looking for expired claims.  Checking data for 60de76ce-ffd4-443d-8179-55ec7bc11664
00:36 Looking for expired claims.  Checking data for a6d3b1e6-23d3-4c4e-b65c-571f8b12ca70
00:37 Looking for expired claims.  Checking data for fec476ac-cb2b-4dfe-b89a-28415c0dd526
00:38 Looking for expired claims.  Checking data for 283de971-a90e-421b-9b80-961a17455489
00:39 Looking for expired claims.  Checking data for acb6f1b6-35eb-4933-a7c8-2b4ec0a77be9
00:40 Looking for expired claims.  Checking data for 36219680-694d-4d92-9651-463426e4516a
00:41 Looking for expired claims.  Checking data for 28aeba90-3c9b-4753-9d42-c4b61c1cfd4b
00:42 Looking for expired claims.  Checking data for dc611ebd-0611-4420-88eb-b92912f281cb
00:43 Looking for expired claims.  Checking data for 82758136-a80f-4f7c-a9c6-d4149182d6b6
00:45 Looking for expired claims.  Checking data for 6ffc4f01-3d5f-391f-8e69-43e8a69ced39
00:46 Looking for expired claims.  Checking data for 8281a21d-7db3-4163-ab3f-b88feb865f26
00:48 Looking for expired claims.  Checking data for 897874a5-afdc-4942-a04a-e21ba984ceb2
00:49 Looking for expired claims.  Checking data for 77c68e46-f640-4978-8b43-3206d3e4e07f
00:51 Looking for expired claims.  Checking data for 4f6f3497-bbf3-477b-aba2-3d9db5bef1da
00:52 Looking for expired claims.  Checking data for c7dff83f-b596-4c03-a717-9e6074c403e9
00:53 Looking for expired claims.  Checking data for 2fb1d366-3157-4305-a8cb-99bd1b5d4cdf
00:54 Looking for expired claims.  Checking data for 0f1b28ae-7e45-4ca6-b11f-f440fc25b15b
00:55 Looking for expired claims.  Checking data for af16cfbb-348e-4cf5-9b1e-bc4ebc95a5a4
00:56 Looking for expired claims.  Checking data for 2a249477-6f39-4785-971c-674e4d6c3aa8
00:58 Looking for expired claims.  Checking data for eba3bdc6-6cf3-4f0c-9f21-50a315d9457f
01:00 Looking for expired claims.  Checking data for ac0fbf42-8e2f-4437-b128-11cb8e9dac68
01:01 Looking for expired claims.  Checking data for 60de76ce-ffd4-443d-8179-55ec7bc11664
01:02 Looking for expired claims.  Checking data for a6d3b1e6-23d3-4c4e-b65c-571f8b12ca70
01:03 Looking for expired claims.  Checking data for fec476ac-cb2b-4dfe-b89a-28415c0dd526
01:04 Looking for expired claims.  Checking data for 283de971-a90e-421b-9b80-961a17455489
01:05 Looking for expired claims.  Checking data for acb6f1b6-35eb-4933-a7c8-2b4ec0a77be9
01:06 Looking for expired claims.  Checking data for 36219680-694d-4d92-9651-463426e4516a
01:07 Looking for expired claims.  Checking data for 28aeba90-3c9b-4753-9d42-c4b61c1cfd4b
01:08 Looking for expired claims.  Checking data for dc611ebd-0611-4420-88eb-b92912f281cb
01:09 Looking for expired claims.  Checking data for 82758136-a80f-4f7c-a9c6-d4149182d6b6
01:10 Looking for expired claims.  Checking data for cb904d43-1154-461f-bf9e-dffb389027ba
01:11 Looking for expired claims.  Checking data for 6ffc4f01-3d5f-391f-8e69-43e8a69ced39
01:12 Looking for expired claims.  Checking data for 8281a21d-7db3-4163-ab3f-b88feb865f26
01:14 Looking for expired claims.  Checking data for 897874a5-afdc-4942-a04a-e21ba984ceb2
01:15 Looking for expired claims.  Checking data for 77c68e46-f640-4978-8b43-3206d3e4e07f
01:17 Looking for expired claims.  Checking data for 4f6f3497-bbf3-477b-aba2-3d9db5bef1da
01:18 Looking for expired claims.  Checking data for c7dff83f-b596-4c03-a717-9e6074c403e9
01:19 Looking for expired claims.  Checking data for 2fb1d366-3157-4305-a8cb-99bd1b5d4cdf
01:20 Looking for expired claims.  Checking data for 0f1b28ae-7e45-4ca6-b11f-f440fc25b15b
01:21 Looking for expired claims.  Checking data for af16cfbb-348e-4cf5-9b1e-bc4ebc95a5a4
01:22 Looking for expired claims.  Checking data for 2a249477-6f39-4785-971c-674e4d6c3aa8
01:24 Looking for expired claims.  Checking data for eba3bdc6-6cf3-4f0c-9f21-50a315d9457f
01:26 Looking for expired claims.  Checking data for ac0fbf42-8e2f-4437-b128-11cb8e9dac68
01:27 Looking for expired claims.  Checking data for 60de76ce-ffd4-443d-8179-55ec7bc11664
01:28 Looking for expired claims.  Checking data for a6d3b1e6-23d3-4c4e-b65c-571f8b12ca70
01:29 Looking for expired claims.  Checking data for fec476ac-cb2b-4dfe-b89a-28415c0dd526
01:30 Looking for expired claims.  Checking data for 283de971-a90e-421b-9b80-961a17455489
01:31 Looking for expired claims.  Checking data for acb6f1b6-35eb-4933-a7c8-2b4ec0a77be9
01:32 Looking for expired claims.  Checking data for 36219680-694d-4d92-9651-463426e4516a
01:33 Looking for expired claims.  Checking data for 28aeba90-3c9b-4753-9d42-c4b61c1cfd4b
01:34 Looking for expired claims.  Checking data for dc611ebd-0611-4420-88eb-b92912f281cb
01:35 Looking for expired claims.  Checking data for 82758136-a80f-4f7c-a9c6-d4149182d6b6
01:36 Looking for expired claims.  Checking data for cb904d43-1154-461f-bf9e-dffb389027ba
01:37 Looking for expired claims.  Checking data for 6ffc4f01-3d5f-391f-8e69-43e8a69ced39
01:38 Looking for expired claims.  Checking data for 8281a21d-7db3-4163-ab3f-b88feb865f26
01:40 Looking for expired claims.  Checking data for 897874a5-afdc-4942-a04a-e21ba984ceb2
01:41 Looking for expired claims.  Checking data for 77c68e46-f640-4978-8b43-3206d3e4e07f
01:43 Looking for expired claims.  Checking data for 4f6f3497-bbf3-477b-aba2-3d9db5bef1da
01:44 Looking for expired claims.  Checking data for c7dff83f-b596-4c03-a717-9e6074c403e9
01:45 Looking for expired claims.  Checking data for 2fb1d366-3157-4305-a8cb-99bd1b5d4cdf
01:46 Looking for expired claims.  Checking data for 0f1b28ae-7e45-4ca6-b11f-f440fc25b15b
01:47 Looking for expired claims.  Checking data for af16cfbb-348e-4cf5-9b1e-bc4ebc95a5a4
01:48 Looking for expired claims.  Checking data for 2a249477-6f39-4785-971c-674e4d6c3aa8
01:50 Looking for expired claims.  Checking data for eba3bdc6-6cf3-4f0c-9f21-50a315d9457f
01:52 Looking for expired claims.  Checking data for ac0fbf42-8e2f-4437-b128-11cb8e9dac68
01:54 Looking for expired claims.  Checking data for a6d3b1e6-23d3-4c4e-b65c-571f8b12ca70
01:55 Looking for expired claims.  Checking data for fec476ac-cb2b-4dfe-b89a-28415c0dd526
01:56 Looking for expired claims.  Checking data for 283de971-a90e-421b-9b80-961a17455489
01:57 Looking for expired claims.  Checking data for acb6f1b6-35eb-4933-a7c8-2b4ec0a77be9
01:58 Looking for expired claims.  Checking data for 36219680-694d-4d92-9651-463426e4516a
01:59 Looking for expired claims.  Checking data for 28aeba90-3c9b-4753-9d42-c4b61c1cfd4b
02:00 Looking for expired claims.  Checking data for dc611ebd-0611-4420-88eb-b92912f281cb
02:01 Looking for expired claims.  Checking data for 82758136-a80f-4f7c-a9c6-d4149182d6b6
02:02 Looking for expired claims.  Checking data for cb904d43-1154-461f-bf9e-dffb389027ba
02:03 Looking for expired claims.  Checking data for 6ffc4f01-3d5f-391f-8e69-43e8a69ced39
02:04 Looking for expired claims.  Checking data for 8281a21d-7db3-4163-ab3f-b88feb865f26
02:06 Looking for expired claims.  Checking data for 897874a5-afdc-4942-a04a-e21ba984ceb2
02:07 Looking for expired claims.  Checking data for 77c68e46-f640-4978-8b43-3206d3e4e07f
02:09 Looking for expired claims.  Checking data for 4f6f3497-bbf3-477b-aba2-3d9db5bef1da
02:10 Looking for expired claims.  Checking data for c7dff83f-b596-4c03-a717-9e6074c403e9
02:11 Looking for expired claims.  Checking data for 2fb1d366-3157-4305-a8cb-99bd1b5d4cdf
02:12 Looking for expired claims.  Checking data for 0f1b28ae-7e45-4ca6-b11f-f440fc25b15b
02:13 Looking for expired claims.  Checking data for af16cfbb-348e-4cf5-9b1e-bc4ebc95a5a4
02:14 Looking for expired claims.  Checking data for 2a249477-6f39-4785-971c-674e4d6c3aa8
02:16 Looking for expired claims.  Checking data for eba3bdc6-6cf3-4f0c-9f21-50a315d9457f
02:18 Looking for expired claims.  Checking data for ac0fbf42-8e2f-4437-b128-11cb8e9dac68
02:19 Looking for expired claims.  Checking data for 60de76ce-ffd4-443d-8179-55ec7bc11664
02:20 Looking for expired claims.  Checking data for a6d3b1e6-23d3-4c4e-b65c-571f8b12ca70
02:21 Looking for expired claims.  Checking data for fec476ac-cb2b-4dfe-b89a-28415c0dd526
02:22 Looking for expired claims.  Checking data for 283de971-a90e-421b-9b80-961a17455489
02:23 Looking for expired claims.  Checking data for acb6f1b6-35eb-4933-a7c8-2b4ec0a77be9
02:24 Looking for expired claims.  Checking data for 36219680-694d-4d92-9651-463426e4516a
02:25 Looking for expired claims.  Checking data for 28aeba90-3c9b-4753-9d42-c4b61c1cfd4b
02:26 Looking for expired claims.  Checking data for dc611ebd-0611-4420-88eb-b92912f281cb
02:27 Looking for expired claims.  Checking data for 82758136-a80f-4f7c-a9c6-d4149182d6b6
02:28 Looking for expired claims.  Checking data for cb904d43-1154-461f-bf9e-dffb389027ba
02:29 Looking for expired claims.  Checking data for 6ffc4f01-3d5f-391f-8e69-43e8a69ced39
02:30 Looking for expired claims.  Checking data for 8281a21d-7db3-4163-ab3f-b88feb865f26
02:32 Looking for expired claims.  Checking data for 897874a5-afdc-4942-a04a-e21ba984ceb2
02:33 Looking for expired claims.  Checking data for 77c68e46-f640-4978-8b43-3206d3e4e07f
02:35 Looking for expired claims.  Checking data for 4f6f3497-bbf3-477b-aba2-3d9db5bef1da
02:36 Looking for expired claims.  Checking data for c7dff83f-b596-4c03-a717-9e6074c403e9
02:37 Looking for expired claims.  Checking data for 2fb1d366-3157-4305-a8cb-99bd1b5d4cdf
02:38 Looking for expired claims.  Checking data for 0f1b28ae-7e45-4ca6-b11f-f440fc25b15b
02:39 Looking for expired claims.  Checking data for af16cfbb-348e-4cf5-9b1e-bc4ebc95a5a4
02:40 Looking for expired claims.  Checking data for 2a249477-6f39-4785-971c-674e4d6c3aa8
02:42 Looking for expired claims.  Checking data for eba3bdc6-6cf3-4f0c-9f21-50a315d9457f
02:44 Looking for expired claims.  Checking data for ac0fbf42-8e2f-4437-b128-11cb8e9dac68
02:45 Looking for expired claims.  Checking data for 60de76ce-ffd4-443d-8179-55ec7bc11664
02:46 Looking for expired claims.  Checking data for a6d3b1e6-23d3-4c4e-b65c-571f8b12ca70
02:47 Looking for expired claims.  Checking data for fec476ac-cb2b-4dfe-b89a-28415c0dd526
02:48 Looking for expired claims.  Checking data for 283de971-a90e-421b-9b80-961a17455489
02:49 Looking for expired claims.  Checking data for acb6f1b6-35eb-4933-a7c8-2b4ec0a77be9
02:50 Looking for expired claims.  Checking data for 36219680-694d-4d92-9651-463426e4516a
02:51 Looking for expired claims.  Checking data for 28aeba90-3c9b-4753-9d42-c4b61c1cfd4b
02:52 Looking for expired claims.  Checking data for dc611ebd-0611-4420-88eb-b92912f281cb
02:53 Looking for expired claims.  Checking data for 82758136-a80f-4f7c-a9c6-d4149182d6b6
02:54 Looking for expired claims.  Checking data for cb904d43-1154-461f-bf9e-dffb389027ba
02:55 Looking for expired claims.  Checking data for 6ffc4f01-3d5f-391f-8e69-43e8a69ced39
02:56 Looking for expired claims.  Checking data for 8281a21d-7db3-4163-ab3f-b88feb865f26
02:58 Looking for expired claims.  Checking data for 897874a5-afdc-4942-a04a-e21ba984ceb2
02:59 Looking for expired claims.  Checking data for 77c68e46-f640-4978-8b43-3206d3e4e07f
03:01 Looking for expired claims.  Checking data for 4f6f3497-bbf3-477b-aba2-3d9db5bef1da
03:02 Looking for expired claims.  Checking data for c7dff83f-b596-4c03-a717-9e6074c403e9
03:03 Looking for expired claims.  Checking data for 2fb1d366-3157-4305-a8cb-99bd1b5d4cdf
03:04 Looking for expired claims.  Checking data for 0f1b28ae-7e45-4ca6-b11f-f440fc25b15b
03:05 **Delivering** 33 blocks to VirusOnYT

**Comment by NocturneNetwork** [comment]
So from 00:05 untill 03:05, only 3 players got 33 claim blocks. This isn't right? Why did the other players not get any claimblocks and why was there a break that lasted 3 hours(!!) when not a single player got any claim blocks. This must be a bug.

**Comment by RoboMWM** [comment]
maybe he was afk? I don't see any chat so that's probably why.

**Comment by RoboMWM** [comment]
Or he was offline

**Comment by Jikoo** [comment]
Closing this as there's been no further information.

Likely either a) users have already achieved max claim blocks per https://github.com/TechFortress/GriefPrevention/issues/807#issuecomment-626040134 or b) users are underwater per #1060
