### ISSUE TITLE
Claim depth don't work

### ISSUE THREAD

**Issue by PurPLeEPiC** [GriefPrevention/GriefPrevention#819]
What happened:
When player or adminclaim use to claim after 14 blocks down of claim others can mine
ExtendIntoGroundDistance: 5 and we change to ExtendIntoGroundDistance: 100 but its not working

What we expected:
is so when player or adminclaims its get claim from skylimit to bedrock and we don't need to change in config

**Comment by RoboMWM** [comment]
Believe this only applies to new claims according to another user

**Comment by RoboMWM** [comment]
so either need to recreate or just have players build downwards in existing claims and it should extend by 100 blocks instead of 5

**Comment by PurPLeEPiC** [comment]
okay but after a while claim go back from bedrock to only 14 blocks down of claim

**Comment by RoboMWM** [comment]
Uh... that's strange.

I think I recall the task actively checks for player blocks - but I don't recall if it dynamically moves it up or down or if it's only set to go down.

Try setting the value to something larger, like `256`?

**Comment by samuelthng** [comment]
Any updates on this actually? We've got this exact issue as well. Also, RoboMWM, anything we can do to help debug this issue? We've got a dev environment to play with some stuff.

What we experience: 
Players claim at some arbitary depth, fly below that depth to check for claims, will be marked unclaimed.
Place block on unclaimed area and check again - will be updated as claimed.
During time as unclaimed, an untrusted player is able to open chests and place/break blocks.

Will edit my post once i can confirm other details.

**Comment by RoboMWM** [comment]
> Any updates on this actually? We've got this exact issue as well. Also, RoboMWM, anything we can do to help debug this issue? 

Starting by pasting your config would help.

    ```yml
    paste it in a code block like this
    ```

**Comment by Jikoo** [comment]
Duplicate of #312

**Comment by Jikoo** [comment]
Since there was mention new player claim chests I checked just to be sure, and they do also use the [extend into ground distance](https://github.com/TechFortress/GriefPrevention/blob/03ab872f6d575472f894a09ac219be5134dd9575/src/main/java/me/ryanhamshire/GriefPrevention/BlockEventHandler.java#L357).
