### ISSUE TITLE
Server Console error

### ISSUE THREAD

**Issue by mmagoo13** [GriefPrevention/GriefPrevention#82]
I keep seeing the following errors in my console
http://pastebin.com/ac7Q3wd2

Im not sure what would be causing them honestly but it seems to be a persistent bug my server has experienced over the last few versions of GP

**Comment by bigpresh** [comment]
The new issue template requests Grief Prevention version, MC server version, and a list of plugins for a reason - there's very little detail here.  My gut reaction would be "using the wrong GP version for your MC version", but I can't be sure of that.

Are you seeing any errant behaviour, or are the log messages the only issue you're seeing?

At a glance, it could be struggling to load data for a specific player - `57b454b3-3f1e-4d3a-8de5-6c1ff0f36c9c` looks to be their UUID - do you see that specific one every time, or do you see it for various players?

**Comment by mmagoo13** [comment]
actually it is that same id every time after checking and we are using the latest GP on MC 1.11.2 as far as plugins our list is rather long... 

WildTP, LampControl, PlugMan, EnchantsPlus, MoreItems, ConsoleSpamFix, CamStorage, Actions, ParticleLIB, Elytra, PlayerMagnet, CoreProtect, AsyncWorldEditInjector, dynmap, WorldEdit, Skript, VeinMiner, ChatControl, SkQuery, Votifier, ProtocolLib, LibsDisguises, AsyncWorldEdit, PermissionsEx, FeatherBoard, HCTeamsFreeze, NightVisionReloaded, mcMMO, GAListener, Vault, LuckyBlockSuper, PerWorldInventory, PlotSquared, VoteParty, WorldGuard, CraftHeads, WeatherMan, WirelessRedstone, MineMaze, Essentials, Jobs, Auctions, SilkSpawners, Multiverse-Core, ChopTree3, ColoredTags, Shopkeepers, CraftBook, Multiverse-Portals, GriefPrevention, EnjinMinecraftPlugin, HolographicDisplays, EssentialsProtect, Multiverse-NetherPortals, EssentialsSpawn, Statz, Autorank, ArmorPlus, CommandSigns

**Comment by RoboMWM** [comment]
"latest" is not a version.

Please follow the template, namely:
- Spigot/Paper/CB `/version`
- GriefPrevention version (you can use `/version GriefPrevention` to figure this out.)
- Conditions which cause said error to occur (on boot, when player logs in, etc.?)

**Comment by mmagoo13** [comment]
okay im sorry about that
im using spigot and i'm not sure what the version is but this is what i see in console: git-Spigot-b4417b8-a1d3777 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
gp version is v16.6
as far as conditions go there are none that i can tell, the error occur randomly even if no players are on the server

**Comment by RoboMWM** [comment]
I'm going to guess it's a corrupt player file. Remove the indicated player file in the error messages from your playerdata folder

**Comment by mmagoo13** [comment]
okay thanks for the help

**Comment by RoboMWM** [comment]
Is the issue resolved?

**Comment by mmagoo13** [comment]
yes sorry i didn't get back sooner, the removing of the file fixed everything
