### ISSUE TITLE
players can't farm cocao beans with containertrust

### ISSUE THREAD

**Issue by destro174** [GriefPrevention/GriefPrevention#839]
### What happened:
Players need build trust to be able to farm cocao beans in a claim

### What was expected:
players should be able to farm cocao beans with containertrust like other crops
containertrust:
      description: Grants a player access to your claim's containers, crops, animals, bed, buttons, and levers.

### Steps to reproduce:
Create a claim and try to place/break cocao beans with /containertrust

### Server and GriefPrevention version:
Paste of `/version`: 
Paste of `/version GriefPrevention`: 16.13.0

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
Design-wise, this is a bug, but implementation-wise this is a feature, so I'm labeling it as such.

**Comment by RoboMWM** [comment]
Not sure if this has been added yet or not given the numerous PRs.
