### ISSUE TITLE
No build in unclaimed toggle

### ISSUE THREAD

**Issue by Rikk010** [GriefPrevention/GriefPrevention#842]
**As** a player
**I want** an option in config to toggle build-in-unclaimed 
**Because** "creative" mode is not working correctly with epic worldgenerator

Here's how to increase your chances of your feature request being understood (and potentially considered for implementation): https://content.pivotal.io/blog/how-to-write-well-formed-user-stories

Optional questions:

**Is your feature request related to a problem? Please describe.**
Yes, i also opened a issue on this github, its removing random blocks(leaves, stones, dirt) in the epic worldgenerator when /abandonallclaims this is probably epic worldgenerators fault

**Describe alternatives you've considered**
Tried other griefprevention plugins but those are way to complicated for my players and it doenst have a notinclaim build prevention

**Comment by Jikoo** [comment]
Already exists, use SurvivalRequiringClaims mode.

**Comment by RoboMWM** [comment]
Did you... read any of the comments I put?
