### ISSUE TITLE
Confirm to abandonallclaims

### ISSUE THREAD

**Issue by x1p** [GriefPrevention/GriefPrevention#843]
**As** a player, executing `abandonallclaims` is easily done if one isn't thinking clearly.
**I want** players to confirm by entering `/yes` or `/no` (or clickable message) to prevent all claims to be lost.
**Because** the command is the first command if a player does / (tab) (tab) (enter). A mistake is easily made and can have devastating consequences.

Optional questions:

**Is your feature request related to a problem? Please describe.**
When a player confuses this command with the regular `unclaim` bad things can happen. Especially younger children have trouble remembering commands and their consequences.

**Describe alternatives you've considered**
Making a fake command `/aaa` to take the first place in the (tab completion) command list in order to make the command less visible.

**Comment by RoboMWM** [comment]
I'm like almost certain this request already exists

**Comment by TomLewis** [comment]
I requested this about 5 years ago im sure.

**Comment by SlimeCody** [comment]
Bump

**Comment by bigpresh** [comment]
This is a dupe of #745 which had a bit more discussion on how to implement, so let's close this one and discuss there.
