### ISSUE TITLE
Players can fire Sand into claim

### ISSUE THREAD

**Issue by vastolf** [GriefPrevention/GriefPrevention#859]
### What happened:
Player created a small sand "cannon" with a piston just a couple blocks outside the claim, but really high up. They're able to fire sand onto the claim from outside.

### What was expected:
Expected that the sand wouldn't be able to land

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Make a piston about 1-2 blocks outside claim, preferably high so the sand has some room to travel horizontally
2. Sand in front of it, fire
3. Profit

### Server and GriefPrevention version:
Paper 354
Latest GriefPrevention

**Comment by RoboMWM** [comment]
Invalid ticket format (lacks necessary information to determine problem). Please fill out the template you deleted.

**Comment by vastolf** [comment]
@RoboMWM you're asking for console errors when I'm talking about an issue with functionality? There are no errors or logs related to this bug. I can't give you error logs for something that doesn't produce errors. Make a piston 2 blocks outside of a claim, high up. Shoot sand. I can give you an IP to test it on if you'd like.

**Comment by RoboMWM** [comment]
> Latest GriefPrevention

Was basically why. I guess I was too lazy and just used a canned response.
