### ISSUE TITLE
Siege immunity permission

### ISSUE THREAD

**Issue by souldin** [GriefPrevention/GriefPrevention#86]
Siege is working fine, but the issue i am facing is my Admin team is immune to siege? how can i make it to where they can be can siege? they can siege people just fine.

**Comment by RoboMWM** [comment]
Admin claims can't be sieged, if that's what you're asking.

**Comment by souldin** [comment]
yes that is what im asking. anyway around that? i have MODS and ADMIN each with different perms is the issue

**Comment by bigpresh** [comment]
Have them use their own personal claims, not admin claims?

Admin claims are generally intended for "public areas" that don't belong to a specific person - e.g. the general spawn area, public buildings, whatever.

If your admins are using /adminclaim for their *own* stuff, then they're doing it wrong :)

**Comment by souldin** [comment]
Yes these are player claims not admin claims. The admin play just like normal plays unless there admin roles are needed.

**Comment by bigpresh** [comment]
I assume they're not opped?

Check if you've given them the `griefprevention.siegeimmune` permission (either explicitly, or by giving them `griefprevention.*` - if the latter, you'll need to negate it).

However, if the siegeimmune permission allows you to start sieges, but not be sieged, that is arguably a bug - it would be better if being immune from being sieged also meant you couldn't begin sieges, I think.

**Comment by souldin** [comment]
griefprevention.siegeimmune is set to false, along with in groupmanager i dont see it at all

**Comment by souldin** [comment]
Admins have the same as MOD and default.
    - g:GriefPrevention_default
    - g:griefprevention.siege_default

**Comment by souldin** [comment]
and the admin can do OP but when they deop still cant do it

**Comment by bigpresh** [comment]
Right - so, what actual message do your players get when they try to siege one of your admins?

**Comment by souldin** [comment]
player immune to siege

**Comment by bigpresh** [comment]
Right, so, they have the permission I noted, one way or another.  Have another look at your groupmanager config, it's got to be coming from somewhere.

To find out, try `/manucheckp AdminPlayerName griefprevention.siegeimmune` (use the player name of one of your admins) and/or `/mangcheckp Admin griefprevention.siegeimmune` (where Admin is the name of the group your admins are in) - they should get Group Manager to tell you.

**Comment by souldin** [comment]
when running the command i get an internal error occurred while attempting to perform this command

**Comment by bigpresh** [comment]
It sounds like you have some interesting problems to solve, then - have a look in your server's log for clues as to what's going on there?

**Comment by souldin** [comment]
hmmm ok

**Comment by souldin** [comment]
so i did a check on a admin name and and get this, the player 'null' has
the following permissions: Griefprevemtion.siege
and all the permissions from group : default
Default has everyones permissions.

**Comment by bigpresh** [comment]
> so i did a check on a admin name and and get this, the player 'null' has the following permissions: 
> Griefprevemtion.siege

... you want to be looking at griefprevention.siegeimmune, though.  You've already said that they can *start* a siege.

**Comment by souldin** [comment]
Ok so should the siegeimmune be there? When i run the command

On Feb 15, 2017 4:34 PM, "David Precious" <notifications@github.com> wrote:

so i did a check on a admin name and and get this, the player 'null' has
the following permissions:
Griefprevemtion.siege

... you want to be looking at griefprevention.siegeimmune, though. You've
already said that they can *start* a siege.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TechFortress/GriefPrevention/issues/86#issuecomment-280162349>,
or mute the thread

**Comment by bigpresh** [comment]
Right, I just tested on my server with `/manucheckp bigpresh griefprevention.siegeimmune`

You want to see a response of `The player doesn't have access to that permission` and nothing more - no further lines like `The user inherits the permission from group: Mod` or similar.

**Comment by souldin** [comment]
Hmm ok ill haft to look some more at why im getting that error when running
that command

**Comment by plasticblues** [comment]
Running the latest release GP and Groupmanager? Error might be related to an outdated groupmanager plugin and fixed in a more recent build?

Is your groupmanager configuration correct? Any errors with groupmanager on starting the server? Any errors with GP on starting the server? Have you enabled debug in GP and GroupManager to try to diagnose this issue yourself further? Not to invade this thread with my inexperience but there's a lot of lacking information here that may or may not help diagnose the issues you are having...

**Comment by souldin** [comment]
The server is new with updated plugins. No errors when start everything for
groupmanager is working correctly all the players permissions i set and
built in groupmanager are working this is only affecting me and my wife ad
we are the only full admins with the option to op. The mods group is
working fine they can siege and be sieged. Us admins can siege just fine.
We cannt be sieged is the odd part. In the admin permission we have the
siege permssions like all the other groups also.  I have not ran a dbug as
i did not know about it

On Feb 15, 2017 7:09 PM, "plasticblues" <notifications@github.com> wrote:

Running the latest release GP and Groupmanager? Error might be related to
an outdated groupmanager plugin and fixed in a more recent build?

Is your groupmanager configuration correct? Any errors with groupmanager on
starting the server? Any errors with GP on starting the server? Have you
enabled debug in GP and GroupManager to try to diagnose this issue yourself
further? Not to invade this thread with my inexperience but there's a lot
of lacking information here that may or may not help diagnose the issues
you are having...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TechFortress/GriefPrevention/issues/86#issuecomment-280196696>,
or mute the thread

**Comment by RoboMWM** [comment]
Issue is clearly a user-end permission issue.

FYI, groupmanager is dead and not maintained, I highly recommend using something else such as PermissionsEx or zPermissions (there's also LuckPerms too I guess?). Try to avoid giving out wildcard permissions - relying on negating permissions is tricky, and wildcard permissions can cause issues depending on how the permission plugin handles the wildcard.

**Comment by souldin** [comment]
Do they work with essintals

**Comment by bigpresh** [comment]
On Thu, 16 Feb 2017 07:04:21 -0800
souldin <notifications@github.com> wrote:

> Do they work with essintals

Consider taking ten seconds to find the answer to that yourself; this
is a bug tracker for GP bugs, not general Minecraft plugin support :)

http://wiki.mc-ess.net/wiki/FAQ#I_currently_use_a_permissions_system.2C_can_I_use_Essentials.3F

**Comment by souldin** [comment]
Ya im going to stick with groupmanager to many groups set up. The issues
lies somewhere. But rebuilding a new permissions system on a live server is
just a bad idea

**Comment by RoboMWM** [comment]
> Do they work with essintals

Yes.

The permission plugins I mentioned use the Bukkit "superperms" API more or less anyways, and all three are maintained.

Also, at least when I transitioned from GroupManager to PEX long ago, I remember it being very simple, as the structure is pretty much the same.

> Check if you've given them the griefprevention.siegeimmune permission (either explicitly, or by giving them griefprevention.* - if the latter, you'll need to negate it).

May be able to help if you share your permissions file - no guarantees though.

**Comment by plasticblues** [comment]
> Ya im going to stick with groupmanager to many groups set up. The issues lies somewhere. But rebuilding a new permissions system on a live server is just a bad idea

Having an outdated/unsupported permissions plugin is probably worse than trying to rebuild a permission file on a live server, plus you can always use a test server to make the permission file and test then once you're sure its correct put it on the live server and solve issues from there. The most problem you might have is missing permission nodes vs giving too many.

Just my 2 cents.

**Comment by RoboMWM** [comment]
@souldin have you ever resolved your issue?
