### ISSUE TITLE
Creepers wont do World Damage out of Claim. Only Player-Damage

### ISSUE THREAD

**Issue by plonknet** [GriefPrevention/GriefPrevention#862]
### What happened:
Hiho,

i know its early stage but i wanted to report this issue. Im Running a plain Paper 1.16.1 Server (latest) and installed the latest version of griefprevention. Creepers wont do any Worlddamage, neither inside a claim, neider outside. Outside of the claim the player will get playerdamage, but no world damage. Inside of the claim everything is working fine :)
### What was expected:
World Damage

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
see description

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`:  latest
Paste of `/version GriefPrevention`: latest

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Plugin list (if applicable):

latest essentialsx, vault, griefprevention

### Debugging steps attempted

- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server

**Comment by Jikoo** [comment]
Please include all of the information you left out, most importantly your config. Also, "latest" is not a valid version. There's a reason the template specifically requests a paste of the output of `/version`.

While you're poking around in the config I suggest you check the setting for blocking surface explosions, because that's probably what you're encountering.
