### ISSUE TITLE
Protect Respawn Anchors in 1.16

### ISSUE THREAD

**Issue by bigpresh** [GriefPrevention/GriefPrevention#865]
1.16 adds [Respawn Anchors](https://minecraft.gamepedia.com/Respawn_Anchor) which act like a bed in the overworld to set your respawn location for later use with `/home` etc.

They have to be "charged" with glowstone, and each use consumes a charge.

At present, people untrusted in the claim can interact with them and thus consume the owner's charges, leaving the owner unable to /home.

They should probably be protected from interactions unless you have ContainerTrust.

Thanks to @IndigoRoger for reporting.

**Comment by isabelcoolaf** [comment]
Can reproduce this bug

**Comment by RoboMWM** [comment]
1.16 adds features from Essentials?

ok.

**Comment by RoboMWM** [comment]
Wait according to the wiki there is no /home command it's basically a bed for the nether.

**Comment by IndigoRoger** [comment]
Sorry RoboMWM. Yes, its more just that if you right click on a respawn anchor when you die it uses up a charge. Grief prevention supports preventing people without trust from setting respawn location to beds, and that should be applied to respawn anchors as well especially considering it has a cost to the block.

**Comment by RoboMWM** [comment]
@IndigoRoger I'm well aware this should be protected.
