### ISSUE TITLE
Creative Entity Limit

### ISSUE THREAD

**Issue by TomLewis** [GriefPrevention/GriefPrevention#87]
Im still using 16.4 on my main survival, as it was causing full blown crashes the version above that, so I haven't updated yet, but today I needed to test a new plugin compatibility with GP and used the latest 16.6, i was testing a painting changing plugin, and when I went to put another painting in the same claim, it said I reached an entity limit for this small claim! I was like, this is a cool new feature, until I went to look for the configs, There aren't any, or even a message in the messages.yml! First can I confirm this is a new feature of GP, secondly if it is, how do I adjust/turn it off?

**Comment by RoboMWM** [comment]
This limit only applies to worlds in the `Creative` claims mode.

> First can I confirm this is a new feature of GP

It isn't

**Comment by TomLewis** [comment]
Ok, cool, how do I customise its limits?

**Comment by RoboMWM** [comment]
Big_Scary made it non-customizable.

I will be moving this feature out for version 20 and will be in an addon (and customizable).

**Comment by TomLewis** [comment]
Sounds good to me,  thanks for the information.

**Comment by RoboMWM** [comment]
Removal planned with #2019
