### ISSUE TITLE
[Request]Claims automatically stop at WorldBorder

### ISSUE THREAD

**Issue by Thefroness** [GriefPrevention/GriefPrevention#88]
A request to have claims not be allowed to pass/overlap world border.

**Comment by RoboMWM** [comment]
Could you give me an example of why this is needed? Although yea it's silly for claims to extend past the border, player's can't access said area either - so they're just wasting claim blocks.

**Comment by plasticblues** [comment]
One problem I forsee is say someone claims past the worldborder, a patch comes out for minecraft the introduces new stuff, to the (insert world here) so you decide to expand the world border, that player now has an advantage over people who didn't claim in to the worldborder on the new stuff that gets generated within said persons claim.

I'm reaching a bit here to say that it's useful, but really that's the only scenario I can think of :\

**Comment by ShaneBeee** [comment]
Wouldn't they only be able to claim land that is already generated? 
So if minecraft did introduce items it would only generate on an ungenerated chunk? Which therefor wouldn't be claimed?

**Comment by zedwick** [comment]
The main advantage I would see is for servers who reduced the size of the border, rendering claims outside the border inaccessible. As far as I know there is no simple way to remove claims from outside the border without either visiting them, or by modifying files.

Having claims outside the border removed to free up claim blocks by the players affected would help a lot. (I have this issue, as my world ran borderless for years before eventually adding the worldborder plugin and later using the new vanilla world border. Never did quite work out how to remove all the old claims.)

**Comment by RoboMWM** [comment]
Proactively removing claims that extend past the border? That doesn't sound like a good idea

**Comment by bigpresh** [comment]
I think this sounds like something that's so unusually needed, that you'd be better off writing a one-off script that walks through all GP claims, checks if they lie outside your defined world border radius, and if so, removes them - I don't think such support belongs in GP itself.

I can't imagine many people have taken the approach of shrinking their world, leaving players who'd built/claimed further out suddenly missing their stuff, so I don't think it's likely to be of use to many.

**Comment by zedwick** [comment]
I agree with @bigpresh with regards to my own comment, which is upon re-reading actually only partially related to the above request.

**Comment by bigpresh** [comment]
The discussion here has petered out, but I think it's pretty much agreed that this is an uncommon problem and best handled in a plugin/one-off script rather than in GP itself, so I'll close this ticket.
