### ISSUE TITLE
Players can't kill Hoglins in claims

### ISSUE THREAD

**Issue by destro174** [GriefPrevention/GriefPrevention#885]
### What happened:
Players can't kill hogslins in another persons claim.
![image](https://user-images.githubusercontent.com/40720638/87677584-3a85b480-c77a-11ea-96e1-e89c894ceabc.png)

### What was expected:
Hoglins are considered to be aggressive mobs, and therefor shouldn't be protected by claims?

### Steps to reproduce:
1. Make a claim in the nether
2. Spawn a hoglin
3. Try to attack it on another account

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: This server is running Paper version git-Paper-89 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`:  GriefPrevention version 16.14.0

**Comment by RoboMWM** [comment]
They're considered animals in the Bukkit API... I think the only exception to this has been killer bunnies. Do hoglins attack, even if not provoked?

**Comment by RoboMWM** [comment]
According to the (not always but usually is reliable) wiki, it seems they are hostile by default. Idk why they are considered an Animal though... so that's fun.
