### ISSUE TITLE
Players can make claims, but all can access everything in them

### ISSUE THREAD

**Issue by StampedinTurtle** [GriefPrevention/GriefPrevention#888]
### What happened:
Player's claimed blocks, shows up as claimed, all other players can interact with anything inside of all claims

### What was expected:
Players wouldn't be able to interact with claimed land, land does show up as owned, happens in both admin and basic claims

### Steps to reproduce:
1. Had various players/admins put down chests in various claimed lands
2. Had other players interact with chests/items
3. They can still touch all the things but can see that land is claimed
4. Much confuse.

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Paste of `/version GriefPrevention`: 

Keeps saying Unknown command?

### Stack trace/error or server log

```
No error shows up

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

I can't seem to find this file.. I'm sorry I'm newer to modding things and have looked all over the mod files 

```

### Plugin list (if applicable):
EcoBridge
EconomyLite
LuckyPerms-Sponge
PixelEvent
PixelExtras
PixelHunt
Pixelmon
PixelmonBroadcasts
PixelMoney
Quickhomes
Quickteleports
Spongeforge
Tournaments
Xaeros Minimap
Xaeros Worldmap

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

First I just want to say sorry I'm a little lost, I'm newer to modding but would love to get this running for my players.. any and all help would be so appreciated.

Hi there! I'm an admin for a multiplayer pixelmon server (v 1.12.2) that is trying to use this mod as so that our 40+ players don't run into issues when it comes to others touching their stuff. The mod seems to be in working order as players can put down chests, it auto claims, or can use the golden shovel to create claims and such, but the issue is that anyone can still open any chest placed down or make any adjustments to a claim they want. 

I'd appreciate any help that could go into fixing this, I'm just completely lost as to what's causing it to only half work, as is the server owner. I have full backend access for the server so can make any adjustments needed. It's not hosted on a website but a dedicated rig. (In case this makes any difference though I wouldn't think so.) I'd really like to use this mod for our grief prevention as I love how it works, but I'm just stumped. Anyone know what I could do to try and fix it?

**Comment by Jikoo** [comment]
Sounds like you're after [GP for Sponge](https://github.com/MinecraftPortCentral/GriefPrevention), which was discontinued in favor of GriefDefender.

**Comment by StampedinTurtle** [comment]
If I pull GP off of the server to put on grief defender will it break anything? As it's been an active server for about 2 or so weeks now, so just don't want to cause any major breaks, I found the migration bit of the wiki so I'll just give that a try, thank you though!

**Comment by Jikoo** [comment]
I doubt it, GP should only be storing claim data - nothing breaking. Can't guarantee anything, not at all familiar with the Sponge port.

**Comment by RoboMWM** [comment]
This repo is for the original (Bukkit) plugin, the sponge one is a fork that has significantly diverged - so ya, no clue sorry.
