### ISSUE TITLE
Server hangs on loading chunks during entity cleanup

### ISSUE THREAD

**Issue by RWoof** [GriefPrevention/GriefPrevention#889]
### What happened:
Loaded up my server with the latest paper version (98, updated from 88), also updated Coreprotect, Vault and Panilla to their newest versions as of today. On server startup, dynmap started to finish up a fullrender that had been going for a few days with no issues before any updates. After a few minutes the server died with a massive log of errors. Tried to restart but server would not start up, froze on "Reloading ResourceManager: Default, bukkit"

### What was expected:
Server running as normal.

### Steps to reproduce:
I am unsure how to reproduce except to run a server with the same plugins and see what happens.

### Server and GriefPrevention version:
Can't get into my server yet but I was using the latest version: GriefPrevention 16.14.0

### Stack trace/error or server log

https://pastebin.com/XEhTMLeQ
https://pastebin.com/rKG597RM

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    hello new world im dino girl: -1
    hello new world im dino girl_nether: -1
    hello new world im dino girl_the_end: -1
    Creative: -1
    Creative2_nether: -1
    Creative2_the_end: -1
    Creative2: -1
  Claims:
    Mode:
      hello new world im dino girl_the_end: Survival
      hello new world im dino girl_nether: Survival
      Creative2: Survival
      hello new world im dino girl: Survival
      Creative2_nether: Survival
      Creative2_the_end: Survival
      Creative: Creative
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 480
    Claim Blocks Accrued Per Hour:
      Default: 240
    Max Accrued Claim Blocks:
      Default: 80000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 14
      UnusedClaimDays: 180
      AllClaims:
        DaysInactive: 180
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      hello new world im dino girl: true
      hello new world im dino girl_nether: true
      hello new world im dino girl_the_end: true
      Creative: true
      Creative2_nether: true
      Creative2_the_end: true
      Creative2: true
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: false
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: false
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 5.0
    ClaimBlocksSellValue: 0.25
  ProtectItemsDroppedOnDeath:
    PvPWorlds: true
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  CheckPistonMovement: true
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
```

### Plugin list (if applicable):

Coreprotect, Dynmap, Dynmap-Essentials, EssentialsX, EssentialsX-AntiBuild, EssentialsX-Chat, EssentialsX-Geoip, EssentialsX-Spawn, Farmlimiter, Griefprevention, GriefpreventionFlags, IllegalStack, InvincibleWorldChests, Luckperms, Mutiverse Core, Multiverse Inventories, Multiverse Netherportals, Multiverse Portals, Panilla, Playershopgui+, ProtocolLib, ShopGUI+, ShopGUI+ Sillkspawners Bridge, Silkspawners, Spartan, Vault, Viabackwards, Viaversion, VillagerOptimiser, Worldedit

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by RWoof** [comment]
Restored from a backup and rolled Paper back to 89, left the other plugins updated to see what happens. Managed to get past the freeze on server startup, hopefully it's stable.

**Comment by RWoof** [comment]
Update, server died again with the same error spam with Paper 89, perhaps it's one of the other 3 plugins I updated conflicting with GP. Rolling them back now and trying again with Paper 89.

Any idea which plugin?

**Comment by RoboMWM** [comment]
These are watchdog threads due to the server not being able to load chunks. I'm guessing your "massive crash" was probably the disk filling up or something, which can cause region files to save incorrectly (corrupting the file) and causing undefined behavior when the server attempts to load the chunks. GP is checking chunks for entities, presumably the loaded ones, to cleanup on your creative world. If you wish to disable this cleanup you can set the creative world as Survival or SurvivalRequiringClaims.

**Comment by RoboMWM** [comment]
Basically, all I see is that your server is too slow to load chunks. Without timings, it's not really possible to determine why.

**Comment by RWoof** [comment]
Thanks for the help, the disk is far from full, it's 10tb of mostly empty space. The server has been running for months with no issue so far, but who knows what caused this, it's the first time and was coincidentally right after updating paper, coreprotect, vault and panilla. I'll do my best to get a backup running, it seems to have left me with corrupted files.

**Comment by RWoof** [comment]
I got the server running again with the old plugins, here's a timings report from just now: https://timings.aikar.co/?id=0c0eb17931544693b2551b0e6a8d5e03

Perhaps it was one of the newly updated plugins, I'll try a few things on my test server later on.

Please note Dynmap was doing a fullrender during this timings report on the Creative2 world.

**Comment by RWoof** [comment]
Update, crashed again with similar errors :( My server is dead.

**Comment by RoboMWM** [comment]
> Please note Dynmap was doing a fullrender during this timings report on the Creative2 world.

Well, that definitely doesn't help. Dynmap is going to be intensive unless you know how to tune it down properly. I'd recommend doing a fullrender with no other plugins on if that's what you intend to do.

**Comment by RWoof** [comment]
I'm not sure why, but GP today keeps killing the server, dynmap has stopped the render, there's nothing going on and no players, timings seem good but as soon as it goes to run it's entity cleanup the server crashes and dies :(

Oh, I just noticed my log says paper 98 again, I'll replace the jar, maybe it's just some incompatibility with the new version of paper.

**Comment by RWoof** [comment]
Here's an updated timings: https://timings.aikar.co/?id=1b3b46fcda3246ebb14dcd1e53fd8e7f

It still looks to me like the entity cleanup is not working for some reason, or just taking a lot of time. Is there a way to run it manually or see what chunk is breaking it? It always seems to be somewhere in my creative world.

Also, it seems like some others are posting in the paper discord about crashes, I saw someone else with mobfarmmanager have a very similar crash running paper 99, perhaps there's some bug or incompatibility with how entities are removed in these newer paper versions? I'm praying that paper 88 will hold out for me if my worlds aren't somehow damaged by these crashes.

*update* so far running for 40 minutes with 88, I'm thinking paper 98 broke something with entity removal or perhaps multiple worlds, it's my creative world that was breaking and it's a multiverse world with no nether or end. I'll leave it for some time and see how it goes, hopefully it's stable now.

**Comment by Jikoo** [comment]
Looks like Paper's sync chunk load speed is hot trash, but I didn't see any commits that looked like a potential cause between 88 and 98.

Robo, I know you said you don't want to bloat GP by adding another shaded dependency, but this is another area that could see improvements by using PaperLib.

**Comment by RoboMWM** [comment]
Well, I'm more concerned about it seemingly causing chunk loads for entity cleanups - this should only happen in the case of claims being abandoned. I think one of my plans for v20 was to outsource claim modes so addons would take care of extra features for creative worlds and etc., given that those are the less common uses of GP.

**Comment by RWoof** [comment]
My server is still up and running 8 hours later, it's certainly something between paper 88 to 98 as that was the only thing that changed. All other plugins and settings remained the same.

**Comment by Proximyst** [comment]
Can you attempt this with a fork of Paper which reverts the light changes Aikar did in b97? [Rainforest](https://github.com/Proximyst/Rainforest) can do this if you [download a jar here](https://github.com/Proximyst/Rainforest/actions/runs/174721778) (You'll probably want the JDK8 one). This is the same as latest paper builds except without the change in b97.

**Comment by RWoof** [comment]
Thanks, downloaded it, I'll give it a try after work today 👍

**Comment by RWoof** [comment]
> Can you attempt this with a fork of Paper which reverts the light changes Aikar did in b97? [Rainforest](https://github.com/Proximyst/Rainforest) can do this if you [download a jar here](https://github.com/Proximyst/Rainforest/actions/runs/174721778) (You'll probably want the JDK8 one). This is the same as latest paper builds except without the change in b97.

Well of course when you want things to crash, they won't crash. This seems to be the nature of computers for me. I've ran my test server with both Rainforest and Paper 98 and it ran for hours without issue. Before, it was crashing after about 30 minutes each time. I'm reluctant to run this on my main server as the crashes will affect my players. I'll do more testing tomorrow, I'll make sure I've copied over an exact copy of the server as it is and see what happens. Maybe whatever entities GP was trying to clean up are gone now? Hopefully others are testing as well and can help find the problem.

If it matters, my main server is running on lubuntu 16.04 and my test server was running windows 10 (using PowerShell to launch a batch file with aikars flags). I have a second server running lubuntu 20.04 which I'll try tomorrow, although it's a lot more powerful and may not crash.

**Comment by RWoof** [comment]
> Can you attempt this with a fork of Paper which reverts the light changes Aikar did in b97? [Rainforest](https://github.com/Proximyst/Rainforest) can do this if you [download a jar here](https://github.com/Proximyst/Rainforest/actions/runs/174721778) (You'll probably want the JDK8 one). This is the same as latest paper builds except without the change in b97.

Updated my new test server to the latest paper version, crashed with GP entity cleanup very quickly. This server is NOT slow, it's an Intel i7 10700 with 32gb of ddr5 ram, sabrent rocket 4.0 2tb ssd. Running lubuntu 20.04 and Java 8 for Minecraft. Here's the log from start to finish: https://pastebin.com/v2j0F61v

Now testing with rainforest on the same pc and will report back. Paper 88 was running on it stable for a week at least.

**Comment by SlimeCody** [comment]
Just adding, this still happens all the way up to the current paper version.  Version 110

**Comment by RWoof** [comment]
> Just adding, this still happens all the way up to the current paper version. #110

Yes, I'm able to reproduce the issue and have reported it to paper's github here: https://github.com/PaperMC/Paper/issues/3986

It may be related to a fix introduced to help with the light generation in chunks?

**Comment by Proximyst** [comment]
I take it Rainforest ran completely fine, given you drew the conclusion to that being the issue?

**Comment by RWoof** [comment]
> I take it Rainforest ran completely fine, given you drew the conclusion to that being the issue?

I spent a large portion of yesterday paring down my test server to just a few plugins and attempting to make a new instance for it in amp which was acting up. It seems I can reliably reproduce the bug in Paper, I've got rainforest running right now and should know within a couple of hours if it's going to stay running or not, sorry for the delay on that!  So far it's been up for about 20 minutes.

**Comment by RWoof** [comment]
> I take it Rainforest ran completely fine, given you drew the conclusion to that being the issue?

Stated Paper and Rainforest instances, Rainforest about 20 minutes before Paper. Paper just crashed and died, Rainforest is still going.

Update: About 3 hours in with rainforest and no crash. Paper hasn't made it this far so likely it'll keep going.

Uodate 2: Just following up to say we're about 8 hours in with rainforest still running fine. I'll start my second test server up with paper again and Java 14 to see how far it gets.

**Comment by RoboMWM** [comment]
@SlimeCody thanks for the info, but try to avoid referring to build numbers with a #, as you will inadvertently link this issue to an existing GitHub issue instead.

**Comment by RWoof** [comment]
Rainforest has been running all day without an issue, I think it's safe to call it stable at this point.

Java 14 plus new paper failed in less than 20 minutes so I guess it's affected too.

**Comment by mben42** [comment]
Hi, I saw this post and tested rainforest also, but had the same problem.

https://pastebin.com/WfMsAVXa

**Comment by Jikoo** [comment]
@mben42 that's unrelated to this issue - your crash is the server hanging while PowerRanks is checking if a player is an op calculating perms for a check made by DiscordSRV.

**Comment by MithrandirCraft** [comment]
Please point to a stable 1.16.1 GP build.
Else I don't like rolling back Paper, so if there's a newer build that fixes this please say so. :)

**Comment by Muspah** [comment]
Rolling forward might fix this: https://papermc.io/ci/job/Paper-1.16/118/ (or newer!)

**Comment by RWoof** [comment]
> Rolling forward might fix this: https://papermc.io/ci/job/Paper-1.16/118/ (or newer!)

118 ran smoothly for me overnight, I've updated to 123 now, I think they might have fixed it now 😊

**Comment by Muspah** [comment]
Yup, should be fixed here: https://github.com/PaperMC/Paper/commit/76728529f9de02506a5c73aa4c5fc8c12d5fe13c (included in build 118).

**Comment by RoboMWM** [comment]
Thanks for the updates!

**Comment by hotspuraz** [comment]
Can confirm, this is fixed now. Server is running with 60+ players at 20 TPS again 😊
