### ISSUE TITLE
Can claim in worldguarded regions

### ISSUE THREAD

**Issue by JHarris12345** [GriefPrevention/GriefPrevention#891]
### What happened:
In 1.16, CreationRequiresWorldGuardBuildPermission: true doesnt protect worldguarded regions. People can still claim anywhere

### What was expected:
You cant claim in protected areas

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: git-paper-99
Paste of `/version GriefPrevention`: 16.14.0

config.yml: https://pastebin.com/wdSLGuJk

**Comment by Jikoo** [comment]
WG probably changed their API again. If you want to double check, turn on debug logging and check your GP logs after trying to claim in a WG region.

**Comment by JHarris12345** [comment]
Nothing is displayed in GP logs

**Comment by Jikoo** [comment]
Did you turn on debug logging? I ask because it's a debug-only message and debug was off in the config you posted.

**Comment by JHarris12345** [comment]
Yes

**Comment by Jikoo** [comment]
Just checked myself, nothing changed (much) in terms of the WG API that GP uses. Make sure that you're using an appropriate version of WG, the WG claim does not have the build flag set to allow, and that the user attempting to make the claim does not have access to the WG claim either explicitly or via permissions.

**Comment by RoboMWM** [comment]
Yes, also make sure you're using the correct flag, I think the flag is `passthrough`. Also make sure that worldguard/worldedit is up to date.

**Comment by Jikoo** [comment]
Closing in favor of #1140 - WG appears to be working fine, but ideally compatibility will be handled by an addon in the future.
