### ISSUE TITLE
Allow the /claimexplosions flag to persist after a server restart.

### ISSUE THREAD

**Issue by R416alex** [GriefPrevention/GriefPrevention#894]
The /claimexplosions flag should stay set to its last value after the server restarts. Currently, it prevents automatic farms that rely on tnt from working 24/7. The owner of the claim usually returns to their farms to find it hasn't produced anything since the previous days restart.

**Comment by RoboMWM** [comment]
You can keep this open if you'd like, but if you're not interested in such an addon anymore then you can keep it closed as well.

**Comment by Jikoo** [comment]
Duplicate of #860

**Comment by RoboMWM** [comment]
ah ok, thanks.

**Comment by R416alex** [comment]
Yeah sorry didn't see it was already posted.
