### ISSUE TITLE
MySql database disabled the plugin

### ISSUE THREAD

**Issue by eliyash31** [GriefPrevention/GriefPrevention#895]
After entering all the details of MySql database and restarted the server, the plugin is now disabled. I can say that the problem was because of the mysql database that I put in the config because when I remove it and restart the server again, the plugin doesn't show any errors anymore.

Server version is 1.16.1
Paste of `/version GriefPrevention`:  version 16.14.0

**Comment by bigpresh** [comment]
So what errors do you see when you have it configured to use a MySQL database?

What does your config look like?

**Comment by RoboMWM** [comment]
Invalid ticket format (lacks necessary information to determine problem). Please fill out the template you deleted.

**Comment by bigpresh** [comment]
#901 has been raised with the missing details (commenting for anyone who finds this ticket in future)
