### ISSUE TITLE
MySQL Databse disabled the plugin, now with server log

### ISSUE THREAD

**Issue by eliyash31** [GriefPrevention/GriefPrevention#901]
After entering all the details of MySql database and restarted the server, the plugin is now disabled. I can say that the problem was because of the mysql database that I put in the config because when I remove it and restart the server again, the plugin doesn't show any errors anymore.

Server version is 1.16.1
Paste of /version GriefPrevention: version 16.14.0

### GriefPrevention config.yml

Database:
    URL: na02-db.cus.mc-panel.net
    UserName: ******
    Password: ******

### Debugging steps attempted

- [x ] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

SOLUTION OF THE PROBLEM:
URL should look like : jdbc:mysql://MYSQL_HOSTNAME:3306/MYSQL_DATABASE

Thank you so much for those who helped me fix the problem!

**Comment by bigpresh** [comment]
Thanks for the details - will look at the logs / stacktrace and see if I can see what's going on.

> I don't know the use of this yet, I'm afraid users might download the attached file along with the login credentials of my database  but I'm sure that I put the correct infos for the Databse, because some of the plugins already worked with MySQL Database.

That's a very valid concern; you can always edit it replacing the hostname, usename & password with something else before submitting it.  We don't need to see what they are, as long as you're confident that they are correct.

**Comment by Jikoo** [comment]
None of those errors are from GP, they are from plugins that expect GP to be functional when present. Please post the actual server log.

**Comment by RoboMWM** [comment]
Fixed ticket format to retain the code fences (the backticks).

For the config.yml, as mentioned by bigpresh, you can redact that yourself.

**Comment by RoboMWM** [comment]
And as for the error, like Jikoo commented, this is not a GP error but another plugin. If you want further assistance, please paste the entire server log.

**Comment by eliyash31** [comment]
Okay Sir wait a minute please give me time, it was midnight on my country when I posted this issue don't close this issue yet, and yes this is a GP problem because when I remove the Database info or the username and password of mysql, it won't give me errors and the plugin just works fine. I will re edit my statements above along with the config of the plugin. I just can't restart my server as of now because the admins and builders are still working on the server.

**Comment by eliyash31** [comment]
I already posted the Config.yml, is there something wrong with what I put in the details?

**Comment by bigpresh** [comment]
Check the `URL` parameter in your config against the guide at https://github.com/TechFortress/GriefPrevention/wiki/MySQL-Setup

It should look like e.g. `jdbc:mysql://MYSQL_HOSTNAME:3306/MYSQL_DATABASE` not just be a hostname on its own.

**Comment by Jikoo** [comment]
I suspect your URL is invalid - should probably have the protocol, i.e. `jdbc:mysql://` at the start at very least. Consider deleting your username/password out of the issue and removing the edit revisions - we definitely don't need that.

/e Sniped, bigpresh is correct.

If you do continue to have issues, please paste the full startup log.

**Comment by eliyash31** [comment]
jdbc:mysql://MYSQL_HOSTNAME:3306/MYSQL_DATABASE okay I'm almost done, where can I find this MYSQL_DATABASE? I'm done with the username, password, and the hostname and port, just the MYSQL_DATABASE I don't know where I can find it

**Comment by bigpresh** [comment]
It's the name of the database to connect to; your hosting provider can tell you that, we can't.  You could try guessing that it's likely the same as the username you use to connect to the DB, though.

**Comment by eliyash31** [comment]
Okay thank you so much, I appreciate the help with you all I will re edit the problem and put the solution there

**Comment by Jikoo** [comment]
Your edit history is still there, and unfortunately I don't have access to delete that for you. Open edit history, select the edit where you added the username + password, and click "Options" at the top right to be able to remove it.
You probably also need to remove the edit in between adding and removing.

**Comment by RoboMWM** [comment]
I've deleted the sensitive edit history.
