### ISSUE TITLE
Limit pistons to land claims isn't working

### ISSUE THREAD

**Issue by MithrandirCraft** [GriefPrevention/GriefPrevention#902]
### What happened:
You can use pistons freely outside land claims even if "LimitPistonsToLandClaims = true"

### What was expected:
I thought pistons wouldn't be capable of pushing anything unless within a claim.

Note: In any case, (even though I haven't tried it since I can't, and I don't know if this was the original purpose for the option) if pistons didn't work outside a claim, and this option was intended for stopping people from using pistons from outside claims in order to push stuff from within claims, it seems like it would be enough to just claim by a claim, and then use pistons from your claim to push the ones from the neighbour.

I was trying this feature as an alternative to "CheckPistonMovement" because I couldn't bear piston tracking being the second largest lag cause on timings.

### Steps to reproduce:
1. Configure LimitPistonsToLandClaims = true in griefprevention's config.yml
2. Restart the server.
2. Try pistons outside claims. You do get a warning, but they still work.
![imagen](https://user-images.githubusercontent.com/6623704/88349257-de112f00-cd4f-11ea-8d47-02c9e45d5be9.png)

### Server and GriefPrevention version:
Paste of `/version`: Paper version git-Paper-99 (mc 1.16.1)
Paste of `/version GriefPrevention`: 16.14.0

### Debugging steps attempted
- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
>  if pistons didn't work outside a claim, and this option was intended for stopping people from using pistons from outside claims 

Option was intended to reduce performance impact by only allowing pistons to be used within a claim, instead of just anywhere in the world.

**Comment by MithrandirCraft** [comment]
@RoboMWM So it wasn't meant for blocking external manipulation?
Was it meant to work with "CheckPistonMovemen = true"? If so, as some kind of optimization? Wouldn't seem that helpful in general if so.

**Comment by RoboMWM** [comment]
> So it wasn't meant for blocking external manipulation?

Yes, but not in the sense of protecting the "wilderness," just to avoid performance issues since piston checks can get expensive. Claims are supposed to be protected, regardless if this is enabled or not.

**Comment by MithrandirCraft** [comment]
It's just that I can't deal with "CheckPistonMovement". It's too intense.
For now I've done some testing and found out that anyone can move things within alien claims in a range of 13 blocks from border (which is more or less how many blocks a piston can push), with the following configuration:
CheckPistonMovement = false
LimitPistonsToLandClaims = true 

This last config option which is not helping to stop piston pushing from outside claims, and wouldn't seem helpful for optimization either since most pistons are already within claims so people don't go around breaking redstone structures.

**Comment by Jikoo** [comment]
LimitPistonsToLandClaims is overridden by CheckPistonMovement. You can't turn off all piston movement checks and then expect pistons outside of claims to be disabled.

/e
>anyone can move things within alien claims in a range of 13 blocks from border

You're forgetting about [flying machines](https://gfycat.com/idiotictartbream).

**Comment by RoboMWM** [comment]
I put `Need more info` since my assumption about your config was incorrect - as Jikoo mentioned, if you set CheckPistonMovement to false, then the piston checks are disabled altogether, which includes rendering that other piston config option inactive.

**Comment by Bobcat00** [comment]
Hey guys.  Two months late, but...  I'm the person who added CheckPistonMovement to GP (https://github.com/TechFortress/GriefPrevention/pull/671).  I did it because pistons were causing lag on my server and I didn't want to limit pistons to land claims (which was the only alternative at the time).  I guess I thought it would be obvious that if pistons weren't being checked, the LimitPistonsToLandClaims setting would be ignored.

Anyway, sorry for the confusion and I'm glad you changed it to be less confusing.
