### ISSUE TITLE
Hell items can be opened

### ISSUE THREAD

**Issue by botany111** [GriefPrevention/GriefPrevention#903]
### What happened:
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true

### What was expected:
New materials added in 1.16
Unauthorized players can still use

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: Paper version git-Paper-114 (mc 1.16.1)
Paste of `/version GriefPrevention`:  GriefPrevention 16.14.0

**Comment by Jikoo** [comment]
Duplicate of #886
