### ISSUE TITLE
Why is pvp active in claims?

### ISSUE THREAD

**Issue by Adriianh** [GriefPrevention/GriefPrevention#909]
Hi, I have a question (I don't know if it's a mistake).

I have activated the option to protect the users on their lands, but this does not work, the users can get hit on their lands even if the setting is activated, does anyone have an idea why this could happen?

Version Server: 1.16.1
Version Plugin: 16.14.0
Config: https://pastebin.com/JxU01LCu

**Comment by RoboMWM** [comment]
Please use the bug report template instead of the question template, which will suggest troubleshooting options at the bottom of the template for you to help isolate the problem.
