### ISSUE TITLE
TNT can be ignited with a flame arrow in claims where players do not have build permission (no explosive damage is done)

### ISSUE THREAD

**Issue by Ridog** [GriefPrevention/GriefPrevention#912]
### What happened:
TNT can be ignited using a flame arrow in an area where the player does not have permission to build. The TNT doesn't actually do explosion damage unless /claimexplosions is turned on. This issue was encountered when a player was able to ignite a block of TNT being used as a decoration block in an admin claim.
### What was expected:
Players should not be able to ignite TNT within a claim unless they have build permissions.

### Steps to reproduce:
1. Create an Admin Claim
2. Place TNT within Admin Claim
3. De-op yourself
4. Shoot the TNT with a flame arrow

### Server and GriefPrevention version:
Paste of `/version`: This server is running Paper version git-Paper-115 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: GriefPrevention version 16.14.0

### Debugging steps attempted
- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server

**Comment by RoboMWM** [comment]
blockigniteevent changed? Great...

**Comment by Jikoo** [comment]
Started looking into this. Seems like nothing has changed, OP probably has enabled fire spread. As far as I can tell there is no explicit handling for arrows, only generic non-lightning/flint and steel.

**Comment by wmattiso** [comment]
I am now experiencing this bug in a later version of the plugin. I am currently using version 16.17.1 of the plugin.
