### ISSUE TITLE
[Request] Being able to give more claim blocks if someone votes for server (votifier)

### ISSUE THREAD

**Issue by jonassm** [GriefPrevention/GriefPrevention#92]
Pretty much what the title states. It would be very good for vanilla servers who don't want to give players a ton of stuff just for voting, and want to keep it fair, to just give some more claim blocks.

**Comment by RoboMWM** [comment]
`/acb <player> <blocks>`

**Comment by bigpresh** [comment]
What RoboMWM said - "awards" can be defined as a command to run.

The server I admin does just this, using Votifier and Vote Roulette (to give random rewards), and the claim block rewards in Vote Roulette's config are e.g.:

```
    100 Claim Blocks:
        commands:
        - /AdjustBonusClaimBlocks %player% +100
        message: "100 more claim blocks are yours for voting!"
```
