### ISSUE TITLE
1.16 wooden fences (crimson and warped) do not lock in claims

### ISSUE THREAD

**Issue by cunhar** [GriefPrevention/GriefPrevention#920]
### What happened:
1.16 wooden fences (crimson and warped) do not lock in claims

### What was expected:
fences staying closed by people whom dont have access

### Steps to reproduce:
1. Player 1 Claims 1.16 fences
2. Player 2 Opens Fence
3. ???
4. Player 1 sad :(

### Server and GriefPrevention version:
16.14.0

### GriefPrevention config.yml

```yml
    LockFenceGates: true
```

**Comment by Jikoo** [comment]
Duplicate of #886
