### ISSUE TITLE
ProtectHorses option in config no longer applies to non-horse mounts.

### ISSUE THREAD

**Issue by Rodzynus** [GriefPrevention/GriefPrevention#93]
1.11 version split mounts into separate entities, they used to be variations of Horse entity. This causes donkeys, mules, skeleton horses and llamas to require container trust and ignore "ProtectHorses: false" value in the config. 
I use ZHorse plugin to keep horses safe and this problem makes it unable for people to mount their own horses if they happened to dismount on someone else's claim.

**Comment by RoboMWM** [comment]
Yea, I'm currently overhauling the plugin (and likely will have only basic, perhaps configurable protection of such entities), but if you want to PR a fix feel free to do so.
