### ISSUE TITLE
Resizing claims

### ISSUE THREAD

**Issue by Frozensnowmanx** [GriefPrevention/GriefPrevention#930]
### What happened:
when trying to resize claims, it often says "claim cornet set!" instead of "claim resized" and its so buggy that its really hard to resize claim. also shows 'overlapping claim' while attempting to claim again

### What was expected:
I expect to be able to resize the claim easily but when trying to resize it, it just says 'claim corner set!' and when i try to resize again it says 'overlapping claim' which overlaps the original claim that i wanted to resize

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. claim a land
2. attempt to resize claim
3. and the bug will show
4. it may work like half of the time but the other half is just bugged

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Paste of `/version GriefPrevention`: 
16.14.0 (newest on spigot)

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by Frozensnowmanx** [comment]
I found out. The main problem is if you try to resize before the message "you may claim up to xxxx blocks" + "click for land claim help" pop up, it will reset and won't be able to resize properly. This is annoying for a lot of players

**Comment by RoboMWM** [comment]
The delay is to avoid message spamming when changing between multiple slots rapidly. Sounds like this same logic is used to detect if the shovel has been toggled off of which would "cancel" claim creation or admin/subdivision claims mode. The delay is less than a second, so if you have any better solutions that doesn't involve spamming the player when they scroll by the shovel/claim tool in their hotbar lemme know.

**Comment by RoboMWM** [comment]
Actually, I have no idea if that's really the issue you're having since there's next to nothing filled out above.
