### ISSUE TITLE
Moving from flatfile to MYSQL

### ISSUE THREAD

**Issue by Pixiio** [GriefPrevention/GriefPrevention#95]
Hi. We're trying to move from flatfile to MYSQL because players are still getting random claimblocks sometimes. It seems to be an issue with playerfiles not saving correctly while the claimfiles do. We can see this error in the GriefPrevention logs when it happens:
```
Attachment 1
11:29 [Username] has more claimed land than blocks available.  Adding blocks to fix.
11:29 Total blocks: 250 Total claimed area: 2647941
```
We've fixed this problem on one of our other server by moving from Flatfile to MYSQL and setting the accruedblocks to 0 in all playerfiles. Unfortunately the migration in another server isn't going as it should. Why? Because they are getting a massive amount of claimblocks when we set the accruedclaimblocks to 0. This happens because they are having more claims then claimblocks, the same message as above confirms this (Attachment 1).

Is there any way we can we remove the accruedblocks on all players without the server giving lots of claimblocks to them? We don't mind if the players go into minus. It also doesn't matter if claims disappear because of the minus because we can warn players about this.

### Steps/models to reproduce:

1. Fill in the MYSQL data in the config.
2. Restart the server.
3. Going to the MYSQL database.
4. Setting all the accruedblocks to 0 with a simple SQL.
5. Restart the server
6. Players are getting lots of extra bonusblocks, accrued stays on 0 though. (Attachment 1)

### Spigot/Craftbukkit/Paper and GriefPrevention version:

- GriefPrevention: 16.6
- Spigot: This server is running Paper version git-Paper-1056 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

### GriefPrevention config.yml (if applicable)

- https://hastebin.com/ovocehurux.php (removed mysql data)

### Note:
- We're not trying to fix the accruedblocks bug in flatfile, we just want to move to MYSQL because that will also fix it.

Thanks!

**Comment by RoboMWM** [comment]
> We don't mind if the players go into minus.

Big_Scary seems to have a lot of checks in place to stop this, so it wouldn't surprise me if he might've accidentally screwed up something there.

**Comment by Pixiio** [comment]
Ah. Any idea when you can look at it? :) 
https://github.com/BigScary/GriefPrevention/blob/master/src/me/ryanhamshire/GriefPrevention/PlayerData.java

**Comment by RoboMWM** [comment]
I'm overhauling the plugin, so I will be hitting that area soon.

**Comment by Pixiio** [comment]
@RoboMWM Please please please help us, players are getting so many random amounts of claimblocks last 2 days. If It will help: please add me on Discord/Skype? Then we'll post a solution here after..

**Comment by RoboMWM** [comment]
Do you have debug logging on in your config?

**Comment by RoboMWM** [comment]
> Total blocks: 250 Total claimed area: 2647941

Is this info correct? Also, does the user receive any bonus claim blocks?

**Comment by Pixiio** [comment]
Yes, debug is enabled. And yes, it's correct, but it's only the accrued amount I think. And yes, the plugin gives the new claimblocks on bonusclaimblocks.

Also note: I see it's also still happening on the other server with MYSQL enabled. Probably because we did the transfer the same way there.

**Comment by RoboMWM** [comment]
[GriefPrevention.zip](https://github.com/TechFortress/GriefPrevention/files/800432/GriefPrevention.zip)
Try this, rename to .jar

**Comment by RoboMWM** [comment]
[GriefPrevention.zip](https://github.com/TechFortress/GriefPrevention/files/800532/GriefPrevention.zip)

**Comment by RoboMWM** [comment]
https://github.com/TechFortress/GriefPrevention/tree/dont-fix-claimblocks

[GriefPrevention.zip](https://github.com/TechFortress/GriefPrevention/files/800600/GriefPrevention.zip)

**Comment by RoboMWM** [comment]
FYI, claim blocks are not consumed when used for claiming, but represent the total amount the player has accumulated. If the player somehow has claimed more land, then there indeed is an issue. (I believe I thought the issue was that the claim block fixer wasn't properly fixing - I now see that it was a misconception on the server owner regarding the value of accruedClaimBlocks).
