### ISSUE TITLE
Change all files to LF/CRLF file ending

### ISSUE THREAD

**Issue by FrankHeijden** [GriefPrevention/GriefPrevention#957]
My preference goes to the LF eol.

**Comment by FrankHeijden** [comment]
I don't understand why all "features" are automatically considered "Add-on Suggestion", but this should really happen within GP, lol

**Comment by Jikoo** [comment]
Features are labelled addon suggestions because 99% of them are :p

I'm going to mark this as invalid because it is [already specified](https://github.com/TechFortress/GriefPrevention/blob/732fa2e0155b6b10efa6d97df96da6f47f59491c/.editorconfig#L3). I will, however, leave it open for Robo to make a decision on because I usually set my client to automatically convert CRLF->LF on commit so it's definitely been a pain in the butt for me already.

**Comment by FrankHeijden** [comment]
It is not invalid, some files are LF and some files are CRLF; we should choose one of them & convert them all

**Comment by Jikoo** [comment]
Fair enough, wasn't aware of the mix.

**Comment by RoboMWM** [comment]
`.gitattributes` I think is handling this already, so to me everything is CRLF no matter what... If you can find out how to normalize line endings with git (I think I tried once with another project and it ended up as a mess that I can't even recall if or how I resolved) that'd be appreciated.

I think the automatic thing for git is to always have files in the repo as LF, and at least on Windows it'll auto-convert as needed. (Though tbh I'd prefer the vice versa behavior, cuz go Windows! c: )

**Comment by Jikoo** [comment]
The issue is that there are mixed line endings when GP explicitly desires CRLF. I'm fine with either (though I prefer LF), but it's kind of a mess for anyone but you to modify them because then you'd have to check literally every line of the commit for something that takes about 5 button presses to do.

**Comment by RoboMWM** [comment]
`.gitattributes` should be telling git to normalize line endings tho...?

**Comment by Jikoo** [comment]
It doesn't do it until they're actually included in a commit iirc, and even then depending on client it may not. On my end it's a 55+ file diff to convert to CRLF.

![image](https://user-images.githubusercontent.com/1353270/89777926-9bcf4800-dada-11ea-8ad1-6455ba1660b2.png)

**Comment by FrankHeijden** [comment]
Yup, if github detected these changes it wouldn't have been such a huge issue

**Comment by nouish** [comment]
All cached files can be updated to CRLF using the following commands:

```
git rm --cached -r .
git add .
```

I'm assuming you have `core.autocrlf` set to `true` here (to match editorconfig).

<details>
<summary>List of changed files (18 total)</summary>

```
modified:   src/main/java/me/ryanhamshire/GriefPrevention/CustomizableMessage.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/DeliverClaimBlocksTask.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/EntityCleanupTask.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/EquipShovelProcessingTask.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/IpBanInfo.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/MaterialCollection.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/MaterialInfo.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/PlayerRescueTask.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/RestoreNatureExecutionTask.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/SecureClaimTask.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/SendPlayerMessageTask.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/ShovelMode.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/SiegeCheckupTask.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/SiegeData.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/Visualization.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/VisualizationApplicationTask.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/VisualizationElement.java
modified:   src/main/java/me/ryanhamshire/GriefPrevention/VisualizationType.java
```
</details>

@RoboMWM

**Comment by RoboMWM** [comment]
I basically followed https://stackoverflow.com/questions/15641259/how-to-normalize-working-tree-line-endings-in-git and as such this should be closed with e3bce9a35ebaaf1f35d81d7635532c59268ede83 so if I dun goof'd lemme know.

**Comment by RoboMWM** [comment]
Re autocrlf: https://stackoverflow.com/a/20653073 (git bash defaults to `true` so this setting is generally properly set by default on Windows - perhaps the only potential case for it being set/used incorrectly may be when using git via WSL.)

Afaik, your git settings should dictate how your git client checks out code, and on check-in it should convert to LF if it's CRLF.

If needed, the entry in `.editorconfig` can be removed if it doesn't matter what line ending is used on the client.

**Comment by Jikoo** [comment]
> The issue is that there are mixed line endings when GP explicitly desires CRLF.

This probably shouldn't be closed yet, this repo is still full of LF-only files. I guess using GH's ignore line ending options (which I was unable to find on mobile, only on desktop site) will make diffs readable when LF files are modified, but it would be easier if they were made consistent in advance.

Edit: Just saw that you did exactly that, ignore me.

**Comment by RoboMWM** [comment]
ya, only thing I think that prolly should be modified is `.editorconfig` to not have a preference on line endings.
