### ISSUE TITLE
/unclaim makes craters in roads

### ISSUE THREAD

**Issue by jhkoenig** [GriefPrevention/GriefPrevention#96]
### What behaviour is expected:
/unclaim should return land to "available"
_What you expected to see_
### What behaviour is observed:
massive chunks of roadway destroyed, going very deep
### Steps/models to reproduce:
/claim
/unclaim
wait 2 minutes
### Spigot/Craftbukkit/Paper and GriefPrevention version:
Spigot: 1.11.2-R0.1-SNAPSHOT
GriefPrevention version 16.6
### Stack trace/error (if applicable)
no errors are generated
```
Paste entire stack trace inside here
```

### GriefPrevention config.yml (if applicable)

```yml
Paste config inside here
```

### Plugin list (if applicable):
 Plugins (25): AlwaysDay, AntiCreeper, CityWorld, CleanroomGenerator, CoreProtect, Essentials, EssentialsChat, GriefPrevention, Holograms, MCBans, Multiverse-Core, Multiverse-Portals, MultiVoteListener, OnTime, PermissionsEx, PlugMan, ProtocolLib, RoadBlock, ServerListPlus, Vault, VoteLinks, Votifier, WorldEdit, WorldGuard, ZeroSwear
![2017-02-24_13 17 16](https://cloud.githubusercontent.com/assets/26014023/23321511/be3035aa-fa94-11e6-8084-a76d5d3df510.png)

**Comment by RoboMWM** [comment]
Set the sea level of the world to the proper y level of this world. The generator is not reporting the proper level to bukkit is my guess.

**Comment by jhkoenig** [comment]
Thanks for the advice! I had previously set sea level to a calculated level with no impact. But following your suggestion, I set it to an absurd level (165) and now things seem to be working!

Really appreciate the help!!!
