### ISSUE TITLE
It's Completely Broken for me

### ISSUE THREAD

**Issue by MrFool23** [GriefPrevention/GriefPrevention#963]
I am downloading the .jar file and adding it to my Scalacube server. Then I restart the server and the plugin doesn't change from the .jar to the one you can edit, and doesn't say that I have the plugin in-game. I don't know whats wrong please help!

**Comment by bigpreshkt** [comment]
Please fill in the issue template which asks for versions, log output etc.  I don't know what you mean by "doesn't change from the .jar to the one you can edit"... do you mean that no config dir under plugins gets created (e.g. `plugins/GriefPreventionData`)?  That'll just be a symptom of the plugin not loading.

Without any idea what server software & version you're using, what GP version you're using, and the console output as the server starts and attempts to load the plugin, there's nothing we'll be able to do to help.

**Comment by bigpreshkt** [comment]
Also - for the benefits of others seeing this ticket - I had no idea what a "Scalacube server" was, but a Google suggests they're a Minecraft hosting company, and they provide various types ("Standard", by which I guess they mean Vanilla, Spigot, PaperMC, and various modpacks).
