### ISSUE TITLE
Admins cant remove claims

### ISSUE THREAD

**Issue by GGTEC** [GriefPrevention/GriefPrevention#965]
administrators are unable to remove clains that they do not belong to, not even the server OP, just or do not claim to remove it, I have correctly applied all permissions, but it does not work, I am using a 1.16.1 with a last update of the plugin

**Comment by Jikoo** [comment]
If you feel that you are experiencing a bug, please fill out the bug report template. As far as what little information you've given goes, "last update" is not a valid version, people have a tendency to say that they're running the latest version without actually checking.

This sounds like an issue with your permissions configuration. If you're using LuckPerms, you can enable verbose mode while trying to perform an action or use the test command to check if permissions evaluate correctly for a player.
