### ISSUE TITLE
Mooving blocks inside claims

### ISSUE THREAD

**Issue by pontusdevspace** [GriefPrevention/GriefPrevention#968]
People can use sticky pistons to drag blocks out of a claim. Imagine if someone built a wall of netherite or something. Like I said before they just use a piston and a torch and they can destroy everything that is movable. Please fix this as fast a possible. Thanks in advance / VernoxTV

**Comment by Jikoo** [comment]
Please fill out one of the issue templates. You have probably turned off piston checks.
