### ISSUE TITLE
[GriefPrevention] That belongs to X

### ISSUE THREAD

**Issue by Kyrobi** [GriefPrevention/GriefPrevention#971]
Every-so-often, something like `[GriefPrevention] That belongs to` will be printed to console. What's weirder is that it always says the same person

i.e. `[GriefPrevention] That belongs to Kyrobi`. What could be causing this?

**Comment by Jikoo** [comment]
GP only sends that message when a player damages a claimed entity, and it sends it to the player, not console. Probably a plugin creating fake players which are then attempting to attack claimed pets.

**Comment by Jikoo** [comment]
Found the probable culprit today by accident poking through the code, somehow managed to miss a field usage last time I looked at this. Should be able to be reproduced by using a dispenser to throw a poison or jump potion on entities.

**Comment by RoboMWM** [comment]
I think I reported this myself long long ago but never bothered to find out why or how - I think my guess was witches, but that probably makes more sense. #60

**Comment by Jikoo** [comment]
Oh yeah, witches would be a naturally occurring case too. It's in EntityEventHandler#onPotionSplash, any non-Player ProjectileSource yields a console message specifically for jump and poison. I'll probably tackle this, but my list of stuff I'm aware of that I want to address is now up to 15+ items after all the annotation work.
