### ISSUE TITLE
GriefPrevention Bonus Claim Blocks reset to 0

### ISSUE THREAD

**Issue by eliyash31** [GriefPrevention/GriefPrevention#979]
### What happened:
I don't know when this happens, but I already observed this many times that my bonus claims resets back to zero. I don't know what caused the problem, but I think it can be a mysql database bug? I also tried to restart the server but it didn't reset. I don't know what time or when it will reset back to zero.
![test1](https://user-images.githubusercontent.com/68148578/90992485-ad3c4800-e5e2-11ea-9981-86ce58a34e0a.PNG)
![test2](https://user-images.githubusercontent.com/68148578/90992487-ae6d7500-e5e2-11ea-815b-750d959236d8.PNG)

### What was expected:
I expected that the bonus claims should not reset back to 0. 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

https://pastebin.com/dDt9nXxK



### Debugging steps attempted
<!--These will be checkboxes you can click after creating the issue)-->
- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by eliyash31** [comment]
Please help anyone?

**Comment by eliyash31** [comment]
Please help anyone really need this to be fixed :(

**Comment by RoboMWM** [comment]
Isn't this a duplicate, and I need reproduction steps along with debug mode logging.

**Comment by cloakfox** [comment]
Have same issue with MySQL data storage. No idea how to reproduce.

**Comment by good3n** [comment]
Also getting this - absolutely no idea how to reproduce and it seems to happen to players randomly (or at least they're reporting it randomly). Also using MySQL.

**Comment by Jikoo** [comment]
Closing in favor of #666
