### ISSUE TITLE
Please allow the initial chest claim to be disabled

### ISSUE THREAD

**Issue by zhro** [GriefPrevention/GriefPrevention#98]
There is no facility in config.yml to disable this feature. Many of my players find it confusing as they may place a chest somewhere and then try to claim elsewhere and not understand that their previous chest had staked a claim.

I initially attempted to set "AutomaticNewPlayerClaimsRadius: 0" but this still protects the initial claim and creates a record in their /claimslist with an area of -1.

Please provide a way to disable the initial chest claim.

**Comment by RoboMWM** [comment]
There is. It's documented I believe. Set the radius to -1, not 0.
