### ISSUE TITLE
PlaceholderAPI Player ignored placeholder.

### ISSUE THREAD

**Issue by peacefulfarms** [GriefPrevention/GriefPrevention#984]
Placeholder request for player ignored.

i.e if i ignored player "playerB" placeholder %griefprevention_ignored_{player}% would
return "yes".

Quick and simple, let me know :D

**Comment by Jikoo** [comment]
You'll have much better luck opening an issue in [Expansions](https://github.com/pixar02/Expansions), I doubt the author of the hook monitors this repo's issues for feature requests.
