### ISSUE TITLE
Delete all claims of all players in a single world command

### ISSUE THREAD

**Issue by IITFA** [GriefPrevention/GriefPrevention#992]
I have multiple worlds on my server (as many server owners do). I have a resource world that I plan to put on a long-cycle reset (maybe once every six to twelve months). I was just thinking that it would be nice if users could use griefprevention in that world to protect their bases/homes, but when the world is reset, I would like to remove all claims of all users but only in THAT world.

So, I am requesting a command that would be useful to more than just me. A command that can be executed to delete all claims in a single specified world.

Example:
/gp deleteallclaims worldname
The result would only delete claims in that one world and leave other worlds alone.

**Comment by Jikoo** [comment]
`/deleteclaimsinworld`, `/deleteuserclaimsinworld`
