### ISSUE TITLE
In the log it said that there was an internal error and it had to disable itself

### ISSUE THREAD

**Issue by Jrgaming001** [GriefPrevention/GriefPrevention#993]
### What happened:
The log said Internal error and it disabled itself

### What was expected:
the thing to work

### Steps to reproduce:
__This may include a build schematic, a video, or detailed instructions to help reconstruct the issue__
1. Step 1. put it in the plugins folder
2. Step 2. restart the server
3. ???
4. Profit!

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`: 
Paste of `/version GriefPrevention`: 

### Stack trace/error or server log

```
Paste entire stack trace right here inside these backticks.

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

```

### Debugging steps attempted

- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

**Comment by Jikoo** [comment]
So, are you going to include the logs? "There was an error" tells us nothing. There's so little information that we can't even be sure you have the right issue tracker, GriefPrevention is in no way mentioned in anything other than the template you didn't fill out.
